Text_SwordsDanceTeach::
    .string "Það koma ekki margir hingað út.\p"
    .string "Ef ég æfi hér, er ég viss um að\n"
    .string "ég verð sterkari og sterkari.\p"
    .string "Já, sterkari og sterkari…\p"
    .string "Viltu læra slíka árás?\n"
    .string "Hún er SWORDS DANCE.$"

Text_SwordsDanceDeclined::
    .string "Jæja, það er líka í lagi.$"

Text_SwordsDanceWhichMon::
    .string "Allt í lagi, veldu hvaða\n"
    .string "Vasaskrímsli ég á að kenna þetta.$"

Text_SwordsDanceTaught::
    .string "Ef við gætum bara alltaf orðið\n"
    .string "sterkari og sterkari, ha?$"

SevenIsland_Text_IslandSign::
    .string "SJÖ EYJA Leitar eyja Óendanleikans$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "Þessar eyjar eru kallaðar SEVII\n"
    .string "ISLANDS því þær eru sjö.\p"
    .string "…Eða að minnsta kosti trúa unga\n"
    .string "fólkið því.\p"
    .string "Sannleikurinn er sá að nafnið kemur\n"
    .string "af því að sagt er að eyjarnar hafi\p"
    .string "verið skapaðar á sjö dögum.$"

SevenIsland_Text_IslandVirtuallyUntouched::
    .string "Þessi eyja hefur nánast haldist\n"
    .string "ósnortin í náttúrulegu ástandi.\p"
    .string "Þess vegna getur verið dálítið\n"
    .string "erfitt að ganga hér um.$"
