OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
    .string "BILL: Hæ, þú! CELIO!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
    .string "CELIO: BILL! Ég trúi því ekki að þú\n"
    .string "komst hingað út.$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
    .string "BILL: Já, alveg örugglega! Hvernig\n"
    .string "gengur rannsóknin þín?\p"
    .string "…Ó, bíddu aðeins.$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
    .string "{PLAYER}, þetta er vinur minn CELIO.\n"
    .string "Hann er algjör TÖLVU-BRJÁLINGUR!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
    .string "CELIO, þetta er {PLAYER},\n"
    .string "upprennandi kandídat sem\p"
    .string "Vasaskrímsla CHAMP!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
    .string "CELIO, þetta er {PLAYER}, ríkjandi\n"
    .string "Vasaskrímsla CHAMP!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
    .string "CELIO: Þetta er virkilega\n"
    .string "áhrifamikið.\p"
    .string "Ég hata að segja það, en ég hef enga\n"
    .string "hæfileika í bardögum.\p"
    .string "Engu að síður, ánægjulegt að hitta\n"
    .string "þig.$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
    .string "BILL: Svo, segðu mér fréttirnar.\n"
    .string "Hvernig gengur vélin þín?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
    .string "CELIO: Hún gengur fínt, en við erum\n"
    .string "of langt í burtu hér.\p"
    .string "Tölvurnar á þessari eyju geta bara\n"
    .string "ekki tengst tölvunni þinni, BILL.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
    .string "BILL: Ó, já? Allt í lagi, leyfðu mér\n"
    .string "að líta á þetta.\p"
    .string "…Bíddu aðeins… Ég held að við getum\n"
    .string "látið þetta virka. Leyfðu mér að\p"
    .string "hjálpa þér, allt í lagi?$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
    .string "{PLAYER}, geturðu beðið eftir mér\n"
    .string "aðeins?\p"
    .string "…Reyndar, gætirðu gert mér greiða?\p"
    .string "Eyjan við hliðina á þessari heitir\n"
    .string "TWO EYJA.\p"
    .string "Þar er gaur sem rekur LEIKJAKRÓK.\p"
    .string "Hann er veikur fyrir sjaldgæfum\n"
    .string "steinum og gimsteinum.\p"
    .string "Við hittumst hér aftur þegar þú\n"
    .string "hefur farið með þetta til hans.$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
    .string "{PLAYER} þáði METEORITE frá BILL.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
    .string "CELIO: {PLAYER}, ef þú ert að fara\n"
    .string "til TWO EYJU, taktu þetta með þér.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
    .string "Þetta er PASS fyrir ferjuþjónustuna\n"
    .string "á eyjunum hér.\p"
    .string "Hann leyfir þér að ferðast á milli\n"
    .string "ONE, TWO og THREE EYJU.\p"
    .string "Ó, þú ættir að fá þetta líka.$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
    .string "{PLAYER} fékk aukasíðu fyrir\n"
    .string "BÆJARKORTIÐ!$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
    .string "{PLAYER} fékk BÆJARKORT!$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
    .string "BILL: Ég sé þig seinna! Heilsaðu\n"
    .string "stráknum frá mér!$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
    .string "Hmm…\p"
    .string "Hvað ef við reynum þetta svona…$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
    .string "Ó, hæ, {PLAYER}!\p"
    .string "Sástu? Við fengum tölvuna til að\n"
    .string "virka!\p"
    .string "Ég á nokkra hluti til að sýna CELIO\n"
    .string "hér.\p"
    .string "Geturðu farið í göngutúr eða\n"
    .string "eitthvað í smá stund í viðbót?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .string "Ég biðst afsökunar á að hafa tekið\n"
    .string "svo mikinn tíma BILLs.\p"
    .string "Ég biðst líka afsökunar á að hafa\n"
    .string "verið svo lélegur gestgjafi í\p"
    .string "heimsókn þinni hingað.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
    .string "Venjuleg tölvuþjónusta er ekki laus…$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
    .string "BILL: Ó, hæ! {PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
    .string "BILL: Hvað varð um þig? Varstu að\n"
    .string "skemmta þér?\p"
    .string "Við kláruðum það. Tölvurnar eru\n"
    .string "komnar í gang!$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
    .string "CELIO: Verkið gekk ótrúlega hratt.\p"
    .string "BILL er ótrúlegur gaur…$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
    .string "BILL: Nei, nei! Það var næstum ekki\n"
    .string "neitt eftir fyrir mig að gera.\p"
    .string "CELIO, ég verð að hrósa þér. Þú\n"
    .string "hefur lært mikið.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
    .string "CELIO: Oh, really? Ehehe…$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
    .string "BILL: Jæja, þar hefurðu það. Ég er\n"
    .string "búinn með verkið. Við ættum\p"
    .string "að fara aftur til KANTO.\p"
    .string "CELIO, ég sé þig aftur.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
    .string "CELIO: {PLAYER}, mér þykir virkilega\n"
    .string "það leitt að við sendum þig einan í\p"
    .string "dag.\p"
    .string "Ég lofa, ég mun sýna þér um þessar\n"
    .string "eyjar einhvern tímann.$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
    .string "CELIO: Halló! Þú lítur ótrúlega\n"
    .string "upptekinn út eins og alltaf.\p"
    .string "Hvernig gengur mér?\p"
    .string "Jæja, ég er að breyta Netvélinni\n"
    .string "minni.\p"
    .string "Þegar ég er búinn með vélina, vona\n"
    .string "ég að þú verðir fyrstur til að nota\p"
    .string "hana,\p"
    .string "{PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
    .string "CELIO: {PLAYER}, hvernig hefur\n"
    .string "gengið hjá þér?\p"
    .string "Ó, er það svo? Þú hefur fangað\n"
    .string "fleiri Vasaskrímsli.\p"
    .string "Veistu hvað? Kannski get ég orðið\n"
    .string "þér að gagni.$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
    .string "Ég er að breyta Net Vél núna.\p"
    .string "Ég er að laga hana svo hún ráði við\n"
    .string "skipti yfir langar vegalengdir.\p"
    .string "Þegar ég klára geturðu skipt við\n"
    .string "fjarlæga ÞJÁLFARA og fengið framandi\p"
    .string "Vasaskrímsli.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
    .string "En, það er smá galli.\p"
    .string "Til að tengingin virki, þarf Vélin\n"
    .string "sérstakan gimstein.\p"
    .string "Hann á að vera á EYJU EINNAR, en ég\n"
    .string "hef ekki fundið einn enn.\p"
    .string "Hver veit hvar hann gæti verið.$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
    .string "Ég reyndi að finna gimsteininn\n"
    .string "jafnvel á meðan ég var að læra.\p"
    .string "Afleiðingin er sú að mér hefur\n"
    .string "ekkert miðað, hvorki í leitinni né\p"
    .string "náminu…\p"
    .string "Ef ég treysti á BILL er ég viss um\n"
    .string "að rannsóknin mín myndi ganga betur.\p"
    .string "En í þetta sinn vil ég reyna að gera\n"
    .string "hlutina sjálfur.$"

OneIsland_PokemonCenter_1F_Text_OhThats::
    .string "Ó! Þ-þetta er…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
    .string "{PLAYER} afhenti CELIO RUBY.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
    .string "Takk fyrir! {PLAYER}, þú ert\n"
    .string "einfaldlega frábær.\p"
    .string "… … … … … …\p"
    .string "Um… Má ég biðja þig um einn enn\n"
    .string "risa-greiða?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
    .string "Þ-þetta er ekkert skrýtið.\n"
    .string "Vinsamlegast, ég þarf hjálp þína.$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
    .string "Á meðan ég var að rannsaka gimsteina\n"
    .string "uppgötvaði ég eitthvað mikilvægt.\p"
    .string "Það er annar gimsteinn sem myndar\n"
    .string "par með þessum RUBY.\p"
    .string "Sá gimsteinn á að vera í SEVII\n"
    .string "EYJUM.\p"
    .string "{PLAYER}, vinsamlegast, ég þarf að\n"
    .string "þú finnir hinn gimsteininn.$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
    .string "{PLAYER} skilaði ÞRÍPASSA og fékk\n"
    .string "REGNBOGAPASSA.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
    .string "Fékk aukasíðu fyrir BÆJARKORTIÐ!$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
    .string "Þetta er mitt eigið ferju-PASS.\p"
    .string "Það leyfir þér að komast til allra\n"
    .string "SEVII EYJA.\p"
    .string "{PLAYER}, vinsamlegast, ég get þetta\n"
    .string "ekki án hjálpar þinnar.$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
    .string "{PLAYER} afhenti CELIO SAPPHIRE.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
    .string "CELIO: Svo þetta er gimsteinninn sem\n"
    .string "myndar par með RUBY…\p"
    .string "{PLAYER}, þú hefur gengið í gegnum\n"
    .string "margt til að fá hann, er það ekki?\p"
    .string "Þú þarft ekki að segja mér það. Ég\n"
    .string "veit að það var ekki auðvelt.\p"
    .string "Kærar þakkir!\p"
    .string "Nú er komið að mér að vinna fyrir\n"
    .string "þig! Gefðu mér smá tíma.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .string "Allt í lagi, þetta er gott…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .string "Ég gerði það! Ég tengdist LANETTE!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .string "{PLAYER}… {PLAYER}, mér tókst það!\p"
    .string "Mér tókst að tengjast ÞJÁLFURUM í\n"
    .string "HOENN-héraðinu!\p"
    .string "Loksins er Net Vél komin í fulla\n"
    .string "virkni!\p"
    .string "{PLAYER}, ég á þér þetta allt að\n"
    .string "þakka!\p"
    .string "Þökk sé þér rættist draumurinn minn…$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .string "É-ég er ekki að gráta.\p"
    .string "Nóg um mig!\p"
    .string "{PLAYER}, þú heldur áfram að leita\n"
    .string "að framandi Vasaskrímslum,\p"
    .string "er það ekki?\p"
    .string "Ég óska þér góðs gengis!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .string "CELIO: Halló!\p"
    .string "{PLAYER}, ég hef heyrt sögur um þig.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .string "{PLAYER}, hvaða gerð af\n"
    .string "Vasaskrímslum er í uppáhaldi hjá\p"
    .string "þér?\p"
    .string "BILL er SKRÍMSLASJÚKUR, svo hann\n"
    .string "elskar allar gerðir.\p"
    .string "Sagt er að fyrsta Vasaskrímslið sem\n"
    .string "hann fangaði hafi verið TÖFRI.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .string "Annars, {PLAYER}, þú ert frá PALLET\n"
    .string "BÆ, er það ekki?\p"
    .string "Ég hef heyrt að það sé rólegur og\n"
    .string "þægilegur staður.\p"
    .string "Heimabær BILL er GOLDENROD BORG, þar\n"
    .string "sem fjölskylda hans býr enn.\p"
    .string "Ég hef heyrt að það sé ansi lífleg\n"
    .string "og iðandi borg.\p"
    .string "Ég myndi vilja fara þangað einn\n"
    .string "daginn.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .string "{PLAYER}, er eitthvað sem þú þolir\n"
    .string "ekki?\p"
    .string "Svo virðist sem BILL þoli\n"
    .string "einfaldlega ekki mjólk.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .string "Ó, þú ert ókunnug/ur hér! Hæ! Hvaðan\n"
    .string "kemurðu?\p"
    .string "…PALLET BÆ? Ég þekki hann ekki!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .string "Á þessari eyju er risastórt\n"
    .string "eldfjall.\p"
    .string "Það hefur ekki gosið nýlega, svo af\n"
    .string "hverju ekki að njóta gönguferðar?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .string "Ég vildi að ég gæti skipt\n"
    .string "Vasaskrímslum við kærastann minn sem\p"
    .string "býr langt í burtu…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .string "Ég skipti á Vasaskrímslum við\n"
    .string "kærastann minn langt í burtu!\p"
    .string "Allir segja að við getum þakkað þér\n"
    .string "og CELIO.\p"
    .string "Svo, takk fyrir!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .string "Net Vél Tengistig 0\p"
    .string "…Geymslukerfi Vasaskrímsla í\n"
    .string "stillingu…$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .string "Net Vél Tengistig 1\p"
    .string "Tenging komin á við KANTO-svæðið.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .string "Net Vél Tengistig 2\p"
    .string "Tenging komin á við KANTO- og\n"
    .string "HOENN-svæðin.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
    .string "Fékk ÞRÍPASSA!$"

