SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Suss! Sérðu ekki að ég er í felum?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "Ha? Er ROCKET-GENGIÐ farið?$"

SilphCo_4F_Text_Grunt1Intro::
    .string "ROCKET-GENGIÐ hefur tekið yfir\n"
    .string "SILPH CO.!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "Fwahahaha! FORINGINN minn hefur\n"
    .string "verið á eftir þessum stað!$"

SilphCo_4F_Text_RodneyIntro::
    .string "Vasaskrímslið mitt er tryggur þjónn minn.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "Fjárinn! Veika Vasaskrímslið þitt!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "Dyrnar eru raflæstar.\p"
    .string "Það þarf KORTALYKIL til að opna\n"
    .string "dyrnar hér.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "Innbrotsþjófur sést!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "Hver ert þú?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "Ég ætti að segja FORINGJANUM á 11H!$"

SilphCo_4F_Text_FloorSign::
    .string "SILPH CO. HÖFUÐSKRIFSTOFA 4H$"
