PokemonMansion_1F_Text_TedIntro::
    .string "Hver ert þú? Það ætti enginn að vera\n"
    .string "hér.$"

PokemonMansion_1F_Text_TedDefeat::
    .string "Ái!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "Lykill? Ég veit ekki hvað þú ert að\n"
    .string "tala um.$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "V-v-váá! Þú brá mér! Ég hélt að þú\n"
    .string "værir draugur.$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "Tsk! Ég næ engum sigrum.$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "Ég var að kanna hér einn, en mér er\n"
    .string "farið að bregða.\p"
    .string "Ég ætti að fara bráðum.$"

