SixIsland_GreenPath_Text_JaclynIntro::
    .string "…Ha?\p"
    .string "Ég var að sjá húsið mitt fyrir mér,\n"
    .string "en þetta er staðurinn sem ég\p"
    .string "FJARFLUTN. sendir mig á?$"

SixIsland_GreenPath_Text_JaclynDefeat::
    .string "Stór mistök!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
    .string "Ég er svo utan við mig!\p"
    .string "Ég þarf að einbeita mér svo ég geti\n"
    .string "notað FJARFLUTN. rétt heim til mín!$"

SixIsland_GreenPath_Text_LeftRouteSign::
    .string "GREEN PATH PATTERN BUSH AHEAD$"

SixIsland_GreenPath_Text_RightRouteSign::
    .string "GREEN PATH Think Green, Keep Nature\n"
    .string "Clean!$"
