SixIsland_GreenPath_Text_JaclynIntro::
    .string "…Ha?\p"
    .string "Ég var að sjá húsið mitt fyrir mér,\n"
    .string "en þetta er staðurinn sem ég\p"
    .string "FJARFLUTNINGUR sendir mig á?$"

SixIsland_GreenPath_Text_JaclynDefeat::
    .string "Stór mistök!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
    .string "Ég er svo utan við mig!\p"
    .string "Ég þarf að einbeita mér svo ég geti\n"
    .string "notað FJARFLUTNING rétt heim til mín!$"

SixIsland_GreenPath_Text_LeftRouteSign::
    .string "GRÆNN STÍGUR\n"
    .string "MYNSTURRUNNI FRAMUNDAN$"

SixIsland_GreenPath_Text_RightRouteSign::
    .string "GRÆNN STÍGUR Hugsaðu grænt, haltu\n"
    .string "náttúrunni hreinni!$"
