FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "WARDEN: Hif fuff hefifoo!\p"
    .string "Ha lof ha feef ee hafahi ho. Heff\n"
    .string "hee fwee!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "Ah howhee ho hoo! Eef ee hafahi ho!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "Ha? He ohay heh ha hoo ee haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER} gaf VÖRÐINUM GULLTENNURNAR.$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "WARDEN setti tennurnar í sig!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "VÖRÐUR: Takk, sonur! Þú ert\n"
    .string "sannkallaður bjargvættur!\p"
    .string "Enginn gat skilið orð af því sem ég\n"
    .string "sagði, ekki eitt einasta!\p"
    .string "Ég skammaðist mín of mikið til að\n"
    .string "sýna mig við SKRIFSTOFUNA, jafnvel.\p"
    .string "Leyfðu mér að gefa þér eitthvað\n"
    .string "fyrir erfiðið.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "VÖRÐUR: Takk, stelpa! Þú ert\n"
    .string "sannkallaður bjargvættur!\p"
    .string "Enginn gat skilið orð af því sem ég\n"
    .string "sagði, ekki eitt einasta!\p"
    .string "Ég skammaðist mín of mikið til að\n"
    .string "sýna mig við SKRIFSTOFUNA, jafnvel.\p"
    .string "Leyfðu mér að gefa þér eitthvað\n"
    .string "fyrir erfiðið.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER} fékk HM04 frá VÖRÐINUM.$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "VÖRÐUR: Í HM04 finnurðu STYRK.\p"
    .string "Hún leyfir Vasaskrímslum að færa\n"
    .string "stór björg utan bardaga.\p"
    .string "Ó já, fannstu LEYNIHÚSIÐ í SAFARI\n"
    .string "SVÆÐINU?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや にもつ いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "Myndir og steingervingar af\n"
    .string "Vasaskrímslum eru til sýnis.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "Gamall Vasaskrímsla-varningur er til\n"
    .string "sýnis.$"

