SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "…Bíddu! Ekki segja orð!\p"
    .string "Þú vildir þetta!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} fékk TM29 frá MR.\n"
    .string "HUGAR.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "Þú veist það nú þegar, er það ekki?\n"
    .string "TM29 er HUGAR.\p"
    .string "Árásin getur líka lækkað sérstakar\n"
    .string "tölur skotmarksins.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Hvert ætlarðu að setja þetta? Þú\n"
    .string "hefur ekkert pláss.$"
