RockTunnel_B1F_Text_SofiaIntro::
    .string "Veistu hvernig þú getur forðast að\n"
    .string "villast í fjöllunum?\p"
    .string "Þú getur beygt greinar sem\n"
    .string "leiðarmerki.$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "Óóó! Ég gerði mitt besta!$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "Mig langar heim!$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "Hahaha! Geturðu sigrað kraftinn\n"
    .string "minn?$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "Úps! Þú varst sterkari!$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "Ég vel kraft því ég hata að hugsa.$"

RockTunnel_B1F_Text_CooperIntro::
    .string "Ertu með VasaDEX? Mig langar líka í\n"
    .string "svoleiðis.$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "Skot! Ég er svo öfundsjúkur!$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "Þegar þú klárar VasaDEX-ið þitt, má\n"
    .string "ég þá fá það?$"

RockTunnel_B1F_Text_SteveIntro::
    .string "Umm... Veistu um\n"
    .string "vasaskrímsla-búningaleik?$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "Jæja, þá er það það.$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "Vasaskrímsla-búningaleikur er að\n"
    .string "klæða sig eins og vasaskrímsli til\p"
    .string "gamans.\p"
    .string "BLEIKÁLFUR er vinsæll kostur.$"

RockTunnel_B1F_Text_AllenIntro::
    .string "Vasaskrímslatæknin mín lætur þig\n"
    .string "gráta!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "Ég gefst upp! Þú ert betri\n"
    .string "tæknimaður!$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "Í fjöllum finnurðu oft STEIN-gerðar\n"
    .string "vasaskrímsli.$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "Ég kem ekki oft hingað, en ég ætla\n"
    .string "að berjast við þig.$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "Ó! Ég tapaði!$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "Mér líkar við pínulítil\n"
    .string "vasaskrímsli. Þau stóru eru of\p"
    .string "ógnvekjandi!$"

RockTunnel_B1F_Text_EricIntro::
    .string "Skelltu þínu besta á mig!$"

RockTunnel_B1F_Text_EricDefeat::
    .string "Skotið af!$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "Ég ala vasaskrímslin mín upp til að\n"
    .string "sigra þín, krakki.$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "Ég teikna myndir af vasaskrímslum\n"
    .string "þegar ég er heima.$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "Úff... Ég er örmagna...$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "Ég er listamaður, ekki bardagamaður.\n"
    .string "Ég fer heim að teikna.$"

