CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MJÁGJARN: Mjá!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "Þú ættir ekki að eyða öllum\n"
    .string "peningunum þínum í drykki.\p"
    .string "Prófaðu þetta í staðinn.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Ekkert slær á þorsta eins og heitt\n"
    .string "TE.\p"
    .string "Það er í alvöru það besta.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "Kæru vasaskrímslin mín halda mér\n"
    .string "félagsskap. MJÁGJARN kemur jafnvel\p"
    .string "með peninga heim!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Ó, hæ gæskur. Sástu ánægður með TEIÐ\n"
    .string "mitt?\p"
    .string "Áttu annars, af einhverju tilfelli,\n"
    .string "heima í PALLET BÆ?\p"
    .string "Stúlka frá PALLET BÆ, DAISY, hún\n"
    .string "nýtur þess að drekka TE á hverjum\p"
    .string "degi.\p"
    .string "Hún fer í CELADON VÖRUHÚSIÐ til að\n"
    .string "kaupa TE.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "BLEIKÁLFUR: Pí pípppí!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDORAN♀: Kja kjaó!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "CELADON STÓRHÝSI Íbúð stjórnanda$"
