CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "VASAFLAUTA vekur sofandi\n"
    .string "vasaskrímsli. Þú veist það.\p"
    .string "Hún gerir það með hljóði sem aðeins\n"
    .string "þau heyra.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "Ég hjólaði hingað frá FUCHSIA.\p"
    .string "CYCLING ROAD liggur upp í móti, svo\n"
    .string "ég er örmagna.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "Ef ég ætti HJÓL færi ég á CYCLING\n"
    .string "ROAD!$"

