Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "Ég er í rólegri hjólaferð á nýja\n"
    .string "hjólinu mínu með kærustunni.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "Við ætlum að hjóla saman á nýju\n"
    .string "hjólunum okkar.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "Sjáum hvað sjónaukinn sýnir...\p"
    .string "Það er CELADON DEPT. STORE!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "Sjáum hvað sjónaukinn sýnir...\p"
    .string "Það er löng leið yfir vatn langt í\n"
    .string "burtu.$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "Hæ! Manstu eftir mér? Ég er einn af\n"
    .string "AÐSTOÐARMÖNNUM Prófessor EIK.\p"
    .string "Ef VasaDEX-ið þitt er með full gögn\n"
    .string "um 40 tegundir á ég að gefa þér\p"
    .string "verðlaun.\p"
    .string "Prófessor EIK fól mér HEILLAPENING\n"
    .string "handa þér.\p"
    .string "Svo, {PLAYER}, leyfðu mér að spyrja.\p"
    .string "Hefurðu safnað gögnum um að minnsta\n"
    .string "kosti 40 gerðir vasaskrímsla?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "Frábært! Þú hefur náð eða átt\n"
    .string "{STR_VAR_3} gerðir vasaskrímsla!\p"
    .string "Til hamingju! Gjörðu svo vel!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "{PLAYER} fékk HEILLAPENING frá\n"
    .string "AÐSTOÐARMANNINUM.$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "HEILLAPENINGUR er hlutur sem\n"
    .string "vasaskrímsli heldur á.\p"
    .string "Ef vasaskrímslið birtist í sigruðum\n"
    .string "bardaga færðu meiri peninga.$"

