FuchsiaCity_Text_DidYouTrySafariGame::
    .string "Prófaðirðu SAFARI-LEIKINN?\p"
    .string "Þar eru nokkur sjaldgæf Vasaskrímsli\n"
    .string "sem aðeins má fanga þar.$"

FuchsiaCity_Text_SafariZoneZooInFront::
    .string "SAFARI SVÆÐIÐ er með dýragarð fyrir\n"
    .string "framan innganginn.\p"
    .string "Aftan við er SAFARI LEIKURINN þar\n"
    .string "sem hægt er að fanga Vasaskrímsli.$"

FuchsiaCity_Text_WheresSara::
    .string "ERIK: Hvar er SARA? Ég sagðist ætla\n"
    .string "að hitta hana hér.$"

FuchsiaCity_Text_ItemBallInThere::
    .string "Þessi hlutabolti þarna inni…\n"
    .string "Vildirðu ná í hann?\p"
    .string "Ég líka! …Ha? Er þetta Vasaskrímsli?$"

FuchsiaCity_Text_CitySign::
    .string "FUCHSIA BORG Sjáðu! Hún er ástríðu\n"
    .string "bleik!$"

FuchsiaCity_Text_SafariZoneSign::
    .string "VASaSKRÍMSLA-PARADÍS SAFARI SVÆÐI$"

FuchsiaCity_Text_SafariGameSign::
    .string "SAFARI-LEIKUR FANGAÐU VASASKRÍMSLI!$"

FuchsiaCity_Text_WardensHomeSign::
    .string "SAFARI SVÆÐI HEIMILI VÖRÐARINS$"

FuchsiaCity_Text_SafariZoneOfficeSign::
    .string "VASaSKRÍMSLA-PARADÍS! Velkomin/n á\n"
    .string "SAFARI SVÆÐIÐ! SKRIFSTOFA SAFARI\p"
    .string "SVÆÐIS$"

FuchsiaCity_Text_GymSign::
    .string "FUCHSIA BORG Vasaskrímslasalur\n"
    .string "LEIÐTOGI: KOGA Eitraði\p"
    .string "Ninjameistarinn$"

FuchsiaCity_Text_ChanseySign::
    .string "Nafn: SÆLEGG Það er algjör heppni að\n"
    .string "fanga eitt.$"

FuchsiaCity_Text_VoltorbSign::
    .string "Nafn: STUÐBOLTI Sjálf ímynd VASA\n"
    .string "BOLTA.$"

FuchsiaCity_Text_KangaskhanSign::
    .string "Nafn: KENGÚRILL\p"
    .string "Móðurlegt Vasaskrímsli sem elur\n"
    .string "ungann í poka á kviðnum.$"

FuchsiaCity_Text_SlowpokeSign::
    .string "Nafn: SLJÓN Vingjarnlegt og mjög\n"
    .string "hægt á ferð.$"

FuchsiaCity_Text_LaprasSign::
    .string "Nafn: LAGARGANDU EÐA konungur\n"
    .string "hafanna.$"

FuchsiaCity_Text_OmanyteSign::
    .string "Nafn: KUÐUNGI Mjög sjaldgæft\n"
    .string "Vasaskrímsli sem var endurlífgað\p"
    .string "úr steingervingi.$"

FuchsiaCity_Text_KabutoSign::
    .string "Nafn: BOTNSETI Mjög sjaldgæft\n"
    .string "Vasaskrímsli sem var endurlífgað\p"
    .string "úr steingervingi.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .string "Æ, ég vildi að ég væri ungi\n"
    .string "KENGÚRILLS.\p"
    .string "Ég myndi vilja vera staðgengill\n"
    .string "ungans…\p"
    .string "Og kúra í poka móður KENGÚRILLS.\p"
    .string "En aðeins Vasaskrímsli geta notað\n"
    .string "tæknina STAÐGENGIL…\p"
    .string "Viltu að ég kenni einu\n"
    .string "Vasaskrímslinu þínu STAÐGENGIL?$"

Text_SubstituteDeclined::
    .string "Ó, í alvöru? STAÐGENGILL virðist\n"
    .string "svo skemmtilegur…$"

Text_SubstituteWhichMon::
    .string "Hvaða Vasaskrímsli vill læra\n"
    .string "SUBSTITUTE?$"

Text_SubstituteTaught::
    .string "Ó, hvað ég gæfi fyrir að skríða í\n"
    .string "poka KENGÚRILLS…$"

FuchsiaCity_Text_MyFatherIsGymLeader::
    .string "Faðir minn er SALARLEIÐTOGI þessa\n"
    .string "bæjar.\p"
    .string "Ég æfi mig líka í að nota EITUR\n"
    .string "Vasaskrímsli, rétt eins og hann.$"
