ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "Sæl/l! Hvernig gengur?\p"
    .string "Hvað er ég að gera hér, spyrðu? Ég\n"
    .string "er að leita að gulli!\p"
    .string "Þegar ég verð ríkur kaupi ég hús í\n"
    .string "KANTO.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "Sæl/l! Hvernig gengur? Heyrðirðu? Ég\n"
    .string "fann gull!\p"
    .string "Þú mundir að ég var að leita, er það\n"
    .string "ekki?\p"
    .string "Þú getur ekki ímyndað þér hvað ég er\n"
    .string "glaður.\p"
    .string "Svo ég sýni þér það! Þetta er fyrir\n"
    .string "þig!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "Þetta er NUGGET!\p"
    .string "Ég get ekki gefið þér neina gullmola\n"
    .string "af visku, svo þetta verður að duga!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "Úbbs, TASKAN þín er troðfull! Ég gef\n"
    .string "þér þetta seinna.$"

