ThreeIsland_Text_IslandSign::
    .string "ÞRJÚ EYJA Frændeyja fjölskyldu banda$"

ThreeIsland_Text_IslandBelongsToUs::
    .string "Hýjú!\p"
    .string "Frá og með deginum í dag tilheyrir\n"
    .string "þessi eyja okkur!$"

ThreeIsland_Text_GoBackToKanto::
    .string "Við þurfum ekki á ykkur að halda sem\n"
    .string "koma með hávaða og vandræði hingað!\p"
    .string "Við biðjum ykkur að fara aftur til\n"
    .string "KANTO!$"

ThreeIsland_Text_BossIsOnHisWay::
    .string "Hæ, farðu að gráta annars staðar.\n"
    .string "Yfirmaðurinn okkar er á leiðinni.\p"
    .string "Þegar hann kemur, munum við sýna þér\n"
    .string "geggjaða mótorhjólasýningu sem þú\p"
    .string "gleymir seint!$"

ThreeIsland_Text_GetOffIslandNow::
    .string "H-hvað!? Aldrei í lífinu! Farðu af\n"
    .string "eyjunni núna!$"

ThreeIsland_Text_WhosGonnaMakeMe::
    .string "Hver ætlar að láta mig?$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
    .string "Ertu yfirmaðurinn? Farðu aftur til\n"
    .string "KANTO strax!$"

ThreeIsland_Text_JustGotHerePal::
    .string "Ha?\p"
    .string "Ég komst bara hingað, vinur.\p"
    .string "Hvað er með þessa fjandsamlegu\n"
    .string "framkomu? Þetta er mjög kalt af þér!$"

ThreeIsland_Text_FollowersRaisingHavoc::
    .string "Gengi fylgjenda þinna hefur verið að\n"
    .string "valda usla á hjólum sínum.\p"
    .string "Hefurðu hugmynd um hversu miklum\n"
    .string "vandræðum þeir hafa valdið okkur á\p"
    .string "eyjunni?$"

ThreeIsland_Text_OughtToBeThankingUs::
    .string "Nei, maður, ég skil þetta alls ekki.\p"
    .string "Skoðaðu þennan stað. Hvað gerirðu\n"
    .string "þér til skemmtunar?\p"
    .string "Þú ættir að þakka okkur fyrir að\n"
    .string "lífga upp á þetta syfjulega þorp.\p"
    .string "En hey, ef þú krefst þess, geturðu\n"
    .string "reynt að láta okkur fara.$"

ThreeIsland_Text_YouCowardsToughInPack::
    .string "Grr… Þið hugleysingjar… Svo harðir\n"
    .string "þegar þið eruð í hóp…$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
    .string "Þú, hvað ertu að glápa á? Veistu\n"
    .string "ekki að það er ókurteist?\p"
    .string "Viltu gera eitthvað úr því eða hvað?$"

ThreeIsland_Text_ThatsSmart::
    .string "Það er snjallt. Haltu þér fyrir utan\n"
    .string "þetta.$"

ThreeIsland_Text_Biker1Intro::
    .string "Heh, mér líkar kjarkurinn í þér. Þú\n"
    .string "tapar peningum til mín, en…$"

ThreeIsland_Text_Biker1Defeat::
    .string "Hva… Hvað er þetta barn?!$"

ThreeIsland_Text_Biker1PostBattle::
    .string "Æ, maður… Ekki voga þér að hlæja!$"

ThreeIsland_Text_Biker2Intro::
    .string "Ertu ekki frá KANTO? Þú ættir að\n"
    .string "vera með okkur!$"

ThreeIsland_Text_Biker2Defeat::
    .string "Hættu að fíflast!$"

ThreeIsland_Text_Biker2PostBattle::
    .string "Hvað er að þér, að verða svona\n"
    .string "heitur?\p"
    .string "Algjörlega ókúl, maður!$"

ThreeIsland_Text_Biker3Intro::
    .string "Við buðum yfirmanninum hingað, en þú\n"
    .string "þurftir að klúðra því!\p"
    .string "Þú skammaðir okkur, maður!$"

ThreeIsland_Text_Biker3Defeat::
    .string "… … … … … …$"

ThreeIsland_Text_Biker3PostBattle::
    .string "Yfirmaður, ég segi þér, þú verður að\n"
    .string "gera eitthvað í sambandi við þetta\p"
    .string "barn!$"

ThreeIsland_Text_PaxtonIntro::
    .string "Ég hef fylgst með þér, og ég myndi\n"
    .string "segja að þú hafir gert nóg.\p"
    .string "Hvað ertu, vinur þeirra eða\n"
    .string "eitthvað?\p"
    .string "Þá giska ég á að þú munir berjast\n"
    .string "við mig í þeirra stað.$"

ThreeIsland_Text_PaxtonDefeat::
    .string "Allt í lagi, nóg! Við förum eins og\n"
    .string "þú vildir!\p"
    .string "Við verðum ánægðir að sjá þessa\n"
    .string "leiðinlegu eyju í síðasta sinn!$"

ThreeIsland_Text_PaxtonPostBattle::
    .string "Humph! Já, haltu bara áfram að hanga\n"
    .string "með þessum sveitapésum!$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
    .string "Takk fyrir! Þessir durgar voru\n"
    .string "ekkert nema vandræði.\p"
    .string "Ó, sjáðu, Vasaskrímslin þín meiddust\n"
    .string "mín vegna.$"

ThreeIsland_Text_GivenFullRestore::
    .string "{PLAYER} fékk FULL RESTORE.$"

ThreeIsland_Text_OhYourBagIsFull::
    .string "Ó? Taskan þín er full.$"

ThreeIsland_Text_YouveGotImpressiveMons::
    .string "Þú ert með virkilega glæsileg\n"
    .string "Vasaskrímsli með þér.$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
    .string "Það væri frábært ef einhver jafn\n"
    .string "sterk/ur og þú byggi hér.\p"
    .string "Ég vona að þú dveljir hér að minnsta\n"
    .string "kosti um stund.\p"
    .string "…Fyrirgefðu? Ertu að leita að\n"
    .string "LOSTELLE?\p"
    .string "LOSTELLE fór í átt að TENGIBRÚ fyrir\n"
    .string "nokkru.\p"
    .string "Þú finnur hana kannski ef þú ferð þá\n"
    .string "leið.$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
    .string "ÞRJÚ EYJAN er í raun sú fjölmennasta\n"
    .string "af eyjunum hér.\p"
    .string "Samt gæti hún verið minna syfjuð.\p"
    .string "En ég myndi ekki vilja sjá skúrka\n"
    .string "eins og þessa BIKERS hér aftur.$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
    .string "Ég ætla að þjálfa PARFUGL minn í\n"
    .string "BERJA SKÓGI.\p"
    .string "Þegar hann þróast ætla ég að spila\n"
    .string "leik á TVÖ EYJU.$"

ThreeIsland_Text_Doduo::
    .string "PARFUGL: Gigiih!$"
