CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "Þetta er mynd af BLAINE og MR. FUJI.\p"
    .string "Þeir standa öxl við öxl og brosa\n"
    .string "breitt.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "Við rannsökum vasaskrímsli ítarlega\n"
    .string "á hverjum degi.\p"
    .string "Fólk kemur oft með sjaldgæf\n"
    .string "vasaskrímsli til skoðunar.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "Mynd af stofnanda\n"
    .string "rannsóknarstofunnar... DR. FUJI?!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "VASASKRÍMSLARANNSÓKNARSTOFA\n"
    .string "Fundarherbergi$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "VASASKRÍMSLARANNSÓKNARSTOFA R & D\n"
    .string "herbergi$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "VASASKRÍMSLARANNSÓKNARSTOFA\n"
    .string "Prófunarherbergi$"

