MtMoon_1F_Text_MarcosIntro::
    .string "VÁ! Þú brá mér! ...Ó, þú ert bara\n"
    .string "krakki!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Vá! Þú brást mér aftur!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "Krakkar eins og þú ættu ekki að ráfa\n"
    .string "hér um í myrkrinu.$"

MtMoon_1F_Text_JoshIntro::
    .string "Komstu líka til að kanna hellinn?$"

MtMoon_1F_Text_JoshDefeat::
    .string "Það er ömurlegt að tapa! Algjörlega\n"
    .string "ókúl.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "Ég kom alla leið hingað niður til að\n"
    .string "sýna mig fyrir stelpum.$"

MtMoon_1F_Text_MiriamIntro::
    .string "Vá! Hér er miklu stærra en ég hélt!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Ó! Ég missti þetta!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "Hvernig kemst maður út héðan? Þetta\n"
    .string "er svo stórt að ég gæti villst.$"

MtMoon_1F_Text_JovanIntro::
    .string "Hvað! Ekki læðast aftan að mér!$"

MtMoon_1F_Text_JovanDefeat::
    .string "Vasaskrímslin mín duga ekki!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "Ég verð að finna sterkari\n"
    .string "vasaskrímsli. Hvar ætli þau séu?$"

MtMoon_1F_Text_IrisIntro::
    .string "Hvað? Ég er að bíða eftir að vinir\n"
    .string "mínir finni mig hér.$"

MtMoon_1F_Text_IrisDefeat::
    .string "Ég tapaði?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "Ég kom því ég heyrði að hér væru\n"
    .string "mjög sjaldgæfir steingervingar.$"

MtMoon_1F_Text_KentIntro::
    .string "Grunsamlegir menn eru í hellinum.\n"
    .string "Hvað með þig?$"

MtMoon_1F_Text_KentDefeat::
    .string "Þú náðir mér!$"

MtMoon_1F_Text_KentPostBattle::
    .string "Ég sá þá! Ég er viss um að þeir eru\n"
    .string "úr ROCKET-GENGINU!$"

MtMoon_1F_Text_RobbyIntro::
    .string "Þú þarft að fara í gegnum þennan\n"
    .string "helli til að komast til CERULEAN\p"
    .string "BORGAR.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "Ég tapaði.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "BLAKILDI er harðgert! En ef þú nærð\n"
    .string "einu geturðu treyst á það.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "Varúð! BLAKILDI sýgur blóð!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Hæ, ég er að grafa eftir\n"
    .string "steingervingum hér undir MT. MOON.\p"
    .string "Stundum hjálpar BROCK úr\n"
    .string "PEWTER-SALNUM mér.$"
