PokemonMansion_B1F_Text_LewisIntro::
    .string "Uh-oh... Hvar er ég núna?$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "Áúú!$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "Þú getur fundið hluti liggjandi hér.\n"
    .string "Íbúarnir hljóta að hafa skilið þá\p"
    .string "eftir.$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "Þessi staður er fullkominn fyrir\n"
    .string "rannsóknarstofu. Sjáðu allt plássið.$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "Til hvers var þetta?$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "Mér líkar hér. Þetta stuðlar að\n"
    .string "rannsóknum mínum.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "Dagbók: 1. sept. TVÍMÝTA er allt of\n"
    .string "kraftmikil.\p"
    .string "Okkur tókst ekki að hemja illvígar\n"
    .string "hneigðir hennar...$"

