SevenIsland_TrainerTower_Text_DarioIntro::
    .string "Ég skynjaði nálgun þína.$"

SevenIsland_TrainerTower_Text_DarioDefeat::
    .string "Gefstu upp…$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .string "Í framtíð þinni skynja ég að þú munt\n"
    .string "hitta marga aðra.\p"
    .string "Ég held að þið verðið tengd saman af\n"
    .string "undarlegum krafti.$"

SevenIsland_TrainerTower_Text_RodetteIntro::
    .string "Einhvers staðar á þessari eyju sofa\n"
    .string "sérkennileg Vasaskrímsli.$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .string "What an amazing ÞJÁLFARI!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .string "Einhvers staðar á þessari eyju sofa\n"
    .string "sérkennileg Vasaskrímsli.\p"
    .string "Gæti verið að þau bíði eftir þér?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .string "INNGANGUR ÞJÁLFARATURNS Taktu\n"
    .string "áskoruninni, ÞJÁLFARAR!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .string "ÞJÁLFARI TOWER AHEAD$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "トレーナータワーには いまは はいれない みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "トレーナータワーが あいてる！ さっそく はいってみよう！$"

