VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "Viltu ekki dást að yndislega halanum\n"
    .string "á LEIFTURSKO mínum?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "Hmph!\p"
    .string "LEIFTURSKO minn er tvöfalt sætari en\n"
    .string "þessi!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "Ég dýrka KÓPANGA minn! Hann er svo\n"
    .string "elskulegur!\p"
    .string "Hann tístir, Kyuuuh, þegar ég knúsa\n"
    .string "hann!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Ó, kæri minn!\p"
    .string "KÓPANGI minn er miklu fallegri.\n"
    .string "Tvöfalt fallegri, myndi ég segja.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "LEIFTURSKO: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "KÓPANGI: Kyuoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "Ég er formaður\n"
    .string "Vasaskrímsla-aðdáendaklúbbsins!\p"
    .string "Ég ala upp meira en hundrað\n"
    .string "vasaskrímsli!\p"
    .string "Ég er mjög vandlátur þegar kemur að\n"
    .string "vasaskrímslum! Sannarlega!\p"
    .string "Svo...\p"
    .string "Komstu í heimsókn til að heyra um\n"
    .string "vasaskrímslin mín?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Gott! Hlustaðu þá!\p"
    .string "Uppáhalds ELDKLÁRINN minn...\p"
    .string "Hann er... sætur... yndislegur...\n"
    .string "klár... og... magnaður... finnst þér\p"
    .string "ekki?... ó já... hann er...\n"
    .string "stórkostlegur... blíður... ég elska\p"
    .string "hann!\p"
    .string "Knúsa hann... þegar hann sefur...\n"
    .string "hlýr og mjúkur... glæsilegur...\p"
    .string "hrífandi... ...Úps! Sjáðu hvað\n"
    .string "klukkan er orðin! Ég hélt þér of\p"
    .string "lengi!\p"
    .string "Takk fyrir að hlusta á mig! Ég vil\n"
    .string "að þú fáir þetta!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} fékk REIÐHJÓLSMIÐA frá\n"
    .string "FORMANNINUM.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Farðu með REIÐHJÓLSMIÐANN í\n"
    .string "HJÓLABÚÐINA í CERULEAN BORG.\p"
    .string "Skiptu honum fyrir REIÐHJÓL, alveg\n"
    .string "ókeypis!\p"
    .string "Ekki hafa áhyggjur, uppáhalds\n"
    .string "GEIGHEGRINN minn getur FLY mig hvert\p"
    .string "sem ég þarf að fara.\p"
    .string "Þannig að ég þarf ekkert REIÐHJÓL.\p"
    .string "Ég vona að þér líki að hjóla!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Ó. Komdu aftur þegar þú vilt heyra\n"
    .string "söguna mína!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Halló, {PLAYER}!\p"
    .string "Komstu aftur til að heyra um\n"
    .string "vasaskrímslin mín?\p"
    .string "Nei? Verst!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Gerðu pláss fyrir þetta!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "FORMANNINUM okkar verður tíðrætt um\n"
    .string "vasaskrímsli.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Við skulum öll hlusta kurteislega á\n"
    .string "aðra ÞJÁLFARA!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "Ef einhver montar sig, montaðu þig\n"
    .string "þá á móti!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "FORMANNINUM okkar þykir sannarlega\n"
    .string "vænt um vasaskrímslin sín.\p"
    .string "En manneskjan sem vasaskrímslum\n"
    .string "líkar best við er DAISY, held ég.$"
