FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
    .string "VÖRÐUR SAFARI SVÆÐISINS er gamall,\n"
    .string "en hann er enn mjög virkur.\p"
    .string "Allar tennurnar hans eru þó\n"
    .string "gervitennur.$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
    .string "Hmm? Hefurðu hitt BILL?\p"
    .string "Hann er barnabarn mitt!\p"
    .string "Hann hafði alltaf gaman af því að\n"
    .string "safna hlutum, jafnvel sem barn!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
    .string "BILL skráir eigin Vasaskrímslagögn á\n"
    .string "PC tölvuna sína.\p"
    .string "Sýndi hann þér það?$"

