Route7_EastEntrance_Text_ThirstyOnGuardDuty::
    .string "Ég er á vakt. Úff, ég er þyrstur,\n"
    .string "þó!\p"
    .string "Ó, bíddu þarna, vegurinn er lokaður.$"

Route7_EastEntrance_Text_ThatTeaLooksTasty::
    .string "Ó, þetta TE… Það lítur hræðilega vel\n"
    .string "út…$"

Route7_EastEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Ha? Má ég fá þennan drykk? Vá, takk!\n"
    .string "… … Glugg, glugg… … … Gulp…\p"
    .string "Ef þú vilt fara til SAFFRON BORGAR…\n"
    .string "… … Þú mátt fara í gegn.\p"
    .string "Ég deili þessu TE með hinum\n"
    .string "vörðunum!$"

Route7_EastEntrance_Text_HiHowsItGoing::
    .string "Hæ, hvað segirðu?$"

