SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
    .string "Dóttir mín er svo sjálfhverf. Hún á\n"
    .string "aðeins fáa vini.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
    .string "Dóttir mín hefur gaman af að herma\n"
    .string "eftir fólki. Það er frekar pirrandi.\p"
    .string "Eftirherman hennar hefur fært henni\n"
    .string "gælunafnið COPYCAT hérna í kring.$"

SaffronCity_CopycatsHouse_1F_Text_Chansey::
    .string "SÆLEGG: Chaan! Sii!$"

