PokemonTower_7F_Text_Grunt1Intro::
    .string "Hvað viltu? Af hverju ertu hér?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "Ég gefst upp!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "Ég mun ekki gleyma þessu!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "Þessi gamli maður ruddist beint inn\n"
    .string "í FELUSTAÐINN okkar.\p"
    .string "Svo fór hann að rausa um að\n"
    .string "ROCKET-GENGIÐ misnotaði\p"
    .string "Vasaskrímsli.\p"
    .string "Við erum bara að ræða þetta eins og\n"
    .string "fullorðið fólk.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "Vinsamlegast! Ekki meira!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "Vasaskrímsli eru bara góð til að\n"
    .string "græða peninga. Af hverju ekki að\p"
    .string "nota þau?\p"
    .string "Haltu þér frá okkar málum!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "Þú ert ekki að bjarga neinum,\n"
    .string "krakki!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "Ekki berjast við okkur ROCKETS!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "Þú kemst ekki upp með þetta!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "MR. FUJI: Ha? Komstu til að bjarga\n"
    .string "mér?\p"
    .string "Takk fyrir. En ég kom hingað af\n"
    .string "fúsum og frjálsum vilja.\p"
    .string "Ég kom til að róa anda móður\n"
    .string "BEINFARA.\p"
    .string "Ég held að andi HNAUSKÚPU hafi loks\n"
    .string "yfirgefið okkur.\p"
    .string "Ég verð að þakka þér fyrir\n"
    .string "umhyggjuna.\p"
    .string "Fylgdu mér heim til mín, í\n"
    .string "VASASKRÍMSLAHÚS við rætur\p"
    .string "turnsins.$"
