PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "Já, já. Barnamiði kostar ¥50.\p"
    .string "Viltu koma inn?$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "Komdu aftur!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "Rétt, ¥50! Takk fyrir!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "Þú átt ekki næga peninga.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "Góða skemmtun.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "Þú getur ekki laumast inn\n"
    .string "bakdyramegin! Góð tilraun, krakki,\p"
    .string "en nei.\p"
    .string "Æ, hvað um það! Veistu hvað AMBER\n"
    .string "er?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "AMBER inniheldur erfðaefni fornra\n"
    .string "vasaskrímsla.\p"
    .string "Einhvers staðar er RANNSÓKNARSTOFA\n"
    .string "að reyna að endurlífga vasaskrímsli\p"
    .string "úr AMBER.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "AMBER er í raun trjákvoða, klístraða\n"
    .string "efnið sem lekur úr trjám.\p"
    .string "Forn trjákvoða steingerðist með\n"
    .string "tímanum og varð að grjóthörðu AMBER.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "Vinsamlegast farðu hringinn.$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "Ég ætti að vera þakklátur fyrir\n"
    .string "langa ævi.\p"
    .string "Aldrei hélt ég að ég fengi að sjá\n"
    .string "bein dreka!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "Suss! Heyrðu, ég þarf að deila\n"
    .string "leyndarmáli með einhverjum.\p"
    .string "Ég held að þessi AMBER-klumpur\n"
    .string "innihaldi DNA úr vasaskrímsli!\p"
    .string "Það yrði stórkostlegt vísindalegt\n"
    .string "gegnumbrot ef hægt væri að\p"
    .string "endurlífga vasaskrímsli úr honum.\p"
    .string "En samstarfsfólk mitt hunsar bara\n"
    .string "það sem ég segi.\p"
    .string "Svo ég þarf að biðja þig greiða!\p"
    .string "Ég vil að þú látir rannsaka þetta á\n"
    .string "einhverri rannsóknarstofu fyrir\p"
    .string "vasaskrímsli.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "{PLAYER} fékk OLD AMBER frá\n"
    .string "manninum.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "Suss! Láttu skoða OLD AMBER!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "Þú hefur ekki pláss fyrir þetta.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "Við sýnum tvo steingervinga\n"
    .string "sjaldgæfra, forsögulegra\p"
    .string "vasaskrímsla.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "Þarna er fallegur AMBER-klumpur í\n"
    .string "tærum gullnum lit.$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "HIMINVÁ steingervingur Frumstætt og\n"
    .string "sjaldgæft vasaskrímsli.$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "DJÚPSAXI steingervingur Frumstætt og\n"
    .string "sjaldgæft vasaskrímsli.$"

