SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .string "Dans, dans! SÆLEGG-dans!\p"
    .string "Vertu með líka! Dans, dans!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .string "Viltu dansa?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .string "Komdu, dansaðu!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
    .string "{PLAYER} dansaði SÆLEGG-dansinn!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .string "Ahahahaha!\p"
    .string "Þarna, þú ert öll hress núna!\n"
    .string "Heppinn!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
    .string "SÆLEGG: Chansi! Chansi!$"
