VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "Ég læt DÚFUTETUR minn fljúga með\n"
    .string "bréf til SAFFRON í norðri.$"

VermilionCity_House3_Text_Pidgey::
    .string "DÚFUTETUR: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Kæra PIPPI, ég vona að ég sjái þig\n"
    .string "brátt.\p"
    .string "Ég heyrði að SAFFRON ætti í\n"
    .string "vandræðum með ROCKET-GENGIÐ.\p"
    .string "VERMILION virðist vera örugg.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "Ég vil skiptast á BRÉFUM við alls\n"
    .string "konar fólk.\p"
    .string "Ég sendi DÚFUTETUR minn í UNION ROOM\n"
    .string "til að skipta á BRÉFUM fyrir mig.$"

