Route18_Text_WiltonIntro::
    .string "Ég skoða alltaf hvert graslendi\n"
    .string "eftir nýjum vasaskrímslum.$"

Route18_Text_WiltonDefeat::
    .string "Tsk!$"

Route18_Text_WiltonPostBattle::
    .string "Ég vildi að ég ætti HJÓL!$"

Route18_Text_RamiroIntro::
    .string "Kurukkoo! Hvernig líst þér á\n"
    .string "fuglakallið mitt?$"

Route18_Text_RamiroDefeat::
    .string "Ég varð að angra þig!$"

Route18_Text_RamiroPostBattle::
    .string "Ég safna sjó-vasaskrímslum um helgar\n"
    .string "því sjórinn er svo nálægt.$"

Route18_Text_JacobIntro::
    .string "Þetta er mitt svæði! Komdu þér\n"
    .string "héðan!$"

Route18_Text_JacobDefeat::
    .string "Fjandinn!$"

Route18_Text_JacobPostBattle::
    .string "Þetta er uppáhaldssvæðið mitt til að\n"
    .string "ná vasaskrímslum.$"

Route18_Text_RouteSign::
    .string "LEIÐ 18 CELADON BORG - FUCHSIA BORG$"

Route18_Text_CyclingRoadSign::
    .string "HJÓLAVEGUR Gangandi vegfarendur\n"
    .string "bannaðir!$"

