Text_SeismicTossTeach::
    .string "Leyndardómar geimsins...\n"
    .string "Leyndardómar jarðar...\p"
    .string "Það er svo margt sem við vitum lítið\n"
    .string "um.\p"
    .string "En það ætti að hvetja okkur til að\n"
    .string "læra meira, ekki gefast upp.\p"
    .string "Það eina sem þú ættir að kasta...\p"
    .string "Jæja, hvað með JARÐSKJÁLFTAKAST?\n"
    .string "Á ég að\n"
    .string "kenna vasaskrímsli það?$"

Text_SeismicTossDeclined::
    .string "Er það svo? Ég er viss um að þú\n"
    .string "kemur aftur eftir því.$"

Text_SeismicTossWhichMon::
    .string "Hvaða vasaskrímsli vill læra\n"
    .string "JARÐSKJÁLFTAKAST?$"

Text_SeismicTossTaught::
    .string "Ég vona að þú gefist ekki upp. Haltu\n"
    .string "áfram.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "TUNGLSTEINN, ha?\p"
    .string "Hvað er svona sérstakt við hann?\n"
    .string "Hann lítur út eins og venjulegur\p"
    .string "steinn fyrir mér.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "20. júlí 1969!\p"
    .string "Mannkyn steig fyrst fæti á tunglið\n"
    .string "þann dag.\p"
    .string "Ég keypti litasjónvarp bara til að\n"
    .string "horfa á fréttirnar.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "Í þessum mánuði erum við með\n"
    .string "geimsýningu.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "Mig langar í LEIFTURSKOTTA!\n"
    .string "Það er svo krúttlegt!\p"
    .string "Ég bað pabba að ná\n"
    .string "LEIFTURSKOTTA fyrir mig!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Já, þú færð LEIFTURSKOTTA\n"
    .string "bráðum, ég lofa!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "Geimskutla$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "Loftsteinn sem féll á MT. MOON.\n"
    .string "Talið er að hann sé TUNGLSTEINN.$"
