SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "Ah! Loksins!\p"
    .string "Þú ert fyrsta manneskjan til að ná\n"
    .string "til LEYNDARHÚSSINS!\p"
    .string "Þótt ég hafi gert herferð fyrir\n"
    .string "okkar stórkostlegu opnun,\p"
    .string "var ég farinn að hafa áhyggjur af\n"
    .string "því að enginn myndi vinna\p"
    .string "herferðarverðlaunin okkar.\p"
    .string "Til hamingju! Þú hefur unnið!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
    .string "{PLAYER} fékk HM03 frá þjóninum!$"

SafariZone_SecretHouse_Text_ExplainSurf::
    .string "HM03 er BRIM.\p"
    .string "Vasaskrímsli getur flutt þig yfir\n"
    .string "vatn með henni.\p"
    .string "Og þessi HM eyðist ekki, svo þú\n"
    .string "getur notað hana aftur og aftur.\p"
    .string "Þú ert ofboðslega heppin/n að vinna\n"
    .string "þessi frábæru verðlaun!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "Þú hefur ekki pláss fyrir þessi\n"
    .string "frábæru verðlaun!$"

