Route19_Text_RichardIntro::
    .string "Ég þarf að æfa mig og hita upp áður\n"
    .string "en ég fer út að synda.$"

Route19_Text_RichardDefeat::
    .string "Alveg orðinn heitur!$"

Route19_Text_RichardPostBattle::
    .string "Takk, krakki! Ég er tilbúinn í sund.$"

Route19_Text_ReeceIntro::
    .string "Bíddu! Hægðu á þér! Þú færð\n"
    .string "hjartaáfall!$"

Route19_Text_ReeceDefeat::
    .string "Úú! Þetta er kalt!$"

Route19_Text_ReecePostBattle::
    .string "Passaðu þig á HOLSEPI. Þau stinga\n"
    .string "svo sársaukafullt.$"

Route19_Text_MatthewIntro::
    .string "Ég elska sund! Hvað með þig?$"

Route19_Text_MatthewDefeat::
    .string "Magalending!$"

Route19_Text_MatthewPostBattle::
    .string "Ég get meira að segja unnið\n"
    .string "sjó-vasaskrímsli í sundi.$"

Route19_Text_DouglasIntro::
    .string "Hvað er handan sjóndeildarhringsins?$"

Route19_Text_DouglasDefeat::
    .string "Glúbb!$"

Route19_Text_DouglasPostBattle::
    .string "Ég sé nokkrar eyjar þarna úti!$"

Route19_Text_DavidIntro::
    .string "Ég reyndi að kafa eftir\n"
    .string "vasaskrímslum, en það gekk ekkert.$"

Route19_Text_DavidDefeat::
    .string "Hjálp!$"

Route19_Text_DavidPostBattle::
    .string "Ætli maður þurfi að veiða\n"
    .string "sjó-vasaskrímsli.$"

Route19_Text_TonyIntro::
    .string "Ég horfi á sjóinn til að gleyma öllu\n"
    .string "slæmu sem gerðist.$"

Route19_Text_TonyDefeat::
    .string "Úú! Áfall!$"

Route19_Text_TonyPostBattle::
    .string "Ég horfi á sjóinn til að gleyma því\n"
    .string "slæma sem gerðist!$"

Route19_Text_AnyaIntro::
    .string "Ó, ég elska fararskjótann þinn! Má\n"
    .string "ég fá hann ef ég vinn?$"

Route19_Text_AnyaDefeat::
    .string "Ó! Ég tapaði!$"

Route19_Text_AnyaPostBattle::
    .string "Það er enn langt til SEAFOAM EYJA...\p"
    .string "Mig langar aftur til FUCHSIA...$"

Route19_Text_AliceIntro::
    .string "Sund er frábært! Sólbruni er það\n"
    .string "ekki!$"

Route19_Text_AliceDefeat::
    .string "Stuð!$"

Route19_Text_AlicePostBattle::
    .string "Kærastinn minn vildi synda til\n"
    .string "SEAFOAM EYJA.$"

Route19_Text_AxleIntro::
    .string "Ahoy, þarna! Þessi vötn eru varasöm!$"

Route19_Text_AxleDefeat::
    .string "Úú! Hættulegt!$"

Route19_Text_AxlePostBattle::
    .string "F-fæturnir mínir! Þeir krumpuðust!\n"
    .string "Glúbb, glúbb...$"

Route19_Text_ConnieIntro::
    .string "Ég synti hingað með vinum mínum...\n"
    .string "Ég er þreytt...$"

Route19_Text_ConnieDefeat::
    .string "Ég er örmagna...$"

Route19_Text_ConniePostBattle::
    .string "Ef ég ætti að ríða vasaskrímsli á\n"
    .string "sjónum myndi ég vilja LAGARGANDU.\p"
    .string "LAGARGANDU er svo stór að ég veðja\n"
    .string "að hún héldi mér þurrum á vatninu.$"

Route19_Text_RouteSign::
    .string "SJÓLEIÐ 19 FUCHSIA BORG - SEAFOAM\n"
    .string "EYJAR$"

Route19_Text_LiaIntro::
    .string "LIA: Ég passa litla bróður minn.\n"
    .string "Hann varð nýlega ÞJÁLFARI.$"

Route19_Text_LiaDefeat::
    .string "LIA: Svona kemur maður ekki fram við\n"
    .string "litla bróður minn!$"

Route19_Text_LiaPostBattle::
    .string "LIA: Áttu yngri bróður?\p"
    .string "Ég vona að þú sért að kenna honum\n"
    .string "alls konar hluti.$"

Route19_Text_LiaNotEnoughMons::
    .string "LIA: Ég vil berjast með litla bróður\n"
    .string "mínum.\p"
    .string "Áttu ekki tvö vasaskrímsli?$"

Route19_Text_LucIntro::
    .string "LUC: Stóra systir kenndi mér að\n"
    .string "synda og þjálfa vasaskrímsli.$"

Route19_Text_LucDefeat::
    .string "LUC: Ó, vá! Einhver sterkari en\n"
    .string "stóra systir!$"

Route19_Text_LucPostBattle::
    .string "LUC: Stóra systir er sterk og góð.\n"
    .string "Mér finnst hún frábær!$"

Route19_Text_LucNotEnoughMons::
    .string "LUC: Ég vil ekki gera þetta nema ég\n"
    .string "geti barist við þig með stóru\p"
    .string "systur.\p"
    .string "Áttu ekki tvö vasaskrímsli?$"
