VictoryRoad_1F_Text_NaomiIntro::
    .string "Ég velti því fyrir mér hvort þú sért\n"
    .string "nógu fær fyrir mig?$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "Ég tapaði…$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "Ég vildi aldrei tapa fyrir neinum,\n"
    .string "síst af öllu yngra barni…$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "Ég sé að þú ert fær. Leyfðu mér að\n"
    .string "sjá nákvæmlega hversu fær!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "Ég átti möguleika…$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "Tsk! Ég viðurkenni það, þú ert\n"
    .string "betri en ég!$"
