SevenIsland_TanobyRuins_Text_BrandonIntro::
    .string "Veistu eitthvað um þetta\n"
    .string "steinherbergi?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
    .string "Þetta var óþarfi. Þú þurftir ekki að\n"
    .string "vera svona harkaleg/ur.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
    .string "TANOBY-RÚSTIRNAR eru a.m.k. 1.500\n"
    .string "ára gamlar.\p"
    .string "En það er enn ráðgáta hvers vegna\n"
    .string "þær voru byggðar.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
    .string "Sagt er að dulrænt Vasaskrímsli sofi\n"
    .string "hér inni.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
    .string "Ég er ekki mjög góður í bardaga.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
    .string "Ég heyri að til séu aðrar rústir\n"
    .string "eins og þessar.\p"
    .string "Gætu þær verið hvílustaðir annarra\n"
    .string "dulrænna Vasaskrímsla?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
    .string "CLIFFORD er að kenna mér að mála.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
    .string "Við gætum lent í vandræðum fyrir að\n"
    .string "vera hávær hér.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
    .string "Ég sagðist vilja mála gamla\n"
    .string "byggingu.\p"
    .string "Þess vegna kom CLIFFORD með mig\n"
    .string "hingað.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
    .string "Í dag komum við, auk kennslunnar,\n"
    .string "til að skoða hólfið.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
    .string "Mín, hversu óvenjulegt.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
    .string "Ah, svo þú ert að rannsaka\n"
    .string "Vasaskrímsli upp á eigin spýtur…\p"
    .string "Já, þú ert sannarlega óvenjuleg\n"
    .string "manneskja.$"
