CeruleanCity_House1_Text_AnyInterestInBerries::
    .string "Ég blanda alls konar lyf úr\n"
    .string "BERJADUFTI.\p"
    .string "Með góðu BERJADUFTI get ég búið til\n"
    .string "hvaða lyf sem er.\p"
    .string "Segðu mér nú, hefurðu áhuga á\n"
    .string "BERJUM?$"

CeruleanCity_House1_Text_HaveJustTheThing::
    .string "Ah, gott! Þá hef ég einmitt rétta\n"
    .string "hlutinn fyrir þig.$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
    .string "Það er eitthvað nýtt á annarri hæð\n"
    .string "vasaskrímslamiðstöðva, í DIRECT\p"
    .string "CORNER.\p"
    .string "Þar var sett upp Wireless Adapter\n"
    .string "vél til að mylja BER.\p"
    .string "Þarna kemur þú til sögunnar.\p"
    .string "Ég þarf að biðja þig um greiða sem\n"
    .string "ég get aðeins treyst þér fyrir.\p"
    .string "Geturðu búið til BERJADUFT fyrir mig\n"
    .string "með vélinni?\p"
    .string "Ekki gleyma, vélin er í DIRECT\n"
    .string "CORNER í vasaskrímslamiðstöðvum.\p"
    .string "Ég blanda lyf fyrir þig ef þú kemur\n"
    .string "með BERJADUFT.\p"
    .string "Ekki gleyma, myldu BER í BERJADUFT\n"
    .string "og komdu með það til mín.$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
    .string "Hvers vegna þarftu að ljúga að mér?\p"
    .string "Hvað ertu með mörg BER? Ekki eitt\n"
    .string "einasta!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
    .string "Hefurðu engan áhuga á BERJUM?\p"
    .string "Unga manneskja, það er mikilvægt að\n"
    .string "sýna alls konar hlutum áhuga.$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
    .string "Hrm! Komstu með BERJADUFT handa mér?$"

CeruleanCity_House5_Text_ExchangeWithWhat::
    .string "Fyrir hvað viltu skipta því?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
    .string "Gott, þú ætlar að skipta\n"
    .string "BERJADUFTINU þínu fyrir eitt\p"
    .string "{STR_VAR_1}?$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
    .string "Hm? Þú átt ekki nóg BERJADUFT.$"

CeruleanCity_House1_Text_TradeMoreBerryPowder::
    .string "Þetta er sannarlega fínt BERJADUFT.\n"
    .string "Það verður að frábæru lyfi.\p"
    .string "Viltu skipta meira BERJADUFTI fyrir\n"
    .string "eitthvað annað?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain::
    .string "Það er allt í lagi. Ég vona að þú\n"
    .string "komir aftur.$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
    .string "Komdu til mín ef þú vilt skipta\n"
    .string "BERJADUFTINU þínu.$"

