Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Mörg vasaskrímsli lifa aðeins í\n"
    .string "skógum og hellum.\p"
    .string "Þú þarft að vera þrautseigur og\n"
    .string "leita alls staðar til að finna\p"
    .string "ólíkar gerðir.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Hefurðu tekið eftir mjóu trjánum við\n"
    .string "veginn?\p"
    .string "Ég heyri að sérstök\n"
    .string "vasaskrímslahreyfing geti fellt þau.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Þekkirðu tæknina til að stöðva\n"
    .string "þróun?\p"
    .string "Þegar vasaskrímsli er að þróast\n"
    .string "geturðu stöðvað ferlið.\p"
    .string "Þetta er tækni til að ala upp\n"
    .string "vasaskrímsli eins og þau eru.$"

