Route20_Text_BarryIntro::
    .string "Vatnið er grunnt hér. Margt fólk er\n"
    .string "að synda.$"

Route20_Text_BarryDefeat::
    .string "Skvamp!$"

Route20_Text_BarryPostBattle::
    .string "Ég vildi að ég gæti riðið\n"
    .string "vasaskrímslinu mínu. Ég veðja að þú\p"
    .string "sért ekki þreyttur.$"

Route20_Text_ShirleyIntro::
    .string "SJÁVARFROÐU EYJAR eru kyrrlátur\n"
    .string "felustaður. Ég er í fríi hér.$"

Route20_Text_ShirleyDefeat::
    .string "Hættu þessu!$"

Route20_Text_ShirleyPostBattle::
    .string "Það er risastór hellir undir þessari\n"
    .string "eyju.$"

Route20_Text_TiffanyIntro::
    .string "Ég elska að fljóta með fiskunum hér\n"
    .string "á öldunum.$"

Route20_Text_TiffanyDefeat::
    .string "Ái!$"

Route20_Text_TiffanyPostBattle::
    .string "Viltu fljóta með mér?$"

Route20_Text_IreneIntro::
    .string "Ertu líka í fríi?$"

Route20_Text_IreneDefeat::
    .string "Engin miskunn!$"

Route20_Text_IrenePostBattle::
    .string "SJÁVARFROÐA var ein stór eyja í\n"
    .string "fjarlægri fortíð.$"

Route20_Text_DeanIntro::
    .string "Skoðaðu stælta skrokkinn minn!$"

Route20_Text_DeanDefeat::
    .string "Aumingjalegt!$"

Route20_Text_DeanPostBattle::
    .string "Ég hefði átt að styrkja\n"
    .string "vasaskrímslin mín, ekki sjálfan mig!$"

Route20_Text_DarrinIntro::
    .string "Af hverju ríðurðu vasaskrímsli?\n"
    .string "Kanntu ekki að synda?$"

Route20_Text_DarrinDefeat::
    .string "Ái! Torpedó!$"

Route20_Text_DarrinPostBattle::
    .string "Það lítur sannarlega skemmtilega út\n"
    .string "að ríða vasaskrímsli!$"

Route20_Text_RogerIntro::
    .string "Ég reið fugla-vasaskrímslinu mínu\n"
    .string "hingað.$"

Route20_Text_RogerDefeat::
    .string "Ó, nei! Hvað á ég nú að gera?$"

Route20_Text_RogerPostBattle::
    .string "Fuglarnir mínir eru örmagna. Þeir\n"
    .string "geta ekki flogið mér til baka!$"

Route20_Text_NoraIntro::
    .string "Kærastinn minn gaf mér stórar\n"
    .string "perlur.$"

Route20_Text_NoraDefeat::
    .string "Ó, nei! Perlurnar mínar voru í þeim!$"

Route20_Text_NoraPostBattle::
    .string "Munu perlurnar mínar stækka inni í\n"
    .string "VÍGULKERI?$"

Route20_Text_MissyIntro::
    .string "Ég synti hingað frá CINNABAR EYJU.\n"
    .string "Það var ekki auðvelt, segi ég þér.$"

Route20_Text_MissyDefeat::
    .string "Ég er svo vonsvikin!$"

Route20_Text_MissyPostBattle::
    .string "Vasaskrímsli hafa lagt undir sig\n"
    .string "yfirgefið herrasetur á CINNABAR.\p"
    .string "Þau kalla það\n"
    .string "VASASKRÍMSLAHERRASETRIÐ núna.$"

Route20_Text_MelissaIntro::
    .string "CINNABAR í vestri er með\n"
    .string "rannsóknarstofu fyrir vasaskrímsli.\p"
    .string "Pabbi minn vinnur þar.$"

Route20_Text_MelissaDefeat::
    .string "Bíddu! Þú átt að bíða!$"

Route20_Text_MelissaPostBattle::
    .string "CINNABAR er eldfjallaeyja.\p"
    .string "Ég heyrði að hún hafi risið úr\n"
    .string "sjónum þegar eldfjall gaus.$"

Route20_Text_SeafoamIslands::
    .string "SJÁVARFROÐU EYJAR$"

Route20_Text_MistyTrainsHere::
    .string "Sterkir ÞJÁLFARAR og\n"
    .string "VATNS-vasaskrímsli sjást oft hér um\p"
    .string "slóðir.\p"
    .string "Þeir segja að MISTY úr CERULEAN SAL\n"
    .string "æfi hér.$"
