SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .string "Þú, mon petit! Við erum upptekin\n"
    .string "hér! Úr vegi!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
    .string "Ég sá skrýtið BER í ruslinu. Ég\n"
    .string "velti fyrir mér hvað það var.$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .string "Ég er svo upptekinn að mig svimar!\n"
    .string "Þú verður að gefa mér pláss hér!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .string "Hum-de-hum-de-ho…\p"
    .string "Ég flysja kartöflur á hverjum degi!\n"
    .string "Hum-hum…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
    .string "Heyrðirðu um HROTÞURS? Hann er\n"
    .string "mathákur.\p"
    .string "Ekkert annað vasaskrímsli borðar og\n"
    .string "sefur eins og HROTÞURS getur og\p"
    .string "gerir!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .string "Snökt… Snökt…\p"
    .string "Ég fæ bara að flysja lauk… Snökt…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .string "Hrm! Sannarlega er ég le KOKKUR!\p"
    .string "Le aðalrétturinn er$"

SSAnne_Kitchen_Text_SalmonDuSalad::
    .string "Laxasalat!\p"
    .string "Gestirnir gætu kvartað yfir því að\n"
    .string "þetta sé fiskur aftur, samt!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .string "Grillaðir álar!\p"
    .string "Ég óttast að les gestir geri\n"
    .string "uppreisn.$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .string "Fyrsta flokks nautasteik!\p"
    .string "En hef ég nóg af nautafille?$"
