SilphCo_2F_Text_ConnorIntro::
    .string "Hjálp! Ég er starfsmaður SILPH.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "Hvernig vissirðu að ég væri ROCKET?$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "Ég vinn bæði fyrir SILPH og\n"
    .string "ROCKET-GENGIÐ.$"

SilphCo_2F_Text_JerryIntro::
    .string "Hér er bannaður aðgangur! Farðu heim!$"

SilphCo_2F_Text_JerryDefeat::
    .string "Þú ert fær.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "Geturðu leyst völundarhúsið hér?\n"
    .string "Það er ekki auðvelt, skal ég segja þér!$"

SilphCo_2F_Text_Grunt1Intro::
    .string "Börn mega ekki vera hér inni!$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "Harður slagur!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "Tígullaga flísarnar eru\n"
    .string "fjarflutningsblokkir.\p"
    .string "Þær eru flutningstæki fyrir þessa\n"
    .string "hátæknibyggingu.$"

SilphCo_2F_Text_Grunt2Intro::
    .string "Hei, krakki! Hvað ertu að ráfa\n"
    .string "hérna?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "Ég klúðraði!$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "SILPH CO. verður tengt\n"
    .string "ROCKET-GENGINU!$"

Text_ThunderWaveTeach::
    .string "Ííík! Nei! Hættu! Hjálp!\p"
    .string "Ó, þú ert ekki með ROCKET-GENGINU.\n"
    .string "Fyrirgefðu, ég hélt…\p"
    .string "Fyrirgefurðu mér ef ég kenni þér\n"
    .string "ELDINGABYLGJU?$"

Text_ThunderWaveDeclined::
    .string "Ó… En ELDINGABYLGJA er svo nytsamleg…$"

Text_ThunderWaveWhichMon::
    .string "Hvaða Vasaskrímsli á ég að kenna\n"
    .string "ELDINGABYLGJU?$"

Text_ThunderWaveTaught::
    .string "ELDINGABYLGJA veldur lömun hjá\n"
    .string "mark-Vasaskrímslinu.\p"
    .string "Lamað Vasaskrímsli getur stundum\n"
    .string "ekki hreyft sig í bardaga.\p"
    .string "Þetta er RAF-gerðar bragð, svo það\n"
    .string "virkar ekki á sum Vasaskrímsli.$"

SilphCo_2F_Text_FloorSign::
    .string "SILPH CO. HÖFUÐSKRIFSTOFA 2H$"
