Route21_South_Text_JackIntro::
	.string "Ég náði vasaskrímslinu mínu úti á\n"
	.string "sjó.$"

Route21_South_Text_JackDefeat::
	.string "Kafari!! Niður!!$"

Route21_South_Text_JackPostBattle::
	.string "Hvar náðir þú vasaskrímslinu þínu?$"

Route21_South_Text_JeromeIntro::
	.string "Núna er ég í þríþrautarmóti.$"

Route21_South_Text_JeromeDefeat::
	.string "Más... Más... Más...$"

Route21_South_Text_JeromePostBattle::
	.string "Ég er búinn! En ég á enn\n"
	.string "hjólakeppnina og maraþonið eftir!$"

Route21_South_Text_RolandIntro::
	.string "Ahh! Finndu sólina og vindinn!$"

Route21_South_Text_RolandDefeat::
	.string "Vá! Ég tapaði!$"

Route21_South_Text_RolandPostBattle::
	.string "Ég er brunninn eins og skorpa!$"

Route21_South_Text_ClaudeIntro::
	.string "Hey, ekki fæla fiskana burt!$"

Route21_South_Text_ClaudeDefeat::
	.string "Fyrirgefðu! Ég er bara svo pirraður\n"
	.string "yfir að ná engu.$"

Route21_South_Text_ClaudePostBattle::
	.string "Ansans, ég hef ekki náð neinu.\p"
	.string "Gæti þessi staður í raun verið\n"
	.string "risastór sundlaug eða eitthvað?$"

Route21_South_Text_NolanIntro::
	.string "Haltu mér félagsskap þar til það\n"
	.string "bítur.$"

Route21_South_Text_NolanDefeat::
	.string "Þetta drap smá tíma.$"

Route21_South_Text_NolanPostBattle::
	.string "Ó, bíddu! Það beit á! Já!$"

Route21_North_Text_LilIntro::
	.string "LIL: Ha? Bardagi? IAN, geturðu ekki\n"
	.string "gert þetta einn?$"

Route21_North_Text_LilDefeat::
	.string "LIL: Ó, sérðu? Við töpuðum. Ánægður\n"
	.string "núna?$"

Route21_North_Text_LilPostBattle::
	.string "LIL: Ég er þreytt. Getum við ekki\n"
	.string "farið heim nú þegar?$"

Route21_North_Text_LilNotEnoughMons::
	.string "LIL: Ha? Bardagi? Ég nenni ekki að\n"
	.string "gera þetta ein.\p"
	.string "Komdu með tvö vasaskrímsli, viltu?$"

Route21_North_Text_IanIntro::
	.string "IAN: Systir mín hreyfir sig ekki\n"
	.string "nóg, svo ég lét hana koma.$"

Route21_North_Text_IanDefeat::
	.string "IAN: Æææ, systir! Taktu þig saman!$"

Route21_North_Text_IanPostBattle::
	.string "IAN: Komdu nú, systir!\p"
	.string "Þú léttist ekki svona!$"

Route21_North_Text_IanNotEnoughMons::
	.string "IAN: Við viljum tveir-á-tveir\n"
	.string "bardaga. Geturðu komið með tvö\p"
	.string "vasaskrímsli?$"
