FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
    .string "Þú ferðast út um allt, er það ekki?\p"
    .string "Þú ert ekki að keyra Vasaskrímslin\n"
    .string "þín of hart, er það?\p"
    .string "Leyfðu mér að skoða þau. … … … … … …$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
    .string "Ah, hmm… Ég skil, ég skil…$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
    .string "Ó, glæsilegt. Þú kemur vel fram við\n"
    .string "Vasaskrímslin þín.\p"
    .string "Ég held að hægt sé að treysta þér\n"
    .string "fyrir þessu.\p"
    .string "Vinsamlegast, ég vil að þú eigir\n"
    .string "þetta.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
    .string "{PLAYER} fékk EGG frá manninum!$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
    .string "…Því miður er ekki pláss fyrir þetta\n"
    .string "í hópnum þínum.\p"
    .string "Þú ættir að koma aftur eftir því\n"
    .string "seinna.$"

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
    .string "やあ タマゴを もらいに きて くれたんだね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
    .string "Ég fékk þetta EGG á ferðalögum\n"
    .string "mínum.\p"
    .string "Ég er ánægð að hafa hitt einhvern\n"
    .string "eins og þig.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
    .string "Ó, sæll. Þetta er krúttlegt\n"
    .string "{STR_VAR_2}.\p"
    .string "Að sjá það minnir mig á ljúfa litla\n"
    .string "stelpu sem ég hitti á ferðalagi.\p"
    .string "Hún snyrti Vasaskrímsli af mikilli\n"
    .string "umhyggju… Hún var eins og lítill\p"
    .string "engill.\p"
    .string "Nafn litlu stelpunnar… Ég held að\n"
    .string "það hafi verið DAISY.$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
    .string "Þetta er frábært umhverfi til að ala\n"
    .string "upp Vasaskrímsli.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
    .string "Vasaskrímslin þín vaxa alveg\n"
    .string "aðdáunarlega vel!$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
    .string "Veistu, ég held að þú hafir\n"
    .string "hæfileika til að verða góður\p"
    .string "BREEDER.$"
