FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Fwahahaha!\p"
    .string "Barn eins og þú dirfist að skora á\n"
    .string "mig?\p"
    .string "Tilfinningin ein fær mig til að\n"
    .string "skjálfa af gleði!\p"
    .string "Jæja þá, ég sýni þér sannan hrylling\n"
    .string "ninjameistara.\p"
    .string "Eitur færir stöðugan dauða. Svefn\n"
    .string "gerir óvini varnarlausa.\p"
    .string "Örvæntu yfir lævísum hryllingi\n"
    .string "EITUR-gerðar\p"
    .string "Vasaskrímsla!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Humph! Þú hefur sannað gildi þitt!\p"
    .string "Hér! Taktu SOULBADGE!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "Þegar Vasaskrímsli verður fyrir\n"
    .string "EITRUN versnar líðan þess sífellt.\p"
    .string "Skaðinn eykst eftir því sem\n"
    .string "bardaginn dregst á langinn!\p"
    .string "Það mun hræða óvini!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Nú þegar þú hefur SÁLARMERKIÐ hækkar\n"
    .string "VÖRN Vasaskrímsla þinna.\p"
    .string "Það leyfir þér líka að BRIMMA utan\n"
    .string "bardaga.\p"
    .string "Ah! Taktu þetta líka!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} fékk TM06 frá KOGA.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "Innsiglað í þeirri TM06 liggur\n"
    .string "TOXIC!\p"
    .string "Þetta er leyndartækni sem á rætur\n"
    .string "sínar að rekja fjögur hundruð ár\p"
    .string "aftur í tímann.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Gerðu pláss fyrir þetta, barn!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "Styrkur er ekki lykillinn að\n"
    .string "Vasaskrímslum. Skilurðu það?\p"
    .string "Vasaskrímsli snúast um taktík!\p"
    .string "Ég sýni þér hvernig taktík sigrar\n"
    .string "hráan styrk.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "Hvað? Ótrúlegt!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "Svo þú blandar saman krafti og viti?\n"
    .string "Góð taktík!\p"
    .string "Það er merkilegt hjá ungum ÞJÁLFARA.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "Ég var töframaður einu sinni.\p"
    .string "En ég dreymdi um að verða ninja, svo\n"
    .string "ég gekk í þennan SALUR.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "Ég er búinn!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Jafnvel þó ég hafi tapað, mun ég\n"
    .string "halda áfram að æfa samkvæmt\p"
    .string "kenningum\p"
    .string "KOGA, ninja meistarans míns.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Sjáum hvort þú getir sigrað\n"
    .string "sérstakar tækni mínar!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "Þú blekktir mig!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "Mér líkar við eitur- og svefntækni,\n"
    .string "þar sem þær endast eftir bardaga!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Stoppaðu strax!\p"
    .string "Hefurðu orðið pirraður á hinum frægu\n"
    .string "ósýnilegu veggjum FUCHSIA SALUR?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Vá! Þú hefur það!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "Þú heillaðir mig! Hér er vísbending!\p"
    .string "Leitaðu mjög vel að eyðum í\n"
    .string "ósýnilegu veggjunum!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "Ég læri líka ninjaleiðina með\n"
    .string "Meistara KOGA!\p"
    .string "Ninjar hafa langa sögu í notkun\n"
    .string "dýra!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Áúú!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "Ég hef enn mikið að læra.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Meistari KOGA kemur úr langri ætt\n"
    .string "ninja.\p"
    .string "Hvaðan ert þú kominn?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "Þú ert færari en ég hefði haldið!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Þar sem er ljós, þar er skuggi!\p"
    .string "Ljós og skuggi! Hvort velurðu?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Hæ! Verðandi meistari!\p"
    .string "FUCHSIA SALUR er flókinn staður.\n"
    .string "Hann er fullur af ósýnilegum\p"
    .string "veggjum!\p"
    .string "KOGA gæti virst nálægur, en hann er\n"
    .string "lokaður af.\p"
    .string "Þú verður að finna eyður í veggjunum\n"
    .string "til að ná til hans.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "Það er ótrúlegt hvernig ninjar geta\n"
    .string "hrætt, ennþá!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "FUCHSIA Vasaskrímslasalur LEIÐTOGI:\n"
    .string "KOGA\p"
    .string "SIGURÞJÁLFARAR: {RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "FUCHSIA Vasaskrímslasalur LEIÐTOGI:\n"
    .string "KOGA\p"
    .string "SIGURÞJÁLFARAR: {RIVAL}, {PLAYER}$"
