SafariZone_West_Text_RestHouse::
    .string "HVÍLDARHÚS$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .string "BEIÐNI\p"
    .string "Finndu týndu GULLTENNUR\n"
    .string "SAFARI-VARÐARINS. Þær eru hér\p"
    .string "einhvers staðar.\p"
    .string "Verðlaun í boði! Hafðu samband:\n"
    .string "VÖRÐUR$"

SafariZone_West_Text_SearchForSecretHouse::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Svæðakönnunarherferð! Leitin að\n"
    .string "LEYNIHÚSINU!$"

SafariZone_West_Text_AreaSign::
    .string "SVÆÐI 3 AUSTUR: MIÐSVÆÐI$"

