VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .string "Ég er VEIÐIMEISTARINN!\p"
    .string "Ég einfaldlega eeeelska að veiða! Ég\n"
    .string "þoli ekki að vera án þess.\p"
    .string "Segðu mér, finnst þér gaman að\n"
    .string "veiða?$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "Stórgott! Mér líkar stíllinn þinn.\n"
    .string "Ég held að við getum orðið vinir.\p"
    .string "Taktu þetta og veiddu, ungi vinur!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} fékk GAMLA STÖNG frá\n"
    .string "VEIÐIMEISTARANUM.$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .string "Veiði er lífsstíll! Hún er eins og\n"
    .string "fínasta ljóðlist.\p"
    .string "Frá sjó til áa, farðu út og landaðu\n"
    .string "þeim stóra, vinur minn.$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "Ó... Það veldur svo miklum\n"
    .string "vonbrigðum...$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "Halló, {PLAYER}!\p"
    .string "Bíta fiskarnir vel?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
    .string "Ó, nei!\p"
    .string "Ég var með góða gjöf handa þér, en\n"
    .string "þú hefur ekkert pláss fyrir hana!$"

