SSAnne_1F_Room6_Text_TakeAShortRest::
    .string "Þú lítur þreytt út. Viltu hvíla þig\n"
    .string "smástund?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
    .string "Það gleður mig að sjá að allir eru\n"
    .string "hressir og endurnærðir.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .string "Ó, afsakaðu að ég hugsaði svona um\n"
    .string "þig. Þú líkist litla bróður mínum...$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .string "Ó, afsakaðu að ég hugsaði svona um\n"
    .string "þig. Þú líkist litlu systur minni...$"

