CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "SNIÐDÝR getur þróast í eina af\n"
    .string "þremur tegundum vasaskrímsla.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "Það er tölvupóstur.\p"
    .string "... ... ...\p"
    .string "Til eru þrjú goðsagnakennd\n"
    .string "fugla-vasaskrímsli.\p"
    .string "Þau eru ÉLJASKARFU, ÞÓRSHANI og\n"
    .string "BLOSSAGAUK.\p"
    .string "Dvalarstaðir þeirra eru óþekktir.\p"
    .string "Við ætlum að kanna hellinn nálægt\n"
    .string "CERULEAN.\p"
    .string "Frá: VASASKRÍMSLA-RANNSÓKNARHÓPUR...$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "Rafpípa úr rafi!$"

