Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
    .string "Allt í lagi, sex VASA BOLTAR á\n"
    .string "beltið...\p"
    .string "Já, þetta ætti að duga. Þú getur\n"
    .string "mest haft sex vasaskrímsli með þér.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
    .string "ROCKET-GENGIÐ ræðst á borgara í\n"
    .string "CERULEAN...\p"
    .string "Það líður ekki dagur án þess að\n"
    .string "ROCKET-GENGIÐ sé í fréttunum.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
    .string "MAÐUR: Sæll, strákur! Ég er með\n"
    .string "tilboð handa þér!\p"
    .string "Ég læt þig fá leynilegt vasaskrímsli\n"
    .string "- GREYSLEPPA - fyrir aðeins ¥500!\p"
    .string "Þú kaupir það, ekki satt?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
    .string "MAÐUR: Sæl, elskan! Ég er með tilboð\n"
    .string "handa þér!\p"
    .string "Ég læt þig fá leynilegt vasaskrímsli\n"
    .string "- GREYSLEPPA - fyrir aðeins ¥500!\p"
    .string "Þú kaupir það, ekki satt?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .string "{PLAYER} greiddi fáránlegar ¥500 og\n"
    .string "keypti GREYSLEPPA...$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .string "Nei? Segirðu nei? Ég geri þetta bara\n"
    .string "sem greiða fyrir þig!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .string "Það virðist ekki vera pláss fyrir\n"
    .string "fleiri vasaskrímsli.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .string "Þú þarft meiri peninga en það!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
    .string "MAÐUR: Jæja, ég endurgreiði ekki. Þú\n"
    .string "vissir hvað þú varst að fá!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .string "Stundum ertu með of mörg\n"
    .string "vasaskrímsli til að bæta fleirum\p"
    .string "við.\p"
    .string "Þá ættirðu bara að geyma nokkur með\n"
    .string "hvaða PC sem er.$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .string "Þetta er dagblað.$"

