PokemonLeague_BrunosRoom_Text_Intro::
    .string "Ég er BRUNO úr ELÍTUFERNINGNUM!\p"
    .string "Með hörðum æfingum geta fólk og\n"
    .string "Vasaskrímsli orðið sterkari\p"
    .string "án takmarka.\p"
    .string "Ég hef lifað og æft með bardaga-\n"
    .string "Vasaskrímslunum mínum! Og það\p"
    .string "breytist aldrei!\p"
    .string "{PLAYER}!\p"
    .string "Við kremjum þig með yfirburða\n"
    .string "krafti okkar!\p"
    .string "Hoo\n"
    .string "hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .string "Ég er BRUNO úr ELÍTUFERNINGNUM!\p"
    .string "Með hörðum æfingum geta fólk og\n"
    .string "Vasaskrímsli orðið sterkari\p"
    .string "án takmarka.\p"
    .string "Ég hef lifað og æft með bardaga-\n"
    .string "Vasaskrímslunum mínum! Og það\p"
    .string "breytist aldrei!\p"
    .string "{PLAYER}!\p"
    .string "Við kremjum þig með yfirburða\n"
    .string "krafti okkar!\p"
    .string "Hoo\n"
    .string "hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat::
    .string "Hvers vegna? Hvernig gat ég tapað?$"

PokemonLeague_BrunosRoom_Text_PostBattle::
    .string "Verki mínu er lokið. Farðu og mættu\n"
    .string "næstu áskorun.$"
