SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "SKIPSTJÓRI: Óaaargh... Mér líður\n"
    .string "hræðilega... Urrp! Sjóveiki...$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER} nuddaði bakið á\n"
    .string "SKIPSTJÓRANUM!\p"
    .string "Nudd-nudd... Nudd-nudd...$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "SKIPSTJÓRI: Úff! Takk fyrir!\n"
    .string "Mér líður miklu betur núna.\p"
    .string "Viltu sjá leynilegu tæknina\n"
    .string "sem heitir HÖGGVA?\p"
    .string "Ég gæti kennt þér HÖGGVA ef ég\n"
    .string "væri ekki svona veikur...\p"
    .string "Ég veit! Þú mátt fá þessa\n"
    .string "FÖLDU VÉL!\p"
    .string "Kenndu vasaskrímslinu þínu\n"
    .string "HÖGGVA.\p"
    .string "Þá getur það höggvið tré\n"
    .string "hvenær sem er!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} fékk HM01 frá\n"
    .string "SKIPSTJÓRANUM!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Með HÖGGVA má höggva niður lítil\n"
    .string "tré.\p"
    .string "Prófaðu það á trjánum í kringum\n"
    .string "VERMILION BORG!$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "SKIPSTJÓRI: ...Úff!\p"
    .string "Nú þegar ég er ekki veikur lengur\n"
    .string "held ég að tíminn sé kominn.\p"
    .string "S.S. ANNE leggur fljótlega úr höfn!\p"
    .string "Vertu sæl, þar til við snúum aftur\n"
    .string "til VERMILION BORGAR!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "Ó, nei! Þú hefur ekkert pláss fyrir\n"
    .string "þetta!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "Oj! Hefði ekki átt að líta!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "Hvernig má sigrast á sjóveiki...\n"
    .string "SKIPSTJÓRINN er að lesa þetta!$"
