SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "SKIPSTJÓRI: Óaaargh... Mér líður\n"
    .string "hræðilega... Urrp! Sjóveiki...$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER} nuddaði bakið á\n"
    .string "SKIPSTJÓRANUM!\p"
    .string "Nudd-nudd... Nudd-nudd...$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "SKIPSTJÓRI: Úff! Takk fyrir! Mér\n"
    .string "líður miklu betur núna.\p"
    .string "Viltu sjá leynilegu CUT tæknina\n"
    .string "mína?\p"
    .string "Ég gæti sýnt þér dýrmætu CUT tæknina\n"
    .string "mína ef ég væri ekki svona veikur...\p"
    .string "Ég veit! Þú mátt fá þetta! Þessa\n"
    .string "FÖLDU VÉL!\p"
    .string "Kenndu vasaskrímslinu þínu CUT, og\n"
    .string "þú getur séð það CUT-a hvenær sem\p"
    .string "er!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} fékk HM01 frá\n"
    .string "SKIPSTJÓRANUM!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Með CUT geturðu höggvið niður lítil\n"
    .string "tré.\p"
    .string "Af hverju prófarðu það ekki á\n"
    .string "trjánum í kringum VERMILION BORG?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "SKIPSTJÓRI: ...Úff!\p"
    .string "Nú þegar ég er ekki veikur lengur\n"
    .string "held ég að tíminn sé kominn.\p"
    .string "S.S. ANNE leggur fljótlega úr höfn!\p"
    .string "Vertu sæl, þar til við snúum aftur\n"
    .string "til VERMILION BORGAR!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "Ó, nei! Þú hefur ekkert pláss fyrir\n"
    .string "þetta!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "Oj! Hefði ekki átt að líta!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "Hvernig má sigrast á sjóveiki...\n"
    .string "SKIPSTJÓRINN er að lesa þetta!$"

