PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "DAISY: Hæ, {PLAYER}!\p"
    .string "Bróðir minn, {RIVAL}, er úti á\n"
    .string "rannsóknarstofu afa.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "DAISY: {PLAYER}, ég heyrði að þú\n"
    .string "hefðir átt í bardaga gegn {RIVAL}.\p"
    .string "Ég vildi að ég hefði séð það!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "Afi bað þig um að ganga erinda?\p"
    .string "Jæja, þetta er letilegt af honum.\n"
    .string "Hér mun þetta hjálpa þér.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} fékk BÆJARKORT frá DAISY.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "Þú hefur ekki pláss fyrir þetta í\n"
    .string "TÖSKUNNI þinni.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "Þú getur notað BÆJARKORTIÐ til að\n"
    .string "finna út hvar þú ert, eða athuga\p"
    .string "nöfn staða.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "DAISY: Rétt eins og fólk er\n"
    .string "VASaSKRÍMSLI lifandi verur.\p"
    .string "Þegar þeir verða þreyttir,\n"
    .string "vinsamlegast gefðu þeim hvíld.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "Það er stórt kort af KANTO svæðinu.\n"
    .string "Nú væri þetta gagnlegt!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "Hillurnar eru fullar af bókum á\n"
    .string "VASaSKRÍMSLI.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "DAISY: Hæ, {PLAYER}! Góð\n"
    .string "tímasetning.\p"
    .string "Ég er að fara að fá mér te. Viltu\n"
    .string "vera með mér?\p"
    .string "Ó, en sjáðu. VASaSKRÍMSLI þínir eru\n"
    .string "svolítið óhreinir.\p"
    .string "Viltu að ég snyrti einn?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "Þarftu enga snyrtingu? Allt í lagi,\n"
    .string "við fáum okkur bara te.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "Hvorn ætti ég að snyrta?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "DAISY: Allt í lagi, ég læt það líta\n"
    .string "vel út á skömmum tíma.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
    .string "Sjáðu? Lítur það ekki vel út?\p"
    .string "Giggle… Þetta er svo sætur\n"
    .string "VASaSKRÍMSLI.$"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "Sjáðu? Lítur það ekki vel út?\p"
    .string "Giggle… Þetta er svo sætur\n"
    .string "VASaSKRÍMSLI.$"
#endif
    .string "Sjáðu? Lítur það ekki vel út?\p"
    .string "Giggle… Þetta er svo sætur\n"
    .string "VASaSKRÍMSLI.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "Æ, því miður. Ég get satt að segja\n"
    .string "ekki snyrt EGG.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "DAISY: VASaSKRÍMSLI þín stækkar að\n"
    .string "elska þig ef þú elur þá upp með ást.\p"
    .string "Til dæmis, {PLAYER}, má ég sjá\n"
    .string "fyrsta VASaSKRÍMSLI þinn?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "Það gæti ekki mögulega elskað þig\n"
    .string "meira en það gerir núna.\p"
    .string "VASaSKRÍMSLI þinn er ánægður án\n"
    .string "orða.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "Það lítur mjög ánægjulegt út.\p"
    .string "Ég vildi að {RIVAL} gæti séð þetta\n"
    .string "og lært eitthvað af því.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "Það er frekar vingjarnlegt við þig.\n"
    .string "Haltu áfram að vera góður við það!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "Það fer að hitna hjá þér. Traust\n"
    .string "hlýtur að vaxa á milli ykkar.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "Það er ekki alveg kunnugt um þig\n"
    .string "ennþá.\p"
    .string "VASaSKRÍMSLI eru allir nokkuð á\n"
    .string "varðbergi þegar þú færð þá fyrst.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, mér líkar ekki hvernig það\n"
    .string "horfir á þig.\p"
    .string "Gætirðu prófað að vera aðeins fínni\n"
    .string "við það?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "…Um, það er ekki auðvelt fyrir mig\n"
    .string "að segja þetta, en…\p"
    .string "Er einhver ástæða fyrir því að\n"
    .string "VASaSKRÍMSLI þinn myndi hata þig\p"
    .string "svona mikið?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "'Hinn yndislegi og ljúfi BLEIKÁLFUR'$"
