SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "Ég velti fyrir mér hvort SILPH sé búið…$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "Takk fyrir að bjarga okkur!$"

SilphCo_8F_Text_Grunt1Intro::
    .string "Lengra kemstu ekki!$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "Ekki nægur kjarkur!$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "Ef þú snýrð ekki við… kalla ég\n"
    .string "á liðsauka!$"

SilphCo_8F_Text_ParkerIntro::
    .string "Þú ert að valda okkur vandræðum!$"

SilphCo_8F_Text_ParkerDefeat::
    .string "Ha? Ég tapaði?$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "Svo, hvað finnst þér um völundarhús\n"
    .string "SILPH-BYGGINGARINNAR?$"

SilphCo_8F_Text_Grunt2Intro::
    .string "Ég er einn af fjórum\n"
    .string "ROCKET-BRÆÐRUM!$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "Úff! Ó, bræður!$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "Ég læt bræður mína um þig.$"

SilphCo_8F_Text_FloorSign::
    .string "SILPH CO. HÖFUÐSKRIFSTOFA 8H$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .string "FORINGI ROCKET-GENGISINS er\n"
    .string "hræðilega grimmur!\p"
    .string "Í hans augum eru Vasaskrímsli bara\n"
    .string "verkfæri til að nota.\p"
    .string "Hvað gerist ef þessi harðstjóri\n"
    .string "tekur yfir fyrirtækið okkar…$"
