SSAnne_2F_Room4_Text_LamarIntro::
    .string "Hvort finnst þér verðmætara, sterkt\n"
    .string "eða sjaldgæft vasaskrímsli?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "Ég verð að heilsa þér að\n"
    .string "hermannasið!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "Persónulega kýs ég sterk og sjaldgæf\n"
    .string "vasaskrímsli.$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "Ég man ekki eftir að hafa séð þig í\n"
    .string "veislunni?$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "Taktu því rólega!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "Ó, ég dáist að sterku\n"
    .string "vasaskrímslunum þínum! Ó, hvað ég\p"
    .string "öfunda þig af þeim!$"

