SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .string "Þú mátt halda öllum hlutum sem þú\n"
    .string "finnur í SAFARI SVÆÐINU.\p"
    .string "En tíminn klárast ef þú reynir að ná\n"
    .string "þeim öllum í einu.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .string "Farðu í dýpsta hluta SAFARI\n"
    .string "SVÆÐISINS. Þá vinnurðu verðlaun!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .string "SNIÐDÝRIÐ mitt þróaðist í GLÓÐBÚA.\p"
    .string "En SNIÐDÝR vinar míns varð að\n"
    .string "MARBÚA. Af hverju skyldi það vera?$"

