ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
    .string "Hey, heyrðirðu fréttirnar?\p"
    .string "Tölvukerfið hér getur nú tengst\n"
    .string "tölvum í KANTO.\p"
    .string "Ég veit ekki hvernig það gerðist, en\n"
    .string "það er frábært!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
    .string "Það er ómögulegt að SURFA á milli\n"
    .string "eyjanna hér í kring.\p"
    .string "Flóðið er of hratt og hættulegt.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
    .string "Mölvum BER! …Væri það sóun á BERJUM?\p"
    .string "Þú finnur alltaf BER á jörðinni í\n"
    .string "BERJA SKÓGI.$"
