OneIsland_KindleRoad_Text_MariaIntro::
    .string "Veðrið er dásamlegt! Fullkomið fyrir\n"
    .string "bardaga!$"

OneIsland_KindleRoad_Text_MariaDefeat::
    .string "Aíííí!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
    .string "Vinsamlegast ekki skvetta á andlitið\n"
    .string "á mér! Þú munt eyðileggja farðann.$"

OneIsland_KindleRoad_Text_AbigailIntro::
    .string "Ég er farin að fá sólbruna…$"

OneIsland_KindleRoad_Text_AbigailDefeat::
    .string "Ó, þú ert svo hræðilegur.$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
    .string "Mér líkar við húfuna þína. Kannski\n"
    .string "ætti ég líka að vera með eina…$"

OneIsland_KindleRoad_Text_FinnIntro::
    .string "Séð héðan, rís MT. EMBER hátt til\n"
    .string "himins.$"

OneIsland_KindleRoad_Text_FinnDefeat::
    .string "Jæja, ertu ekki harður?$"

OneIsland_KindleRoad_Text_FinnPostBattle::
    .string "Himinninn er gríðarstór hér í kring.$"

OneIsland_KindleRoad_Text_GarrettIntro::
    .string "Ég tók mér pásu frá sundi, bara til\n"
    .string "að þú ögraðir mér?$"

OneIsland_KindleRoad_Text_GarrettDefeat::
    .string "Ha, hvað… Þú ert góður!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
    .string "Í stað þess að nota SURF alltaf,\n"
    .string "ættirðu að synda aðeins.$"

OneIsland_KindleRoad_Text_TommyIntro::
    .string "Bíddu! Bíddu aðeins! Ég held að ég\n"
    .string "hafi krækt í stóran!$"

OneIsland_KindleRoad_Text_TommyDefeat::
    .string "Ég hef misst allt aftur…$"

OneIsland_KindleRoad_Text_TommyPostBattle::
    .string "Ég tapaði ekki bara, heldur slapp sá\n"
    .string "stóri frá mér líka!$"

OneIsland_KindleRoad_Text_SharonIntro::
    .string "Gætirðu hjálpað mér með þjálfunina\n"
    .string "mína?$"

OneIsland_KindleRoad_Text_SharonDefeat::
    .string "Þú varst mér fremri.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
    .string "Það er ljóst að þú ert fær. Mér\n"
    .string "líkar við þig!$"

OneIsland_KindleRoad_Text_TanyaIntro::
    .string "Það er enginn dagur sem við\n"
    .string "þjálfumst ekki!$"

OneIsland_KindleRoad_Text_TanyaDefeat::
    .string "Ég er svo mikið fífl!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
    .string "Ég mun þjálfa mig enn harðar héðan í\n"
    .string "frá!$"

OneIsland_KindleRoad_Text_SheaIntro::
    .string "Á hverjum morgni, fyrir morgunmat,\n"
    .string "syndi ég umhverfis þessa eyju.$"

OneIsland_KindleRoad_Text_SheaDefeat::
    .string "Más… Más…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
    .string "Ég tapaði vegna þess að ég er\n"
    .string "uppgefinn af öllu hlaupinu sem ég\p"
    .string "tók…$"

OneIsland_KindleRoad_Text_HughIntro::
    .string "Klæddu þig viðeigandi fyrir bardaga!\n"
    .string "Losnaðu við þennan léttúðuga búning!$"

OneIsland_KindleRoad_Text_HughDefeat::
    .string "Af hverju ég?!$"

OneIsland_KindleRoad_Text_HughPostBattle::
    .string "Jafnvel bardagalistamenn eru að\n"
    .string "verða meðvitaðir um tísku þessa\p"
    .string "dagana…$"

OneIsland_KindleRoad_Text_BryceIntro::
    .string "Veistu, allt bragðast vel þegar þú\n"
    .string "ert úti í náttúrunni.$"

OneIsland_KindleRoad_Text_BryceDefeat::
    .string "Awww, búið!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
    .string "Vatnið á eldfjallasvæðum er\n"
    .string "ljúffengt.$"

OneIsland_KindleRoad_Text_ClaireIntro::
    .string "Hádegismaturinn minn fyllti okkur,\n"
    .string "svo viltu berjast við okkur til að\p"
    .string "hreyfa þig?$"

OneIsland_KindleRoad_Text_ClaireDefeat::
    .string "Það gerði mig alveg sveitta.$"

OneIsland_KindleRoad_Text_ClairePostBattle::
    .string "Hvað á ég að gera? Ég er orðinn\n"
    .string "svangur aftur.$"

OneIsland_KindleRoad_Text_KiaIntro::
    .string "KIA: Stóri bróðir minn og ég erum\n"
    .string "frábær samsetning!$"

OneIsland_KindleRoad_Text_KiaDefeat::
    .string "KIA: Ha?! Ég trúi því ekki!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
    .string "KIA: Hvernig gæti nokkur verið betri\n"
    .string "en stóri bróðir minn?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
    .string "KIA: Ef þú vilt berjast við okkur,\n"
    .string "þarftu að hafa að minnsta kosti tvö\p"
    .string "Vasaskrímsli með þér.$"

OneIsland_KindleRoad_Text_MikIntro::
    .string "MIK: Saman með KIA, er ég hræddur\n"
    .string "við ekkert!$"

OneIsland_KindleRoad_Text_MikDefeat::
    .string "MIK: Vá! Þetta er of mikið!$"

OneIsland_KindleRoad_Text_MikPostBattle::
    .string "MIK: Hvernig gat samsetning mín með\n"
    .string "KIA mistekist?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
    .string "MIK: Hey, viltu berjast við okkur\n"
    .string "tvö?\p"
    .string "Komdu þá með tvö eða fleiri\n"
    .string "Vasaskrímsli.$"

OneIsland_KindleRoad_Text_RouteSign::
    .string "Þetta er KYNDILVEGUR.\p"
    .string "Farið beint á MT. EMBER.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
    .string "Kveiktu eldinn í hjarta þínu! EMBER\n"
    .string "SPA$"
