PokemonTower_4F_Text_PaulaIntro::
    .string "Draugur! Nei! Kwaaah!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "Hvar er draugurinn?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "Ég hlýt að hafa verið að dreyma…$"

PokemonTower_4F_Text_LaurelIntro::
    .string "Vertu bölvaður með mér! Kwaaah!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "Hvað!$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "Við getum ekki ákvarðað hverjir\n"
    .string "draugarnir eru…$"

PokemonTower_4F_Text_JodyIntro::
    .string "Huhuhu… Ekki berja mig!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "Ha? Hver? Hvað?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "Megi horfin Vasaskrímsli hvíla í\n"
    .string "friði…$"
