CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "ÖFLUGT FÆLNIREYSI heldur veikum\n"
    .string "vasaskrímslum í skefjum…\p"
    .string "Hmm, þetta er kraftmeira en\n"
    .string "venjulegt FÆLNIREYSI.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "Fyrir langar ferðir er gott að kaupa\n"
    .string "LÍFGUNARLYF.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "Úrvalsvarningur fyrir ÞJÁLFARA!\p"
    .string "2F: ÞJÁLFARAMARKAÐUR$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "Við eigum viðskiptavin, LANCE, sem\n"
    .string "kemur stundum.\p"
    .string "Hann kaupir alltaf skikkjur.\p"
    .string "Ég velti fyrir mér... á hann margar\n"
    .string "alveg eins skikkjur heima?$"
