SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "ROCKET-GENGIÐ er í uppnámi út af\n"
    .string "einhverjum innbrotsþjófi.\p"
    .string "Það ert þú, ekki satt?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "ROCKET-GENGIÐ flúði! Þú ert\n"
    .string "hetjan okkar! Takk fyrir!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "Ég heyrði að krakki væri á ráfi.$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "Búmm!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "Það er ekki gáfulegt að hefja slag\n"
    .string "við ROCKET-GENGIÐ!$"

SilphCo_5F_Text_BeauIntro::
    .string "Við rannsökum VASA BOLTA-tækni á\n"
    .string "þessari hæð.$"

SilphCo_5F_Text_BeauDefeat::
    .string "Ansans! Fjárinn!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "Við unnum að fullkomnum VASA BOLTA\n"
    .string "sem gæti fangað hvað sem er.$"

SilphCo_5F_Text_DaltonIntro::
    .string "Hvað?\p"
    .string "Það eiga engin börn að vera\n"
    .string "hér!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "Ó, góði minn!$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "Þú ert bara á 5H. Það er langt\n"
    .string "til FORINGJANS míns!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "Sýndu ROCKET-GENGINU smá virðingu!$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "Hóst… Hóst…$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "Sem minnir mig á…\p"
    .string "KÍGILDI þróast í PÚSTASKRÁP!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "It's a Vasaskrímsli REPORT!\p"
    .string "Vasaskrímsli LAB created GRAFÍKJA,\n"
    .string "fyrsta sýndarveruleika-\p"
    .string "Vasaskrímsli.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "It's a Vasaskrímsli REPORT!\p"
    .string "Yfir 350 Vasaskrímsla-brögð\n"
    .string "hafa verið staðfest.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "It's a Vasaskrímsli REPORT!\p"
    .string "Staðfest hefur verið að sum\n"
    .string "Vasaskrímsli þróast þegar þau eru\p"
    .string "skipst á þeim.$"

SilphCo_5F_Text_FloorSign::
    .string "SILPH CO. HÖFUÐSKRIFSTOFA 5H$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "Þessir bófar sem tóku yfir\n"
    .string "bygginguna okkar…\p"
    .string "FORINGI þeirra sagðist leita að\n"
    .string "sterkum Vasaskrímslum.\p"
    .string "Ég vona að FORSTJÓRINN okkar hafi\n"
    .string "forðast vandræði…$"
