LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "Ég leita að hlutum sem hækka\ntölur\n"
    .string "Vasaskrímsla.\n\nÞeir virka í einum\p"
    .string "bardaga.\n\nX ÁRÁS, X VÖRN, X HRAÐI\n"
    .string "og\nX SÉR eru það sem ég leita\p"
    .string "að.\n\nVeistu hvar ég fæ þá?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "Keyptirðu ENDURLÍFGANIR? Þær\n"
    .string "endurlífga hvaða yfirliðna\p"
    .string "Vasaskrímsli sem er!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "Stundum skorar ÞJÁLFARA-tvíeyki á\n"
    .string "þig með tveimur Vasaskrímslum\p"
    .string "í einu.\p"
    .string "Ef það gerist þarftu líka að senda\n"
    .string "útt tvö Vasaskrímsli í bardaga.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この あいだ やまおくで きんのたまを ひろい ましてね！\p"
    .string "つかえない しなもの ですが うったら なんと 5000¥でした$"
