SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "Gnýr!\p"
    .string "Ég er KARATE MEISTARINN! Ég er\n"
    .string "LEIÐTOGINN hér!\p"
    .string "Þú vilt skora á okkur? Búist ekki\n"
    .string "við miskunn!\p"
    .string "Fwaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "Hwa! Arrgh! Sigraður!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "Sannarlega, ég tapaði!\p"
    .string "En ég sárbæni þig, taktu ekki merki\n"
    .string "okkar sem verðlaunagrip!\p"
    .string "Í staðinn gef ég þér verðmætt\n"
    .string "BARDAGA Vasaskrímsli!\p"
    .string "Veldu það sem þér líst best á!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "Gnýr! Vertu og æfðu karate með\n"
    .string "okkur!$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "Hoargh! Taktu skóna af þér!$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "Ég gefst upp!$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "Bíddu bara þar til þú sérð\n"
    .string "MEISTARANN okkar! Ég er smáfiskur\p"
    .string "miðað við hann!$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "Ég heyri að þú sért góður! Sýndu\n"
    .string "mér!$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "Dómari! Eitt stig!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
    .string "MEISTARINN okkar er atvinnumaður í\n"
    .string "bardaga. Vertu viðbúinn að tapa!$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "Hiyah! Ég óttast ekkert sem er\n"
    .string "erfitt!\p"
    .string "Ég mölva steina í æfingum á hverjum\n"
    .string "degi!$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "Jæja! Marið á fingrum!$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "Það eina sem hræðir okkur er\n"
    .string "sálarkraftur!$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "Hwaah!\p"
    .string "Þú ert að brjóta þig inn í okkar\n"
    .string "BARDAGADÓJÓ!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "Úff! Ég gefst upp!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "Helstu bardagamenn landsins þjálfa\n"
    .string "sig hér.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "Viltu SPYRNIRinn sem sparkar hart?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "{PLAYER} fékk {STR_VAR_1} frá KARATE\n"
    .string "MEISTARANUM.$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "Viltu HNEFLAinn sem hnefahöggvar\n"
    .string "eins og stimpill?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER}は カラテ だいおう から {STR_VAR_1}を\n"
    .string "もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "Betra að verða ekki gráðugur…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "Óvinir á öllum hliðum!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "Það sem gengur í hringi kemur aftur.$"

SaffronCity_Dojo_Text_FightingDojo::
    .string "BARDAGADÓJÓ$"
