Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Let's see… Uh-oh! You have caught\n"
	.string "only {STR_VAR_3} kinds of\p"
	.string "Vasaskrímsli!\p"
	.string "You need {STR_VAR_1} kinds if you\n"
	.string "want the {STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "…Oh. I see.\p"
	.string "When you get {STR_VAR_1} kinds of\n"
	.string "Vasaskrímsli, come back for the\p"
	.string "{STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Ó! Ég sé að þú hefur ekki pláss\n"
	.string "fyrir {STR_VAR_2}.$"
