Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Sjáum… Úbbs! Þú hefur aðeins náð\n"
	.string "{STR_VAR_3} tegundum af\p"
	.string "Vasaskrímslum!\p"
	.string "Þú þarft {STR_VAR_1} tegundir ef þú\n"
	.string "vilt {STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "…Ó. Ég skil.\p"
	.string "Þegar þú færð {STR_VAR_1} tegundir\n"
	.string "af Vasaskrímslum, komdu aftur fyrir\p"
	.string "{STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Ó! Ég sé að þú hefur ekki pláss\n"
	.string "fyrir {STR_VAR_2}.$"
