@ The text here is a copy/paste from Hoenn's various berry NPCs, all unused and untranslated

PetalburgCity_Gym_Text_GiveEnigmaBerry::
	.string "パパ'やあ {PLAYER}！\p"
	.string "めずらしい きのみを てに いれたから プレゼント するよ！$"

Route104_Text_PlantBerriesInSoilTakeThis::
	.string "ふかふかの つちに はえている きのみは じゆうに とっても\n"
	.string "よいのじゃが‥\p"
	.string "1つだけ きのみを おなじ ばしょに うめる それが れいぎと\n"
	.string "いうものじゃ\p"
	.string "ほれ これを わけてやろう$"

Route104_Text_TrainersOftenMakeMonHoldBerries::
	.string "あんた みたところ トレーナーじゃろ？\p"
	.string "トレーナーは よく きのみを ポケモンに もたせとるわい\p"
	.string "ふやすも つかうも あんた しだいじゃ$"

Route111_Text_WateredPlantsEveryDayTakeBerry::
	.string "いつも みずを あげてたら たくさん はなが さいたんだ\p"
	.string "そしたら きのみも たくさん できた！\p"
	.string "はい！ これ あげる$"

Route111_Text_TryToMakeRedPokeblock::
	.string "がんばって あかいポロック つくるんだ！ {STR_VAR_1}も\n"
	.string "がんばってね！$"

Route111_Text_WhatColorBerriesToLookForToday::
	.string "きょうは なにいろの きのみを さがそっかなー$"

Route114_Text_GatheringBerriesForContest::
	.string "ポケモンコンテストの ゆうしょうを めざして きのみを あつめているんだ\p"
	.string "よかったら きみにも わけて あげるよ！$"

Route114_Text_GoodLuckToYouToo::
	.string "きみも がんばれ！$"

Route114_Text_WhatBerriesShouldIPlantToday::
	.string "きょうは どの きのみを うめるか‥ そして なにいろの ポロックを\n"
	.string "つくるか‥\p"
	.string "なやむのも また たのしいよ$"

Route120_Text_PokeblocksExpressionOfLove::
	.string "ケースを ふると でてくる ポロック‥\p"
	.string "そして それを キャッチして たべてくれる ポケモン‥\p"
	.string "これって あい だよね？$"

Route120_Text_YouUnderstandTakeThis::
	.string "うん うん！ やっぱ わかるひとには わかるよね\p"
	.string "これ あげる$"

Route120_Text_OwnImpressionsImportantTakeThis::
	.string "そっか‥‥ でも ちがうと かんじることも たいせつだね\p"
	.string "これ あげる$"

Route120_Text_BerryIsRareRaiseItWithCare::
	.string "その きのみは めずらしいもの らしいから たいせつに そだててね！$"

Route120_Text_IllGetMoreBerriesFromBerryMaster::
	.string "また きのみめいじんに もらって こようっと$"

LilycoveCity_Text_BerrySuitsYou::
	.string "やっぱり\p"
	.string "わたしに スーツが にあうように うみには しおかぜが にあうな そして\n"
	.string "きみには きのみが にあいそうだ‥‥\p"
	.string "なんでだろうね？$"

LilycoveCity_Text_BecauseYoureTrainer::
	.string "やっぱり それは‥‥‥‥\p"
	.string "きみが トレーナーだからだ！$"

LilycoveCity_Text_PokeblocksSuitPokemon::
	.string "やっぱり\p"
	.string "わたしに シンプルさが にあうように ポケモンには ポロックが にあうな$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry::
	.string "わしは きのみめいじんと よばれておる\p"
	.string "わしは せかいじゅうを うつくしい はなで うめつくそうと きのみを\n"
	.string "そだてて そして くばり まくって おるのじゃ\p"
	.string "きみにも きのみを わけて あげよう！$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother::
	.string "ほれ えんりょ せずに もう ひとつ！$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop::
	.string "カナズミの ちかくにある サン·トウカという フラワーショップも\n"
	.string "よろしくの\p"
	.string "せかいに はなを さかせましょう！$"

Route123_BerryMastersHouse_Text_DoneForToday::
	.string "きょうは もう おしまいじゃ また おいで\p"
	.string "せかいに はなを さかせましょう！$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately::
	.string "じいさんの きのみの そだてかたは そりゃあ せかいいちじゃ\p"
	.string "わしも はなが たかいわい\p"
	.string "ところで あんた いい ことばを きいたことが ないかい？$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis::
	.string "おお！ とても よい ことばじゃ！ かんどう したわい\p"
	.string "ほれ これを もっていきなされ$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis::
	.string "おお！ なかなか よい ことばじゃ あんたも たいしたもんじゃ\p"
	.string "ほれ これを もっていきなされ$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife::
	.string "まごたち 4にんも じいさんを しのぐ おおものに なるじゃろうて\p"
	.string "じんせい たのしいことが つきんのう！$"

Route123_BerryMastersHouse_Text_Ah::
	.string "Hó...$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop::
	.string "こんにちは！\p"
	.string "はなを せかいに ひろめる フラワーショップ サン·トウカです！$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries::
	.string "{PLAYER}{KUN} きのみの こと しりたい？$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries::
	.string "あなたの なまえは‥‥\p"
	.string "{PLAYER}{KUN}ね！ とっても いい なまえだね！\n"
	.string "{PLAYER}{KUN} きのみのこと しりたい？$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation::
	.string "きのみはね くろい ふかふかの つちの ところで たまに とれるの\n"
	.string "でね‥‥\p"
	.string "とったら その1つを また うめるの！\p"
	.string "そうすると その きのみ から めがでて みきが できて はながさいて\n"
	.string "また きのみ が できるの\p"
	.string "そうやって はなを ふやして せかいじゅうを はなに するのが わたしの\n"
	.string "ゆめ なんだ！\p"
	.string "だから {PLAYER}{KUN}も きのみを うめて せかいに はなを\n"
	.string "ふやしてね！$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness::
	.string "おはなって とっても しあわせな きぶんに してくれるよね$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis::
	.string "こんにちは！\p"
	.string "おはなは せわを すれば するほど たくさん きれいに さいて くれるの\p"
	.string "あなたも せわを したく なった でしょ？ これ あげるわ$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation::
	.string "きのみが そだつ たびに じょうろで みずを あげてね！\p"
	.string "あとね\p"
	.string "きのみは ずっと ずっと ほうっておくと じめんに おちてしまうの\n"
	.string "でもね そこから また めがでて くるの！\p"
	.string "すごいよね！ いきものの ちからを かんじるよね$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers::
	.string "おねーちゃんたちを みならって がんばって おはなを そだててるの\p"
	.string "はい！ これあげる！$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries::
	.string "きのみは うめて おおきく したり ポケモンに もたせたり できるの\p"
	.string "でも さいきん きのみを いくつか まぜると ポケモンの おかしになる\n"
	.string "きかいが ある らしいんだ\p"
	.string "あたしも おかし ほしー$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese::
	.string "{STR_VAR_1} なまえ なんていうの？\p"
	.string "‥‥‥ ‥‥‥ ‥‥‥ へー いいねー\p"
	.string "わたしは キリ っていう なまえなの\p"
	.string "パパと ママが すくすくと そだって こころの あたたかい おんなのこに\n"
	.string "なって ほしいっていう ねがいを こめたんだって！\p"
	.string "{STR_VAR_1}にも これ あげる$"

SootopolisCity_Text_GiveYouThisBerryToo::
	.string "あと {STR_VAR_1}には キリの だいすきな この きのみも\n"
	.string "あげちゃう！$"

SootopolisCity_Text_WhatKindOfWishInYourName::
	.string "{STR_VAR_1}の なまえには どんな ねがいが こめられてるの？$"

SootopolisCity_Text_LikeSeasonBornIn::
	.string "はる なつ あき ふゆ はるに うまれると はるが すきで なつに\n"
	.string "うまれると なつが すきなのかな？$"

SootopolisCity_Text_ThenILoveAutumn::
	.string "じゃあ キリは あきに うまれたから あきが だいすき！\p"
	.string "{STR_VAR_1}は いつが すき？$"

SootopolisCity_Text_OhDoesntMatter::
	.string "そっか‥ かんけいないのか‥\p"
	.string "しりたいことって たくさんあるなー$"
