@ The text here is a copy/paste from Hoenn's competitive brothers, the NPCs in Sootopolis who request to see big Barboach/Shroomish (Seedot/Lotad in Emerald). It's all unused and untranslated

SootopolisCity_Text_PleaseShowMeBigMon::
    .string "わしは おおきな {STR_VAR_1}に とても きょうみが ある！\p"
    .string "ん？ きみ {STR_VAR_1} もってるの？ ちょ ちょ\n"
    .string "ちょっと··· おじさんに みせて おくれ！$"

SootopolisCity_Text_GrandMonThanksForShowingMe::
    .string "おお！ こいつは でかい！ とても すばらしい\n"
    .string "{STR_VAR_1}だ！\p"
    .string "みせて くれて ありがとう おれいに これを もって いきなさい$"

SootopolisCity_Text_ReceivedOneItem::
    .string "{PLAYER}は {STR_VAR_2}を もらった！$"

SootopolisCity_Text_HuhBagIsCrammedFull::
    .string "ありゃ？ きみ もちもの いっぱいだね$"

SootopolisCity_Text_IveSeenBiggerMonThanThisOne::
    .string "ううむ わしは これより おおきい {STR_VAR_1}を みたこと\n"
    .string "あるな···$"

SootopolisCity_Text_QuiteSomethingButNotMon::
    .string "おお こいつは なかなか···って これ {STR_VAR_1}じゃ\n"
    .string "ないよ！$"

SootopolisCity_Text_TooBadDontHaveBigMon::
    .string "おおきい {STR_VAR_1} もってないの？ それは ざんねん···\n"
    .string "こんど おおきい {STR_VAR_1} みせてね$"

SootopolisCity_Text_BiggestMonPlayersXCmColossus::
    .string "しじょう さいだいの {STR_VAR_1}！ {STR_VAR_2}の\n"
    .string "{STR_VAR_3}cmのやつ！$"
