@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "Ég er DAGGÆSLUMAÐURINN.\p"
	.string "Ég hjálpa til við að annast dýrmæt\n"
	.string "Vasaskrímsli ÞJÁLFARA.\p"
	.string "Ef þú vilt að ég ali upp\n"
	.string "Vasaskrímslið þitt skaltu tala við\p"
	.string "konuna mína.$"

DayCare_Text_DoYouWantEgg::
	.string "Ah, þetta ert þú!\p"
	.string "Við vorum að ala upp Vasaskrímslið\n"
	.string "þitt, og svei mér, við urðum hissa!\p"
	.string "Vasaskrímslið þitt var með EGG!\p"
	.string "Við vitum ekki hvernig það komst\n"
	.string "þangað, en það var með það.\p"
	.string "Þú vilt það, er það ekki?$"

DayCare_Text_YourMonIsDoingFine::
	.string "Ah, þetta ert þú! Gaman að sjá þig.\n"
	.string "{STR_VAR_1} hefur það gott.$"

DayCare_Text_IllKeepIt::
	.string "Jæja þá, ég geymi það. Takk!$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "Þú hefur ekki pláss fyrir það… Komdu\n"
	.string "aftur þegar þú hefur búið til pláss.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER} fékk EGGIÐ frá\n"
	.string "DAGGÆSLUMANNINUM.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "Farðu vel með það.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "Talaðu við konuna mína ef þú vilt\n"
	.string "sækja Vasaskrímslið þitt.$"

DayCare_Text_YourMonsAreDoingFine::
	.string "Ah, þetta ert þú! {STR_VAR_1} og\n"
	.string "{STR_VAR_2} hafa það gott.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "Ég mun virkilega geyma það. Þú vilt\n"
	.string "þetta, er það ekki?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "Ég er DAGGÆSLUKONAN.\p"
	.string "Við getum alið upp Vasaskrímsli fyrir þig.\p"
	.string "Viltu að við ölum eitt upp?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "Hvaða Vasaskrímsli eigum við að ala\n"
	.string "upp fyrir þig?$"

DayCare_Text_WellRaiseYourMon::
	.string "Gott, við ölum upp {STR_VAR_1}\n"
	.string "um stund.\p"
	.string "Komdu aftur seinna að sækja það.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "Við getum alið upp tvö af\n"
	.string "Vasaskrímslunum þínum.\p"
	.string "Viltu að við ölum upp eitt\n"
	.string "Vasaskrímsli í viðbót fyrir þig?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "Maðurinn minn var að leita að þér.$"

DayCare_Text_FineThenComeAgain::
	.string "Ó, allt í lagi þá. Komdu aftur.$"

DayCare_Text_NotEnoughMoney::
	.string "Þú átt ekki nægan pening…$"

DayCare_Text_TakeOtherOneBackToo::
	.string "Viltu taka hitt líka til baka?$"

DayCare_Text_ComeAgain::
	.string "Gott. Komdu aftur.$"

DayCare_Text_GoodToSeeYou::
	.string "Ah, þetta ert þú! Gaman að sjá þig.\p"
	.string "Vasaskrímslið þitt getur varla haft\n"
	.string "það betra!$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "{STR_VAR_1} hefur hækkað um\n"
	.string "{STR_VAR_2} stig.$"

DayCare_Text_YourPartyIsFull::
	.string "Vasaskrímslahópurinn þinn er fullur.\n"
	.string "Búðu til pláss og komdu svo til mín.$"

DayCare_Text_TakeBackWhichMon::
	.string "Hvort Vasaskrímslið viltu taka til baka?$"

DayCare_Text_ItWillCostX::
	.string "Ef þú vilt fá {STR_VAR_1} aftur\n"
	.string "kostar það ¥{STR_VAR_2}.$"

DayCare_Text_HeresYourMon::
	.string "Fullkomið! Hér er Vasaskrímslið þitt.$"

DayCare_Text_TookBackMon::
	.string "{PLAYER} tók {STR_VAR_1} til baka frá\n"
	.string "DAGGÆSLUKONUNNI.$"

DayCare_Text_YouHaveJustOneMon::
	.string "Ó? En þú ert bara með eitt\n"
	.string "Vasaskrímsli.\p"
	.string "Komdu aftur síðar.$"

DayCare_Text_TakeYourMonBack::
	.string "Viltu taka Vasaskrímslið þitt\n"
	.string "til baka?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "Ef þú skilur þetta Vasaskrímsli eftir,\n"
	.string "með hverju ætlarðu að berjast?\p"
	.string "Komdu aftur síðar.$"

DayCare_Text_Huh::
	.string "Ha?$"
