@ The text here is a copy/paste from Hoenn's Eon Ticket event, all unused and untranslated

Text_DadLetterArrivedForYouPlayer::
	.string "パパ'{PLAYER}！ よく きたな！ {PLAYER}あての\n"
	.string "てがみが とどけられたぞ$"

Text_DadPassForShipNeverSeenBefore::
	.string "パパ'わたしも みたことのない ふねの チケット だな‥‥ ミナモに\n"
	.string "いってみると いいだろう$"

Text_FerryToSlateportOhThatPass::
	.string "カイナいき れんらくせん‥‥\p"
	.string "あら？ その チケットは‥‥！$"

Text_YoureOneWhoBroughtOddPass::
	.string "ヘンテコな チケットを もってきたのは おまえさんか？\p"
	.string "おまえが いこうと しているのは みなみの はての ちっぽけな しま‥‥\p"
	.string "そこでは なにが おこるのか だれも わからねえ‥‥ ううむ ふなのりの\n"
	.string "ちが さわぐぜ！\p"
	.string "さあ のりな！$"

Text_NothingHereSailBackToLilycove::
	.string "なにもねえ ちんけな しま だな‥‥ ミナモへ かえるか？$"

Text_SailHomeWeWill::
	.string "よし！ かえると するか！$"

Text_AsYouLikeThen::
	.string "そうかい まあ すきにするが いいさ$"

SouthernIsland_Interior_Text_Sign::
	.string "すべての ゆめは もうひとつの げんじつ それを わすれるべからず‥‥$"

SouthernIsland_Exterior_Text_Sign::
	.string "きおく かすみし ものは こころに きざみつける ことを のぞむ‥‥$"
