gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "PALLET BÆR$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "PALLET BÆR$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "PALLET BÆR$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "PALLET BÆR$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "PALLET BÆR$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "PALLET BÆR$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "PALLET BÆR$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "PALLET BÆR$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "PALLET BÆR$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "PALLET BÆR$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "PALLET BÆR$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "PALLET BÆR$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "PALLET BÆR$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "PALLET BÆR$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "PALLET BÆR$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "PALLET BÆR$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "PALLET BÆR$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "PALLET BÆR$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "PALLET BÆR$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "PALLET BÆR$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "PALLET BÆR$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "PALLET BÆR$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "PALLET BÆR$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "PALLET BÆR$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "PALLET BÆR$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "PALLET BÆR$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "PALLET BÆR$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "PALLET BÆR$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "PALLET BÆR$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "PALLET BÆR$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "PALLET BÆR$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "PALLET BÆR$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "PALLET BÆR$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "PALLET BÆR$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "PALLET BÆR$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "PALLET BÆR$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "PALLET BÆR$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "RANNSÓKNARSTOFA$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "RANNSÓKNARSTOFA$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "VIRIDIAN-BORG$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "Vasaskrímsli LEAGUE$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "RANNSÓKNARSTOFA$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "RANNSÓKNARSTOFA$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "VERMILION-BORG$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "VATNAVÖLUNDARHÚS$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "VIRIDIAN-BORG$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "CELADON-SETRIÐ$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "FJÓREY$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "PEWTER-BORG$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "PEWTER SALUR$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "PEWTER-BORG$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "LEIÐ 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "MÁNAFJALL$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "PEWTER-SAFNIÐ$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "CERULEAN-BORG$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "CERULEAN SALUR$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "CERULEAN SALUR$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "SJÁFROÐUEYJAR$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "CERULEAN-HÖFÐI$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "CERULEAN-BORG$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "VERMILION-BORG$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "VERMILION SALUR$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "VERMILION SALUR$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "VERMILION SALUR$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "VERMILION SALUR$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "VERMILION-BORG$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "CELADON-BORG$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "CELADON SALUR$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "CELADON SALUR$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "CELADON SALUR$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "CELADON SALUR$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "CELADON-SETRIÐ$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "FUCHSIA-BORG$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "FUCHSIA SALUR$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "FUCHSIA SALUR$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "FUCHSIA-BORG$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "FUCHSIA-BORG$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "SAFARI SVÆÐI$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "SAFFRON-BORG$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "ÞRÍEY$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "SAFFRON SALUR$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "SAFFRON SALUR$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "SAFFRON-BORG$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "SAFFRON SALUR$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "CINNABAR-EYJA$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "CINNABAR SALUR$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "CINNABAR SALUR$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "CINNABAR-EYJA$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "CINNABAR SALUR$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "GLÆSILEGT DVALARSVÆÐI$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "Vasaskrímsli LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "Vasaskrímsli LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "FJÓREY$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "FIMMEY$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "FJÓREY$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "FJÓREY$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "Vasaskrímsli LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "Vasaskrímsli LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "SAFFRON-BORG$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "GLÓÐARLAUGAR$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "TVÍEY$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "SJÖHVOLFA GLJÚFUR$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "Vasaskrímsli LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "INDIGO-HÁSLÉTTA$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "INDIGO-HÁSLÉTTA$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "SJÖEY$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "Vasaskrímsli LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "SEXEY$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "Vasaskrímsli LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "Vasaskrímsli LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "SAFFRON-BORG$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "CELADON-VERSL.$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "INDIGO-HÁSLÉTTA$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "INDIGO-HÁSLÉTTA$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "CERULEAN-BORG$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "CERULEAN-BORG$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "FUCHSIA-BORG$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "EINEY$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "EINEY$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "EINEY$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "LAVENDER-BÆR$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "Vasaskrímsli TOWER$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "LAVENDER-BÆR$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "LAVENDER-BÆR$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "CINNABAR SALUR$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "CINNABAR-EYJA$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "ROCKET-FELUSTAÐUR$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "SILPH-FYRIRTÆKIÐ$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "SILPH-FYRIRTÆKIÐ$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "VIRIDIAN SALUR$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "VIRIDIAN SALUR$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "ROCKET-VÖRUHÚS$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "SKILTI$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "Prófessor EIK$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "AÐSTOÐARMAÐUR$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "AÐSTOÐARMAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "AÐSTOÐARMAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "KONA$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "ELDRI KONA$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "SKILTI$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "BROCK$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "UNGUR MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "STRÁKUR$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "SKILTI$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "MISTY$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "UNGUR MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "DAMA$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "SKILTI$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "LT. SURGE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "DWAYNE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "SKILTI$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "SKILTI$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "SKILTI$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "UNGUR MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "SKILTI$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "BLAINE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "KONA$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "MYND$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "ELDRI MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "LÍTIL STELPA$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "ELDRI KONA$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "KRAMARI$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "KONA$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "KRAMARI$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "KRAMARI$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "KRAMARI$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "ELDRI KONA$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "KONA$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "LÍTIL STELPA$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "UNGUR MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "LITILL DRENGUR$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "ELDRI MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "LÍTIL STELPA$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "ROCKET-GENGIÐ$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "MYND$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "VASASKRÍMSLA TÍMARIT$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "VÍSINDAMAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "VÍSINDAMAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "MAÐUR$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: PEWTER SALUR LEIÐTOGI\n"
	.string "BROCK!\p"
	.string "BROCK hlær sjaldan, en sagt er að\n"
	.string "hann geti ekki hætt ef hann byrjar.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: CERULEAN SALUR\n"
	.string "LEIÐTOGI MISTY!\p"
	.string "Sagt er að MISTY dýrki LORELEI úr\n"
	.string "ELITE FOUR.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: VERMILION SALUR\n"
	.string "LEIÐTOGI LT. SURGE!\p"
	.string "Sagt er að LT. SURGE hafi verið\n"
	.string "flugmaður heima í Ameríku.\p"
	.string "Hann notaði rafmagnið sem\n"
	.string "Vasaskrímsli framleiddu til að knýja\p"
	.string "flugvél sína.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: CELADON SALUR\n"
	.string "LEIÐTOGI ERIKA!\p"
	.string "Orðrómur segir að ef þú kíkir inn í\n"
	.string "CELADON SALUR, sjáirðu oft\p"
	.string "ERIKA kúra.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: FUCHSIA SALUR\n"
	.string "LEIÐTOGI KOGA!\p"
	.string "Sagt er að KOGA búi yfir djúpri\n"
	.string "þekkingu á lækningum.\p"
	.string "Hann blandar jafnvel lyf til að\n"
	.string "hjúkra Vasaskrímslum sínum.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: SAFFRON SALUR\n"
	.string "LEIÐTOGI SABRINA!\p"
	.string "Fólk segir að SABRINA geti samskipti\n"
	.string "við Vasaskrímsli sín\p"
	.string "án þess að tala í bardaga.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: CINNABAR SALUR\n"
	.string "LEIÐTOGI BLAINE!\p"
	.string "Sagt er að BLAINE taki af sér dökk\n"
	.string "gleraugu sín aðeins þegar hann er\p"
	.string "að hugsa upp nýjar spurningar.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: LORELEI úr ELITE\n"
	.string "FOUR!\p"
	.string "Þekkt fyrir rökréttan, útreiknaðan\n"
	.string "og svalan bardagastíl, á LORELEI\p"
	.string "óvænta leyndarmál!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: BRUNO úr ELITE FOUR!\p"
	.string "BRUNO gekk víst í ELITE FOUR vegna\n"
	.string "brennandi metnaðar síns til að\p"
	.string "berjast við bestu ÞJÁLFARANA.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: AGATHA úr ELITE FOUR!\p"
	.string "Á yngri árum voru AGATHA og PRÓF.\n"
	.string "EIK keppinautar sem börðust\p"
	.string "um yfirburði sem ÞJÁLFARAR.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: LANCE úr ELITE FOUR!\p"
	.string "Afi LANCE er talinn vera öldungur\n"
	.string "frægrar ættar drekameistara.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: Prófessor EIK,\n"
	.string "Vasaskrímslafræðingurinn!\p"
	.string "Prófessor EIK býr víst með\n"
	.string "barnabörnum sínum DAISY og {RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "Þetta er VASASKRÍMSLA TÍMARIT frá\n"
	.string "árum áður…\p"
	.string "VASASKRÍMSLA TÍMARIT KEPPNI\n"
	.string "Sérútgáfa!\p"
	.string "Stórmeistari vor-keppninnar er DAISY\n"
	.string "EIK frá PALLET BÆ!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "VASASKRÍMSLA TÍMARIT\p"
	.string "Sérstök grein: MR. FUJI frá\n"
	.string "VASASKRÍMSLA HÚSI!\p"
	.string "Ritstjóri: Feiminn MR. FUJI hafnaði\n"
	.string "viðtalsbeiðnum okkar.\p"
	.string "Hann er góðhjartaður maður sem er\n"
	.string "elskaður og virtur í LAVENDER BÆR.$"
