@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Hún er troðfull af\n"
	.string "Vasaskrímslabókum.$"

Text_NothingButPokemonBooks::
	.string "Í bókahillunni eru bara\n"
	.string "Vasaskrímslabækur.$"

Text_ATownMap::
	.string "BÆJARKORT.$"

Text_PokeMartShelf::
	.string "Vá! Fullt af Vasaskrímsladóti!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Diskar og plötur eru snyrtilega\n"
	.string "raðaðar upp.$"

Text_Kitchen::
	.string "Það lyktar dásamlega! Einhver hefur\n"
	.string "verið að elda hér.$"

Text_Dresser::
	.string "Þetta er vönduð kommóða. Hún getur\n"
	.string "geymt mikið af dóti.$"

Text_Snacks::
	.string "Hér er hrúga af snakki.$"

Text_PokemartSign::
	.string "Allt sem þig vantar!\n"
	.string "Vasaskrímslabúð$"

Text_PokecenterSign::
	.string "Læknaðu Vasaskrímslin þín!\n"
	.string "Vasaskrímslasetur$"

Text_Indigo_UltimateGoal::
	.string "INDIGO PLATEAU\p"
	.string "Endanlegt markmið ÞJÁLFARA!\n"
	.string "HÖFUÐSTÖÐVAR Vasaskrímsladeildar$"

Text_Indigo_HighestAuthority::
	.string "INDIGO PLATEAU\p"
	.string "Æðsta yfirvald Vasaskrímsla!\n"
	.string "HÖFUÐSTÖÐVAR Vasaskrímsladeildar$"

Text_Food::
	.string "Það ætti að vera fullt af alls kyns\n"
	.string "ljúffengum hlutum til að borða.$"

Text_Blueprints::
	.string "Þetta er einhvers konar teikning.\n"
	.string "Hún er full af skýringarmyndum og\p"
	.string "texta.$"

Text_Painting::
	.string "Þetta er falleg mynd af\n"
	.string "Vasaskrímsli. Það virðist\p"
	.string "líða vel.$"

Text_PowerPlantMachine::
	.string "Hvað gæti þessi vél verið? Betra að\n"
	.string "fikta ekki í henni!$"

Text_Telephone::
	.string "Þetta er sími. Betra að nota hann\n"
	.string "ekki.$"

Text_Computer::
	.string "Þetta eru allt flókin orð og tölur\n"
	.string "sem eru óskiljanleg…$"

Text_AdvertisingPoster::
	.string "Þetta er auglýsingaplakat um alls\n"
	.string "konar vörur.$"

Text_TastyFood::
	.string "Ó, þetta lyktar girnilega! Það gæti\n"
	.string "látið magann kurra!$"

Text_TrashBin::
	.string "Inni í þessu… ……\p"
	.string "Það er ekkert hér!$"

Text_Cup::
	.string "Þetta er bolli með Vasaskrímsla\n"
	.string "merki á honum.$"

Text_PolishedWindow::
	.string "Glugginn er mjög vel pússaður.$"

Text_BeautifulSkyWindow::
	.string "Fyrir utan gluggann…\p"
	.string "Himinninn lítur stórkostlega fagur\n"
	.string "út.$"

Text_BlinkingLights::
	.string "Ljós í mismunandi litum eru að\n"
	.string "blikka á og af.$"

Text_NeatlyLinedUpTools::
	.string "Alls kyns verkfæri eru snyrtilega\n"
	.string "raðað upp.$"

Text_ImpressiveMachine::
	.string "Þetta er einhvers konar vél. Hún er\n"
	.string "vissulega áhrifamikil.$"

Text_VideoGame::
	.string "Þetta er nýjasti tölvuleikurinn!\n"
	.string "Hann lítur vissulega skemmtilega út!$"

Text_Burglary::
	.string "Hér eru augljós merki um innbrot…$"

Text_PlayerFacingTVScreen::
	.string "Það er Vasaskrímsli í sjónvarpinu!\n"
	.string "Það virðist skemmta sér vel.$"
