Help_Text_WhatShouldIDo::
	.string "Hvað ætti ég að gera í þessari\n"
	.string "stöðu?$"

Help_Text_HowDoIDoThis::
	.string "Hvernig geri ég þetta?$"

Help_Text_WhatDoesThisTermMean::
	.string "Hvað þýðir þetta hugtak?$"

Help_Text_AboutThisGame::
	.string "Um þennan leik$"

Help_Text_TypeMatchupList::
	.string "Tegundarviðmiðunarlisti$"

Help_Text_Exit::
	.string "HÆTTA$"

Help_Text_Cancel::
	.string "HÆTTA VIÐ$"

Help_Text_TryDoingItOnYourOwn::
	.string "Reyndu að gera það sjálf/ur!$"

Help_Text_DescWhatShouldIDo::
	.string "Veldu til að fá vísbendingar um\n"
	.string "hvernig á að takast á við krefjandi\p"
	.string "aðstæður.$"

Help_Text_DescHowDoIDoThis::
	.string "Ítarlegar leiðbeiningar eru gefnar\n"
	.string "fyrir mismunandi aðgerðir.$"

Help_Text_DescWhatDoesThisTermMean::
	.string "Ítarlegar lýsingar eru gefnar á\n"
	.string "hugtökum sem birtast í leiknum.$"

Help_Text_DescAboutThisGame::
	.string "Ítarlegar lýsingar eru gefnar um\n"
	.string "þennan leik.$"

Help_Text_DescTypeMatchupList::
	.string "Tegundarviðmiðun Vasaskrímsla og\n"
	.string "hreyfinga er skráð.$"

Help_Text_DescExit::
	.string "Veldu til að hætta í HJÁLPARKERFINU.$"

Help_Text_Greetings::
	.string "Halló! Þetta er HJÁLPARKERFIÐ.\n"
	.string "Kallaðu á mig hvenær og hvar sem þú\p"
	.string "þarft með því að ýta á L eða R\n"
	.string "takkann. Hjálparskilaboðin breytast\p"
	.string "eftir\p"
	.string "aðstæðum, svo athugaðu þau oft,\n"
	.string "vinsamlegast.$"

Help_Text_PlayingForFirstTime::
	.string "Ég er að spila í fyrsta skipti.\n"
	.string "Hjálp!$"

Help_Text_WhatShouldIBeDoing::
	.string "Hvað ætti ég að vera að gera?$"

Help_Text_CantGetOutOfRoom::
	.string "Ég kemst ekki út úr herbergi!$"

Help_Text_CantFindPersonIWant::
	.string "Ég finn ekki þann sem ég leita að.$"

Help_Text_TalkedToEveryoneNowWhat::
	.string "Ég hef talað við alla. Hvað nú?$"

Help_Text_SomeoneBlockingMyWay::
	.string "Það er einhver að loka leið minni!$"

Help_Text_ICantGoOn::
	.string "Ég get ekki haldið áfram!$"

Help_Text_OutOfThingsToDo::
	.string "Ég er búinn með verkefni.$"

Help_Text_WhatHappenedToItemIGot::
	.string "Hvað varð um hlutinn sem ég fékk?$"

Help_Text_WhatAreMyAdventureBasics::
	.string "Hver eru grunnatriði ævintýrisins\n"
	.string "míns?$"

Help_Text_HowAreRoadsForestsDifferent::
	.string "Hvernig eru vegir og skógar ólíkir?$"

Help_Text_HowAreCavesDifferent::
	.string "Hvernig eru hellar ólíkir?$"

Help_Text_HowDoIProgress::
	.string "Hvernig kemst ég áfram?$"

Help_Text_WhenCanIUseItem::
	.string "Hvenær get ég notað hluti?$"

Help_Text_WhatsABattle::
	.string "Hvað er bardagi?$"

Help_Text_HowDoIPrepareForBattle::
	.string "Hvernig undirbý ég mig fyrir\n"
	.string "bardaga?$"

Help_Text_WhatIsAMonsVitality::
	.string "Hvað er lífsorka Vasaskrímslis?$"

Help_Text_MyMonsAreHurt::
	.string "Vasaskrímslin mín eru særð!$"

Help_Text_WhatIsStatusProblem::
	.string "Hvað er stöðuvandamál?$"

Help_Text_WhatHappensIfAllMyMonsFaint::
	.string "Hvað gerist ef öll Vasaskrímslin mín\n"
	.string "falla í yfirlið?$"

Help_Text_CantCatchMons::
	.string "Ég get ekki fangað Vasaskrímsli!$"

Help_Text_RanOutOfPotions::
	.string "Ég kláraði SEYÐIÐ.$"

Help_Text_CanIBuyPokeBalls::
	.string "Get ég keypt VASA BOLTA?$"

Help_Text_WhatsATrainer::
	.string "Hvað er ÞJÁLFARI?$"

Help_Text_HowDoIWinAgainstTrainer::
	.string "Hvernig vinn ég gegn ÞJÁLFARA?$"

Help_Text_WhereDoMonsAppear::
	.string "Hvar birtast Vasaskrímsli?$"

Help_Text_WhatAreMoves::
	.string "Hverjar eru hreyfingar Vasaskrímsla?$"

Help_Text_WhatAreHiddenMoves::
	.string "Hvað eru FALDAR hreyfingar?$"

Help_Text_WhatMovesShouldIUse::
	.string "Hvaða hreyfingar ætti ég að nota?$"

Help_Text_WantToAddMoreMoves::
	.string "Ég vil bæta við fleiri hreyfingum.$"

Help_Text_WantToMakeMonStronger::
	.string "Ég vil gera Vasaskrímslið mitt\n"
	.string "sterkara.$"

Help_Text_FoeMonsTooStrong::
	.string "Vasaskrímsli óvinarins eru of sterk!$"

Help_Text_WhatDoIDoInCave::
	.string "Hvað geri ég í helli?$"

Help_Text_NothingIWantToKnow::
	.string "Það er ekkert sem ég vil vita!$"

Help_Text_WhatsPokemonCenter::
	.string "Hvað er Vasaskrímsli MIÐSTÖÐ?$"

Help_Text_WhatsPokemonMart::
	.string "Hvað er Vasaskrímsli VERSLUN?$"

Help_Text_WantToEndGame::
	.string "Ég vil ljúka leiknum.$"

Help_Text_WhatsAMon::
	.string "Hvað er Vasaskrímsli?$"

Help_Text_WhatIsThatPersonLike::
	.string "Hvernig er sú manneskja?$"

Help_Text_WhatDoesHiddenMoveDo::
	.string "Hvað gerir FÖLDU hreyfing?$"

Help_Text_WhatDoIDoInSafari::
	.string "Hvað geri ég í SAFARI LEIKNUM?$"

Help_Text_WhatAreSafariRules::
	.string "Hverjar eru reglurnar í SAFARI\n"
	.string "LEIKNUM?$"

Help_Text_WantToEndSafari::
	.string "Ég vil ljúka þessum SAFARI LEIK!$"

Help_Text_WhatIsAGym::
	.string "Hvað er SALUR?$"

Help_Text_AnswerPlayingForFirstTime::
	.string "Þú verður aðalpersónan og kannar\n"
	.string "heim Vasaskrímsla.\p"
	.string "Með því að tala við fólk og leysa\n"
	.string "gátur munu nýjar leiðir opnast\p"
	.string "fyrir þér. Strefðu að markmiðinu\n"
	.string "saman með dásamlegu Vasaskrímslunum\p"
	.string "þínum.$"

Help_Text_AnswerWhatShouldIBeDoing::
	.string "Þegar þú hittir aðra manneskju,\n"
	.string "gakktu að henni og ýttu á A\p"
	.string "takkann. Það fær þau til að tala og\n"
	.string "hafa samskipti við persónuna þína.\p"
	.string "Þú getur líka skoðað ýmsa hluti og\n"
	.string "hluti á sama hátt. Talaðu við\p"
	.string "fólk og athugaðu hluti oft til að fá\n"
	.string "upplýsingar.$"

Help_Text_AnswerCantGetOutOfRoom::
	.string "Á stigum eða útgöngum úr byggingu er\n"
	.string "rauð mottu. Færðu\p"
	.string "persónuna þína til að standa á rauðu\n"
	.string "mottunni. Ýttu á {PLUS} stýripúðann\p"
	.string "í átt að stigunum eða útgöngunni til\n"
	.string "að halda áfram.$"

Help_Text_AnswerCantFindPersonIWant::
	.string "Þetta er ekki eitthvað sem þú ættir\n"
	.string "að hafa of miklar áhyggjur af.\p"
	.string "Talaðu við aðra\p"
	.string "menn, athugaðu skilti, athugaðu\n"
	.string "hluti, og svo framvegis. Stundum\p"
	.string "gætirðu þurft\p"
	.string "að flytja til nýs bæjar eða staðar.$"

Help_Text_AnswerTalkedToEveryoneNowWhat::
	.string "Reyndu að halda áfram á nýjan veg,\n"
	.string "bæ, eða stað.$"

Help_Text_AnswerSomeoneBlockingMyWay::
	.string "Það gæti verið eitthvað í bænum eða\n"
	.string "inni í byggingu sem er\p"
	.string "orsökin. Reyndu að tala við fólkið á\n"
	.string "svæðinu aftur. Ef það er\p"
	.string "vandamál sem þau þurfa að leysa,\n"
	.string "gætirðu þurft að hjálpa. Eftir það,\p"
	.string "reyndu\p"
	.string "að tala við manneskjuna sem lokar\n"
	.string "leið þinni aftur.$"

Help_Text_AnswerICantGoOn::
	.string "Reyndu að tala við fólk með því að\n"
	.string "ganga að þeim og ýta á A takkann.\p"
	.string "Reyndu líka að athuga hluti eins og\n"
	.string "skrítin tré og undarlega steina með\p"
	.string "A\p"
	.string "takkanum. Ýttu á {PLUS} stýripúðann\n"
	.string "og reyndu að fara á staði sem\p"
	.string "virðast\p"
	.string "ófærðir líka.$"

Help_Text_AnswerOutOfThingsToDo::
	.string "Reyndu að fara á staði sem þú hefur\n"
	.string "ekki heimsótt ennþá. Athugaðu líka\p"
	.string "allt sem lítur grunsamlega út með\n"
	.string "því að ýta á A takkann.$"

Help_Text_AnswerWhatHappenedToItemIGot::
	.string "Allir hlutir sem þú færð frá annarri\n"
	.string "persónu fara í TÖSKUNA þína.\p"
	.string "Hluturinn er sjálfkrafa flokkaður og\n"
	.string "settur í einn af þremur vösum. Fyrir\p"
	.string "leiðbeiningar um notkun TÖSKUNNAR,\n"
	.string "vinsamlegast skoðaðu HJÁLPARKERFIÐ\p"
	.string "undir\p"
	.string "fyrirsögninni 'Hvernig geri ég\n"
	.string "þetta?'$"

Help_Text_AnswerWhatAreMyAdventureBasics::
	.string "Ef Vasaskrímsli særast í bardaga,\n"
	.string "farðu með þau á Vasaskrímsli MIÐSTÖÐ\p"
	.string "og láttu starfsfólkið lækna þau.\n"
	.string "Venstu því að vista leikinn þinn\p"
	.string "og skrá framvindu þína. Safnaðu\n"
	.string "lækningahlutum í Vasaskrímsli\p"
	.string "VERSLUNUM áður en þú ferðast langt.$"

Help_Text_AnswerHowAreRoadsForestsDifferent::
	.string "Skógar eru í grundvallaratriðum eins\n"
	.string "og vegir en þeir geta verið eins og\p"
	.string "völundarhús.\p"
	.string "Allir skógar hafa leið út, svo ekki\n"
	.string "gefast upp ef þú týnist.$"

Help_Text_AnswerHowAreCavesDifferent::
	.string "Hellar eru dimmir og hættulegir.\n"
	.string "Villt Vasaskrímsli geta birst hvar\p"
	.string "sem er í þeim. Ef neyðarástand er,\n"
	.string "hlauptu á Vasaskrímsli MIÐSTÖÐ eða\p"
	.string "notaðu hluti. Nýir bæir bíða\n"
	.string "uppgötvunar handan sumra hella, svo\p"
	.string "ekki gefast upp.$"

Help_Text_AnswerHowDoIProgress::
	.string "Markmið leiksins er að þjálfa\n"
	.string "Vasaskrímslið þitt og halda áfram.\p"
	.string "Þú verður að safna upplýsingum og\n"
	.string "leysa vandamál. Til dæmis, hvað\p"
	.string "þarftu til að komast framhjá\n"
	.string "hindrun? Hvað myndi fá þessa\p"
	.string "hindrandi manneskju úr vegi?$"

Help_Text_AnswerWhenCanIUseItem::
	.string "Það eru nokkrar tegundir af hlutum.\n"
	.string "Sumir er aðeins hægt að nota á\p"
	.string "vellinum.\p"
	.string "Sumir eru aðeins til notkunar í\n"
	.string "bardaga. Sumir er hægt að nota\p"
	.string "hvenær sem er. Reyndu að nota\p"
	.string "hlut - ef hann er ekki hægt að nota,\n"
	.string "verður þér gert viðvart.$"

Help_Text_AnswerWhatsABattle::
	.string "Í bardaga reyna Vasaskrímsli að\n"
	.string "lækka lífsorku hvors annars,\p"
	.string "sem er gefin upp sem HP. Ef HP\n"
	.string "Vasaskrímslis fellur í núll, fellur\p"
	.string "það í yfirlið, og hitt Vasaskrímslið\n"
	.string "vinnur. Með því að vinna bardaga\p"
	.string "þéna Vasaskrímsli EXP. stig, sem\n"
	.string "hjálpa þeim að hækka um stig (verða\p"
	.string "sterkari).$"

Help_Text_AnswerHowDoIPrepareForBattle::
	.string "Fyrst skaltu lækna Vasaskrímslin í\n"
	.string "hópnum þínum (Vasaskrímslin sem\p"
	.string "eru með þér) að fullu á hvaða\n"
	.string "Vasaskrímsli MIÐSTÖÐ sem er. Þú\p"
	.string "ættir líka að kaupa lækningahluti\n"
	.string "fyrir neyðartilvik í Vasaskrímsli\p"
	.string "VERSLUN.$"

Help_Text_AnswerWhatIsAMonsVitality::
	.string "Lífsorka Vasaskrímslis er gefin upp\n"
	.string "í HP. Ef Vasaskrímsli særast\p"
	.string "í bardaga er HP dregið frá. Ef HP\n"
	.string "þess fellur í núll, fellur\p"
	.string "Vasaskrímslið í yfirlið. Læknaðu\n"
	.string "særð eða yfirliðin Vasaskrímsli á\p"
	.string "Vasaskrímsli MIÐSTÖÐ eða með því að\n"
	.string "nota hluti.$"

Help_Text_AnswerMyMonsAreHurt::
	.string "Vasaskrímsli MIÐSTÖÐ er eins og\n"
	.string "gistihús fyrir Vasaskrímsli. Hún\p"
	.string "mun lækna Vasaskrímsli að fullu af\n"
	.string "hvers kyns stöðuvandamálum og endur-\p"
	.string "heimta HP þeirra að fullu með\n"
	.string "sérstakri vél. Þessi þjónusta er\p"
	.string "ókeypis, svo venstu því að lækna\n"
	.string "Vasaskrímslin þín oft.$"

Help_Text_AnswerWhatIsStatusProblem::
	.string "Stöðuvandamál vísar til kvilla sem\n"
	.string "er valdið Vasaskrímsli af árás\p"
	.string "óvinar þess. Þetta felur í sér\n"
	.string "bruna, lömun, eitrun, svefn og\p"
	.string "frystingu.\p"
	.string "Hægt er að lækna þetta með því að\n"
	.string "heimsækja Vasaskrímsli MIÐSTÖÐ eða\p"
	.string "nota viðeigandi hlut.$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
	.string "Ef öll Vasaskrímslin í hópnum þínum\n"
	.string "(öll Vasaskrímslin með þér) falla í\p"
	.string "yfirlið, tapar þú einhverjum\n"
	.string "Peningum, og þú ert sendur heim eða\p"
	.string "á\p"
	.string "Vasaskrímsli MIÐSTÖÐ. Til að minnka\n"
	.string "þá líkur skaltu heimsækja\p"
	.string "Vasaskrímsli MIÐSTÖÐVAR oft. Venstu\n"
	.string "líka því að vista oft.$"

Help_Text_AnswerCantCatchMons::
	.string "Ef villt Vasaskrímsli sleppur úr\n"
	.string "VASABOLTA, er það augljóslega enn\p"
	.string "frekt. Reyndu að lækka HP þess að\n"
	.string "einhverju leyti, og reyndu að veikja\p"
	.string "það með lömun eða svefni áður en þú\n"
	.string "reynir að veiða það. Ef VASA BOLTINN\p"
	.string "hristist um stund, er bráðin nálægt\n"
	.string "því að vera veidd!$"

Help_Text_AnswerRanOutOfPotions::
	.string "Það eru verslanir, þekktar sem\n"
	.string "Vasaskrímsli VERSLANIR, sem selja\p"
	.string "hluti. Þú finnur ekki Vasaskrímsli\n"
	.string "VERSLANIR á vegum, í skógum eða í\p"
	.string "hellum. Safnaðu nauðsynlegum hlutum\n"
	.string "meðan þú heimsækir bæ með\p"
	.string "Vasaskrímsli VERSLUN.$"

Help_Text_AnswerCanIBuyPokeBalls::
	.string "Þú getur keypt VASA BOLTA í hvaða\n"
	.string "Vasaskrímsli VERSLUN sem er í hvaða\p"
	.string "bæ sem er. Þú finnur ekki\n"
	.string "Vasaskrímsli VERSLANIR á vegum, í\p"
	.string "skógum eða í hellum. Safnaðu VASA\n"
	.string "BOLTUM meðan þú heimsækir bæ með\p"
	.string "Vasaskrímsli VERSLUN.$"

Help_Text_AnswerWhatsATrainer::
	.string "ÞJÁLFARI er manneskja sem ræktar\n"
	.string "Vasaskrímsli með bardögum.\p"
	.string "ÞJÁLFARAR munu skora á þig hvar sem\n"
	.string "þeir eru - það gæti verið á vegi, í\p"
	.string "skógum, hellum, hvar sem er. Ef augu\n"
	.string "ykkar mætast, verður þú að samþykkja\p"
	.string "skorun þeirra. Svo vertu varkár!$"

Help_Text_AnswerHowDoIWinAgainstTrainer::
	.string "Til að sigra ÞJÁLFARA í bardaga,\n"
	.string "notaðu Vasaskrímsli sem hafa\p"
	.string "tegundarforgang yfir Vasaskrímsli\n"
	.string "óvinarins. Þú getur líka notað\p"
	.string "háþjálfuð Vasaskrímsli með\n"
	.string "yfirgnæfandi krafti. Að vera fleiri\p"
	.string "en Vasaskrímsli óvinarins er önnur\n"
	.string "augljós taktík.$"

Help_Text_AnswerWhereDoMonsAppear::
	.string "Villt Vasaskrímsli munu birtast í\n"
	.string "háu grasi, á vegum og í skógum.\p"
	.string "Þau munu birtast hvar sem er í\n"
	.string "dimmum hellum. Það eru engin villt\p"
	.string "Vasaskrímsli eða ÞJÁLFARAR í bæjum,\n"
	.string "svo þeir eru öruggir staðir.$"

Help_Text_AnswerWhatAreMoves::
	.string "Vasaskrímsli geta lært allt að\n"
	.string "fjórar mismunandi tækni, eða\p"
	.string "hreyfingar.\p"
	.string "Það er mikill fjölbreytileiki af\n"
	.string "hreyfingum, þar á meðal árásum og\p"
	.string "þeim sem hafa sérstök áhrif.\n"
	.string "Tegundir hreyfinga sem hægt er að\p"
	.string "læra eru\p"
	.string "mismunandi fyrir hvert Vasaskrímsli.\n"
	.string "Sumar hreyfingar er hægt að læra\p"
	.string "af vélum.$"

Help_Text_AnswerWhatAreHiddenMoves::
	.string "FALDAR hreyfingar eru þær sem eru\n"
	.string "sérstaklega mikilvægar fyrir\p"
	.string "ævintýrið þitt. Til að nota slíka\n"
	.string "hreyfingu utan bardaga, opnaðu\p"
	.string "'Vasaskrímsli' VALMYNDINA og láttu\n"
	.string "Vasaskrímslið sem kann hreyfinguna\p"
	.string "nota hana. Yfirliðið Vasaskrímsli\n"
	.string "getur notað FALDA hreyfingu utan\p"
	.string "bardaga.$"

Help_Text_AnswerWhatMovesShouldIUse::
	.string "Veldu 'BARDAG,' og VALMYND hreyfinga\n"
	.string "mun birtast. Íhugaðu\p"
	.string "tegundarviðmiðun, og notaðu\n"
	.string "áhrifaríkustu hreyfingarnar. Þú\p"
	.string "getur\p"
	.string "skoðað áhrif hreyfinga með því að\n"
	.string "opna 'Vasaskrímsli,' velja\p"
	.string "Vasaskrímsli, opna 'YFIRLIT,' og\n"
	.string "síðan opna 'Vasaskrímsli FÆRNI.'$"

Help_Text_AnswerWantToAddMoreMoves::
	.string "Mest sem Vasaskrímsli getur lært eru\n"
	.string "fjórar hreyfingar. Þær eru lærðar\p"
	.string "eftir því sem Vasaskrímslið hækkar\n"
	.string "um stig. Því er einnig hægt að kenna\p"
	.string "hreyfingu með því að nota TM\n"
	.string "(Tæknivél) eða HM (Falinn vél).\p"
	.string "Það eru líka til fólk sem kennir\n"
	.string "hreyfingar.$"

Help_Text_AnswerWantToMakeMonStronger::
	.string "Lykillinn að því að gera\n"
	.string "Vasaskrímslið þitt sterkt er að\p"
	.string "berjast og vinna oft. EXP. (reynslu)\n"
	.string "stigin sem þénuð eru með því að\p"
	.string "vinna bardaga safnast upp til að\n"
	.string "hækka Vasaskrímsli sem tóku þátt í\p"
	.string "þeim um stig. Berjist oft við villt\n"
	.string "Vasaskrímsli til að hækka hópinn\p"
	.string "þinn um stig.$"

Help_Text_AnswerFoeMonsTooStrong::
	.string "Ef óvinir þínir eru of sterkir,\n"
	.string "reyndu að hækka Vasaskrímslin þín\p"
	.string "eitthvað meira um stig. Farðu til\n"
	.string "baka sömu leið og þú komst og\p"
	.string "berjist við villt Vasaskrímsli til\n"
	.string "að hækka hópinn þinn um stig. Þú\p"
	.string "getur\p"
	.string "líka barist við ÞJÁLFARA sem þú\n"
	.string "hefur ekki barist við áður.$"

Help_Text_AnswerWhatDoIDoInCave::
	.string "Ólíkt vegum og skógum, geta villt\n"
	.string "Vasaskrímsli birst hvar sem er í\p"
	.string "hellum. Ef Vasaskrímslin þín særast\n"
	.string "í helli, hlauptu á Vasaskrímsli\p"
	.string "MIÐSTÖÐ eða notaðu hluti til að\n"
	.string "lækna þau strax. Það er mjög\p"
	.string "hættulegt að reyna á heppnina í\n"
	.string "hellum.$"

Help_Text_AnswerNothingIWantToKnow::
	.string "Treystu eigin þekkingu og krafti.\n"
	.string "Trúðu á sjálfan þig og finndu þína\p"
	.string "leið!$"

Help_Text_AnswerWhatsPokemonCenter::
	.string "Vasaskrímsli MIÐSTÖÐ er auðkennd með\n"
	.string "rauðu þaki og 'P.C' skilti.\p"
	.string "Hver Vasaskrímsli MIÐSTÖÐ býður upp\n"
	.string "á þjónustu eins og fulla lækningu\p"
	.string "Vasaskrímsla og ókeypis tölvunotkun,\n"
	.string "sem gerir hana ómissandi fyrir\p"
	.string "ferðalög þín. Á efri hæð eru aðstaða\n"
	.string "til að tengjast vinum og\p"
	.string "öðrum.$"

Help_Text_AnswerWhatsPokemonMart::
	.string "Vasaskrímsli VERSLUN er auðkennd með\n"
	.string "bláu þaki og 'VERSLUN' skilti.\p"
	.string "Hægt er að kaupa og selja hluti í\n"
	.string "hvaða Vasaskrímsli VERSLUN sem er.\p"
	.string "Sumar VERSLANIR selja hluti sem eru\n"
	.string "aðeins fáanlegir í þeirra bæjum.$"

Help_Text_AnswerWantToEndGame::
	.string "Þú getur örugglega hætt í leiknum\n"
	.string "með því að velja 'VISTA' í\p"
	.string "VALMYNDINNI. Þegar þú hefur vistað\n"
	.string "má slökkva á leiknum.\p"
	.string "Þegar kveikt er aftur geturðu haldið\n"
	.string "áfram þar sem þú vistaðir síðast.$"

Help_Text_AnswerWhatsAMon::
	.string "Vasaskrímsli eru lifandi verur um\n"
	.string "sem margar gátur eru enn óleystar.\p"
	.string "Þú gætir séð þau í grasi, sjónum og\n"
	.string "hellum. Þau virðast hlýða óskum\p"
	.string "ÞJÁLFARANNA sem veiddu þau.$"

Help_Text_AnswerWhatIsThatPersonLike::
	.string "Notaðu FRÆGÐARSJÁNA meðal LYKILHLUTA\n"
	.string "í TÖSKUNNI þinni. Hún\p"
	.string "gæti gefið þér vísbendingu, svo\n"
	.string "prófaðu hana.$"

Help_Text_AnswerWhatDoesHiddenMoveDo::
	.string "FÖLDU hreyfingu er kennt\n"
	.string "Vasaskrímsli með því að nota HM\p"
	.string "(Falinn vél). FÖLDU hreyfing er\n"
	.string "mikilvæg til að hjálpa ævintýrinu\p"
	.string "þínu. Til dæmis er ein notuð til að\n"
	.string "lýsa upp dimma hella. Önnur sker\p"
	.string "niður\p"
	.string "lítil tré. Það er ein til að ferðast\n"
	.string "á vatni, og svo framvegis.$"

Help_Text_AnswerWhatDoIDoInSafari::
	.string "Reyndu að fanga villt Vasaskrímsli\n"
	.string "með því að kasta sérstökum SAFARI\p"
	.string "BOLTUM. Þú mátt líka halda öllum\n"
	.string "hlutum sem þú finnur.$"

Help_Text_AnswerWhatAreSafariRules::
	.string "SAFARI LEIKURINN þinn endar þegar þú\n"
	.string "hefur ferðast ákveðna vegalengd eða\p"
	.string "kastað öllum SAFARI BOLTUM þínum.\n"
	.string "Opnaðu VALMYNDINA til að athuga\p"
	.string "eftirstandandi\p"
	.string "fjölda skrefa og SAFARI BOLTA.$"

Help_Text_AnswerWantToEndSafari::
	.string "Ef þú vilt stytta SAFARI LEIKINN\n"
	.string "þinn, opnaðu VALMYNDINA og veldu\p"
	.string "'RETIRE' efst á listanum.$"

Help_Text_AnswerWhatIsAGym::
	.string "Vasaskrímsla SALIR eru reknir af\n"
	.string "Vasaskrímsla DEILDINNI og eru\p"
	.string "þjálfunarstaðir fyrir ÞJÁLFARA.\n"
	.string "Þeir eru í borgum og bæjum um\p"
	.string "allt land. Hverjum þeirra stýrir\n"
	.string "LEIÐTOGI, mjög fær ÞJÁLFARI.\p"
	.string "Sigraðu LEIÐTOGANN til að fá\n"
	.string "MERKI.$"

Help_Text_UsingPokedex::
	.string "Nota 'VasaDEX'$"

Help_Text_UsingPokemon::
	.string "Nota 'VASASKR'$"

Help_Text_UsingSummary::
	.string "Nota 'YFIRLIT'$"

Help_Text_UsingSwitch::
	.string "Nota 'SKIPTA'$"

Help_Text_UsingItem::
	.string "Nota 'HLUTUR'$"

Help_Text_UsingBag::
	.string "Nota 'TASKA'$"

Help_Text_UsingAnItem::
	.string "Nota hlut$"

Help_Text_UsingKeyItem::
	.string "Nota lykilhlut$"

Help_Text_UsingPokeBall::
	.string "Nota VASA BOLTA$"

Help_Text_UsingPlayer::
	.string "Nota '{PLAYER}'$"

Help_Text_UsingSave::
	.string "Nota 'VISTA'$"

Help_Text_UsingOption::
	.string "Nota 'VALKOSTUR'$"

Help_Text_UsingPotion::
	.string "Nota SEYÐI$"

Help_Text_UsingTownMap::
	.string "Nota BÆJARKORTIÐ$"

Help_Text_UsingTM::
	.string "Nota TM$"

Help_Text_UsingHM::
	.string "Nota HM$"

Help_Text_UsingMoveOutsideOfBattle::
	.string "Að nota hreyfingu utan bardaga$"

Help_Text_RidingBicycle::
	.string "Að hjóla á REIÐHJÓLINU$"

Help_Text_EnteringName::
	.string "Að slá inn nafn$"

Help_Text_UsingPC::
	.string "Að nota tölvu$"

Help_Text_UsingBillsPC::
	.string "Nota '{STR_VAR_1}'S TÖLVU'$"

Help_Text_UsingWithdraw::
	.string "Nota 'TAKA ÚT'$"

Help_Text_UsingDeposit::
	.string "Nota 'LEGGJA INN'$"

Help_Text_UsingMove::
	.string "Nota 'FÆRA'$"

Help_Text_MovingItems::
	.string "Færa hluti$"

Help_Text_UsingPlayersPC::
	.string "Nota '{PLAYER}'s TÖLVU'$"

Help_Text_UsingWithdrawItem::
	.string "Nota 'TAKA HLUT ÚT'$"

Help_Text_UsingDepositItem::
	.string "Nota 'LEGGJA HLUT INN'$"

Help_Text_UsingMailbox::
	.string "Nota 'PÓSTKASSI'$"

Help_Text_UsingProfOaksPC::
	.string "Nota 'TÖLVU Prófessor EIK'$"

Help_Text_OpeningMenu::
	.string "Að opna VALMYNDINA$"

Help_Text_UsingFight::
	.string "Nota 'BERJAST'$"

Help_Text_UsingPokemon2::
	.string "Nota 'VASASKR'$"

Help_Text_UsingShift::
	.string "Nota 'FÆRA'$"

Help_Text_UsingSummary2::
	.string "Nota 'YFIRLIT'$"

Help_Text_UsingBag2::
	.string "Nota 'TASKA'$"

Help_Text_ReadingPokedex::
	.string "Lesa 'VasaDEX'$"

Help_Text_UsingHomePC::
	.string "Að nota tölvuna heima$"

Help_Text_UsingItemStorage::
	.string "Að nota hlutageymslukerfið$"

Help_Text_UsingWithdrawItem2::
	.string "Nota 'TAKA HLUT ÚT'$"

Help_Text_UsingDepositItem2::
	.string "Nota 'LEGGJA HLUT INN'$"

Help_Text_UsingMailbox2::
	.string "Að nota PÓSTKASSANN$"

Help_Text_UsingRun::
	.string "Nota 'FLÝJA'$"

Help_Text_RegisterKeyItem::
	.string "'SKRÁ' lykilhlut$"

Help_Text_UsingBall::
	.string "Nota 'BOLTA'$"

Help_Text_UsingBait::
	.string "Nota 'BEITU'$"

Help_Text_UsingRock::
	.string "Nota 'STEIN'$"

Help_Text_UsingHallOfFame::
	.string "Nota 'FRÆGÐARHÖLLINA'$"

Help_Text_HowToUsePokedex::
	.string "{CIRCLE_1} Veldu 'VasaDEX' í\n"
	.string "VALMYNDINNI. {CIRCLE_2} Veldu\p"
	.string "Vasaskrímsli\p"
	.string "með skipunum eins og 'VASASKRÍMSLA\n"
	.string "LISTI,' 'BÚSVÆÐI VASASKRÍMSLA,'\p"
	.string "og 'LEIT.' {CIRCLE_3} Veldu\n"
	.string "Vasaskrímsli til að fá nákvæmar\p"
	.string "upplýsingar.$"

Help_Text_HowToUsePokemon::
	.string "{CIRCLE_1} Veldu 'Vasaskrímsli' í\n"
	.string "VALMYNDINNI. {CIRCLE_2} Veldu\p"
	.string "Vasaskrímsli í hópnum þínum.\n"
	.string "{CIRCLE_3} Veldu 'YFIRLIT,'\p"
	.string "'SKIPTA,' eða 'HLUTUR.'$"

Help_Text_HowToUseSummary::
	.string "{CIRCLE_1} Veldu 'YFIRLIT.'\n"
	.string "{CIRCLE_2} Ýttu á vinstri eða hægri\p"
	.string "á\p"
	.string "{PLUS} stýripúðanum til að skoða\n"
	.string "upplýsingarnar: 'VASASKRÍMSLA\p"
	.string "UPPLÝSINGAR'\p"
	.string "'VASASKRÍMSLA HÆFNI' 'ÞEKKTAR\n"
	.string "HREYFINGAR'$"

Help_Text_HowToUseSwitch::
	.string "{CIRCLE_1} Veldu Vasaskrímslið sem\n"
	.string "þú vilt skipta um.\p"
	.string "{CIRCLE_2} Veldu 'SKIPTA.'\n"
	.string "{CIRCLE_3} Veldu Vasaskrímslið\p"
	.string "til að skipta við það fyrsta. Það\n"
	.string "Vasaskrímsli vinstra megin á\p"
	.string "skjánum verður það fyrsta sem fer í\n"
	.string "bardaga.$"

Help_Text_HowToUseItem::
	.string "{CIRCLE_1} Veldu 'HLUTUR.'\n"
	.string "{CIRCLE_2} Veldu hvort þú vilt\p"
	.string "'GEFA' Vasaskrímsli\p"
	.string "hlut til að halda, eða 'TAKA' hlut\n"
	.string "sem það heldur. Vasaskrímsli\p"
	.string "getur ekki haldið fleiri en einum\n"
	.string "hlut!$"

Help_Text_HowToUseBag::
	.string "{CIRCLE_1} Veldu 'TASKA' í VALMYND.\n"
	.string "{CIRCLE_2} Ýttu á vinstri eða hægri\p"
	.string "á {PLUS} stýripúðanum til að skoða\n"
	.string "gögnin: 'HLUTIR' 'LYKILHLUTIR'\p"
	.string "'VASA BOLTAR' Ýttu upp eða niður til\n"
	.string "að velja hlut.$"

Help_Text_HowToUseAnItem::
	.string "{CIRCLE_1} Veldu 'HLUTIR' VASA.\n"
	.string "{CIRCLE_2} Ýttu upp eða niður\p"
	.string "á {PLUS} stýripúðanum til að velja\n"
	.string "hlut. {CIRCLE_3} Veldu 'NOTA' til að\p"
	.string "nota valinn hlut. Sumir hlutir má\n"
	.string "ekki nota eftir staðsetningu\p"
	.string "og/eða aðstæðum.$"

Help_Text_HowToUseKeyItem::
	.string "{CIRCLE_1} Veldu 'LYKILHLUTAHÓLF.'\n"
	.string "{CIRCLE_2} Ýttu upp eða niður\p"
	.string "á {PLUS} stýripúðanum til að velja\n"
	.string "lykilhlut. {CIRCLE_3} Veldu 'NOTA'\p"
	.string "til að nota valinn lykilhlut.$"

Help_Text_HowToUsePokeBall::
	.string "{CIRCLE_1} Meðan þú berst við villt\n"
	.string "Vasaskrímsli skaltu velja\p"
	.string "'VASA BOLTAHÓLF' í TÖSKUNNI.\n"
	.string "{CIRCLE_2} Ýttu upp eða niður á\p"
	.string "{PLUS}\p"
	.string "stýripúðanum til að velja VASA\n"
	.string "BOLTA. {CIRCLE_3} Veldu 'NOTA' til\p"
	.string "að kasta\p"
	.string "völdum VASA BOLTA.$"

Help_Text_HowToUsePlayer::
	.string "{CIRCLE_1} Veldu '{PLAYER}' í\n"
	.string "VALMYNDINNI. {CIRCLE_2}\p"
	.string "ÞJÁLFARAKORTIÐ\p"
	.string "þitt birtist með grunnupplýsingum.\n"
	.string "Ýttu á A takkann til að\p"
	.string "snúa KORTINU við. {CIRCLE_3} Ýmsar\n"
	.string "upplýsingar eru á bakhlið KORTSINS.$"

Help_Text_HowToUseSave::
	.string "{CIRCLE_1} Veldu 'VISTA' í VALMYND.\n"
	.string "{CIRCLE_2} Veldu 'JÁ' og\p"
	.string "framfarir þínar eru skráðar í\n"
	.string "vistunarskrána. Þegar leikurinn er\p"
	.string "vistaður geturðu slökkt á leiknum.\n"
	.string "Leikurinn þinn getur haldið áfram\p"
	.string "frá því þar sem þú vistaðir.$"

Help_Text_HowToUseOption::
	.string "{CIRCLE_1} Veldu 'VALKOSTUR' í\n"
	.string "VALMYND. {CIRCLE_2} Ýttu upp eða\p"
	.string "niður á\p"
	.string "{PLUS} stýripúðanum til að velja\n"
	.string "valkost, ýttu svo vinstri eða\p"
	.string "hægri til að breyta stillingum.\n"
	.string "{CIRCLE_3} Veldu 'HÆTTA VIÐ' eða\p"
	.string "ýttu\p"
	.string "á B takkann eftir að hafa gert\n"
	.string "breytingar.$"

Help_Text_HowToUsePotion::
	.string "{CIRCLE_1} Opnaðu VALMYNDINA.\n"
	.string "{CIRCLE_2} Ýttu upp eða niður á\p"
	.string "{PLUS}\p"
	.string "stýripúðanum og veldu 'TASKA.'\n"
	.string "{CIRCLE_3} Veldu 'SEYÐI' í\p"
	.string "'HLUTAHÓLFINU.' {CIRCLE_4} Veldu\n"
	.string "'NOTA.' {CIRCLE_5} Veldu\p"
	.string "Vasaskrímslið sem á að lækna.$"

Help_Text_HowToUseTownMap::
	.string "{CIRCLE_1} Opnaðu VALMYND.\n"
	.string "{CIRCLE_2} Ýttu upp eða niður á\p"
	.string "{PLUS}\p"
	.string "stýripúðanum og veldu 'TASKA.'\n"
	.string "{CIRCLE_3} Ýttu vinstri eða hægri\p"
	.string "til\p"
	.string "að opna 'LYKILHLUTAHÓLF,' ýttu svo\n"
	.string "upp eða niður til að velja 'KORT\p"
	.string "BORGAR.' {CIRCLE_4} Veldu 'NOTA' til\n"
	.string "að opna KORT BORGAR.$"

Help_Text_HowToUseTM::
	.string "{CIRCLE_1} Opnaðu VALMYNDINA.\n"
	.string "{CIRCLE_2} Opnaðu 'LYKILHLUTAHÓLF' í\p"
	.string "'TÖSKUNNI.' {CIRCLE_3} Veldu 'OPNA'\n"
	.string "á TM KASSANUM. {CIRCLE_4} Veldu\p"
	.string "og 'NOTA' á TM. {CIRCLE_5} Veldu\n"
	.string "Vasaskrímsli sem getur lært\p"
	.string "hreyfinguna.$"

Help_Text_HowToUseHM::
	.string "{CIRCLE_1} Opnaðu VALMYNDINA.\n"
	.string "{CIRCLE_2} Opnaðu 'LYKILHLUTAHÓLF' í\p"
	.string "'TÖSKUNNI.' {CIRCLE_3} Veldu 'OPNA'\n"
	.string "á TM KASSANUM. {CIRCLE_4} Veldu\p"
	.string "og 'NOTA' á HM. {CIRCLE_5} Veldu\n"
	.string "Vasaskrímsli sem getur lært hana.\p"
	.string "Erfitt er að fjarlægja HM.$"

Help_Text_HowToUseMoveOutsideOfBattle::
	.string "{CIRCLE_1} Opnaðu VALMYNDINA.\n"
	.string "{CIRCLE_2} Veldu 'Vasaskrímsli.'\p"
	.string "{CIRCLE_3}\p"
	.string "Veldu Vasaskrímsli sem kann HM\n"
	.string "hreyfingu. Notanleg HM hreyfing(ar)\p"
	.string "verða\p"
	.string "sýndar í bláu. Veldu og notaðu\n"
	.string "viðeigandi hreyfingu til að\p"
	.string "eyðileggja\p"
	.string "hindrun, fljúga, surfa, o.s.frv.$"

Help_Text_HowToRideBicycle::
	.string "{CIRCLE_1} Opnaðu VALMYND. Opnaðu\n"
	.string "'LYKILHLUTAHÓLF' í 'TÖSKUNNI' og\p"
	.string "veldu 'HJÓL.' {CIRCLE_2} Þú getur\n"
	.string "notað HJÓLIÐ með því að velja\p"
	.string "'NOTA.' Þú getur líka 'SKRÁÐ' það\n"
	.string "til að nota það strax með SELECT.$"

Help_Text_HowToEnterName::
	.string "{CIRCLE_1} Færðu bendilinn á stafinn\n"
	.string "sem þú vilt með {PLUS} stýripúðanum\p"
	.string "og ýttu á A til að slá hann inn.\n"
	.string "{CIRCLE_2} Ýttu á B til að fara til\p"
	.string "baka.\p"
	.string "{CIRCLE_3} Ýttu á SELECT til að\n"
	.string "skipta á milli hástafa og lágstafa.\p"
	.string "{CIRCLE_4} Ýttu á A á 'OK.'$"

Help_Text_HowToUsePC::
	.string "{CIRCLE_1} Farðu í hvaða\n"
	.string "Vasaskrímsla MIÐSTÖÐ sem er, farðu\p"
	.string "að TÖLVUNNI\p"
	.string "og ýttu á A takkann.$"

Help_Text_HowToUseBillsPC::
	.string "{CIRCLE_1} Veldu '{STR_VAR_1} TÖLVA'\n"
	.string "í TÖLVUNNI. {CIRCLE_2} Veldu eitt af\p"
	.string "þremur efstu VALMYNDARATRIÐUNUM til\n"
	.string "að opna Vasaskrímsla GEYMSLUKERFIÐ.\p"
	.string "Ef þú fangar Vasaskrímsli þegar þú\n"
	.string "ert með sex í hópnum fer það í\p"
	.string "KASSA.$"

Help_Text_HowToUseWithdraw::
	.string "{CIRCLE_1} Veldu Vasaskrímsli í opna\n"
	.string "KASSANUM með {PLUS} stýripúðanum.\p"
	.string "{CIRCLE_2} Veldu 'TAKA ÚT' til að\n"
	.string "fjarlægja Vasaskrímslið úr KASSANUM\p"
	.string "og bæta því við hópinn þinn. Þú mátt\n"
	.string "ekki taka út Vasaskrímsli ef þú\p"
	.string "ert nú þegar með sex Vasaskrímsli\n"
	.string "með þér!$"

Help_Text_HowToUseDeposit::
	.string "{CIRCLE_1} Veldu Vasaskrímsli í\n"
	.string "hópnum þínum með {PLUS}\p"
	.string "stýripúðanum.\p"
	.string "{CIRCLE_2} Veldu 'LEGGJA INN.'\n"
	.string "{CIRCLE_3} Veldu KASSANN, ýttu svo\p"
	.string "á A takkann til að geyma\n"
	.string "Vasaskrímslið. Ef þú ert aðeins með\p"
	.string "eitt Vasaskrímsli með þér, má ekki\n"
	.string "geyma það!$"

Help_Text_HowToUseMove::
	.string "{CIRCLE_1} Veldu Vasaskrímsli í opna\n"
	.string "KASSANUM. {CIRCLE_2} Taktu\p"
	.string "Vasaskrímslið upp með því að velja\n"
	.string "'FÆRA' og færðu það hvert sem er með\p"
	.string "{PLUS} stýripúðanum. {CIRCLE_3}\n"
	.string "Færðu Vasaskrímslið að KASSANAFNINU\p"
	.string "og\p"
	.string "ýttu á vinstri eða hægri til að færa\n"
	.string "það í annan KASSA.$"

Help_Text_HowToMoveItems::
	.string "{CIRCLE_1} Dauft sýnd Vasaskrímsli\n"
	.string "geta haldið hlut ef þú velur þau og\p"
	.string "ýtir\p"
	.string "á A takkann. {CIRCLE_2} Skýrt sýnd\n"
	.string "Vasaskrímsli geta gefið hlutinn sem\p"
	.string "þau halda öðru Vasaskrímsli eða sett\n"
	.string "hann aftur í TÖSKUNA.$"

Help_Text_HowToUsePlayersPC::
	.string "{CIRCLE_1} Veldu '{PLAYER}'s TÖLVA'\n"
	.string "á tölvunni. {CIRCLE_2} Veldu\p"
	.string "annaðhvort\p"
	.string "'HLUTAGEYMSLA' eða 'PÓSTKASSI.' Þú\n"
	.string "getur geymt hluti í eigin tölvu ef\p"
	.string "TASKAN þín er full. Þú getur líka\n"
	.string "tekið hluti út sem eru geymdir í\p"
	.string "tölvunni þinni.$"

Help_Text_HowToUseWithdrawItem::
	.string "{CIRCLE_1} Veldu 'TAKA HLUT ÚT.'\n"
	.string "{CIRCLE_2} Veldu hlutinn sem á að\p"
	.string "taka út. {CIRCLE_3} Hluturinn er\n"
	.string "hægt að taka út og setja í HLUTAHÓLF\p"
	.string "TÖSKUNNAR. Hann má einnig gefa beint\n"
	.string "Vasaskrímsli til að\p"
	.string "halda.$"

Help_Text_HowToUseDepositItem::
	.string "{CIRCLE_1} Veldu 'LEGGJA HLUT INN.'\n"
	.string "{CIRCLE_2} Veldu hlutinn í\p"
	.string "TÖSKUNNI sem á að leggja inn með\n"
	.string "{PLUS} stýripúðanum. {CIRCLE_3} Ef\p"
	.string "það er\p"
	.string "meira en einn hlutur til að leggja\n"
	.string "inn, sláðu inn magnið með {PLUS}\p"
	.string "stýripúðanum, ýttu svo á A takkann.$"

Help_Text_HowToUseMailbox::
	.string "Þegar PÓSTUR er tekinn af\n"
	.string "Vasaskrímsli færist hann í\p"
	.string "PÓSTKASSANN. Ef enginn PÓSTUR er til\n"
	.string "staðar er ekki hægt að nota\p"
	.string "PÓSTKASSANN. {CIRCLE_1} Veldu\n"
	.string "'{PLAYER} TÖLVA' í TÖLVUNNI.\p"
	.string "{CIRCLE_2} Veldu 'PÓSTKASSI' til að\n"
	.string "lesa PÓST eða láta Vasaskrímsli\p"
	.string "halda á honum.$"

Help_Text_HowToUseProfOaksPC::
	.string "{CIRCLE_1} Veldu 'TÖLVA Prófessor\n"
	.string "EIK' í TÖLVUNNI. {CIRCLE_2}\p"
	.string "Prófessor EIK metur\p"
	.string "VasaDEX þinn. Matið hans ætti að\n"
	.string "gefa þér vísbendingar um hvernig þú\p"
	.string "getur fangað fleiri Vasaskrímsli!$"

Help_Text_HowToOpenMenu::
	.string "{CIRCLE_1} Ýttu á START. {CIRCLE_2}\n"
	.string "VALMYNDIN opnast til hægri.\p"
	.string "{CIRCLE_3} Eftir aðstæðum getur\n"
	.string "VALMYNDIN sýnt mismunandi\p"
	.string "valkosti. VALMYNDIN opnast ekki í\n"
	.string "ákveðnum aðstæðum eins og þegar\p"
	.string "talað er, gert eitthvað, barist\n"
	.string "o.s.frv.$"

Help_Text_HowToUseFight::
	.string "{CIRCLE_1} Veldu 'BERJAST.'\n"
	.string "{CIRCLE_2} Veldu eina af\p"
	.string "hreyfingunum\p"
	.string "sem sýndar eru, og sú hreyfing\n"
	.string "verður notuð!$"

Help_Text_HowToUsePokemon2::
	.string "{CIRCLE_1} Veldu 'Vasaskrímsli.'\n"
	.string "{CIRCLE_2} Veldu Vasaskrímslið í\p"
	.string "hópnum þínum sem þú vilt nota.\n"
	.string "{CIRCLE_3} Ef þú ert með tvö eða\p"
	.string "fleiri Vasaskrímsli með þér, er hægt\n"
	.string "að skipta þeim með því að velja\p"
	.string "'SKIPTA.' Skoðaðu Vasaskrímsli gögn\n"
	.string "með því að velja 'YFIRLIT.'$"

Help_Text_HowToUseShift::
	.string "Þessi skipun skiptir Vasaskrímslinu\n"
	.string "í bardaga út fyrir annað í hópnum\p"
	.string "þínum. {CIRCLE_1} Veldu\n"
	.string "Vasaskrímslið sem á að senda út.\p"
	.string "{CIRCLE_2} Veldu 'SKIPTA.'\n"
	.string "{CIRCLE_3} Valið Vasaskrímsli mun\p"
	.string "skipta um stað við Vasaskrímslið í\n"
	.string "bardaga!$"

Help_Text_HowToUseSummary2::
	.string "{CIRCLE_1} Veldu 'YFIRLIT.'\n"
	.string "{CIRCLE_2} Ýttu á vinstri eða hægri\p"
	.string "á {PLUS} stýripúðanum til að skoða\n"
	.string "upplýsingarnar: 'Vasaskrímsli\p"
	.string "UPPLÝSINGAR' 'Vasaskrímsli\n"
	.string "HÆFILEIKAR' 'ÞEKKTAR HREYFINGAR'$"

Help_Text_HowToUseBag2::
	.string "{CIRCLE_1} Veldu 'TASKA.' {CIRCLE_2}\n"
	.string "Ýttu vinstri eða hægri á {PLUS}\p"
	.string "stýripúðanum til að skoða gögnin:\n"
	.string "'HLUTIR' 'LYKILHLUTIR' 'VASA\p"
	.string "BOLTAR' Ýttu upp eða niður til að\n"
	.string "velja hlut.$"

Help_Text_HowToReadPokedex::
	.string "{CIRCLE_3} Veldu 'NÆSTU GÖGN' til að\n"
	.string "sýna KORT BORGAR með búsvæðum\p"
	.string "þess.$"
	.if REVISION < 1
	.string "{CIRCLE_3} Veldu 'NÆSTU GÖGN' til að\n"
	.string "sýna KORT BORGAR með búsvæðum\p"
	.string "þess.$"
	.else
	.string "{CIRCLE_3} Veldu 'NÆSTU GÖGN' til að\n"
	.string "sýna KORT BORGAR með búsvæðum\p"
	.string "þess.$"
	.endif

Help_Text_HowToUseHomePC::
	.string "{CIRCLE_1} Farðu að tölvunni heima,\n"
	.string "ýttu svo á A takkann. {CIRCLE_2}\p"
	.string "Tölvan kveikir á sér. {CIRCLE_3}\n"
	.string "Veldu annaðhvort 'HLUTAGEYMSLA' eða\p"
	.string "'PÓSTKASSI.'$"

Help_Text_HowToUseItemStorage::
	.string "{CIRCLE_1} Veldu 'TAKA HLUT ÚT' til\n"
	.string "að taka út hlut sem er geymdur í\p"
	.string "tölvunni þinni.\p"
	.string "{CIRCLE_2} Veldu 'LEGGJA HLUT INN'\n"
	.string "til að setja hlut úr TÖSKUNNI þinni\p"
	.string "í\p"
	.string "tölvuna þína.$"

Help_Text_HowToUseWithdrawItem2::
	.string "{CIRCLE_1} Veldu 'TAKA HLUT ÚT.'\n"
	.string "{CIRCLE_2} Veldu hlutinn sem á að\p"
	.string "taka út. {CIRCLE_3} Hægt er að taka\n"
	.string "hlutinn út og setja hann í HLUTAHÓLF\p"
	.string "TÖSKUNNAR. Einnig má gefa hann beint\n"
	.string "Vasaskrímsli til að halda á.$"

Help_Text_HowToUseDepositItem2::
	.string "{CIRCLE_1} Veldu 'LEGGJA HLUT INN.'\n"
	.string "{CIRCLE_2} Veldu hlutinn í\p"
	.string "TÖSKUNNI sem á að leggja inn með\n"
	.string "{PLUS} stýripúðanum. {CIRCLE_3} Ef\p"
	.string "það er\p"
	.string "ekki neitt í TÖSKUNNI, er ekki hægt\n"
	.string "að nota þessa skipun!$"

Help_Text_HowToUseMailbox2::
	.string "Þegar PÓSTUR er tekinn af\n"
	.string "Vasaskrímsli færist hann í\p"
	.string "PÓSTKASSANN. Ef enginn PÓSTUR er til\n"
	.string "staðar er ekki hægt að nota\p"
	.string "PÓSTKASSANN. {CIRCLE_1} Veldu PÓST\n"
	.string "eftir nafni til að lesa hann eða\p"
	.string "láta Vasaskrímsli halda á honum.$"

Help_Text_HowToUseRun::
	.string "Þú mátt ekki 'FLÝJA' úr ÞJÁLFARA\n"
	.string "bardaga! {CIRCLE_1} Þú mátt 'FLÝJA'\p"
	.string "frá villtu Vasaskrímsli. {CIRCLE_2}\n"
	.string "Líkur þínar á flótta batna ef\p"
	.string "Vasaskrímslið þitt í bardaga er\n"
	.string "hratt.$"

Help_Text_HowToRegisterKeyItem::
	.string "Þú getur 'SKRÁÐ' lykilhlut til að\n"
	.string "nota hann strax með SELECT!\p"
	.string "{CIRCLE_1} Opnaðu 'LYKILHLUTAHÓLF.'\n"
	.string "{CIRCLE_2} Veldu lykilhlutinn og\p"
	.string "veldu\p"
	.string "svo 'SKRÁ.'$"

Help_Text_HowToUseBall::
	.string "{CIRCLE_1} Veldu til að kasta\n"
	.string "sérstökum SAFARI BOLTA sem er aðeins\p"
	.string "notaður í SAFARI SVÆÐINU. Þegar\n"
	.string "villt Vasaskrímsli birtast skaltu\p"
	.string "kasta mörgum SAFARI BOLTUM til að\n"
	.string "fanga þau!$"

Help_Text_HowToUseBait::
	.string "{CIRCLE_1} Veldu til að kasta\n"
	.string "sérstakri fæðu sem er aðeins notuð í\p"
	.string "SAFARI SVÆÐINU. Þetta er kúlulaga\n"
	.string "Vasaskrímslafóður sem auðvelt er að\p"
	.string "borða. Þegar BEITU er kastað getur\n"
	.string "villt Vasaskrímsli laðast að henni\p"
	.string "og verið ólíklegra til að flýja.$"

Help_Text_HowToUseRock::
	.string "{CIRCLE_1} Veldu til að kasta steini\n"
	.string "sem liggur á jörðinni í SAFARI\p"
	.string "SVÆÐINU. Ef steini er kastað í\n"
	.string "Vasaskrímsli getur það flúið, en það\p"
	.string "verður auðveldara að fanga það!$"

Help_Text_HowToUseHallOfFame::
	.string "{CIRCLE_1} Veldu 'FRÆGÐARHÖLL' á\n"
	.string "tölvunni. {CIRCLE_2} Hægt er að\p"
	.string "skoða Vasaskrímslin sem hafa komist\n"
	.string "í FRÆGÐARHÖLLINA.$"

Help_Text_HP::
	.string "HP$"

Help_Text_EXP::
	.string "EXP. {LEFT_PAREN}EXP.\n"
	.string "punktar{RIGHT_PAREN}$"

Help_Text_Moves::
	.string "ÁRÁSIR$"

Help_Text_Attack::
	.string "SÓKN$"

Help_Text_Defense::
	.string "VÖRN$"

Help_Text_SpAtk::
	.string "SÉR. SÓKN$"

Help_Text_SpDef::
	.string "SÉR. VÖRN$"

Help_Text_Speed::
	.string "HRAÐI$"

Help_Text_Level::
	.string "Stig. {LEFT_PAREN}Stig{RIGHT_PAREN}$"

Help_Text_Type::
	.string "GERÐ$"

Help_Text_OT::
	.string "ÞJÁLFARI$"

Help_Text_Item::
	.string "HLUTUR$"

Help_Text_Ability::
	.string "HÆFILEIKI$"

Help_Text_Money::
	.string "PENINGAR$"

Help_Text_MoveType::
	.string "ÁRÁSARGERÐ$"

Help_Text_Nature::
	.string "EÐLI$"

Help_Text_IDNo::
	.string "Auðkennisnúmer.$"

Help_Text_PP::
	.string "PP$"

Help_Text_Power::
	.string "STYRKUR$"

Help_Text_Accuracy::
	.string "NÁKVÆMNI$"

Help_Text_FNT::
	.string "FNT$"

Help_Text_Items::
	.string "HLUTIR$"

Help_Text_KeyItems::
	.string "LYKILHLUTIR$"

Help_Text_PokeBalls::
	.string "VASA BOLTAR$"

Help_Text_Pokedex::
	.string "VasaDEX$"

Help_Text_PlayTime::
	.string "LEIKTÍMI$"

Help_Text_Badges::
	.string "MERKI$"

Help_Text_TextSpeed::
	.string "TEXTAHRAÐI$"

Help_Text_BattleScene::
	.string "BARDAGASENA$"

Help_Text_BattleStyle::
	.string "BARDAGASTÍLL$"

Help_Text_Sound::
	.string "HLJÓÐ$"

Help_Text_ButtonMode::
	.string "HNAPPAHAMUR$"

Help_Text_Frame::
	.string "RAMMI$"

Help_Text_Cancel2::
	.string "HÆTTA VIÐ$"

Help_Text_TM::
	.string "TM$"

Help_Text_HM::
	.string "HM$"

Help_Text_HMMove::
	.string "HM-ÁRÁS$"

Help_Text_Evolution::
	.string "ÞRÓUN$"

Help_Text_StatusProblem::
	.string "ÁSTANDSVANDI$"

Help_Text_Pokemon::
	.string "Vasaskrímsli$"

Help_Text_IDNo2::
	.string "Auðkennisnúmer.$"

Help_Text_Money2::
	.string "PENINGAR$"

Help_Text_Badges2::
	.string "MERKI$"

Help_Text_DefineHP::
	.string "HP sýnir lífsþrótt Vasaskrímslis. Ef\n"
	.string "HP Vasaskrímslis fer í núll\p"
	.string "fellur það í yfirlið og getur ekki\n"
	.string "barist. Lykillinn í bardaga er því\p"
	.string "að lækka HP óvinarins í núll. Ef\n"
	.string "Vasaskrímslin þín meiðast skaltu\p"
	.string "lækna þau fljótt.$"

Help_Text_DefineEXP::
	.string "EXP. stig merkja 'Reynslustig.'\n"
	.string "Vasaskrímsli fá EXP. stig með því\p"
	.string "að taka þátt í bardögum sem vinnast.\n"
	.string "Þegar Vasaskrímsli safnar nógu\p"
	.string "mörgum\p"
	.string "EXP. stigum hækkar það um stig. EXP.\n"
	.string "stikan sýnir uppsöfnuð EXP. stig.$"

Help_Text_DefineMoves::
	.string "Vasaskrímsli geta lært allt að\n"
	.string "fjórar mismunandi hreyfingar. Til\p"
	.string "eru\p"
	.string "margar gerðir hreyfinga, þar á meðal\n"
	.string "árásir og hreyfingar með sérstök\p"
	.string "áhrif.\p"
	.string "Hvaða hreyfingar er hægt að læra er\n"
	.string "mismunandi eftir Vasaskrímsli. Sumar\p"
	.string "hreyfingar má læra af hlutum.$"

Help_Text_DefineAttack::
	.string "SÓKN sýnir kraft líkamlegrar árásar.\n"
	.string "Því hærri sem talan er, því öflugri\p"
	.string "er árásin. Hún á við um þessar\n"
	.string "tegundir: VENJL., EITUR, JÖRÐ, FLUG,\p"
	.string "SKORDÝ, BARDAG, STEINN, DRAUG og\n"
	.string "STÁL.$"

Help_Text_DefineDefense::
	.string "VÖRN (DEFENSE) sýnir mótstöðu\n"
	.string "Vasaskrímslis gegn líkamlegum\p"
	.string "árásum. Því hærri sem þessi tala er,\n"
	.string "því minni skaða tekur það af\p"
	.string "líkamlegri árás óvinar.$"

Help_Text_DefineSpAtk::
	.string "SP. ATK (Sérstök Árás) gefur til\n"
	.string "kynna kraft sérstakrar\p"
	.string "árásarhreyfingar.\p"
	.string "Því hærri sem þessi tala er, því\n"
	.string "öflugri er sérstaka\p"
	.string "árásarhreyfingin. Hún á við um\n"
	.string "eftirfarandi hreyfingar-\p"
	.string "gerðir: ELDUR, VATN, RAFM,\n"
	.string "GRAS,\p"
	.string "ÍS, HUGAR, DREKI, og MYRKUR.$"

Help_Text_DefineSpDef::
	.string "SÉR. VÖRN (Special Defense) sýnir\n"
	.string "mótstöðu Vasaskrímslis gegn\p"
	.string "sérstökum\p"
	.string "árásum. Því hærri sem þessi tala er,\n"
	.string "því minni skaða tekur það af\p"
	.string "sérstakri árás óvinar.$"

Help_Text_DefineSpeed::
	.string "HRAÐI (SPEED) sýnir snerpu\n"
	.string "Vasaskrímslis. Ef þessi tala er\p"
	.string "hærri\p"
	.string "en hjá óvininum í bardaga getur\n"
	.string "Vasaskrímslið gert hreyfingu á undan\p"
	.string "hægari andstæðingi sínum.$"

Help_Text_DefineLevel::
	.string "Lv. sýnir vöxt og styrk\n"
	.string "Vasaskrímslis. Yfirleitt hækka\p"
	.string "eiginleikar eins og\p"
	.string "HP, SÓKN og VÖRN þegar Vasaskrímsli\n"
	.string "hækkar um stig. Það getur líka lært\p"
	.string "nýja árás við stigahækkun.$"

Help_Text_DefineType::
	.string "Vasaskrímsli og árásir eru flokkuð\n"
	.string "eftir tegundum. Hver tegund hefur\p"
	.string "styrkleika og veikleika gegn öðrum\n"
	.string "tegundum. Til dæmis er VATN sterkt\p"
	.string "gegn ELDUR en veikt gegn GRAS.$"

Help_Text_DefineOT::
	.string "OT merkir 'Upprunalegur ÞJÁLFARI,'\n"
	.string "fyrsti ÞJÁLFARINN sem fangaði\p"
	.string "valið Vasaskrímsli. Þótt skipt sé á\n"
	.string "Vasaskrímslinu helst OT-nafnið eins.$"

Help_Text_DefineItem::
	.string "Öll Vasaskrímsli geta haldið einum\n"
	.string "hlut hvert. Sumir hlutir verða\p"
	.string "notaðir af Vasaskrímslinu sjálfkrafa\n"
	.string "í ákveðnum aðstæðum.\p"
	.string "Til að láta Vasaskrímsli halda hlut,\n"
	.string "veldu hlutinn úr TÖSKUNNI og\p"
	.string "'GEFA' hann Vasaskrímslinu.$"

Help_Text_DefineAbility::
	.string "Öll Vasaskrímsli hafa sérstaka\n"
	.string "HÆFILEIKA. Það eru margar\p"
	.string "mismunandi tegundir af þessum\n"
	.string "hæfileikum, sumir notaðir í bardaga,\p"
	.string "sumir annars staðar. Hæfileikarnir\n"
	.string "eru mismunandi eftir tegundum.\p"
	.string "Sumar tegundir geta haft fleiri en\n"
	.string "eina tegund af hæfileikum.$"

Help_Text_DefineMoney::
	.string "Alltaf þegar þú vinnur bardaga gegn\n"
	.string "ÞJÁLFARA færðu verðlaunafé.\p"
	.string "Safnaðu því svo þú getir verslað í\n"
	.string "Vasaskrímsla-búðum!$"

Help_Text_DefineMoveType::
	.string "Árásir eru líka flokkaðar eftir\n"
	.string "tegundum. Ef Vasaskrímsli notar árás\p"
	.string "af sömu tegund og það sjálft eykst\n"
	.string "kraftur árásarinnar. Ef tegundin er\p"
	.string "sterk gegn skotmarkinu eykst virkni\n"
	.string "hennar líka.$"

Help_Text_DefineNature::
	.string "Öll Vasaskrímsli hafa persónuleika,\n"
	.string "eða 'EÐLI.' Eðli Vasaskrímslisins\p"
	.string "virðist hafa áhrif á hvernig\n"
	.string "Vasaskrímslið mun vaxa við\p"
	.string "stigahækkun.$"

Help_Text_DefineIDNo::
	.string "Auðkennisnúmerið er sérstakt númer\n"
	.string "sem er úthlutað þér sem ÞJÁLFARA.\p"
	.string "Ásamt OT-nafninu auðkennir það\n"
	.string "upprunalega ÞJÁLFARANN nákvæmlega.\p"
	.string "Auðkennisnúmerið breytist ekki þótt\n"
	.string "skipt sé á Vasaskrímslinu.$"

Help_Text_DefinePP::
	.string "PP stendur fyrir kraftpunkta. Það\n"
	.string "sýnir hversu oft má nota ákveðna\p"
	.string "árás í bardaga. Eins og HP má\n"
	.string "endurheimta PP í\p"
	.string "Vasaskrímsla-MIÐSTÖÐ\p"
	.string "eða með ákveðnum hlutum.$"

Help_Text_DefinePower::
	.string "KRAFTUR sýnir styrk árásar. Því\n"
	.string "hærri sem talan er, því meiri skaða\p"
	.string "er hægt að valda óvininum!$"

Help_Text_DefineAccuracy::
	.string "NÁKVÆMNI (ACCURACY) gefur til kynna\n"
	.string "líkur á að hreyfingin hitti óvininn.\p"
	.string "Því hærri sem þessi tala er, því\n"
	.string "líklegra er að hreyfingin hitti\p"
	.string "skotmarkið.$"

Help_Text_DefineFNT::
	.string "FNT merkir 'örmagnað.' Vasaskrímsli\n"
	.string "örmagnast ef HP þess fer niður í\p"
	.string "núll. Þá getur það ekki tekið þátt í\n"
	.string "bardaga. Læknaðu örmagnað\p"
	.string "Vasaskrímsli í Vasaskrímsla-MIÐSTÖÐ\n"
	.string "eða með hlut.$"

Help_Text_DefineItems::
	.string "Venjulegir hlutir úr Vasaskrímsla-\n"
	.string "búðum fara í HLUTAHÓLFIÐ.\p"
	.string "Hægt er að nota hluti, gefa\n"
	.string "Vasaskrímsli þá til að halda á,\p"
	.string "eða henda þeim.$"

Help_Text_DefineKeyItems::
	.string "Mikilvægir hlutir sem þú finnur eða\n"
	.string "færð frá fólki fara í\p"
	.string "LYKILHLUTAHÓLF.\p"
	.string "Lykilhluti má nota eða skrá fyrir\n"
	.string "skjóta notkun með SELECT.\p"
	.string "Þegar hlutur er skráður má nota hann\n"
	.string "án þess að opna VALMYND og TÖSKU.$"

Help_Text_DefinePokeBalls::
	.string "VASA BOLTAR, notaðir til að fanga\n"
	.string "villt Vasaskrímsli, fara í VASA\p"
	.string "BOLTAHÓLFIÐ. Þeir fást í\n"
	.string "Vasaskrímsla-búðum. Hægt er að nota\p"
	.string "þá, gefa Vasaskrímsli þá til að\n"
	.string "halda á, eða henda þeim.$"

Help_Text_DefinePokedex::
	.string "Þetta sýnir fjölda Vasaskrímsla-\n"
	.string "tegunda sem þú hefur fangað og/eða\p"
	.string "þróað til að fylla VasaDEX. Reyndu\n"
	.string "að fanga alls konar Vasaskrímsli!$"

Help_Text_DefinePlayTime::
	.string "Þetta er heildartíminn sem þú hefur\n"
	.string "spilað þennan leik.$"

Help_Text_DefineBadges::
	.string "VasaskrímslaDEILDAR-MERKIN sem þú\n"
	.string "hefur unnið eru skráð og sýnd.\p"
	.string "Fáðu MERKI með því að sigra\n"
	.string "SALARLEIÐTOGA í ýmsum borgum og\p"
	.string "bæjum.$"

Help_Text_DefineTextSpeed::
	.string "Þú getur stillt hversu hratt textinn\n"
	.string "birtist. Veldu einn: HÆGT, MIÐ,\p"
	.string "eða HRATT.$"

Help_Text_DefineBattleScene::
	.string "Þú getur valið að kveikja eða\n"
	.string "slökkva á bardagahreyfingum.$"

Help_Text_DefineBattleStyle::
	.string "Þú getur valið hvort ÞJÁLFARI getur\n"
	.string "skipt um Vasaskrímsli eftir að það\p"
	.string "hefur látið andstæðing sinn falla í\n"
	.string "yfirlið. Stilltu á 'SKIPTA' ef þú\p"
	.string "vilt fá tækifæri til að skipta um\n"
	.string "Vasaskrímsli eftir að það hefur\p"
	.string "látið andstæðing sinn falla í\n"
	.string "yfirlið.$"

Help_Text_DefineSound::
	.string "Þú getur valið á milli MONO og\n"
	.string "STEREO hljóðúttaks.$"

Help_Text_DefineButtonMode::
	.string "Stilltu á 'HJÁLP' til að sýna\n"
	.string "hjálpar- skilaboð með því að ýta á L\p"
	.string "eða R\p"
	.string "takkann. Stilltu á 'LR' til að\n"
	.string "virkja skipti á VasaDEX síðum og\p"
	.string "TÖSKUVÖSUM með L og R tökkunum.\n"
	.string "Stilltu á 'L=A' til að láta L\p"
	.string "takkann virka eins og A takkann.$"

Help_Text_DefineFrame::
	.string "Þú getur valið hönnun rammans\n"
	.string "umhverfis ákveðnar valmyndir.\p"
	.string "Prófaðu\p"
	.string "þær og sjáðu hvað þér líkar.$"

Help_Text_DefineCancel2::
	.string "Stillingarnar verða breyttar í þær\n"
	.string "valkosti sem sýndir eru í rauðu, og\p"
	.string "þú\p"
	.string "munt snúa aftur í VALMYNDINA.$"

Help_Text_DefineTM::
	.string "TM (Tæknivél) er tæki sem notað er\n"
	.string "til að kenna Vasaskrímsli hreyfingu.\p"
	.string "Það eru margar mismunandi tegundir.\n"
	.string "Hreyfingar er aðeins hægt að kenna\p"
	.string "þeim Vasaskrímslum sem eru fær um að\n"
	.string "nota þær. TM brotnar eftir eina\p"
	.string "notkun.$"

Help_Text_DefineHM::
	.string "HM (Falin Vél) er tæki sem notað er\n"
	.string "til að kenna Vasaskrímsli FALNA\p"
	.string "hreyfingu. FALNA hreyfingu er aðeins\n"
	.string "hægt að kenna þeim Vasaskrímslum\p"
	.string "sem eru fær um að nota hana. Ólíkt\n"
	.string "TM, er hægt að nota HM aftur og\p"
	.string "aftur. FALNA hreyfingu getur verið\n"
	.string "erfitt fyrir Vasaskrímsli að gleyma.$"

Help_Text_DefineHMMove::
	.string "FALNAR hreyfingar eru þær sem eru\n"
	.string "sérstaklega mikilvægar fyrir\p"
	.string "ævintýrið þitt. Til að nota slíka\n"
	.string "hreyfingu utan bardaga, opnaðu\p"
	.string "'Vasaskrímsli' VALMYNDINA og láttu\n"
	.string "Vasaskrímslið sem kann hreyfinguna\p"
	.string "nota hana. Vasaskrímsli í yfirliði\n"
	.string "getur notað FALNA hreyfingu utan\p"
	.string "bardaga.$"

Help_Text_DefineEvolution::
	.string "Meðal Vasaskrímsla eru sum sem ganga\n"
	.string "í gegnum miklar breytingar\p"
	.string "(þróun) þegar þau ná ákveðnum\n"
	.string "stigum. Þróun veldur því að\p"
	.string "Vasaskrímsli breytir lögun, nafni,\n"
	.string "og kannski hreyfingum sem það getur\p"
	.string "lært. Sum Vasaskrímsli þróast vegna\n"
	.string "annarra ástæðna en stigahækkunar.$"

Help_Text_DefineStatusProblem::
	.string "Stöðuvandamál eru: Svefn: Getur ekki\n"
	.string "notað hreyfingar. Eitur: Velur\p"
	.string "stöðugt HP tap. Lömun: Getur hindrað\n"
	.string "hreyfingar. Bruni: HP tap og\p"
	.string "lækkar ÁRÁS. Frysting: Getur ekki\n"
	.string "notað hreyfingar. Þetta er hægt að\p"
	.string "lækna með\p"
	.string "hlutum o.s.frv.$"

Help_Text_DefinePokemon::
	.string "Vasaskrímsli er nafn sem gefið er\n"
	.string "til að lýsa undraverðum verum sem\p"
	.string "búa í öllum heimshornum. Fólk ræktar\n"
	.string "Vasaskrímsli til að hafa þau sem\p"
	.string "gæludýr, notar þau í bardaga, og svo\n"
	.string "framvegis.$"

Help_Text_DefineIDNo2::
	.string "Auðkennisnúmerið er sérstakt númer\n"
	.string "sem er úthlutað sérstaklega þér sem\p"
	.string "ÞJÁLFARA. Saman með OT nafninu er\n"
	.string "Auðkennisnúmerið notað til að\p"
	.string "þekkja nákvæmlega upprunalega\n"
	.string "ÞJÁLFARANN. Auðkennisnúmerið\p"
	.string "breytist\p"
	.string "ekki jafnvel þótt Vasaskrímslinu sé\n"
	.string "skipt.$"

Help_Text_DefineMoney2::
	.string "Alltaf þegar þú vinnur bardaga gegn\n"
	.string "ÞJÁLFARA, færðu verðlaunapeninga.\p"
	.string "Safnaðu verðlaunapeningunum þínum\n"
	.string "svo þú getir notið þess að versla\p"
	.string "í Vasaskrímslabúð!$"

Help_Text_DefineBadges2::
	.string "Þetta sýnir fjölda Vasaskrímsla-\n"
	.string "DEILDAR-MERKJA sem þú hefur unnið.\p"
	.string "Fáðu MERKI með því að sigra\n"
	.string "SALARLEIÐTOGA í ýmsum borgum og\p"
	.string "bæjum.$"

Help_Text_TheHelpSystem::
	.string "HJÁLPARKERFIÐ$"

Help_Text_TheGame::
	.string "Leikurinn$"

Help_Text_WirelessAdapter::
	.string "Þráðlaus millistykki$"

Help_Text_GameFundamentals1::
	.string "Grunnatriði leiksins 1$"

Help_Text_GameFundamentals2::
	.string "Grunnatriði leiksins 2$"

Help_Text_GameFundamentals3::
	.string "Grunnatriði leiksins 3$"

Help_Text_WhatArePokemon::
	.string "Hvað eru Vasaskrímsli?$"

Help_Text_DescTheHelpSystem::
	.string "Hjálparskilaboðin breytast eftir því\n"
	.string "hversu langt þú hefur komist í\p"
	.string "leiknum. Þau eru hönnuð til að\n"
	.string "styðja þig þegar þú þarft á þeim að\p"
	.string "halda. Ef\p"
	.string "það er eitthvað sem þú skilur ekki,\n"
	.string "vinsamlegast skoðaðu HJÁLPAR-\p"
	.string "kerfið!$"

Help_Text_DescTheGame::
	.string "Þú verður aðalpersónan til að kanna\n"
	.string "heim Vasaskrímsla!\p"
	.string "Með því að tala við fólk og leysa\n"
	.string "dulúðir munu nýjar leiðir opnast\p"
	.string "þér. Leitastu við markmiðið saman\n"
	.string "með yndislegu Vasaskrímslunum þínum!$"

Help_Text_DescWirelessAdapter::
	.string "Þessi leikur samskiptir yfir\n"
	.string "þráðlausa tengingu með þráðlausa\p"
	.string "millistykkinu.\p"
	.string "Vertu þráðlaus hvar sem er, hvenær\n"
	.string "sem er, og með hverjum sem er!\p"
	.string "Reyndu að spila með þráðlausa\n"
	.string "millistykkið alltaf tengt!$"

Help_Text_DescGameFundamentals1::
	.string "Heimsóttu hverja borg og bæ,\n"
	.string "ferðastu hvern veg, skoðaðu hvern\p"
	.string "helli, og\p"
	.string "horfðu frammi fyrir hverri áskorun\n"
	.string "þegar þú leitast við að verða\p"
	.string "mesti ÞJÁLFARI Vasaskrímsla!$"

Help_Text_DescGameFundamentals2::
	.string "Í ævintýri þínu muntu standa frammi\n"
	.string "fyrir mörgum hindrunum. Hver hindrun\p"
	.string "er hægt að yfirstíga með því að gera\n"
	.string "eitthvað eða með því að leysa gátur.\p"
	.string "Sumar\p"
	.string "hindranir eru fyrir áhrifum af\n"
	.string "einhverju sem gerist langt í burtu.$"

Help_Text_DescGameFundamentals3::
	.string "Sumar hindranir á vegi þínum er hægt\n"
	.string "að fjarlægja þegar Vasaskrímslin þín\p"
	.string "læra ákveðnar hreyfingar.$"

Help_Text_DescWhatArePokemon::
	.string "Vasaskrímsli eru undraverðar verur\n"
	.string "sem eru huldar dulúð. Þú gætir\p"
	.string "hitt þau um allan heim… í háu grasi,\n"
	.string "í hellum, sjónum og víðar. Þau\p"
	.string "virðast hlýða ÞJÁLFURUM sem fanga\n"
	.string "þau.$"

Help_Text_UsingTypeMatchupList::
	.string "Að nota tegundarviðmiðunarlistann$"

Help_Text_OwnMoveDark::
	.string "Eigin hreyfingartegund: MYRKUR$"

Help_Text_OwnPokemonDark::
	.string "Eigin Vasaskrímsla tegund: MYRKUR$"

Help_Text_OwnMoveRock::
	.string "Eigin hreyfingartegund: BERG$"

Help_Text_OwnPokemonRock::
	.string "Eigin Vasaskrímsla tegund: STEINN$"

Help_Text_OwnMovePsychic::
	.string "Eigin hreyfingartegund: SÁLAR$"

Help_Text_OwnPokemonPsychic::
	.string "Eigin Vasaskrímsla tegund: HUGAR$"

Help_Text_OwnMoveFighting::
	.string "Eigin hreyfingartegund: BERJAST$"

Help_Text_OwnPokemonFighting::
	.string "Eigin Vasaskrímsla tegund: BARDAGI$"

Help_Text_OwnMoveGrass::
	.string "Eigin hreyfingartegund: GRAS$"

Help_Text_OwnPokemonGrass::
	.string "Eigin Vasaskrímsla tegund: GRAS$"

Help_Text_OwnMoveGhost::
	.string "Eigin hreyfingartegund: DRAUGUR$"

Help_Text_OwnPokemonGhost::
	.string "Eigin Vasaskrímsla tegund: DRAUGUR$"

Help_Text_OwnMoveIce::
	.string "Eigin hreyfingartegund: ÍS$"

Help_Text_OwnPokemonIce::
	.string "Eigin Vasaskrímsla tegund: ÍS$"

Help_Text_OwnMoveGround::
	.string "Eigin hreyfingartegund: JÖRÐ$"

Help_Text_OwnPokemonGround::
	.string "Eigin Vasaskrímsla tegund: JÖRÐ$"

Help_Text_OwnMoveElectric::
	.string "Eigin hreyfingartegund: RAFMAGN$"

Help_Text_OwnPokemonElectric::
	.string "Eigin Vasaskrímsla tegund: RAFMAGN$"

Help_Text_OwnMovePoison::
	.string "Eigin hreyfingartegund: EITUR$"

Help_Text_OwnPokemonPoison::
	.string "Eigin Vasaskrímsla tegund: EITUR$"

Help_Text_OwnMoveDragon::
	.string "Eigin hreyfingartegund: DREKI$"

Help_Text_OwnPokemonDragon::
	.string "Eigin Vasaskrímsla tegund: DREKI$"

Help_Text_OwnMoveNormal::
	.string "Eigin hreyfingartegund: VENJULEG$"

Help_Text_OwnPokemonNormal::
	.string "Eigin Vasaskrímsla tegund: VENJULEG$"

Help_Text_OwnMoveSteel::
	.string "Eigin hreyfingartegund: STÁL$"

Help_Text_OwnPokemonSteel::
	.string "Eigin Vasaskrímsla tegund: STÁL$"

Help_Text_OwnMoveFlying::
	.string "Eigin hreyfingartegund: FLJÚGANDI$"

Help_Text_OwnPokemonFlying::
	.string "Eigin Vasaskrímsla tegund: FLUG$"

Help_Text_OwnMoveFire::
	.string "Eigin hreyfingartegund: ELDUR$"

Help_Text_OwnPokemonFire::
	.string "Eigin Vasaskrímsla tegund: ELDUR$"

Help_Text_OwnMoveWater::
	.string "Eigin hreyfingartegund: VATN$"

Help_Text_OwnPokemonWater::
	.string "Eigin Vasaskrímsla tegund: VATN$"

Help_Text_OwnMoveBug::
	.string "Eigin hreyfingartegund: SKORDÝR$"

Help_Text_OwnPokemonBug::
	.string "Eigin Vasaskrímsla tegund: SKORDÝR$"

Help_Text_HowToUseTypeMatchupList::
	.string "Það fer eftir samsvörun\n"
	.string "hreyfingartegundar og tegundar\p"
	.string "Vasaskrímslisins sem er\p"
	.string "skotmark, virkni hreyfingarinnar er\n"
	.string "mismunandi: {CIRCLE_DOT}: Ofur\p"
	.string "virkt! {TRIANGLE}: Ekki mjög virkt\n"
	.string "{BIG_MULT_X}: Alls ekki virkt\p"
	.string "(Engar breytingar fyrir aðrar\n"
	.string "samsvöranir.)$"

Help_Text_TypeMatchupOwnMoveDark::
	.string "Áhrif á andstætt Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: HUGAR, DRAUG\p"
	.string "{TRIANGLE}: BARDAG, MYRKUR, STÁL$"

Help_Text_TypeMatchupOwnPokemonDark::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: BARDAG, SKORDÝ\p"
	.string "{TRIANGLE}: DRAUG, MYRKUR\p"
	.string "{BIG_MULT_X}: HUGAR$"

Help_Text_TypeMatchupOwnMoveRock::
	.string "Áhrif á andstætt Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: ELDUR, ÍS, FLUG,\n"
	.string "SKORDÝ\p"
	.string "{TRIANGLE}: BARDAG, JÖRÐ, STÁL$"

Help_Text_TypeMatchupOwnPokemonRock::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: VATN, GRAS, BARDAG,\n"
	.string "JÖRÐ, STÁL\p"
	.string "{TRIANGLE}: VENJL., ELDUR, EITUR,\n"
	.string "FLUG$"

Help_Text_TypeMatchupOwnMovePsychic::
	.string "Áhrif á andstætt Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: BARDAG, EITUR\p"
	.string "{TRIANGLE}: HUGAR, STÁL\p"
	.string "{BIG_MULT_X}: MYRKUR$"

Help_Text_TypeMatchupOwnPokemonPsychic::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: SKORDÝ, DRAUG, MYRKUR\p"
	.string "{TRIANGLE}: BARDAG, HUGAR$"

Help_Text_TypeMatchupOwnMoveFighting::
	.string "Áhrif á andstætt Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: VENJL., ÍS, STEINN,\n"
	.string "MYRKUR, STÁL\p"
	.string "{TRIANGLE}: EITUR, FLUG, HUGAR,\n"
	.string "SKORDÝ\p"
	.string "{BIG_MULT_X}: DRAUG$"

Help_Text_TypeMatchupOwnPokemonFighting::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: FLUG, HUGAR\p"
	.string "{TRIANGLE}: SKORDÝ, STEINN, MYRKUR$"

Help_Text_TypeMatchupOwnMoveGrass::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: VATN, JÖRÐ, STEINN\p"
	.string "{TRIANGLE}: ELDUR, GRAS, EITUR,\n"
	.string "FLUG, SKORDÝR, DREKI, STÁL$"

Help_Text_TypeMatchupOwnPokemonGrass::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: ELDUR, ÍS, EITUR,\n"
	.string "FLUG, SKORDÝR\p"
	.string "{TRIANGLE}: VATN, RAFMAGN, GRAS,\n"
	.string "JÖRÐ$"

Help_Text_TypeMatchupOwnMoveGhost::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: HUGAR, DRAUGUR\p"
	.string "{TRIANGLE}: MYRKUR, STÁL\p"
	.string "{BIG_MULT_X}: VENJULEG$"

Help_Text_TypeMatchupOwnPokemonGhost::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: DRAUGUR, MYRKUR\p"
	.string "{TRIANGLE}: EITUR, SKORDÝR\p"
	.string "{BIG_MULT_X}: VENJULEG, BARDAGI$"

Help_Text_TypeMatchupOwnMoveIce::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: GRAS, JÖRÐ, FLUG,\n"
	.string "DREKI\p"
	.string "{TRIANGLE}: ELDUR, VATN, ÍS, STÁL$"

Help_Text_TypeMatchupOwnPokemonIce::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: ELDUR, BARDAGI,\n"
	.string "STEINN, STÁL\p"
	.string "{TRIANGLE}: ÍS$"

Help_Text_TypeMatchupOwnMoveGround::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: ELDUR, RAFMAGN, EITUR,\n"
	.string "STEINN, STÁL\p"
	.string "{TRIANGLE}: GRAS, SKORDÝR\n"
	.string "{BIG_MULT_X}: FLUG$"

Help_Text_TypeMatchupOwnPokemonGround::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: VATN, GRAS, ÍS\p"
	.string "{TRIANGLE}: EITUR, STEINN\p"
	.string "{BIG_MULT_X}: RAFMAGN$"

Help_Text_TypeMatchupOwnMoveElectric::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: VATN, FLUG\p"
	.string "{TRIANGLE}: RAFMAGN, GRAS, DREKI\p"
	.string "{BIG_MULT_X}: JÖRÐ$"

Help_Text_TypeMatchupOwnPokemonElectric::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: JÖRÐ\p"
	.string "{TRIANGLE}: RAFMAGN, FLUG, STÁL$"

Help_Text_TypeMatchupOwnMovePoison::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: GRAS\p"
	.string "{TRIANGLE}: EITUR, JÖRÐ, STEINN,\n"
	.string "DRAUGUR\p"
	.string "{BIG_MULT_X}: STÁL$"

Help_Text_TypeMatchupOwnPokemonPoison::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: JÖRÐ, HUGAR\p"
	.string "{TRIANGLE}: GRAS, BARDAGI, EITUR,\n"
	.string "SKORDÝR$"

Help_Text_TypeMatchupOwnMoveDragon::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: DREKI\p"
	.string "{TRIANGLE}: STÁL$"

Help_Text_TypeMatchupOwnPokemonDragon::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: ÍS, DREKI\p"
	.string "{TRIANGLE}: ELDUR, VATN, RAFMAGN,\n"
	.string "GRAS$"

Help_Text_TypeMatchupOwnMoveNormal::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{TRIANGLE}: STEINN, STÁL\p"
	.string "{BIG_MULT_X}: DRAUGUR$"

Help_Text_TypeMatchupOwnPokemonNormal::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: BARDAGI\p"
	.string "{BIG_MULT_X}: DRAUGUR$"

Help_Text_TypeMatchupOwnMoveSteel::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: ÍS, STEINN\p"
	.string "{TRIANGLE}: ELDUR, VATN, RAFMAGN,\n"
	.string "STÁL$"

Help_Text_TypeMatchupOwnPokemonSteel::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: ELDUR, BARDAGI, JÖRÐ\n"
	.string "{TRIANGLE}: VENJULEG, GRAS, ÍS,\p"
	.string "FLUG, HUGAR, SKORDÝR, STEINN,\n"
	.string "DRAUGUR, DREKI, MYRKUR, STÁL\p"
	.string "{BIG_MULT_X}:\p"
	.string "EITUR$"

Help_Text_TypeMatchupOwnMoveFlying::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: GRAS, BARDAGI, SKORDÝR\p"
	.string "{TRIANGLE}: RAFMAGN, STEINN, STÁL$"

Help_Text_TypeMatchupOwnPokemonFlying::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: RAFMAGN, ÍS, STEINN\p"
	.string "{TRIANGLE}: GRAS, BARDAGI, SKORDÝR\p"
	.string "{BIG_MULT_X}: JÖRÐ$"

Help_Text_TypeMatchupOwnMoveFire::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: GRAS, ÍS, SKORDÝR,\n"
	.string "STÁL\p"
	.string "{TRIANGLE}: ELDUR, VATN, STEINN,\n"
	.string "DREKI$"

Help_Text_TypeMatchupOwnPokemonFire::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: VATN, JÖRÐ, STEINN\p"
	.string "{TRIANGLE}: ELDUR, GRAS, ÍS,\n"
	.string "SKORDÝR, STÁL$"

Help_Text_TypeMatchupOwnMoveWater::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: ELDUR, JÖRÐ, STEINN\p"
	.string "{TRIANGLE}: VATN, GRAS, DREKI$"

Help_Text_TypeMatchupOwnPokemonWater::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: RAFMAGN, GRAS\p"
	.string "{TRIANGLE}: ELDUR, VATN, ÍS, STÁL$"

Help_Text_TypeMatchupOwnMoveBug::
	.string "Áhrif á Vasaskrímsli andstæðingsins:\p"
	.string "{CIRCLE_DOT}: GRAS, HUGAR, MYRKUR\p"
	.string "{TRIANGLE}: ELDUR, BARDAGI, EITUR,\n"
	.string "FLUG, DRAUGUR, STÁL$"

Help_Text_TypeMatchupOwnPokemonBug::
	.string "Áhrif árásar óvinar á eigið\n"
	.string "Vasaskrímsli:\p"
	.string "{CIRCLE_DOT}: ELDUR, FLUG, STEINN\p"
	.string "{TRIANGLE}: GRAS, BARDAGI, JÖRÐ$"
