Trade_Text_LookingForMonWannaTradeForMon::
	.string "I'm looking for the Vasaskrímsli\n"
	.string "{STR_VAR_1}!\p"
	.string "Wanna trade one for my {STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "Awww! Oh, well…$"

Trade_Text_WhatThatsNoMon::
	.string "Hvað? Þetta er ekki {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Hey, takk!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Er ekki gamla {STR_VAR_2} mín\n"
	.string "frábær?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Halló! Ertu nokkuð með {STR_VAR_1}?\p"
	.string "Viltu skipta því fyrir {STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Jæja, ef þú vilt ekki…$"

Trade_Text_ThisIsntMon::
	.string "Hmm? Þetta er ekki {STR_VAR_1}.\p"
	.string "Mundu eftir mér ef þú færð slíkt.$"

Trade_Text_Thanks::
	.string "Takk!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "{STR_VAR_2} sem ég skipti við þig,\n"
	.string "hefur hún orðið sterkari?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Hæ! Ertu með {STR_VAR_1}?\p"
	.string "Viltu skipta því fyrir {STR_VAR_2}?$"

Trade_Text_ThatsTooBad::
	.string "Það er of slæmt.$"

Trade_Text_ThisIsNoMon::
	.string "…Þetta er ekki {STR_VAR_1}.\p"
	.string "Ef þú færð einn, skiptu honum við\n"
	.string "mig.$"

Trade_Text_ThanksYoureAPal::
	.string "Takk, þú ert vinur!$"

Trade_Text_HowIsMyOldMon::
	.string "Hvernig hefur gamla {STR_VAR_2} það?\n"
	.string "{STR_VAR_1} hjá mér hefur það\p"
	.string "frábært!$"
