gOtherText_NewName::
    .string "NÝTT NAFN$"

gNameChoice_Green::
    .string "GRÆNN$"

gNameChoice_Red::
    .string "RAUÐUR$"

gNameChoice_Leaf::
    .string "LAUF$"

gNameChoice_Fire::
    .string "ELDUR$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "Hér eru hnapparnir útskýrðir\n"
    .string "í mikilvægustu röð.$"

gControlsGuide_Text_DPad::
    .string "Færir persónuna. Einnig\n"
    .string "notað til að velja atriði.$"

gControlsGuide_Text_AButton::
    .string "Staðfestir val og skoðar hluti,\n"
    .string "spjallar og flettir texta.$"

gControlsGuide_Text_BButton::
    .string "Hættir, fer til baka eða\n"
    .string "fellir val úr gildi.$"

gControlsGuide_Text_StartButton::
    .string "Ýttu á þennan hnapp til að opna\n"
    .string "VALMYND.$"

gControlsGuide_Text_SelectButton::
    .string "Færir hluti og notar\n"
    .string "skráðan hlut.$"

gControlsGuide_Text_LRButtons::
    .string "Vantar þig hjálp við leikinn\n"
    .string "eða hvað á að gera?\p"
    .string "Ýttu þá á L eða R.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Segðu mér. Ertu strákur\n"
    .string "eða stelpa?$"

gPikachuIntro_Text_Page1::
    .string "Í heiminum sem bíður þín\n"
    .string "ferð þú í stórt ævintýri,\p"
    .string "með þig sem hetju. Talaðu\n"
    .string "við fólk og skoðaðu allt,\p"
    .string "í bæjum, á leiðum og í\n"
    .string "hellum. Safnaðu vísbendingum.$"

gPikachuIntro_Text_Page2::
    .string "Nýjar leiðir opnast þegar\n"
    .string "þú hjálpar fólki í vanda,\p"
    .string "sigrar áskoranir og leysir\n"
    .string "leyndardóma. Stundum munu\p"
    .string "aðrir skora á þig og villtar\n"
    .string "verur ráðast á þig.\p"
    .string "Vertu hugrakkur og haltu áfram.$"

gPikachuIntro_Text_Page3::
    .string "Í ævintýrinu vonum við að\n"
    .string "þú kynnist alls kyns fólki\p"
    .string "og þroskist sjálfur. Það er\n"
    .string "stærsta markmið okkar.\p"
    .string "Ýttu á A og láttu ævintýrið\n"
    .string "byrja!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Halló! Gaman að hitta þig!\p"
    .string "Velkomin í heim Vasaskrímsla!\p"
    .string "Ég heiti EIK.\p"
    .string "Fólk kallar mig oft\n"
    .string "Vasaskrímsla-prófessor.$"

gOakSpeech_Text_ThisWorld::
    .string "Þessi heimur…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…er víða byggður verum\n"
    .string "sem kallast Vasaskrímsli.$"

gOakSpeech_Text_IStudyPokemon::
    .string "Sumir hafa Vasaskrímsli sem\n"
    .string "gæludýr. Aðrir nota þau til\p"
    .string "baráttu.\p"
    .string "Sjálfur rannsaka ég\n"
    .string "Vasaskrímsli.$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "En fyrst, segðu mér aðeins frá\n"
    .string "sjálfum þér.$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Byrjum á nafninu þínu.\n"
    .string "Hvað heitirðu?$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Rétt... Þú heitir {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "Þetta er barnabarnið mitt.\p"
    .string "Hann hefur verið keppinautur\n"
    .string "þinn frá barnæsku.\p"
    .string "Æ, hvað hét hann aftur?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Hvað hét keppinautur\n"
    .string "þinn aftur?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "Æ, var það {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "Já, rétt! Nú man ég! Hann heitir\n"
    .string "{RIVAL}!$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Þín eigin Vasaskrímsla-saga\n"
    .string "er að hefjast!\p"
    .string "Heimur drauma og ævintýra\n"
    .string "með Vasaskrímslum bíður!\p"
    .string "Af stað!$"
