Text_ObtainedTheX::
	.string "Fékkst {STR_VAR_2}!$"

Text_BagIsFull::
	.string "TASKAN er full…$"

Text_PutItemAway::
	.string "{PLAYER} setti {STR_VAR_2} í\n"
	.string "{STR_VAR_3}.$"

Text_FoundOneItem::
	.string "{PLAYER} fann einn {STR_VAR_2}!$"

Text_TooBadBagFull::
	.string "Æi! TASKAN er full…$"

Text_FoundXCoins::
	.string "{PLAYER} fann {STR_VAR_1}\n"
	.string "{STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} setti MYNTIR í MYNTVESKI.$"

Text_CoinCaseIsFull::
	.string "Æi! MYNTVESKIÐ er fullt…$"

Text_NothingToPutThemIn::
	.string "Æi! Þú hefur ekkert til að setja\n"
	.string "þetta í…$"

Text_FoundXItems::
	.string "{PLAYER} fann {STR_VAR_1}\n"
	.string "{STR_VAR_2}!$"

Text_ObtainedTheDecor::
	.string "Fékkst {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "Of slæmt! Það er ekkert pláss eftir\n"
	.string "fyrir annað {STR_VAR_2}…$"

Text_DecorTransferredToPC::
	.string "{STR_VAR_2} var flutt í tölvuna.$"
