Text_MonSentToBoxInSomeonesPC::
    .string "{STR_VAR_2} var sent í tölvu\n"
    .string "Einhvers.\p"
    .string "Það var sett í KASSA '{STR_VAR_1}.'$"

Text_MonSentToBoxInBillsPC::
    .string "{STR_VAR_2} var sent í tölvu BILL.\p"
    .string "Það var sett í KASSA '{STR_VAR_1}.'$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "KASSI '{STR_VAR_3}' í tölvu Einhvers\n"
    .string "var fullur.\p"
    .string "{STR_VAR_2} var sent í KASSA\n"
    .string "'{STR_VAR_1}.'$"

Text_MonSentToBoxBillsBoxFull::
    .string "KASSI '{STR_VAR_3}' í tölvu BILL var\n"
    .string "fullur.\p"
    .string "{STR_VAR_2} var sent í KASSA\n"
    .string "'{STR_VAR_1}.'$"

Text_PlayerObtainedTheMon::
    .string "{PLAYER} fékk {STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを もちきれないので パソコンの\n"
    .string "ボックス'{STR_VAR_1}' に {STR_VAR_2}を\p"
    .string "てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "There's no more room for\n"
    .string "Vasaskrímsli!\p"
    .string "The Vasaskrímsli BOXES are full and\n"
    .string "can't accept any more!$"
