Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "VASaSKRÍMSLA GÆI: Sá hraðari af\n"
	.string "bardagamönnunum ræðst fyrst á.$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "ROTTÓTTURinn minn virðist hafa verið\n"
	.string "hraðari en DÚFUTETURinn.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "Bardagamennirnir skiptast á að\n"
	.string "ráðast á og lækka HP hvors annars.$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "ROTTÓTTURinn minn lækkaði HP\n"
	.string "andstæðingsins í núll og vinnur!\p"
	.string "Vasaskrímslin sem tóku þátt í\n"
	.string "bardaganum fá EXP. stig.\p"
	.string "Þegar Vasaskrímsli safnar nógu\n"
	.string "mörgum EXP. stigum hækkar það um\p"
	.string "stig.\p"
	.string "Stigahækkun gerir Vasaskrímslið þitt\n"
	.string "sterkara en áður.$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "VASaSKRÍMSLA GÆI: Úff… ROTTÓTTURinn\n"
	.string "minn er eitraður…\p"
	.string "Ef Vasaskrímsli er eitrað missir það\n"
	.string "HP smám saman.$"

Pokedude_Text_HealStatusRightAway::
	.string "Ef Vasaskrímsli fær stöðuvanda\n"
	.string "skaltu lækna það strax.$"

Pokedude_Text_UsingItemTakesTurn::
	.string "Að nota hlut á Vasaskrímsli kostar\n"
	.string "eina umferð.\p"
	.string "Nú er komið að andstæðingnum!$"

Pokedude_Text_YayWeManagedToWin::
	.string "Jibbí! Okkur tókst að vinna!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "VASaSKRÍMSLA GÆI: Árásin BÚBBLUR er\n"
	.string "af VATN-tegund.\p"
	.string "KÁLHAUSinn sem varð fyrir henni er\n"
	.string "GRAS/EITUR Vasaskrímsli.\p"
	.string "VATN-árás veikist gegn GRAS-tegund…\p"
	.string "Þess vegna verður árásin ekki mjög\n"
	.string "áhrifarík og veldur bara helmingi\p"
	.string "venjulegs skaða.$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "Úff, þetta er ekki gott!\p"
	.string "ABSORB-árásin sem þú sást er af\n"
	.string "GRAS-tegund.\p"
	.string "POTTGORMUR er VATN Vasaskrímsli.\p"
	.string "Þess vegna verður ABSORB mjög\n"
	.string "áhrifarík og tvöfaldar skaðann.$"

Pokedude_Text_LetsTryShiftingMons::
	.string "Það verður ekki auðvelt að vinna með\n"
	.string "þessari viðureign…\p"
	.string "Prófum að skipta um Vasaskrímsli!$"

Pokedude_Text_ShiftingUsesTurn::
	.string "Að skipta Vasaskrímsli inn og út\n"
	.string "kostar eina umferð.\p"
	.string "Nú er komið að andstæðingnum.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "FRÍRILDI er SKORDÝ/FLUG\n"
	.string "Vasaskrímsli.\p"
	.string "Gegn þessu Vasaskrímsli veldur\n"
	.string "GRAS-árás…\p"
	.string "…bara helmingi venjulegs skaða á\n"
	.string "SKORDÝ-tegund…\p"
	.string "…og líka bara helmingi skaða á\n"
	.string "FLUG-tegund.\p"
	.string "Þess vegna tekur FRÍRILDI, sem er\n"
	.string "SKORDÝ/FLUG, aðeins fjórðung af\p"
	.string "venjulegum skaða.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "KÁLHAUS er GRAS/EITUR Vasaskrímsli.\p"
	.string "FLUG- eða HUGAR-árás er mjög\n"
	.string "áhrifarík gegn því.\p"
	.string "Slík árás veldur tvöföldum\n"
	.string "venjulegum skaða.\p"
	.string "Allt í lagi, nú byrjum við!$"

Pokedude_Text_YeahWeWon::
	.string "Já! Við unnum!$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "VASaSKRÍMSLA GÆI: Þegar þú reynir að\n"
	.string "fanga Vasaskrímsli skaltu ekki\p"
	.string "kasta VASA BOLTUM strax.\p"
	.string "Fyrst þarftu að veikja það með því\n"
	.string "að lækka HP þess.$"

Pokedude_Text_BestIfTargetStatused::
	.string "Allt í lagi, það ætti að vera nógu\n"
	.string "gott.\p"
	.string "Ef hægt er, er samt best að\n"
	.string "skotmarkið sé með stöðuvanda.\p"
	.string "Til dæmis er auðveldara að fanga það\n"
	.string "ef það sefur eða er lamað.$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "Þetta gerir Vasaskrímslið miklu\n"
	.string "auðveldara að fanga!\p"
	.string "Já, og eitt enn. Ef þú lamar\n"
	.string "Vasaskrímsli geturðu ekki líka svæft\p"
	.string "það.\p"
	.string "Með öðrum orðum, þú getur ekki lagt\n"
	.string "tvo stöðuvanda ofan á hvorn annan,\p"
	.string "allt í lagi?$"

Pokedude_Text_LetMeThrowBall::
	.string "Allt í lagi! Leyfðu mér að kasta\n"
	.string "VASA BOLTANUM mínum!$"

Pokedude_Text_PickBestKindOfBall::
	.string "Áður en þú kastar VASA BOLTA skaltu\n"
	.string "huga að ástandi og tegund\p"
	.string "Vasaskrímslisins og velja þann BOLTA\n"
	.string "sem virkar best.$"
