PokedexRating_Text_HowIsPokedexComingAlong::
	.string "EIK: Gaman að sjá þig! Hvernig\n"
	.string "gengur með VasaDEX-ið þitt?\p"
	.string "Leyfðu mér að líta á það.$"

PokedexRating_Text_SeenXOwnedY::
	.string "Framfarir þínar í VasaDEX-inu eru:\p"
	.string "{STR_VAR_1} Vasaskrímsli séð og\n"
	.string "{STR_VAR_2} Vasaskrímsli í eigu.\p"
	.string "{FONT_NORMAL}Mat Prófessor EIK:$"

PokedexRating_Text_LessThan10::
	.string "Þú átt enn mikið eftir.\p"
	.string "Farðu í hvert grasblett sem þú sérð\n"
	.string "og leitaðu að Vasaskrímslum!$"

PokedexRating_Text_LessThan20::
	.string "Það lítur út fyrir að þú sért á\n"
	.string "réttri leið!\p"
	.string "Ég gaf einum AÐSTOÐARMANNA minna\n"
	.string "FLASH HM. Vertu viss um að sækja það!$"

PokedexRating_Text_LessThan30::
	.string "VasaDEX-ið þitt mætti enn vera\n"
	.string "aðeins fyllra!\p"
	.string "Reyndu að fanga fleiri tegundir af\n"
	.string "Vasaskrímslum!$"

PokedexRating_Text_LessThan40::
	.string "Gott, það sést að þú leggur þig\n"
	.string "fram!\p"
	.string "Ég gaf einum AÐSTOÐARMANNA minna\n"
	.string "ITEMFINDER. Mundu að sækja hann!$"

PokedexRating_Text_LessThan50::
	.string "VasaDEX-ið þitt gengur bara nokkuð\n"
	.string "vel!\p"
	.string "Ég gaf einum AÐSTOÐARMANNA minna\n"
	.string "AMULET COIN. Vertu viss um að sækja hann!$"

PokedexRating_Text_LessThan60::
	.string "Ah, þú hefur loksins náð yfir\n"
	.string "50 tegundir!\p"
	.string "Ég gaf einum AÐSTOÐARMANNA minna\n"
	.string "EXP. SHARE. Vertu viss um að sækja það!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! Þetta er að verða ansi\n"
	.string "virðingarvert VasaDEX!$"

PokedexRating_Text_LessThan80::
	.string "Mjög gott!\p"
	.string "Ég held að þú safnir enn fleiri\n"
	.string "Vasaskrímslum með því að veiða!$"

PokedexRating_Text_LessThan90::
	.string "Dásamlegt! Leyfðu mér að giska… Þér\n"
	.string "líkar að safna hlutum, ekki satt?$"

PokedexRating_Text_LessThan100::
	.string "Ég er hrifinn! Þetta hlýtur að hafa\n"
	.string "verið erfitt!$"

PokedexRating_Text_LessThan110::
	.string "Þú náðir loksins 100 tegundum! Ég\n"
	.string "trúi varla hvað þú ert fær!$"

PokedexRating_Text_LessThan120::
	.string "Þú átt meira að segja þróuð form\n"
	.string "Vasaskrímsla! Frábært!$"

PokedexRating_Text_LessThan130::
	.string "Frábært! Skiptu við vini til að fá\n"
	.string "fleiri!$"

PokedexRating_Text_LessThan140::
	.string "Stórkostlegt! Þú ert nú algjör\n"
	.string "sérfræðingur í þessu!$"

PokedexRating_Text_LessThan150::
	.string "Ég hef ekkert eftir að segja! Þú ert\n"
	.string "VASASKRÍMSLA-PRÓFESSORINN núna!$"

PokedexRating_Text_Complete::
	.string "VasaDEX-ið þitt er alveg fullklárað!\n"
	.string "Til hamingju!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "Og ÞJÓÐAR-VasaDEX-ið þitt er:\p"
	.string "{STR_VAR_1} Vasaskrímsli séð og\n"
	.string "{STR_VAR_2} Vasaskrímsli í eigu.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Ég hlakka til að sjá þig fylla\n"
	.string "ÞJÓÐAR-VasaDEX-ið!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Loksins…\p"
	.string "Þú hefur fullklárað\n"
	.string "VasaDEX-ið!\p"
	.string "Það er stórfenglegt! Þetta er\n"
	.string "sannarlega frábært afrek!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Vroooooooaaaaaarrrr!$"

PokedexRating_Text_HaHa::
	.string "Haah haah…$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Takk, {PLAYER}! Innilega,\n"
	.string "takk fyrir! Þú hefur gert draum minn\p"
	.string "að veruleika!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "EIK: Ah, vertu velkomin!\p"
	.string "Segðu mér, hvernig gengur með\n"
	.string "VasaDEX-ið þitt?\p"
	.string "Wahaha!\p"
	.string "Reyndar veit ég hvernig það gengur,\n"
	.string "en ég elska samt að sjá það!\p"
	.string "Sjáum til…$"
