Text_MayIHelpYou::
	.string "Hæ, þú! Get ég hjálpað þér?$"

Text_FillOutQuestionnaire::
	.string "Þetta er spurningalisti. Viltu fylla\n"
	.string "hann út?$"

Text_QuestionnaireThankYou::
	.string "Takk fyrir að gefa þér tíma til að\n"
	.string "fylla út spurningalistann okkar.\p"
	.string "Álit þitt verður notað til framtíðar\n"
	.string "viðmiðunar.$"

Text_YouKnowThoseWords::
	.string "Ó, halló! Þú þekkir þessi orð?\p"
	.string "Það þýðir að þú hlýtur að vita um\n"
	.string "MYSTERY GIFT.\p"
	.string "Upp frá þessu ættirðu að fá MYSTERY\n"
	.string "GIFTS!$"

Text_YouCanAccessMysteryGift::
	.string "Þegar þú vistar leikinn geturðu\n"
	.string "nálgast MYSTERY GIFT.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Takk fyrir að fá aðgang að MYSTERY\n"
	.string "GIFT kerfinu.$"
