Text_OnlySkilledTrainersAllowedThrough::
	.string "Aðeins sannarlega færir ÞJÁLFARAR\n"
	.string "mega fara hér í gegn.\p"
	.string "Þú ert ekki með {STR_VAR_1} enn!$"

Text_CantLetYouPass::
	.string "Reglur eru reglur. Ég get ekki\n"
	.string "hleypt þér í gegn.$"

Text_OhThatsBadgeGoRightAhead::
	.string "Ó! Þetta er {STR_VAR_1}! Farðu\n"
	.string "endilega áfram.$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "Þú mátt aðeins fara hér í gegn ef\n"
	.string "þú ert með {STR_VAR_1}.\p"
	.string "Þú ert ekki með {STR_VAR_1} enn.\p"
	.string "Þú þarft það til að komast í\n"
	.string "VASASKRÍMSLADEILDINA.$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "Þú mátt aðeins fara hér í gegn ef\n"
	.string "þú ert með {STR_VAR_1}.\p"
	.string "Ó! Þetta er\n"
	.string "{STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Allt í lagi. Farðu endilega áfram.$"
