@ The text here is a copy/paste from Hoenn's Safari Zone, and any unused text was left untranslated

SafariZone_Text_WouldYouLikeToExit::
	.string "Viltu fara út úr SAFARI SVÆÐINU\n"
	.string "núna?$"

SafariZone_Text_TimesUp::
	.string "PA: Ding-dong!\p"
	.string "Tíminn er búinn!\p"
	.string "PA: SAFARI LEIKURINN þinn er búinn!$"

SafariZone_Text_OutOfBalls::
	.string "PA: Ding-dong!\p"
	.string "Þú ert uppiskroppa með SAFARI BOLTA!\p"
	.string "PA: SAFARI LEIKURINN þinn er búinn!$"

SafariZone_Text_WelcomeToSafariZone::
	.string "サファリゾーンへ ようこそ！\p"
	.string "ここでは ホウエンでは なかなか みることの できない ポケモンを\p"
	.string "しぜんの すがたの まま めに することが できます\p"
	.string "また ポケモントレーナーの ようぼうに おこたえ して\p"
	.string "ポケモンを つかまえる ことも できます！\p"
	.string "サファリゾーンを たのしんで いってね！$"

SafariZone_Text_WelcomeFirstTime::
	.string "サファリゾーンへ ようこそ！ サファリゾーンは はじめて ですか？$"

SafariZone_Text_ComeInAndEnjoy::
	.string "サファリゾーンを たのしんで いってね！$"

SafariZone_Text_FirstTimeInfo::
	.string "サファリゾーンでは 30この サファリボールを つかって ポケモンを\n"
	.string "つかまえる ことが できます\p"
	.string "サファリボールを つかいきるか 500ぽ あるくと\p"
	.string "ゲームは しゅうりょう です\p"
	.string "サファリゾーンを たのしんで いってね！$"

SafariZone_Text_WouldYouLikeToPlay::
	.string "サファリゾーンへ ようこそ！\p"
	.string "500えんで ポケモン つかまえほうだい！ サファリゲームに さんか\n"
	.string "しますか？$"

SafariZone_Text_PlayAnotherTime::
	.string "そうですか こんど ぜひ さんか してください！$"

SafariZone_Text_NotEnoughMoney::
	.string "おかねが たりませんよ！$"

SafariZone_Text_ThatWillBe500Please::
	.string "それでは 500えん いただきます$"

SafariZone_Text_HereAreYourSafariBalls::
	.string "では サファリボールを どうぞ！$"

SafariZone_Text_Received30SafariBalls::
	.string "{PLAYER}は サファリボールを 30こ うけとった！$"

SafariZone_Text_PleaseEnjoyYourself::
	.string "じかんに なりましたら こちらから おしらせ しますので\p"
	.string "ぞんぶんに おたのしみ ください！ では いってらっしゃい！$"

SafariZone_Text_ExcuseMeYourPCBoxIsFull::
	.string "Afsakaðu! PC-KASSINN þinn er fullur.$"

SafariZone_Text_YouNeedPokeblockCase::
	.string "あ！ おきゃくさん ポロックケースを おもちで ないですね？\p"
	.string "サファリゾーンは ポロックを つかうと より おたのしみ\n"
	.string "いただけますので\p"
	.string "ぜひ ポロックケースを おもちに なって おこし ください！$"

SafariZone_South_Text_StillHaveTimeExit::
	.string "まだ じかんが のこっていますが サファリゾーンを やめますか？$"

SafariZone_South_Text_EnjoyTheRestOfYourAdventure::
	.string "では ひきつづき おたのしみ ください！$"

SafariZone_South_Text_ExitEarlyThankYouForPlaying::
	.string "わかりました\p"
	.string "それでは のこりの サファリボールを おあずかり します\p"
	.string "おつかれさまでした また ごりよう ください$"

SafariZone_South_Text_GoodLuck::
	.string "それでは いってらっしゃい！ なにか ありましたら わたしに こえを\n"
	.string "かけて くださいね$"

SafariZone_South_Text_Boy::
	.string "しってた？\p"
	.string "あの しかくい はこに ポロックを おくと ポケモンが あつまって\n"
	.string "くるんだよ！$"

SafariZone_South_Text_Man::
	.string "この さきに いきたい けど じてんしゃ もって くるの わすれた‥‥\p"
	.string "おくに めずらしい ポケモンが いそうな きが するのに！$"

SafariZone_Southwest_Text_Woman::
	.string "ポケモンに ポロックを なげても しらんぷり される ときが あるのよ\p"
	.string "ポケモンにも すききらいが あるのかしら？$"

SafariZone_Northwest_Text_Man::
	.string "ぜぇ‥‥ ぜぇ‥‥ やっと ここまで きたけど‥‥\p"
	.string "つかれちゃって ポケモン つかまえる げんきも のこって ないよ‥‥$"

SafariZone_North_Text_Fisherman::
	.string "ホウエンに いない みずポケモンを さがしに きたんだけど‥‥\p"
	.string "みずうみは どこにあるのか きみ しってるかい？$"

SafariZone_North_Text_Man::
	.string "ここで めずらしい ポケモンを たくさん つかまえて ともだちと\n"
	.string "こうかん するんだ！$"

SafariZone_South_Text_Youngster::
	.string "ポロックおきばに おいた ポロックが いつのまにか なくなっていた‥‥\p"
	.string "しらない うちに ポケモンが たべちゃったのかな？$"

Route121_SafariZoneEntrance_Text_TrainerTip::
	.string "サファリゾーンの おとくな じょうほう！\p"
	.string "であった ポケモンに ポロックを なげると にげにくく なります！$"

SafariZone_Southwest_Text_RestHouseSign::
	.string "あるき つかれたら ちょっと ひといき！ 'みんなの きゅうけいじょ'$"

SafariZone_RestHouse_Text_Youngster::
	.string "おれ ポロック もってないけど ポケモン たくさん つかまえたよ\p"
	.string "ちかづいて ボールを なげる だけで けっこう つかまえられる\n"
	.string "もんだよ！$"

SafariZone_RestHouse_Text_PsychicM::
	.string "ポロックを つかうと いつもより ちょっぴり にげにくく なるみたい\p"
	.string "だから にげにくい ポケモンに つかっても あんまり いみが ないかもね$"

SafariZone_RestHouse_Text_FatMan::
	.string "ポロックおきばに ポロック おいて ポケモンを つかまえると\p"
	.string "おなじ ような せいかくの ポケモンが あつまる きが するなあ$"
