gText_WouldYouLikeToSaveTheGame::
	.string "Viltu vista leikinn?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Það er þegar til vistun. Má skrifa\n"
	.string "yfir hana?$"

gText_SavingDontTurnOffThePower::
	.string "SAVING… DON'T TURN OFF THE POWER.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} vistaði leikinn.$"

gText_SaveFailed2::
	.string "セーブに しっぱい しました‥$"

gText_DifferentGameFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\p"
	.string "Vasaskrímsli, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"
