gText_WouldYouLikeToSaveTheGame::
	.string "Viltu vista leikinn?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Það er þegar til vistun. Má skrifa\n"
	.string "yfir hana?$"

gText_SavingDontTurnOffThePower::
	.string "VISTAR… EKKI SLÖKKVA Á RAFMAGNINU.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} vistaði leikinn.$"

gText_SaveFailed2::
	.string "セーブに しっぱい しました‥$"

gText_DifferentGameFile::
	.string "VIÐVÖRUN!\p"
	.string "Það er önnur vistunarskrá sem er\n"
	.string "þegar vistuð.\p"
	.string "Ef þú vistar núna, mun ævintýri\n"
	.string "hinnar skrárinnar, þar á meðal\p"
	.string "hlutir og\p"
	.string "Vasaskrímsli, glatast alveg.\p"
	.string "Ertu viss um að þú viljir vista núna\n"
	.string "og skrifa yfir hina vistunarskrána?$"
