@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "Hmm… Er það svo…$"

PalletTown_Text_OhLookLook::
	.string "Ó! Sjáðu, sjáðu!$"

PalletTown_Text_ReadItReadIt::
	.string "Lestu það, lestu það!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "ÞJÁLFARA RÁÐ\p"
	.string "Ýttu á START til að opna VALMYNDINA!$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Skilti eru gagnleg, er það ekki?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "Sjáðu, sjáðu!\p"
	.string "Ég skrifaði upp eitt af þessum\n"
	.string "ÞJÁLFARA RÁÐ-skiltum!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "ÞJÁLFARA RÁÐ!\p"
	.string "Ýttu á START til að opna VALMYNDINA!$"
