VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "Rafhlaðan er ekki nægilega hlaðin.\p"
	.string "Fjöldi skrefa sem þarf til að\n"
	.string "fullhlaða rafhlöðuna:\p"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "Engir ÞJÁLFARAR eru innan seilingar\n"
	.string "sem geta barist…\p"
	.string "VS LEITARINN var slökktur.\n"
	.string "{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "Hinir ÞJÁLFARARNIR virðast ekki vera\n"
	.string "tilbúnir í bardaga.\p"
	.string "Bíðum til síðar.{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro::
	.string "Hæ! Ég sá þig í VIRIDIAN FOREST!$"

Route3_Text_BenRematchIntro::
	.string "Hæ! Mér líkar við stuttbuxur! Þær\n"
	.string "eru þægilegar og auðveldar í notkun!\p"
	.string "Þú ættir líka að vera í stuttbuxum!$"

Route3_Text_JaniceRematchIntro::
	.string "Afsakið! Þú ert alltaf að horfa á\n"
	.string "mig, er það ekki?$"

Route3_Text_GregRematchIntro::
	.string "Þú ert ÞJÁLFARI, er það ekki? Gerum\n"
	.string "þetta strax!$"

Route3_Text_SallyRematchIntro::
	.string "Þetta augnaráð sem þú gefur mér… Það\n"
	.string "heillar mig svo!$"

Route3_Text_CalvinRematchIntro::
	.string "Hæ! Hvað er að þér? Þú ert enþá ekki\n"
	.string "í stuttbuxum!$"

Route3_Text_JamesRematchIntro::
	.string "Ég mun berjast við þig með\n"
	.string "Vasaskrímslunum sem ég byrjaði að\p"
	.string "rækta.$"

Route3_Text_RobinRematchIntro::
	.string "Æ! Ýttirðu við mér?$"

Route4_Text_CrissyRematchIntro::
	.string "Ég veiði alltaf sveppa Vasaskrímsli\n"
	.string "á MT. MOON.$"

Route6_Text_RickyRematchIntro::
	.string "Ó! Þú ert þetta forvitna barn sem\n"
	.string "hlustaði á okkur!$"

Route6_Text_NancyRematchIntro::
	.string "Afsakið! Sagði ég þér ekki að þetta\n"
	.string "væri einkasamtal?\p"
	.string "Þú ættir ekki að hlusta, þú\n"
	.string "ókurteisa manneskja!$"

Route6_Text_KeigoRematchIntro::
	.string "I'm trying to find something good\n"
	.string "það er ekki SKORDÝ Vasaskrímsli, en…$"

Route6_Text_JeffRematchIntro::
	.string "Ha? Viltu fara með mér aftur?$"

Route6_Text_IsabelleRematchIntro::
	.string "Ég? Jæja, allt í lagi. Ég spila\n"
	.string "þetta einu sinni.$"

Route6_Text_ElijahRematchIntro::
	.string "Hæ, langt síðan! Hefurðu orðið\n"
	.string "betri?$"

Route8_Text_AidanRematchIntro::
	.string "Þú ert góður í Vasaskrímslum, en\n"
	.string "hvernig er efnafræðieinkunnin þín?$"

Route8_Text_StanRematchIntro::
	.string "Allt í lagi! Spilum annan leik!$"

Route8_Text_GlennRematchIntro::
	.string "Þú þarft stefnu til að vinna í\n"
	.string "bardögum.\p"
	.string "Ertu að fylgja ráðum mínum?$"

Route8_Text_PaigeRematchIntro::
	.string "Ég hef safnað mörgum NIDORAN. Ég vil\n"
	.string "ekki að þau þróist, en…$"

Route8_Text_LeslieRematchIntro::
	.string "Skólinn er skemmtilegur, en mér\n"
	.string "finnst Vasaskrímsli líka skemmtileg.$"

Route8_Text_AndreaRematchIntro::
	.string "MJÁGJARN og KLÓFESSOR eru svo sæt,\n"
	.string "mjálf, mjálf, mjálf!$"

Route8_Text_MeganRematchIntro::
	.string "Við lítum kannski kjánalega út\n"
	.string "standandi hér svona, en ég get samt\p"
	.string "barist.$"

Route8_Text_RichRematchIntro::
	.string "Ég er ráfandi, spilandi gaur! Ég er\n"
	.string "á vinningshrinu!$"

Route8_Text_JuliaRematchIntro::
	.string "Hvað er sætt, kringlótt og loðið\n"
	.string "Vasaskrímsli?\p"
	.string "Þú veist það nú þegar, er það ekki?$"

Route8_Text_RicardoRematchIntro::
	.string "Hjólið mitt er enn að stríða mér,\n"
	.string "maður.$"

Route8_Text_JarenRematchIntro::
	.string "Allt í lagi, krakki! Ekki búast við\n"
	.string "miskunn að þessu sinni!$"

Route8_Text_EliRematchIntro::
	.string "ELI: Tvíburakrafturinn okkar varð\n"
	.string "enn betri!$"

Route8_Text_AnneRematchIntro::
	.string "ANNE: Tvíburakrafturinn okkar\n"
	.string "styrktist!$"

Route9_Text_AliciaRematchIntro::
	.string "Við eigum að berjast aftur? Að þessu\n"
	.string "sinni, ertu minn!$"

Route9_Text_ChrisRematchIntro::
	.string "Ég hef ekki gleymt að þú varst með\n"
	.string "þessum fallegu Vasaskrímslum.$"

Route9_Text_DrewRematchIntro::
	.string "Ég er að fara í STEINA GÖNGIN til\n"
	.string "LAVENDER…\p"
	.string "En ég er stöðugt stoppaður af öllum\n"
	.string "á leiðinni…$"

Route9_Text_CaitlinRematchIntro::
	.string "Ekki dirfast að niðurlægja mig í\n"
	.string "dag! Við erum að spila upp á allt!$"

Route9_Text_JeremyRematchIntro::
	.string "Bwahaha! Frábært! Mér leiddist\n"
	.string "aftur, ha!$"

Route9_Text_BriceRematchIntro::
	.string "Hahaha! Smá harðhaus, eins og\n"
	.string "alltaf!$"

Route9_Text_BrentRematchIntro::
	.string "Ég vaknaði snemma á hverjum degi til\n"
	.string "að þjálfa Vasaskrímslin mín úr\p"
	.string "púpunum!$"

Route9_Text_AlanRematchIntro::
	.string "Hahahaha! Ég vinn að þessu sinni!$"

Route9_Text_ConnerRematchIntro::
	.string "Farðu og sigraðu, ofur SKORDÝ Vasaskrímslið mitt!$"

Route10_Text_MarkRematchIntro::
	.string "Vá, komstu hingað aftur? Kannski\n"
	.string "ertu líka SKRÍMSLASJÚKUR? Viltu\p"
	.string "sjá safnið mitt?$"

Route10_Text_ClarkRematchIntro::
	.string "Ha-hahah-ah-ha! Ég get ekki hætt að\n"
	.string "hnerra!$"

Route10_Text_HermanRematchIntro::
	.string "Hæ, krakki! Sýndi ég þér\n"
	.string "Vasaskrímslin mín?$"

Route10_Text_HeidiRematchIntro::
	.string "Ég fór aftur í Vasaskrímsli SAL.\p"
	.string "…En ég tapaði eins og venjulega.$"

Route10_Text_TrentRematchIntro::
	.string "Ah! Þetta fjallaloft er dásamlegt!\n"
	.string "Það er svo gott, ég get ekki farið!$"

Route10_Text_CarolRematchIntro::
	.string "Höfuðið á mér er farið að snúast. Ég\n"
	.string "hef verið að ganga of lengi…$"

Route11_Text_HugoRematchIntro::
	.string "Vinna, tapa eða jafntefli! Nú er\n"
	.string "komið að endurleiknum okkar!$"

Route11_Text_JasperRematchIntro::
	.string "Að keppa er fullkominn spenna. Ég\n"
	.string "get enn ekki fengið nóg!$"

Route11_Text_EddieRematchIntro::
	.string "Þú veist, ekki satt? Förum, en ekki\n"
	.string "svindla!$"

Route11_Text_BraxtonRematchIntro::
	.string "Hæ, þarna!\p"
	.string "En vertu varkár! Ég er enn að leggja\n"
	.string "niður snúrur!$"

Route11_Text_DillonRematchIntro::
	.string "Ég varð ÞJÁLFARI fyrir stuttu. En ég\n"
	.string "held að ég geti unnið.$"

Route11_Text_DirkRematchIntro::
	.string "Fwahaha! Ég hef aldrei tapað!\p"
	.string "…Og ef ég gerði það, hef ég gleymt\n"
	.string "því alveg!$"

Route11_Text_DarianRematchIntro::
	.string "Ég hef aldrei unnið áður…\p"
	.string "Kannski er mér ætlað að vera þannig…$"

Route11_Text_YasuRematchIntro::
	.string "Ég er bestur í mínum bekk. Ég æfi\n"
	.string "hvern morgun og kvöld!$"

Route11_Text_BernieRematchIntro::
	.string "Passaðu þig á straumleiðslum!$"

Route11_Text_DaveRematchIntro::
	.string "Ég ræktaði Vasaskrímslin mín\n"
	.string "vandlega. Þau ættu að vera tilbúin\p"
	.string "núna. Í þetta skiptið ættu þau líka\n"
	.string "að vinna.$"

Route12_Text_NedRematchIntro::
	.string "Já! Ég fékk bit, hér! Þ-þetta gæti\n"
	.string "verið alvöru!$"

Route12_Text_ChipRematchIntro::
	.string "Þú ert loksins hér. Veiðar eru\n"
	.string "biðleikur.$"

Route12_Text_JustinRematchIntro::
	.string "Finn ennþá ekki MOON STONE… Hefur þú\n"
	.string "fundið einn?$"

Route12_Text_LucaRematchIntro::
	.string "Rafmagn hefur alltaf verið sérgrein\n"
	.string "mín.\p"
	.string "Ég veit þó ekkert um Vasaskrímsli\n"
	.string "sjávarins.$"

Route12_Text_HankRematchIntro::
	.string "FISKIMANNINN vs. Vasaskrímsla\n"
	.string "BARNIÐ! Önnur umferð, berjist!$"

Route12_Text_ElliotRematchIntro::
	.string "Ég elska að veiða, misskildu mig\n"
	.string "ekki. En, ég vildi að ég hefði meiri\p"
	.string "vinnu… …Það er\p"
	.string "erfitt að hætta að veiða!$"

Route12_Text_AndrewRematchIntro::
	.string "Hvað er að veiðast?\p"
	.string "Þú munt aldrei vita nema þú sigrir\n"
	.string "mig!$"

Route12_Text_JesRematchIntro::
	.string "JES: Ég vinn hér í dag og bið GIA\n"
	.string "mína.$"

Route12_Text_GiaRematchIntro::
	.string "GIA: Hæ, JES… Ég hef beðið lengi\n"
	.string "núna.\p"
	.string "Ef við vinnum í dag, giftist ég þér!$"

Route13_Text_SebastianRematchIntro::
	.string "Fugla Vasaskrímslin mín muna eftir\n"
	.string "þér!$"

Route13_Text_SusieRematchIntro::
	.string "Ég vil vera besti ÞJÁLFARINN á meðan\n"
	.string "ég er krakki!$"

Route13_Text_ValerieRematchIntro::
	.string "Vá! Þú fékkst fleiri flott BADGES!$"

Route13_Text_GwenRematchIntro::
	.string "Sætu Vasaskrímslin mín óska eftir að\n"
	.string "kynnast þér aftur.$"

Route13_Text_AlmaRematchIntro::
	.string "Ég tæmdi sparnaðinn minn og keypti\n"
	.string "meira CARBOS.$"

Route13_Text_PerryRematchIntro::
	.string "Ég ætla ekki að tapa að þessu sinni.\n"
	.string "Vindurinn blæs í mína átt!$"

Route13_Text_LolaRematchIntro::
	.string "Ó, þú ert kominn aftur?\p"
	.string "Jú, ég spila aftur með þér, eldgos.$"

Route13_Text_SheilaRematchIntro::
	.string "Geturðu ekki gleymt því að þú\n"
	.string "barðist við mig?$"

Route13_Text_JaredRematchIntro::
	.string "Hvað ertu að stara á?$"

Route13_Text_RobertRematchIntro::
	.string "Ég vel alltaf fugla Vasaskrímsli. Ég\n"
	.string "hef helgað mig þeim.$"

Route14_Text_CarterRematchIntro::
	.string "Ég notaði TMs til að kenna\n"
	.string "Vasaskrímslunum mínum góðar árásir.$"

Route14_Text_MitchRematchIntro::
	.string "Fugla Vasaskrímslin mín ættu að vera\n"
	.string "tilbúin í bardaga í þetta skiptið.$"

Route14_Text_BeckRematchIntro::
	.string "Ertu að nota TMs á Vasaskrímsli? Að\n"
	.string "halda þeim er gagnslaust.$"

Route14_Text_MarlonRematchIntro::
	.string "Hefur þú kennt fugla Vasaskrímslunum\n"
	.string "þínum að FLJÚGA?\p"
	.string "Þú munt geta svifið með því upp í\n"
	.string "himininn! Reyndu það.$"

Route14_Text_DonaldRematchIntro::
	.string "Sagan um vængjuðu hillingarnar… Þú\n"
	.string "hefur heyrt hana, ekki satt?$"

Route14_Text_BennyRematchIntro::
	.string "Ég er eiginlega ekki í stuði, en\n"
	.string "allt í lagi. Förum!$"

Route14_Text_LukasRematchIntro::
	.string "Hæ! Ég man eftir þér!\p"
	.string "Komdu, komdu. Förum, förum, förum!$"

Route14_Text_IsaacRematchIntro::
	.string "Þú ert hér aftur, ha? Þegiðu og\n"
	.string "berjist.$"

Route14_Text_GeraldRematchIntro::
	.string "Við höfum verið að hjóla hér vegna\n"
	.string "hinna víðu svæða.$"

Route14_Text_MalikRematchIntro::
	.string "Vasaskrímsla bardagi, er það ekki?\n"
	.string "Kúl! Öskur!$"

Route14_Text_KiriRematchIntro::
	.string "KIRI: JAN, ég vona að við vinnum í\n"
	.string "dag.$"

Route14_Text_JanRematchIntro::
	.string "JAN: KIRI, hér förum við! Vinnum\n"
	.string "fyrir víst að þessu sinni!$"

Route15_Text_KindraRematchIntro::
	.string "Ég ætla að halda áfram að berjast\n"
	.string "með Vasaskrímslunum sem ég fékk í\p"
	.string "skiptum.$"

Route15_Text_BeckyRematchIntro::
	.string "Þú lítur mildilega út, svo ég held\n"
	.string "að ég geti sigrað þig.\p"
	.string "Ég ætla að reyna einu sinni enn!$"

Route15_Text_EdwinRematchIntro::
	.string "Þegar ég flauta safnast fugla-\n"
	.string "Vasaskrímsli í kring.\p"
	.string "Þau eru ótrúlega krúttleg!$"

Route15_Text_ChesterRematchIntro::
	.string "Hmm? Fuglarnir mínir skjálfa! Bíddu,\n"
	.string "ertu ekki sá ÞJÁLFARI…$"

Route15_Text_GraceRematchIntro::
	.string "Ó, þú ert svo sætur! Alveg eins og\n"
	.string "yndislegt Vasaskrímsli! Ég man eftir\p"
	.string "þér núna!$"

Route15_Text_OliviaRematchIntro::
	.string "Ég rækta Vasaskrímsli til varnar því\n"
	.string "ég bý ein. Það hefur ekki breyst.$"

Route15_Text_ErnestRematchIntro::
	.string "Hæ, krakki! Komdu! Ég fékk þetta af\n"
	.string "einhverjum tapara!$"

Route15_Text_AlexRematchIntro::
	.string "Afhentu allan peninginn þinn þegar\n"
	.string "þú tapar fyrir mér, krakki!$"

Route15_Text_CeliaRematchIntro::
	.string "Hvað er flott og í gangi? Að skipta\n"
	.string "á Vasaskrímslum, auðvitað.$"

Route15_Text_YazminRematchIntro::
	.string "Viltu leika við Vasaskrímslin mín\n"
	.string "aftur?$"

Route15_Text_MyaRematchIntro::
	.string "MYA: Hæ, við hittumst alltaf, er það\n"
	.string "ekki?\p"
	.string "Hjálparðu mér að þjálfa litla bróður\n"
	.string "minn aftur?$"

Route15_Text_RonRematchIntro::
	.string "RON: Systir mín er orðin öflugri…$"

Route16_Text_LaoRematchIntro::
	.string "Hvað viltu?$"

Route16_Text_KojiRematchIntro::
	.string "Fínt BIKE! Afhentu það fljótt!$"

Route16_Text_LukeRematchIntro::
	.string "Komdu út og leiktu þér, litla mús.\n"
	.string "Ég skal koma vel fram við þig!$"

Route16_Text_HideoRematchIntro::
	.string "Hæ, bíddu aðeins! Ekki hringja í mig\n"
	.string "og hlaupa svo í burtu!$"

Route16_Text_CamronRematchIntro::
	.string "Mér líður hungraður og illur! Ég\n"
	.string "þarf virkilega boxpúða!$"

Route16_Text_RubenRematchIntro::
	.string "Hæ, þarna! Við munum skemmta okkur\n"
	.string "vel!$"

Route16_Text_JedRematchIntro::
	.string "JED: Ertu hér til að sjá ást okkar,\n"
	.string "sem þekkir engin takmörk?$"

Route16_Text_LeaRematchIntro::
	.string "LEA: Stundum hræðir styrkur ástar\n"
	.string "okkar mig.$"

Route17_Text_RaulRematchIntro::
	.string "Ég sagði þér, það er engin fljótleg\n"
	.string "leið til að auðgast á því að berjast\p"
	.string "við krakka.$"

Route17_Text_IsaiahRematchIntro::
	.string "Ég er mjög stoltur af líkama mínum,\n"
	.string "krakki. Komdu!$"

Route17_Text_VirgilRematchIntro::
	.string "Ertu úti í göngutúr?$"

Route17_Text_BillyRematchIntro::
	.string "Við erum BIKERS! Við ráðum vegunum,\n"
	.string "maður!$"

Route17_Text_NikolasRematchIntro::
	.string "STUÐBOLTI ætlar að rafmagna þig\n"
	.string "alvarlega í dag!$"

Route17_Text_ZeekRematchIntro::
	.string "Ég hækkaði stigið á Vasaskrímslinu,\n"
	.string "en það þróast alls ekki. Af hverju?$"

Route17_Text_JamalRematchIntro::
	.string "Gaah! Ég þarf virkilega að æfa og\n"
	.string "alvarlega skera af mér fitu!$"

Route17_Text_CoreyRematchIntro::
	.string "Vertu uppreisnarmaður!$"

Route17_Text_JaxonRematchIntro::
	.string "Já, það er fínt BIKE! Hvernig er það\n"
	.string "í meðförum?$"

Route17_Text_WilliamRematchIntro::
	.string "Farðu þér, krakki! Ég er búinn á\n"
	.string "því!$"

Route18_Text_WiltonRematchIntro::
	.string "Ég hef verið að leita í öllum\n"
	.string "grösugum svæðum að nýjum\p"
	.string "Vasaskrímslum. En það er ekki alltaf\n"
	.string "auðvelt…$"

Route18_Text_RamiroRematchIntro::
	.string "Koorukukukoo! Er fuglasöngurinn minn\n"
	.string "að verða betri?$"

Route18_Text_JacobRematchIntro::
	.string "Ég varaði þig við áður, þetta er\n"
	.string "mitt svæði!\p"
	.string "Ég vil ekki sjá þig hér.$"

Route19_Text_RichardRematchIntro::
	.string "Ég er næstum búinn að hita mig upp\n"
	.string "til að fara í sund.$"

Route19_Text_ReeceRematchIntro::
	.string "Bíddu! Hægðu á þér! Hvað ef þú færð\n"
	.string "hjartaáfall?$"

Route19_Text_MatthewRematchIntro::
	.string "Ég elska að synda! Ég giska á að þú\n"
	.string "sért surfgerðin.$"

Route19_Text_DouglasRematchIntro::
	.string "Hvað er handan sjóndeildarhringsins?\n"
	.string "Hefurðu séð?$"

Route19_Text_DavidRematchIntro::
	.string "Ég reyndi að kafa eftir\n"
	.string "Vasaskrímslum aftur, en það gekk\p"
	.string "ekki eins og\p"
	.string "áður.$"

Route19_Text_TonyRematchIntro::
	.string "Ég horfi á sjóinn til að gleyma öllu\n"
	.string "því slæma sem gerðist.\p"
	.string "…Eins og að tapa fyrir þér síðast!$"

Route19_Text_AnyaRematchIntro::
	.string "Þú færð alltaf að ríða\n"
	.string "Vasaskrímslinu þínu…\p"
	.string "Það lítur svo afslappandi út. Má ég\n"
	.string "fá það ef ég vinn?$"

Route19_Text_AliceRematchIntro::
	.string "Sund er frábært! Sólbruni er það\n"
	.string "ekki!$"

Route19_Text_AxleRematchIntro::
	.string "Þessi vötn eru hættuleg! Þú ættir\n"
	.string "ekki að koma hingað aftur!$"

Route19_Text_ConnieRematchIntro::
	.string "Ég synti hingað með vinum mínum… Ég\n"
	.string "er þreytt… Verðum við virkilega að\p"
	.string "berjast aftur?$"

Route19_Text_LiaRematchIntro::
	.string "LIA: Þú veist að bróðir minn varð a\n"
	.string "ÞJÁLFARI, er það ekki?\p"
	.string "Ég vil gera hann betri, svo ég þarf\n"
	.string "hjálp þína aftur.$"

Route19_Text_LucRematchIntro::
	.string "LUC: Stóra systir mín kenndi mér\n"
	.string "allt um Vasaskrímsli.\p"
	.string "Ég velti fyrir mér hvort ég sé\n"
	.string "betri?$"

Route20_Text_BarryRematchIntro::
	.string "Vatnið er grunnt hér. Það eru margir\n"
	.string "að synda.$"

Route20_Text_ShirleyRematchIntro::
	.string "Ertu afbrýðisamur að ég sé í fríi á\n"
	.string "SJÁVARFROÐA?$"

Route20_Text_TiffanyRematchIntro::
	.string "Ég elska að fljóta með fiskunum hér\n"
	.string "meðal öldanna.$"

Route20_Text_IreneRematchIntro::
	.string "Varstu í fríi líka?$"

Route20_Text_DeanRematchIntro::
	.string "Sjáðu líkamsbygginguna mína!\p"
	.string "Hún er ennþá stærri en nokkru sinni\n"
	.string "áður!$"

Route20_Text_DarrinRematchIntro::
	.string "Af hverju ertu að ríða Vasaskrímsli?\n"
	.string "Hefurðu ekki lært að synda ennþá?$"

Route20_Text_RogerRematchIntro::
	.string "I rode my bird Vasaskrímsli here.$"

Route20_Text_NoraRematchIntro::
	.string "Kærastinn minn gaf mér stórar\n"
	.string "perlur. Og þær hafa stækkað!$"

Route20_Text_MissyRematchIntro::
	.string "Ég synti hingað frá CINNABAR ISLAND.\n"
	.string "Það var ekki auðvelt, eins og ég\p"
	.string "sagði.$"

Route20_Text_MelissaRematchIntro::
	.string "CINNABAR, í vestri, hefur\n"
	.string "RANNsóknarstofu fyrir Vasaskrímsli.\p"
	.string "Pabbi minn vinnur þar.$"

Route21_North_Text_RonaldRematchIntro::
	.string "Viltu vita hvort fiskurinn sé að\n"
	.string "bíta?$"

Route21_North_Text_WadeRematchIntro::
	.string "Ég fékk stóran afla aftur! Viltu\n"
	.string "fara í það einu sinni enn?$"

Route21_North_Text_SpencerRematchIntro::
	.string "Sjórinn hreinsar líkama minn og sál!$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "きょうも およぎに きちまったぜ$"

Route21_South_Text_JackRematchIntro::
	.string "Ég veiddi Vasaskrímslin mín á sjó.\n"
	.string "Og þar þjálfa ég þau.$"

Route21_South_Text_JeromeRematchIntro::
	.string "Núna er ég í annarri þríþraut\n"
	.string "keppni!$"

Route21_South_Text_RolandRematchIntro::
	.string "Ahh! Finndu sólina og vindinn!$"

Route21_South_Text_ClaudeRematchIntro::
	.string "Hæ, hættu þessu nú þegar. Þú fælar\n"
	.string "alltaf fiskana í burtu!$"

Route21_South_Text_NolanRematchIntro::
	.string "Vertu mér samferða þar til ég fæ\n"
	.string "högg.$"

Route21_North_Text_LilRematchIntro::
	.string "LIL: Ha? Bardagi aftur? IAN, geturðu\n"
	.string "ekki gert það einn?$"

Route21_North_Text_IanRematchIntro::
	.string "IAN: Systir mín er enn sóði.\n"
	.string "Hjálpaðu mér að fá hana í form!$"

Route25_Text_JoeyRematchIntro::
	.string "Ég mun ekki tapa á meðan ég er hér!$"

Route25_Text_DanRematchIntro::
	.string "Pabbi fór með mig í frábært partý á\n"
	.string "S.S. ANNE í VERMILION BORG.$"

Route25_Text_FlintRematchIntro::
	.string "Ég er flottur gaur. Ég á kærustu!\p"
	.string "Ég sýni henni hversu flottur ég er\n"
	.string "fyrir víst að þessu sinni!$"

Route25_Text_KelseyRematchIntro::
	.string "Hæ! Kærastinn minn er flottur!\n"
	.string "Formið mitt er gott í dag!$"

Route25_Text_ChadRematchIntro::
	.string "Ég hafði þessa tilfinningu… Ég vissi\n"
	.string "að ég þyrfti að berjast við þig\p"
	.string "aftur!$"

Route25_Text_HaleyRematchIntro::
	.string "Vinur minn á mörg sæt Vasaskrímsli.\n"
	.string "Ég er svo öfundsjúk!$"

Route25_Text_FranklinRematchIntro::
	.string "Ég þjálfaði mig bara á MT. MOON, en\n"
	.string "ég á enn bensín á tanknum!$"

Route25_Text_NobRematchIntro::
	.string "SKRÍMSLASJÚKUR býr á höfðanum. Hefur\n"
	.string "þú séð safnið hans?$"

Route25_Text_WayneRematchIntro::
	.string "Ætlarðu að hitta BILL aftur? Fyrst\n"
	.string "berjumst við!$"

Route24_Text_ShaneRematchIntro::
	.string "Ég sá afrek þitt úr grasinu!$"

Route24_Text_EthanRematchIntro::
	.string "Allt í lagi! Ég traðka á þér!$"

Route24_Text_ReliRematchIntro::
	.string "Þú lítur alltaf svo upptekinn út…\n"
	.string "Ertu ekki að verða þreyttur?$"

Route24_Text_TimmyRematchIntro::
	.string "Þú hlýtur virkilega að elska að koma\n"
	.string "á NUGGET BRIDGE.$"

Route24_Text_AliRematchIntro::
	.string "Tíminn sem við börðumst…\p"
	.string "Jafnvel þó ég væri annar í röðinni,\n"
	.string "var ég bestur, ekki satt?$"

Route24_Text_CaleRematchIntro::
	.string "Fólk kallar þetta NUGGET BRÚNA!\p"
	.string "Þú hefur nú þegar sigrað okkur, svo\n"
	.string "þú mátt ekki taka áskorunina…\p"
	.string "…En, þér er velkomið að berjast við\n"
	.string "okkur aftur.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Að liggja aftur, vaggandi af\n"
	.string "öldunum… Ég tek ekki eftir því að\p"
	.string "tíminn líður…$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "Veðrið er dásamlegt! Ég reyni að\n"
	.string "spjalla því ekki.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "Sólbruni minn er farinn að meiða…$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "Fjall eldfuglsins varpar risastórum\n"
	.string "skugga…$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "Ég hef þessa sterku tilfinningu að\n"
	.string "ég get unnið að þessu sinni!$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "Bíddu! Bíddu aðeins! Ég er viss um\n"
	.string "að ég hafi krækst í stóran!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "Ætlarðu að hjálpa mér með þjálfunina\n"
	.string "aftur?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "Við höfum ekki misst úr einn einasta\n"
	.string "dag í þjálfun ennþá!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Á hverjum morgni, fyrir morgunmat,\n"
	.string "syndi ég í kringum þessa eyju…\p"
	.string "Þrisvar sinnum!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "Klæddu þig viðeigandi fyrir bardaga!\n"
	.string "Losnaðu við þennan léttúðuga búning,\p"
	.string "sagði ég!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "Veistu, allt bragðast vel þegar þú\n"
	.string "ert úti í náttúrunni.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "Ég borðaði of mikið aftur, svo viltu\n"
	.string "berjast við okkur til að hreyfa þig?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "KIA: Stóri bróðir minn og ég erum\n"
	.string "frábær samsetning!\p"
	.string "Við munum ekki tapa að þessu sinni!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "MIK: Saman með KIA, erum við hrædd\n"
	.string "við ekkert!\p"
	.string "Við munum sanna það fyrir þér að\n"
	.string "þessu sinni!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "Eigum við að berjast aftur?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "Hvaðan ertu kominn, og hvert ertu á\n"
	.string "leið?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "Ég vil synda án flotbaugsins míns\n"
	.string "bráðum.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "Yay, yay! Vasaskrímsli!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "Ó, nei, sagði ég þér það ekki nú\n"
	.string "þegar? Vinsamlegast, haltu þér frá\p"
	.string "mér!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "JOY: Við höfum orðið sterkari! Mikið\n"
	.string "og mikið!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "MEG: Þú getur ekki sigrað okkur í\n"
	.string "dag!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Ó, halló!\p"
	.string "Ertu að rækta Vasaskrímslin þín í\n"
	.string "góðu umhverfi?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "Með þessum höndum mun ég skapa sigur\n"
	.string "minn í dag.$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "Þarf ég að endurtaka mig? Ég er að\n"
	.string "reyna að mála. Vinsamlegast haltu\p"
	.string "þér frá sjónsviði mínu!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "Ég hef ekki náð neinum framförum… Ég\n"
	.string "get ennþá ekki fengið rétta hornið…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "Ó, ætlarðu að gefa mér annað\n"
	.string "tækifæri til að keppa við þig?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "Þeir eru næstum búnir að búa til\n"
	.string "sundlaugina fyrir Vasaskrímslin mín.\p"
	.string "Þú verður að koma í heimsókn.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "Ég er góður hlaupari. Ég hef orðið\n"
	.string "enn hraðari!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "Ég segi, vinur! Njótum tíma okkar\n"
	.string "saman!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "Ég er elstur BIRD BROTHERS. Manstu\n"
	.string "eftir mér?\p"
	.string "Það er rétt, ég er sá sem elskar\n"
	.string "fugla fyrir gogginn þeirra!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "Ég er miðjubarnið í BIRD BROTHERS.\p"
	.string "Ég er sá sem elskar vængi. Berjumst\n"
	.string "aftur!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "Ég er yngstur BIRD BROTHERS.\p"
	.string "Ég elska fugla fyrir dúninn þeirra.\n"
	.string "Ég hélt ekki að ég myndi sjá þig\p"
	.string "aftur!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "Ég er enn að hafa enga heppni.\n"
	.string "Bardagi væri breyting á hraða!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Andvarp… Andvarp…\p"
	.string "Ég synti hingað frá höfn SEX EYJU\n"
	.string "í einu lagi aftur.$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "Þú kemur alltaf með á meðan ég er að\n"
	.string "synda.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "AVA: Höfum annan tveggja á móti\n"
	.string "tveimur sjávarbardaga í dag!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "GEB: Stóra systir mín og ég erum\n"
	.string "miklu harðari en áður!$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "…Ha?\p"
	.string "Ég sé fyrir mér húsið mitt, en\n"
	.string "TELEPORT kemur mér alltaf hingað!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "Ó, halló. Kellega gola er að blása\n"
	.string "aftur.$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Hehehe, ég er að æfa mig í leyni\n"
	.string "aftur.$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "Hvað, ertu orðinn þreyttur á að sjá\n"
	.string "SUNDMENN eins og mig?\p"
	.string "Aww, ekki vera hatursfullur! Berjist\n"
	.string "við mig aftur.$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Sigh… My boyfriend's busy again…$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Komdu, segðu mér, hvar eru fjöllin\n"
	.string "hér í kring?$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "MIU: Hello, Vasaskrímsli! It's time\n"
	.string "to play again!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MIA: Halló, Vasaskrímsli! Það er\n"
	.string "kominn tími til að berjast aftur!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "Það virðast vera mörg leyndarmál enn\n"
	.string "óleyst í þessum heimi.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Hæ, hittumst við ekki áður? Hvað\n"
	.string "neyddi þig til að koma aftur?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "Sagt hefur verið að það séu\n"
	.string "dularfullir steinar á þessari eyju.\p"
	.string "Hefurðu uppgötvað eitthvað síðan við\n"
	.string "hittumst síðast?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "Endurkeppni við þig, svona hátt\n"
	.string "uppi!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "Ég þekki landið hér í kring frekar\n"
	.string "vel.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "Ég fann nálgun þína.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "Einhvers staðar á þessari eyju sofa\n"
	.string "sérkennileg Vasaskrímsli.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "Kyahaha!\p"
	.string "Að koma aftur mun engu breyta. Ég\n"
	.string "mun fleygja þér í burtu\p"
	.string "áreynslulaust!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "Halló! Þú ert meðlimur í aðdáenda-\n"
	.string "klúbbnum mínum, er það ekki?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "Þessi eyja er of víðáttumikil… Að\n"
	.string "vakta staðinn er leiðinlegt…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "Ég fyrirgef ekki fólki sem fer illa\n"
	.string "með Vasaskrímsli!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "EVE: Ég mun taka höndum saman við\n"
	.string "JON og berjast saman aftur.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "JON: Þegar ég er með EVE, finnst mér\n"
	.string "við getum aldrei tapað, aldrei.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Höfum annan bardaga. Formið mitt er\n"
	.string "í toppstandi!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "Það skiptir ekki máli hvort þú átt\n"
	.string "sterkustu Vasaskrímslin…\p"
	.string "Það þýðir ekkert ef þú veist ekki\n"
	.string "hvernig á að nota þau rétt!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "Ég vinn að því að vernda umhverfið.\n"
	.string "Að sama skapi verndar náttúran mig!$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "Í hvert skipti sem við hittumst,\n"
	.string "ertu í þessum flottu skóm.$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "Þú hlýtur að hafa orðið harðari.\n"
	.string "Leyfðu mér að berjast við þig,\p"
	.string "vinsamlegast!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "Ég fékk bestu mögulegu menntun til\n"
	.string "að verða svona sterk.\p"
	.string "Ég mun ekki tapa að þessu sinni.\n"
	.string "Algjörlega ekki!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "LEX: Elsku NYA mín, saman munum við\n"
	.string "vinna fyrir víst!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "NYA: Ég mun ekki draga leiðbeinanda\n"
	.string "minn LEX niður! Við ætlum að vinna!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "Hefurðu uppgötvað eitthvað um þessa\n"
	.string "steinklefa?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "Sagt er að dularfullt Vasaskrímsli\n"
	.string "sofi hér inni.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "Kennarinn minn er að sýna mér\n"
	.string "hvernig á að mála meira.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "Í dag, auk kennslustundar okkar,\n"
	.string "komum við til að sjá herbergið\p"
	.string "aftur.$"
