CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "Þetta er Vasaskrímsla-PRENTARI!\p"
	.string "Hann getur sett mynd af\n"
	.string "Vasaskrímslinu þínu aftan á\p"
	.string "ÞJÁLFARAKORTIÐ.\p"
	.string "Það kostar aðeins ¥50. Viltu\n"
	.string "prófa?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "Þú átt ekki nægan pening.$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "Veldu tegund prentunar.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "Breitt bros fyrir myndina, takk!\n"
	.string "Þrír… Tveir… Einn…\p"
	.string "Bloss!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "Vasaskrímsla-myndin er tilbúin!\n"
	.string "Athugaðu ÞJÁLFARAKORTIÐ þitt.$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "Híhí… Ég safnaði fullt af\n"
	.string "LÍMMIÐUM. Ég vildi að ég gæti sýnt\p"
	.string "þá…$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "Ó, frábært! Þú komst á réttan\n"
	.string "stað!\p"
	.string "Sjáðu, sjáðu! Sérðu? Þetta eru\n"
	.string "LÍMMIÐARNIR mínir! Sjáðu hvað ég á marga!\p"
	.string "Ég veðja að þú vilt nokkra. Alveg örugglega!\p"
	.string "Ég gef þér LÍMMIÐA ef þú segir mér\n"
	.string "eitthvað stórkostlegt um þig.\p"
	.string "Af hverju ætlarðu að monta þig?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "Montaðu þig af einhverju fyrir mig.\n"
	.string "Ég gef þér LÍMMIÐA.$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "Ó, hæ! Hér kemur montarinn.\p"
	.string "Af hverju ætlarðu að monta þig\n"
	.string "í dag?$"

FourIsland_House2_Text_WowHoFLowest::
	.string "Ó, vá, þú komst í\n"
	.string "FRÆGÐARHÖLLINA.\p"
	.string "Það er nokkuð gott, já! Ég gef\n"
	.string "þér einn af þessum.$"

FourIsland_House2_Text_WowHoFLow::
	.string "Ó, vá, þú hefur oft komist í\n"
	.string "FRÆGÐARHÖLLINA!\p"
	.string "Það er glæsilegt, já! Ég gef\n"
	.string "þér einn af þessum.$"

FourIsland_House2_Text_WowHoFHigh::
	.string "Vá! Hefurðu komist svona oft í\n"
	.string "FRÆGÐARHÖLLINA? Það er alveg\p"
	.string "ótrúlegt, já!\p"
	.string "Þú átt VASASKRÍMSLADEILDINA!\n"
	.string "Ég gef þér einn af þessum.$"

FourIsland_House2_Text_WowHoFHighest::
	.string "Ótrúlegt! Hefurðu farið svona oft í\n"
	.string "FRÆGÐARHÖLLINA?\p"
	.string "Þú ert handan alls ótrúlegs, já!\n"
	.string "Nú verð ég að gefa þér þetta.$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "FRÆGÐARHALLAR-LÍMMIÐINN var settur\n"
	.string "á ÞJÁLFARAKORTIÐ.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "Hmm…\p"
	.string "Komdu aftur með betri sögu næst,\n"
	.string "allt í lagi?$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "Ó, nei, það gengur ekki.\p"
	.string "Þú ert nánast lifandi goðsögn.\n"
	.string "Ég á enga LÍMMIÐA eftir til að gefa.$"

FourIsland_House2_Text_WowEggsLowest::
	.string "Ó, vá, eru til Vasaskrímsla-\n"
	.string "EGG? Það vissi ég ekki!\p"
	.string "Það er nokkuð gott, já! Ég gef\n"
	.string "þér einn af þessum.$"

FourIsland_House2_Text_WowEggsLow::
	.string "Hefurðu klakið svona mörgum EGGJUM?\n"
	.string "Þér hlýtur virkilega að líka við þau!\p"
	.string "Það er glæsilegt, já! Ég gef\n"
	.string "þér einn af þessum.$"

FourIsland_House2_Text_WowEggsHigh::
	.string "Vá! Þú hefur klakið heilan helling\n"
	.string "af EGGJUM!\p"
	.string "Þú ert EGGJA-klakvél! Ég gef\n"
	.string "þér einn af þessum.$"

FourIsland_House2_Text_WowEggsHighest::
	.string "Hv… Klaktirðu svona mörgum EGGJUM?\p"
	.string "Hvað liggur að baki ást þinni á EGGJUM?\n"
	.string "Það er handan alls ótrúlegs, já!\p"
	.string "Þú ert of mögnuð manneskja, segi ég.\n"
	.string "Nú verð ég að gefa þér þetta.$"

FourIsland_House2_Text_EggStickerApplied::
	.string "EGGJA-LÍMMIÐINN var settur á\n"
	.string "ÞJÁLFARAKORTIÐ.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "Hmm…\p"
	.string "Komdu aftur með betri sögu næst,\n"
	.string "allt í lagi?$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "Ó, nei, það gengur ekki.\p"
	.string "Þú ert nánast lifandi goðsögn.\n"
	.string "Ég á enga LÍMMIÐA eftir til að gefa.$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "Ó, vá, hefurðu náð árangri í\n"
	.string "tengibardögum?\p"
	.string "Þú ert nokkuð sterk manneskja, já!\n"
	.string "Ég gef þér einn af þessum.$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "Þú hefur oft sigrað vini þína í\n"
	.string "tengibardögum, ha?\p"
	.string "Þú ert glæsilega sterk manneskja, já!\n"
	.string "Ég gef þér einn af þessum.$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "Vá! Þú hefur sigrað vini þína\n"
	.string "ógnarlega oft.\p"
	.string "Hefurðu misst vini út af þessu?\n"
	.string "Ég gef þér einn af þessum.$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "Hv… svakalegt vá! Þú hefur unnið\n"
	.string "ótrúlega oft!\p"
	.string "Mér svimar bara við að hugsa um\n"
	.string "hversu hörð manneskja þú ert.\p"
	.string "Þú ert efni í martraðir!\n"
	.string "Nú verð ég að gefa þér þetta.$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "SIGUR-LÍMMIÐINN var settur á\n"
	.string "ÞJÁLFARAKORTIÐ.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "Hmm…\p"
	.string "Komdu aftur með betri sögu næst,\n"
	.string "allt í lagi?$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "Ó, nei, það gengur ekki.\p"
	.string "Þú ert nánast lifandi goðsögn.\n"
	.string "Ég á enga LÍMMIÐA eftir til að gefa.$"
