Text_FirstShouldRestoreMonsHealth::
	.string "Fyrst ættirðu að koma\n"
	.string "Vasaskrímslunum í fulla heilsu.$"

Text_MonsHealedShouldBuyPotions::
	.string "Vasaskrímslin þín eru komin í\n"
	.string "fulla heilsu.\p"
	.string "Ef orka þeirra, HP, lækkar skaltu\n"
	.string "endilega koma til okkar.\p"
	.string "Ef þú ætlar langt út á land ættirðu\n"
	.string "að kaupa SEYÐI\p"
	.string "í Vasaskrímsla MART.\p"
	.string "Gangi þér vel!$"

Text_MonsHealed::
	.string "Vasaskrímslin þín eru komin í\n"
	.string "fulla heilsu.\p"
	.string "Gangi þér vel!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "Mamma: {PLAYER}! Velkomin heim.\p"
	.string "Þetta hljómar eins og þú hafir\n"
	.string "lent í miklu ævintýri.\p"
	.string "Kannski ættirðu að hvíla þig aðeins.$"

Text_MomExplainHPGetPotions::
	.string "Mamma: Ó, gott! Þú og Vasaskrímslin\n"
	.string "þín lítið vel út.\p"
	.string "Ég heyrði þetta frá Prófessor EIK.\p"
	.string "Hann sagði að orka Vasaskrímsla væri\n"
	.string "mæld í HP.\p"
	.string "Ef Vasaskrímslin missa HP geturðu\n"
	.string "læknað þau í hvaða\p"
	.string "Vasaskrímslasetri sem er.\p"
	.string "Ef þú ætlar langt að ferðast birgir\n"
	.string "klókur ÞJÁLFARI sig upp af\p"
	.string "SEYÐI í Vasaskrímsla MART.\p"
	.string "Gerðu mig stolta, elskan!\p"
	.string "Farðu varlega!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} is out of usable\n"
	.string "Vasaskrímsli!\p"
	.string "{PLAYER} panicked and lost\n"
	.string "¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"

Text_WhitedOut::
	.string "{PLAYER} is out of usable\n"
	.string "Vasaskrímsli!\p"
	.string "{PLAYER} whited out!$"
