SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections::
    .string "Á þessari eyju gerast ólíkir\n"
    .string "atburðir eftir tengingum.\p"
    .string "Hvaða tengingum?\p"
    .string "Það þarftu að uppgötva sjálf/ur.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere::
    .string "Tókstu SÆSKJÓTA-ferju hingað?\p"
    .string "Það eru að minnsta kosti tíu svona\n"
    .string "hraðskip.\p"
    .string "Ég veit samt ekki hvert þau fara\n"
    .string "öll.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower::
    .string "Ef þú ert örugg/ur með þig ættirðu\n"
    .string "að skoða ÞJÁLFARATURNINN.$"
