SevenIsland_SevaultCanyon_Text_CyndyIntro::
    .string "Ég er í toppformi!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
    .string "Ha? Eitthvað er ekki rétt…$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
    .string "Eins og ég er núna þarf ég kannski\n"
    .string "að bíða með ÞJÁLFARATURNINN…$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
    .string "Það skiptir engu þótt þú eigir\n"
    .string "sterkustu Vasaskrímslin…\p"
    .string "Það þýðir ekkert ef þú kannt ekki að\n"
    .string "nota þau rétt!$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
    .string "Þú ert meistari í þessu.$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
    .string "Maður sér það af og til, ÞJÁLFARA\n"
    .string "með frábær Vasaskrímsli sem vita\p"
    .string "ekki hvað þeir eiga að gera.\p"
    .string "Áður en ÞJÁLFARAR þjálfa\n"
    .string "Vasaskrímsli þurfa þeir sjálfir að\p"
    .string "þroskast.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
    .string "Ég vinn að því að vernda umhverfið.\n"
    .string "Náttúran verndar mig í staðinn!$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
    .string "Vá! Þú ert harður! Hvað með að\n"
    .string "vernda mig?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
    .string "Úr fjarlægð meðal stjarnanna er\n"
    .string "plánetan okkar bara vatnsdropi.\p"
    .string "En við viljum vernda þennan\n"
    .string "vatnsdropa fyrir alla.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
    .string "Þessir skór sem þú ert með eru ansi\n"
    .string "flottir.$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
    .string "Þú ert mikill snillingur þrátt fyrir\n"
    .string "sætt útlit.$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
    .string "Mamma þín keypti þessa flottu\n"
    .string "RUNNING SHOES fyrir þig?\p"
    .string "Hún hlýtur að dýrka þig.$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
    .string "Þú lítur sterkur út. Leyfðu mér að\n"
    .string "berjast við þig, vinsamlegast!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
    .string "Ég vissi það! Þú ert jafn harður og\n"
    .string "ég hélt!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
    .string "Hvernig þú berst hefur gefið mér\n"
    .string "mikið af gagnlegum gögnum.\p"
    .string "Kærar þakkir!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
    .string "Ég fékk bestu mögulegu menntun til\n"
    .string "að verða svona sterk.\p"
    .string "Ég vil ekki tapa fyrir neinum!$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
    .string "Takk fyrir. Mér líður eins og ég\n"
    .string "hafi verið frelsaður með því að tapa\p"
    .string "fyrir þér.$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
    .string "Af einhverjum ástæðum verð ég\n"
    .string "brjálaður yfir minnsta hlut.\p"
    .string "Ég mun róa mig með því að anda\n"
    .string "djúpt.$"

SevenIsland_SevaultCanyon_Text_LexIntro::
    .string "LEX: Elskan mín NYA, saman gætum við\n"
    .string "unnið!$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
    .string "LEX: Ég virðist hafa verið of\n"
    .string "áhyggjulaus…$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
    .string "LEX: Ég held að þetta hafi verið góð\n"
    .string "upplifun fyrir NYA.\p"
    .string "Ég þakka þér.$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
    .string "LEX: Má ég biðja þig um að berjast\n"
    .string "við okkur bæði í einu?$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
    .string "NYA: Ég mun gera mitt besta svo ég\n"
    .string "dragi ekki niður leiðbeinanda minn,\p"
    .string "LEX!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
    .string "NYA: Ó, nei… Fyrirgefðu, ég…$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
    .string "NYA: Ég held að ég þurfi miklu meiri\n"
    .string "reynslu og kennslu hjá LEX…\p"
    .string "…Svo, LEX, má ég vera áfram hjá þér\n"
    .string "svona?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
    .string "NYA: Fyrirgefðu, en megum við\n"
    .string "berjast í tveggja á móti tveimur\p"
    .string "stíl?$"

SevenIsland_SevaultCanyon_Text_RouteSign::
    .string "SEVAULT CANYON TANOBY RUINS\n"
    .string "FRAMUNDAN$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
    .string "Að æfa einn er vissulega ekki slæmt.\p"
    .string "En það er heldur ekki slæmt að\n"
    .string "stefna á toppinn með félaga.\p"
    .string "Jafnvel BRUNO… Hann æfði einu sinni\n"
    .string "með manni að nafni BRAWLY.$"
