OneIsland_Text_BillLetsGoSeeCelio::
    .string "BILL: Hér erum við! Þetta er ONE\n"
    .string "EYJA.\p"
    .string "Það eru nokkrar eyjar hér í kring og\n"
    .string "þetta er ein þeirra.\p"
    .string "Vinur minn CELIO sendi bátinn til að\n"
    .string "sækja mig hingað.\p"
    .string "Hann sér einn um tölvunet eyjunnar.\p"
    .string "…Af hverju er ég að segja þér þetta\n"
    .string "núna? Við skulum fara að hitta hann.$"

Text_WhereDoYouWantToSail::
    .string "Halló, þarna! Hvert viltu sigla?$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "Hér erum við á eyju í miðri algjörri\n"
    .string "óbyggð.\p"
    .string "Við erum heppin að hafa svona\n"
    .string "traustan ungan mann eins og CELIO\p"
    .string "hér.\p"
    .string "Barnabarnið mitt varð alveg uppnumið\n"
    .string "yfir vini CELIO.\p"
    .string "Eitthvað um frægan SKRÍMSLASJÚKAN?\p"
    .string "Ég veit ekki alveg hvað það þýðir,\n"
    .string "en CELIO er aldeilis maður!$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "Barnabarn mitt var í uppnámi yfir\n"
    .string "nýrri byltingu.\p"
    .string "Hún sagði að við höfum nú\n"
    .string "tölvutengingu við fólk í KANTO.\p"
    .string "Ég er ekki viss hvað það þýðir, en\n"
    .string "CELIO er mikill maður!$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "Barnabarn mitt var í uppnámi yfir\n"
    .string "nýrri byltingu.\p"
    .string "Hún sagði að við höfum loksins\n"
    .string "tölvutengingu við fólk í HOENN.\p"
    .string "Ég er ekki viss hvað það þýðir, en\n"
    .string "CELIO er mikill maður.\p"
    .string "Hann myndi verða góður eiginmaður\n"
    .string "fyrir barnabarn mitt!$"

OneIsland_Text_IslandSign::
    .string "EINN EYJA Vinir safnast saman á\n"
    .string "Hnúta Eyju$"

OneIsland_Text_PokemonNetCenterSign::
    .string "Stækkum heim Vasaskrímsla!\n"
    .string "VASASKRÍMSLA NETSETUR$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "Hæ, ertu í skoðunarferð? Er ekki\n"
    .string "hlýja loftslagið hér frábært?$"

