LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Trúir þú á drauga?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Í alvöru? Þá eru til þeir sem trúa…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, ég held ekki.\p"
    .string "Þessi hvíta hönd á öxlinni þinni… Ég\n"
    .string "er bara að ímynda mér hana.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "Þessi bær er þekktur sem\ngrafreitur\n"
    .string "Vasaskrímsla.\n\nMinningarathafnir\p"
    .string "eru haldnar í\nVASASKRÍMSLA TURNI.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Draugar birtust í Vasaskrímsla\n"
    .string "TOWER.\p"
    .string "Ég held að þeir séu andar\n"
    .string "Vasaskrímsla sem ROCKETS\p"
    .string "drápu.$"

LavenderTown_Text_TownSign::
    .string "LAVENDER BORG Hin göfuga fjólubláa\n"
    .string "borg$"

LavenderTown_Text_SilphScopeNotice::
    .string "Nýtt SILPH SCOPE! Gerðu hið\n"
    .string "ósýnilega sýnilegt!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER VOLUNTEER Vasaskrímsli\n"
    .string "HOUSE$"

LavenderTown_Text_PokemonTowerSign::
    .string "Vasaskrímsla TOWER Sefar anda\n"
    .string "Vasaskrímsla$"

