PokemonMansion_Text_PressSecretSwitchJP::
    .string "Leynirofi!\p"
    .string "Ýta á hann?$"

PokemonMansion_Text_LetsTryIt::
    .string "Prófum það! ...Smell!$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "Hættir við að ýta á rofann.$"

PokemonMansion_1F_Text_SimonIntro::
    .string "Þessi staður er, sko, risastór!$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "Aí!$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "Ég velti fyrir mér hvert félagi minn\n"
    .string "fór.$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "Leiðbeinandi minn bjó einu sinni\n"
    .string "hér.$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "Úff! Yfirþyrmandi!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "Svo þú ert fastur? Prófaðu að\n"
    .string "stökkva niður þarna!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "Dagbók: 6. feb. MÝTA fæddi af sér.\p"
    .string "Við nefndum nýburann TVÍMÝTU.$"

