LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "ROCKET-GENGIÐ gerir hvað sem er\n"
    .string "fyrir peninga!\p"
    .string "Engin vinna er of skítug, enginn\n"
    .string "verknaður of hræðilegur, enginn\p"
    .string "glæpur of illur!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "Ég sá móður BEINFARA reyna að flýja\n"
    .string "frá ROCKET-GENGINU.\p"
    .string "Hún var drepin þegar hún reyndi að\n"
    .string "komast undan…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "Þú veist hvernig BEINFARI tegundin\n"
    .string "ber hauskúpur, ekki satt?\p"
    .string "Fólk mun borga mikið fyrir eina.$"

