Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "Hæ! Manstu eftir mér? Ég er einn af\n"
    .string "AÐSTOÐARMÖNNUM Prófessor EIK.\p"
    .string "Ef VasaDEX-ið þitt er með full gögn\n"
    .string "um tíu tegundir á ég að gefa þér\p"
    .string "verðlaun.\p"
    .string "Prófessor EIK fól mér HM05 handa\n"
    .string "þér.\p"
    .string "Svo, {PLAYER}, leyfðu mér að spyrja.\p"
    .string "Hefurðu safnað gögnum um að minnsta\n"
    .string "kosti tíu gerðir vasaskrímsla?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "Frábært! Þú hefur náð eða átt\n"
    .string "{STR_VAR_3} gerðir vasaskrímsla!\p"
    .string "Til hamingju! Gjörðu svo vel!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER} fékk HM05 frá\n"
    .string "AÐSTOÐARMANNINUM.$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "HM05 inniheldur földu hreyfinguna\n"
    .string "LEIFTUR.\p"
    .string "LEIFTUR lýsir upp jafnvel dimmustu\n"
    .string "hella og dýflissur.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "Þegar vasaskrímsli lærir LEIFTUR\n"
    .string "kemstu í gegnum ROCK TUNNEL.$"

