Route17_Text_RaulIntro::
    .string "Það græðist ekkert hratt á því að\n"
    .string "berjast við krakka.$"

Route17_Text_RaulDefeat::
    .string "Brenndur út!$"

Route17_Text_RaulPostBattle::
    .string "Þú getur fundið góða hluti liggjandi\n"
    .string "á HJÓLAVEGINUM.\p"
    .string "Það eru góðir peningar í að hirða þá\n"
    .string "og selja.$"

Route17_Text_IsaiahIntro::
    .string "Ég er ótrúlega stoltur af kroppnum\n"
    .string "mínum, krakki. Komdu!$"

Route17_Text_IsaiahDefeat::
    .string "Hú!$"

Route17_Text_IsaiahPostBattle::
    .string "Ég gæti magaskellt þér héðan út!$"

Route17_Text_VirgilIntro::
    .string "Ertu á leið til FUCHSIA?$"

Route17_Text_VirgilDefeat::
    .string "Krass og bruni!$"

Route17_Text_VirgilPostBattle::
    .string "Ég elska að keppa niður brekkur!$"

Route17_Text_BillyIntro::
    .string "Við erum MÓTORHJÓLAMENN! Við ráðum\n"
    .string "vegunum, maður!$"

Route17_Text_BillyDefeat::
    .string "Reyktur!$"

Route17_Text_BillyPostBattle::
    .string "Ertu að leita að ævintýrum?$"

Route17_Text_NikolasIntro::
    .string "Láttu STUÐBOLTA rafmagna þig!$"

Route17_Text_NikolasDefeat::
    .string "Jarðtengdur!$"

Route17_Text_NikolasPostBattle::
    .string "Ég fékk STUÐBOLTANN minn í yfirgefna\n"
    .string "ORKUVERINU.$"

Route17_Text_ZeekIntro::
    .string "Ég hækkaði stigið á vasaskrímslinu\n"
    .string "mínu, en það þróast ekki. Af hverju?$"

Route17_Text_ZeekDefeat::
    .string "Af hverju, þú!$"

Route17_Text_ZeekPostBattle::
    .string "Kannski þurfa sum vasaskrímsli\n"
    .string "frumsteina til að þróast.$"

Route17_Text_JamalIntro::
    .string "Ég þarf smá hreyfingu!$"

Route17_Text_JamalDefeat::
    .string "Úff! Góð æfing!$"

Route17_Text_JamalPostBattle::
    .string "Ég er viss um að ég léttist þarna!$"

Route17_Text_CoreyIntro::
    .string "Vertu uppreisnarmaður!$"

Route17_Text_CoreyDefeat::
    .string "Aaaaargh!$"

Route17_Text_CoreyPostBattle::
    .string "Vertu tilbúinn að berjast fyrir\n"
    .string "sannfæringu þinni!$"

Route17_Text_JaxonIntro::
    .string "Flott HJÓL! Hvernig stýrist það?$"

Route17_Text_JaxonDefeat::
    .string "Skot!$"

Route17_Text_JaxonPostBattle::
    .string "Hallinn gerir erfitt að stýra.$"

Route17_Text_WilliamIntro::
    .string "Láttu þig hverfa, krakki! Ég er\n"
    .string "örmagna!$"

Route17_Text_WilliamDefeat::
    .string "Ertu ánægður?$"

Route17_Text_WilliamPostBattle::
    .string "Ég þarf að leggja mig!$"

Route17_Text_WatchOutForDiscardedItems::
    .string "Þetta er tilkynning.\p"
    .string "Varist hluti sem hefur verið hent.$"

Route17_Text_SameSpeciesGrowDifferentRates::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Öll vasaskrímsli eru einstök.\p"
    .string "Jafnvel vasaskrímsli af sömu tegund\n"
    .string "og sama stigi vaxa mishratt.$"

Route17_Text_PressBToStayInPlace::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Ýttu á B hnappinn til að vera kyrr á\n"
    .string "hallandi leið.$"

Route17_Text_RouteSign::
    .string "LEIÐ 17 CELADON BORG - FUCHSIA BORG$"

Route17_Text_DontThrowGameThrowBalls::
    .string "Þetta er tilkynning!\p"
    .string "Ekki kasta leiknum frá þér, kastaðu\n"
    .string "VASA BOLTUM í staðinn!$"

Route17_Text_CyclingRoadSign::
    .string "HJÓLAVEGURINN Hallinn endar hér!$"
