Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Ég rek DAGVISTINA.\p"
	.string "Viltu að ég ali upp eitt af\n"
	.string "vasaskrímslunum þínum?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Komdu aftur.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "Hvaða vasaskrímsli á ég að ala upp?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Gott. Komdu hvenær sem þú vilt.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Gott, ég lít eftir {STR_VAR_1} um\n"
	.string "stund.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Komdu að hitta mig eftir smástund.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "Ertu strax aftur hér?\p"
	.string "{STR_VAR_1} þarf að eyða meiri tíma\n"
	.string "hjá mér.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "Þú skuldar mér ¥{STR_VAR_2} fyrir að\n"
	.string "fá þetta vasaskrímsli til baka.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "Takk fyrir! Hér er vasaskrímslið\n"
	.string "þitt.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} fékk {STR_VAR_1} aftur frá\n"
	.string "DAGVISTARMANNINUM.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Ó? Þú ert bara með eitt vasaskrímsli\n"
	.string "með þér.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "Ef þú skilur það vasaskrímsli eftir\n"
	.string "hjá mér, með hverju ætlarðu að\p"
	.string "berjast?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "{STR_VAR_1} hefur vaxið mikið. Já,\n"
	.string "mjög mikið, myndi ég segja.\p"
	.string "Láttu mig sjá... Stigalega hefur það\n"
	.string "hækkað um {STR_VAR_2}.\p"
	.string "Er ég ekki frábær?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "Þú getur ekki tekið þetta\n"
	.string "vasaskrímsli til baka ef þú hefur\p"
	.string "ekkert pláss fyrir það.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "Þú átt ekki nógan pening.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
    .string "きみの みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
    .string "わるいけど ひでんのわざを もった ポケモンは あずかれないなぁ$"
