SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
    .string "Kyahaha! Ég feyki þér auðveldlega\n"
    .string "burt!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
    .string "Tsk! Þú ert of sterk/ur!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
    .string "Hvað? Haga ég mér ekki eins og ég\n"
    .string "lít út?\p"
    .string "Heh, það er hluti af aðferðinni\n"
    .string "minni!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
    .string "Sæl/l! Ertu í aðdáendaklúbbnum\n"
    .string "mínum?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
    .string "Ó, svo þú ert ekki aðdáandi…\p"
    .string "Jæja, ég get breytt því. Leyfðu mér\n"
    .string "að syngja fyrir þig!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
    .string "Lalalah… Vasaskrímslin mín, ég sendi\n"
    .string "þau út, allar stelpurnar æpa og\p"
    .string "hrópa!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
    .string "Þessi eyja er svo víðfeðm… Það er\n"
    .string "ekki auðvelt að vakta svæðið.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
    .string "Uh-huh...$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
    .string "ÞJÁLFARAR eins og þú úr borgum eru\n"
    .string "greinilega sterkir.\p"
    .string "Þú ert á leið í TURNINN, er það\n"
    .string "ekki?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
    .string "I punish people who abuse\n"
    .string "Vasaskrímsli!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
    .string "Þú virðist ekki vera\n"
    .string "vandræða-ÞJÁLFARI.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
    .string "Ef þú kemur vel fram við\n"
    .string "Vasaskrímslin þín skilja þau þig.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
    .string "EVE: Ég mun taka höndum saman með\n"
    .string "JON og berjast saman.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
    .string "EVE: Ég og JON töpuðum. Ehehe.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
    .string "EVE: Ég ætla að vinna harðar með\n"
    .string "JON.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
    .string "EVE: Ég vil vera í liði með JON\n"
    .string "þegar ég berst við þig.\p"
    .string "Komdu aftur með tvö Vasaskrímsli,\n"
    .string "allt í lagi?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
    .string "JON: Þegar ég er með EVE, finnst mér\n"
    .string "eins og við gætum aldrei tapað.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
    .string "JON: Þegar ég er með EVE finni ég\n"
    .string "ekki fyrir tapi!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
    .string "JON: Þegar ég er með EVE verð ég\n"
    .string "ringlaður hvort sem ég vinn eða\p"
    .string "tapa.\p"
    .string "Það er töfrum líkast!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
    .string "JON: Ef EVE er með, berst ég glaður\n"
    .string "við þig.\p"
    .string "Því vil ég hafa þetta tveir gegn\n"
    .string "tveimur, ef má.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
    .string "INNGANGUR AÐ SEVAULT CANYON\p"
    .string "ÞJÁLFARAR eru beðnir um að forðast\n"
    .string "að skemma plöntur í CANYON.$"

