Route12_Text_MonSprawledOutInSlumber::
    .string "Vasaskrímsli liggur þarna í djúpum\n"
    .string "og þægilegum svefni.$"

Text_SnorlaxWokeUp::
    .string "HROTÞURS vaknaði!\n\nÞað réðst á í\n"
    .string "fýlukasti!$"

Text_SnorlaxReturnedToMountains::
    .string "HROTÞURS róaðist. Það geispaði\n"
    .string "rækilega… og sneri aftur til fjalla.$"

Text_WantToUsePokeFlute::
    .string "Viltu nota VASaFLAUTUNA?$"

Text_PlayedPokeFlute::
    .string "{PLAYER} spilaði VASaFLAUTUNA.$"

Route12_Text_NedIntro::
    .string "Já! Ég fékk bit hér!$"

Route12_Text_NedDefeat::
    .string "Tch! Just a small fry…$"

Route12_Text_NedPostBattle::
    .string "Bíddu! Línan mín er föst!$"

Route12_Text_ChipIntro::
    .string "Vertu þolinmóður. Veiðar eru bið\n"
    .string "leikur.$"

Route12_Text_ChipDefeat::
    .string "Sá slapp!$"

Route12_Text_ChipPostBattle::
    .string "Með betri STÖNG gæti ég veitt betri\n"
    .string "Vasaskrímsli…$"

Route12_Text_JustinIntro::
    .string "Ég er að leita að TUNGLSTEINI.\n"
    .string "Hefurðu fundið einn?$"

Route12_Text_JustinDefeat::
    .string "Ái!$"

Route12_Text_JustinPostBattle::
    .string "Ég hefði getað látið Vasaskrímslið\n"
    .string "mitt þróast með TUNGLSTEINI.\p"
    .string "Þá hefði ég unnið, ég veðja á það.$"

Route12_Text_LucaIntro::
    .string "Rafmagn er mín sérgrein.\n\nÉg veit\n"
    .string "samt ekkert um\nsjávar-Vasaskrímsli.$"

Route12_Text_LucaDefeat::
    .string "Tengillinn úr!$"

Route12_Text_LucaPostBattle::
    .string "Vatn leiðir rafmagn, svo þú ættir að\n"
    .string "rafsjokka sjávar-Vasaskrímsli.$"

Route12_Text_HankIntro::
    .string "VEIÐI FÍFLIÐ gegn Vasaskrímsla\n"
    .string "KRAKKA!$"

Route12_Text_HankDefeat::
    .string "Of mikið!$"

Route12_Text_HankPostBattle::
    .string "Ég held að maður verði góður í því\n"
    .string "sem manni líkar.\p"
    .string "Þú vannst mig í Vasaskrímslum, en þú\n"
    .string "slærð mig ekki út í veiði.$"

Route12_Text_ElliotIntro::
    .string "Ég elska að veiða, misskiljið mig\n"
    .string "ekki.\p"
    .string "En það væri best ef ég hefði líka\n"
    .string "meiri vinnu.$"

Route12_Text_ElliotDefeat::
    .string "Það er ekki auðvelt…$"

Route12_Text_ElliotPostBattle::
    .string "Það er allt í lagi. Að tapa truflar\n"
    .string "mig ekki lengur.$"

Route12_Text_AndrewIntro::
    .string "Hvað er að veiðast?\p"
    .string "Þú veist aldrei hvað þú gætir veitt!$"

Route12_Text_AndrewDefeat::
    .string "Missti það!$"

Route12_Text_AndrewPostBattle::
    .string "Hvað, GREYSLEPPA?\p"
    .string "Ég veiði þá alltaf, jú. En, vá hvað\n"
    .string "þeir eru veikir.$"

Route12_Text_RouteSign::
    .string "LEIÐ 12 Norður til LAVENDER$"

Route12_Text_SportfishingArea::
    .string "SPORTVEIÐISVÆÐI$"

Route12_Text_JesIntro::
    .string "JES: Ef ég vinn, ætla ég að biðja\n"
    .string "GIA.$"

Route12_Text_JesDefeat::
    .string "JES: Ó, vinsamlegast, af hverju\n"
    .string "gátuð þið ekki látið okkur vinna?$"

Route12_Text_JesPostBattle::
    .string "JES: Ó, GIA, fyrirgefðu mér, ástin\n"
    .string "mín!$"

Route12_Text_JesNotEnoughMons::
    .string "JES: GIA og ég verðum saman að\n"
    .string "eilífu.\p"
    .string "Við berjumst ekki nema þú eigir tvö\n"
    .string "Vasaskrímsli sjálfur.$"

Route12_Text_GiaIntro::
    .string "GIA: Hæ, JES…\p"
    .string "Ef við vinnum, giftist ég þér!$"

Route12_Text_GiaDefeat::
    .string "GIA: Ó, en af hverju?$"

Route12_Text_GiaPostBattle::
    .string "GIA: JES, þú vitleysingur! Þú\n"
    .string "eyðilagðir þetta!$"

Route12_Text_GiaNotEnoughMons::
    .string "GIA: Ég þoli ekki að berjast án JES\n"
    .string "míns!\p"
    .string "Áttu ekki eitt Vasaskrímsli í\n"
    .string "viðbót?$"
