SaffronCity_Gym_Text_SabrinaIntro::
    .string "Ég sá fyrir mér komu þína.\p"
    .string "Ég hef haft sálræna krafta síðan ég\n"
    .string "var barn.\p"
    .string "Það byrjaði þegar skeið sem ég\n"
    .string "kastaði áhugalaust, beygðist.\p"
    .string "Mér líkar ekki að berjast, en ef þú\n"
    .string "vilt, mun ég sýna þér mína\p"
    .string "krafta!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "Þetta tap kemur mér á óvart! En tap\n"
    .string "er tap.\p"
    .string "Ég viðurkenni að ég lagði ekki nógu\n"
    .string "hart að mér til að vinna.\p"
    .string "Sigur þinn hefur fært þér\n"
    .string "MARSHBADGE.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Sálrænn kraftur er ekki eitthvað sem\n"
    .string "aðeins fáir hafa.\p"
    .string "Allir hafa sálrænan kraft. Fólk\n"
    .string "gerir sér bara ekki grein fyrir því.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "MARSHMERKIÐ fær Vasaskrímsli upp að\n"
    .string "Lv. 70 til að hlýða þér.\p"
    .string "Sterkari Vasaskrímsli verða villtari\n"
    .string "og hunsa skipanir þínar í bardaga.\p"
    .string "Ekki þjálfa Vasaskrímslin þín of\n"
    .string "mikið ef þú vilt forðast það.\p"
    .string "Bíddu, taktu þessa TM með þér.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} fékk TM04 frá SABRINA.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "TM04 er RÓLEGUR HUGUR.\p"
    .string "Hún fær Vasaskrímslið til að\n"
    .string "einbeita sér og hækka bæði SP. ATK\p"
    .string "og SP. DEF.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "TASKAN þín er full af öðrum hlutum.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "SABRINA er miklu yngri en ég, en hún\n"
    .string "hefur unnið sér inn virðingu mína.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "Ekki nógu gott!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "Í jafnri baráttu vinnur sá sem hefur\n"
    .string "sterkari vilja.\p"
    .string "Ef þú vilt sigra SABRINA, einbeittu\n"
    .string "þér og viljaðu þér til sigurs.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Hræðir óséður kraftur okkar þig?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "Ég sá þetta aldrei fyrir!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "HUGAR Vasaskrímsli óttast aðeins\n"
    .string "drauga og skordýr!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "Vasaskrímsli taka á sig svip\n"
    .string "ÞJÁLFARA sinna.\p"
    .string "Vasaskrímslin þín hljóta þá að vera\n"
    .string "hörð!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "Ég vissi það!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "Ég á enn margt ólært…\p"
    .string "Ég verð að ná tökum á HUGAR og kenna\n"
    .string "Vasaskrímslunum mínum það…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "Þú skilur það, er það ekki?\p"
    .string "Afl eitt og sér dugir ekki til að\n"
    .string "sigra í heimi Vasaskrímsla.$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "Ég trúi þessu ekki!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "SABRINA sigraði KARATE MEISTARANN\n"
    .string "við hliðina.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "Þú og ég, Vasaskrímslin okkar munu\n"
    .string "berjast!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "Ég tapaði eftir allt saman!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "Ég vissi að þetta myndi gerast.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA er ung, en hún er líka okkar\n"
    .string "hátt hæfi LEIÐTOGI.\p"
    .string "Þú nærð henni ekki auðveldlega!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Úff! Niður og úti!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "Áður voru tveir Vasaskrímsla\n"
    .string "SALIR í SAFFRON.\p"
    .string "BARDAGADÓJÓIÐ í næsta húsi missti\n"
    .string "þó SALAR-stöðu sína.\p"
    .string "Við gjörsigruðum þau þegar ákveðið\n"
    .string "var að hafa bara einn SAL.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "VASaSKRÍMSLASALURINN í SAFFRON er\n"
    .string "frægur fyrir að þjálfa skyggna\p"
    .string "ÞJÁLFARA.\p"
    .string "Þú vilt sjá SABRINA, er það ekki? Ég\n"
    .string "finn það!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "Það er rétt! Ég notaði\n"
    .string "hugsanaflutning til að lesa hugsanir\p"
    .string "þínar!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "Yo! Tilvonandi meistari!\p"
    .string "Vasaskrímsli SABRINU nota hugarkraft\n"
    .string "í stað líkamlegs afls.\p"
    .string "BARDAGA Vasaskrímsli eru sérstaklega\n"
    .string "veik gegn SÁLAR Vasaskrímslum.\p"
    .string "Þau verða sigruð áður en þau ná einu\n"
    .string "sinni að miða höggi!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "Sálrænn kraftur, ha?\p"
    .string "Ef ég hefði það, myndi ég græða\n"
    .string "helling á spilakössunum!$"

SaffronCity_Gym_Text_GymStatue::
    .string "SAFFRON VASaSKRÍMSLASALUR LEIÐTOGI:\n"
    .string "SABRINA\p"
    .string "SIGURÞJÁLFARAR: {RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "SAFFRON VASaSKRÍMSLASALUR LEIÐTOGI:\n"
    .string "SABRINA\p"
    .string "SIGURÞJÁLFARAR: {RIVAL}, {PLAYER}$"
