PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "Skuggalegur karl plataði mig til að\n"
    .string "kaupa þetta skrýtna\p"
    .string "fiskavasaskrímsli!\p"
    .string "Það er algjörlega máttlaust og\n"
    .string "kostaði ¥500!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "Góðir hlutir geta gerst ef þú elur\n"
    .string "vasaskrímsli vandlega.\p"
    .string "Jafnvel veikburða geta komið á óvart\n"
    .string "ef þú gefst ekki upp á þeim.$"

