PokemonTower_6F_Text_AngelicaIntro::
    .string "Give…me… blood…$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "Stynj!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "Mér líður blóðlítil og veik…$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Urff… Kwaah!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "Eitthvað datt út!$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "Hárið mitt féll ekki af! Það var\n"
    .string "illgjarn andi!$"

PokemonTower_6F_Text_JenniferIntro::
    .string "Ke…ke…ke… ke…ke…ke!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "Kí!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "Hvað er að gerast hér?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "Be gone… Intruders…$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "Draugurinn var órólegur andi móður\n"
    .string "BEINFARI!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "Andi móðurinnar var róaður.\p"
    .string "Hann fór til framhaldslífsins…$"

