VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "Það er til illt fólk sem notar\n"
    .string "vasaskrímsli í glæpsamlegum verkum.\p"
    .string "ROCKET-GENGIÐ verslar til dæmis með\n"
    .string "sjaldgæf vasaskrímsli.\p"
    .string "Þau yfirgefa líka vasaskrímsli sem\n"
    .string "þeim finnst óvinsæl eða gagnslaus.\p"
    .string "Svona hræðilegt fólk eru þau,\n"
    .string "ROCKET-GENGIÐ.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "Ég held að vasaskrímsli geti verið\n"
    .string "góð eða slæm. Það fer eftir\p"
    .string "ÞJÁLFARANUM.$"

