Text_ExplosionTeach::
    .string "Geturðu ímyndað þér? Ef þetta\n"
    .string "eldfjall myndi gjósa?\p"
    .string "Sprengingin myndi verða endirinn á\n"
    .string "okkur. Hversu hræðilegt er það?\p"
    .string "Meðan við erum skelfingu lostin,\n"
    .string "viltu að ég kenni þér SPRENGINGU?$"

Text_ExplosionDeclined::
    .string "Já, þú hefur rétt fyrir þér. Það er\n"
    .string "of hræðilegt.$"

Text_ExplosionWhichMon::
    .string "Þú ert hrikalega hugrakkur!\p"
    .string "Hvaða Vasaskrímsli á ég að kenna\n"
    .string "EXPLOSION?$"

Text_ExplosionTaught::
    .string "Að nota SPRENGINGU á þessu\n"
    .string "eldfjalli…\p"
    .string "Þvílík skelfileg spenna!$"

@ Below 4 are unused JP versions of the above texts
Text_ExplosionTeachJP::
    .string "こ この かざんが もし だいばくはつ したら お おれら ひとたまりも\n"
    .string "ないなあ ‥ブルブル！\p"
    .string "こ こわい ついでに だいばくはつ でも おぼえてみる？$"

Text_ExplosionDeclinedJP::
    .string "や やっぱ こわいもんな ブルブル$"

Text_ExplosionWhichMonJP::
    .string "つ つよきだね！ じゃあ どの ポケモンに する？$"

Text_ExplosionTaughtJP::
    .string "かざんで だいばくはつを‥ す すごい スリル！$"

MtEmber_Exterior_Text_WellTryDiggingHere::
    .string "Hérna. Við reynum að grafa hér.\p"
    .string "Þessi fjársjóður sem STJÓRNENDURNIR\n"
    .string "hafa verið að tala um ætti að vera\p"
    .string "hér.$"

MtEmber_Exterior_Text_YoureInTheWayGetLost::
    .string "Hvað í…? Þú ert fyrir. Farðu.$"

MtEmber_Exterior_Text_PunchedThroughAtLast::
    .string "Púff, loksins komist í gegn. Förum í\n"
    .string "fjársjóðsleit!$"

MtEmber_Exterior_Text_WhatsPasswordAgain::
    .string "Allan fjársjóð sem við finnum förum\n"
    .string "við með aftur í VÖRUHÚSIÐ, skilið?\p"
    .string "…Ó, og hver eru lykilorðin? Ég meina\n"
    .string "að ROCKET WAREHOUSE.$"

MtEmber_Exterior_Text_FirstPasswordGoldeen::
    .string "Hvað, gleymdirðu lykilorðinu? Þau\n"
    .string "eru reyndar tvö.\p"
    .string "Það fyrra er 'BLEIKHYRNA þarf\n"
    .string "staur.'\p"
    .string "Og það seinna er…$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn::
    .string "Hey! Þessi njósnari hefur verið að\n"
    .string "hlusta!$"

MtEmber_Exterior_Text_Grunt1Intro::
    .string "Þú hefur verið að hlera okkur, er\n"
    .string "það ekki?$"

MtEmber_Exterior_Text_Grunt1Defeat::
    .string "Ha, hvað?$"

MtEmber_Exterior_Text_Grunt1PostBattle::
    .string "Af hverju þurftirðu að vinna?$"

MtEmber_Exterior_Text_Grunt2Intro::
    .string "Að reyna að troða þér inn á\n"
    .string "fjársjóðinn okkar? Ekki veðja á það!$"

MtEmber_Exterior_Text_Grunt2Defeat::
    .string "Bíddu! En hvernig?$"

MtEmber_Exterior_Text_Grunt2PostBattle::
    .string "Fáðu minnisleysi á þægilegan hátt og\n"
    .string "gleymdu öllu sem þú heyrðir!$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere::
    .string "Þvílíkt áfall… Við þurfum að\n"
    .string "endurhópa okkur.\p"
    .string "Þú! Ekki láta þér detta í hug að\n"
    .string "stíga fæti hér inn!\p"
    .string "Ef þú veist hvað þér er fyrir bestu,\n"
    .string "ekki einu sinni hugsa um það!$"

MtEmber_Exterior_Text_LoganIntro::
    .string "Virkt eldfjall er eitt sem er að\n"
    .string "gjósa, eða er að fara að gjósa.$"

MtEmber_Exterior_Text_LoganDefeat::
    .string "Úff… Þetta var heitt! Svitinn gýs út\n"
    .string "úr mér!$"

MtEmber_Exterior_Text_LoganPostBattle::
    .string "Þeir segja að það séu yfir 1.500\n"
    .string "virk eldfjöll í heiminum.\p"
    .string "Bara að hugsa um þau lætur mig finna\n"
    .string "fyrir hita og klístri innra með mér!$"

MtEmber_Exterior_Text_BethIntro::
    .string "Veistu hvernig hellar myndast inni í\n"
    .string "eldfjöllum?$"

MtEmber_Exterior_Text_BethDefeat::
    .string "Atchah! Þú ert ótrúlega góður!$"

MtEmber_Exterior_Text_BethPostBattle::
    .string "Þegar hraun á yfirborði kviku\n"
    .string "herðist, og kvikan inni flæðir\p"
    .string "út, verða eftir hellar.$"

MtEmber_Exterior_Text_JocelynIntro::
    .string "Ég hef verið í þjálfun svo ég geti\n"
    .string "lagað brotið hjarta mitt…\p"
    .string "Það styrkti mig líkamlega að minnsta\n"
    .string "kosti! Hi-yah!$"

MtEmber_Exterior_Text_JocelynDefeat::
    .string "Ég held að ég hafi reynt að ofgera\n"
    .string "mér…$"

MtEmber_Exterior_Text_JocelynPostBattle::
    .string "Bardagastíllinn þinn minnir mig á\n"
    .string "gaurnum sem henti mér…$"
