SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "Þú veist hvað sagt er um sjómenn og\n"
    .string "bardaga!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "Rétt! Góður bardagi, félagi!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "Hahaha! Viltu verða sjómaður,\n"
    .string "félagi?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "Komdu þá! Sjómaðurstolt mitt er í\n"
    .string "húfi!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "Andinn þinn sökkti mér!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "Sástu VEIÐIMEISTARANN í VERMILION\n"
    .string "BORG?$"

