SixIsland_Text_IslandSign::
    .string "SJÖTTA EYJA Eyja fornrar visku$"

SixIsland_Text_ThatWayToWaterPathRuinValley::
    .string "Haltu áfram þessa leið og þú kemst á\n"
    .string "VATNALEIÐINA.\p"
    .string "Fylgdu henni og þú kemst í\n"
    .string "RÚNADALINN.$"

SixIsland_Text_SkyAtNightIsFantastic::
    .string "Þegar þú ert svona langt frá\n"
    .string "borginni, er himinninn á nóttunni\p"
    .string "frábær.$"

