Text_RockSlideTeach::
    .string "Þegar þú ert uppi á grýttu fjalli\n"
    .string "eins og þessu eru grjóthrun\p"
    .string "hættuleg.\p"
    .string "Geturðu ímyndað þér það? Stórgrýti\n"
    .string "veltandi niður á þig?\p"
    .string "Það væri svona, vááááááááá! Algjör\n"
    .string "hryllingur!\p"
    .string "Þú virðist ekki hræddur. Viltu prófa\n"
    .string "að nota GRJÓTHRUN?$"

Text_RockSlideDeclined::
    .string "Ó, svo þú ert hræddur eftir allt.$"

Text_RockSlideWhichMon::
    .string "Hvaða vasaskrímsli á ég að kenna\n"
    .string "GRJÓTHRUN?$"

Text_RockSlideTaught::
    .string "Það gæti verið ógnvekjandi að nota\n"
    .string "það í þessum göngum...$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "Vísbending: Stórgrýti gæti breytt\n"
    .string "vatnsrennsli.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "HÆTTA Stríður straumur!$"

