CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "Ég? Ég er forritarinn!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "Ég er grafíski hönnuðurinn! Ég\n"
    .string "teiknaði þig!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "Ég skrifaði söguna! Er Erika ekki\n"
    .string "sæt?\p"
    .string "Ég held líka mikið upp á MISTY! Ó,\n"
    .string "og SABRINA, mér líkar vel við hana!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "Er það rétt?\p"
    .string "Ég er leikjahönnuðurinn!\p"
    .string "Að fylla VASASKRÍMSLABÓKINA\n"
    .string "(VasaDEX) er erfitt, en ekki gefast\p"
    .string "upp!\p"
    .string "Þegar þú ert búinn, komdu og segðu\n"
    .string "mér frá því!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "Vá! Framúrskarandi! Þú kláraðir\n"
    .string "VASASKRÍMSLABÓKINA þína! Til\p"
    .string "hamingju! …$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "Þetta er leikjafasinn! Að fikta í\n"
    .string "honum gæti eyðilagt leikinn!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "Einhver er að spila leik í stað þess\n"
    .string "að vinna!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "Þetta er handritið! Betra að kíkja\n"
    .string "ekki á endinn!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "GAME FREAK Þróunarherbergi$"

