CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "Hér fást tölfræðibætar fyrir\n"
    .string "vasaskrímsli, eingöngu á þessum\p"
    .string "stað.\p"
    .string "HEILSUGJÖF eykur grunn-HP hjá\n"
    .string "vasaskrímsli.\p"
    .string "KALSÍUM hækkar grunn-SÉR. ÁRÁS\n"
    .string "tölfræði eins vasaskrímslis.\p"
    .string "SINK bætir grunn-SÉR. VÖRN\n"
    .string "eins vasaskrímslis.\p"
    .string "KOLEFNI eykur grunn-HRAÐA tölfræðina.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "Ég er hier til að kaupa tölfræðibæta\n"
    .string "fyrir vasaskrímsli.\p"
    .string "PRÓTEIN eykur grunn-ÁRÁSARKRAFT.\p"
    .string "JÁRN eykur grunn-VARNARTÖLFRÆÐI.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: LYFJABÚÐ$"
