CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "Hér fást tölfræðibætar fyrir\n"
    .string "vasaskrímsli, eingöngu á þessum\p"
    .string "stað.\p"
    .string "HP UP eykur grunn-HP hjá\n"
    .string "vasaskrímsli.\p"
    .string "CALCIUM hækkar grunn-SP. ATK\n"
    .string "tölfræði eins vasaskrímslis.\p"
    .string "ZINC bætir grunn-SP. DEF tölfræði\n"
    .string "eins vasaskrímslis.\p"
    .string "CARBOS eykur grunn-HRAÐA tölfræðina.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "Ég er hier til að kaupa tölfræðibæta\n"
    .string "fyrir vasaskrímsli.\p"
    .string "PROTEIN eykur grunn-ÁRÁSARKRAFT.\p"
    .string "IRON eykur grunn-VARNARTÖLFRÆÐI.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: LYFJABÚÐ$"

