SilphCo_7F_Text_HaveMonForSavingUs::
    .string "Ó! Hæ! Þú ert ekki ROCKET! Komstu\n"
    .string "til að bjarga okkur? Takk kærlega!\p"
    .string "Ég vil að þú fáir þetta Vasaskrímsli\n"
    .string "fyrir að bjarga okkur.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "{PLAYER} fékk LAGARGANDU frá\n"
    .string "starfsmanni SILPH!$"

SilphCo_7F_Text_ExplainLapras::
    .string "Þetta er LAGARGANDA. Hún er mjög\n"
    .string "gáfað Vasaskrímsli.\p"
    .string "Við höfðum hana í rannsóknarstofunni,\n"
    .string "en henni mun vegna betur hjá þér.\p"
    .string "Ég held að þú verðir góður ÞJÁLFARI\n"
    .string "fyrir LAGARGÖNDU!\p"
    .string "Hún syndir vel. Hún ferjar þig\n"
    .string "yfir vatn!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "FORINGI ROCKET-GENGISINS fór í\n"
    .string "stjórnarherbergið!\p"
    .string "Er FORSTJÓRINN okkar í lagi? Ég hef áhyggjur.$"

SilphCo_7F_Text_OhNo::
    .string "Æ… Ég get ekki borið meira.$"

SilphCo_7F_Text_SavedAtLast::
    .string "Loksins bjargað! Takk fyrir!$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "ROCKET-GENGIÐ var á eftir\n"
    .string "MEISTARABOLTA, sem fangar hvaða\p"
    .string "Vasaskrímsli sem er.$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "Við aflýstum MEISTARABOLTA-verkefninu\n"
    .string "vegna ROCKET-GENGISINS.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "Það væri slæmt ef ROCKET-GENGIÐ tæki\n"
    .string "yfir SILPH eða Vasaskrímslin okkar.$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "Wow!\p"
    .string "Þú hraktir ROCKET-GENGIÐ burt upp á\n"
    .string "eigin spýtur?$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "Þú! Það er mjög hættulegt hér!\p"
    .string "Komstu til að bjarga mér? Þú getur það ekki!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "Kærar þakkir!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "Ó-ó! Ég finn lykt af lítilli mús!$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "Ljósin slokknuðu!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "Þú finnur ekki FORINGJANN minn með\n"
    .string "því að þjóta bara um!$"

SilphCo_7F_Text_JoshuaIntro::
    .string "Heheh!\p"
    .string "Þú tókst mig fyrir starfsmann SILPH?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "Ég er búinn!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "Þrátt fyrir aldur þinn ertu fær\n"
    .string "ÞJÁLFARI!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "Ég er einn af fjórum\n"
    .string "ROCKET-BRÆÐRUM!$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "Aah! Bræður, ég tapaði!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "Skiptir engu. Bræður mínir munu\n"
    .string "endurgjalda greiðann!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "Barn sem braust inn? Það hlýtur að vera þú!$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "Jæja! Ég tapaði!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "Farðu heim áður en FORINGINN minn\n"
    .string "verður öskureiður!$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{RIVAL}: Hvað tafði þig, {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
    .string "{RIVAL}: Hahaha! Ég vissi að þú\n"
    .string "myndir birtast ef ég biði hér!\p"
    .string "ROCKET-GENGIÐ tafði þig víst!\n"
    .string "Ekki að mér sé sama!\p"
    .string "Ég sá þig í SAFFRON, svo ég ákvað\n"
    .string "að sjá hvort þú hefðir batnað!$"

SilphCo_7F_Text_RivalDefeat::
    .string "Ó, maður! Þá ræðurðu við\n"
    .string "ROCKET-FORINGJANN!$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}: Svona, {PLAYER}…\p"
    .string "Með svona getu ertu enn ekki\n"
    .string "fullgildur ÞJÁLFARI!$"

SilphCo_7F_Text_RivalPostBattle::
    .string "Jæja, {PLAYER}! Ég held áfram upp og\n"
    .string "áfram!\p"
    .string "Með því að skoða VasaDEX-ið mitt sé\n"
    .string "ég hvað er sterkt og hvernig þau\p"
    .string "þróast!\p"
    .string "Er ég snillingur eða hvað?\p"
    .string "Ég fer í VASASKRÍMSLADEILDINA\n"
    .string "til að sparka ELÍTUFERNINGNUM út.\p"
    .string "Ég verð öflugasti ÞJÁLFARI\n"
    .string "í heimi!\p"
    .string "{PLAYER}, jæja, gangi þér vel!\n"
    .string "Engar áhyggjur! Sé þig!$"

SilphCo_7F_Text_FloorSign::
    .string "SILPH CO. HÖFUÐSKRIFSTOFA 7H$"
