SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross::
    .string "Hera, hera, HORNUXI! Stór og\n"
    .string "skínandi, pöddustjórinn! Elska hann,\p"
    .string "þarf hann,\p"
    .string "HORNUXI!$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross::
    .string "Íííík! Þetta er HORNUXI!\p"
    .string "Má ég, má ég mæla hvað hann er stór?$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward::
    .string "Íííík, hann er {STR_VAR_2} tommur!\n"
    .string "Ég hef aldrei séð annað eins!\p"
    .string "Þú átt skilið verðlaun!$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne::
    .string "Ég vil sjá miklu, miklu stærri\n"
    .string "HORNUXA en þennan.\p"
    .string "Ó, hvað ég dái þá, stóru HORNUXANA!$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore::
    .string "Ha? Þessi {STR_VAR_2} tommu mæling…\n"
    .string "Ó, svei! Hún er sú sama og áður.$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest::
    .string "Ó, hann er bara {STR_VAR_2} tommur.\n"
    .string "Fyrri HORNUXI var stærri.\p"
    .string "Hann var {STR_VAR_3} tommur, stærsti\n"
    .string "HORNUXI sem þú færðir mér.$"

SixIsland_WaterPath_House1_Text_ThisWontDo::
    .string "Ó nei! Þetta gengur ekki!\p"
    .string "HORNUXI er miklu karlmannlegri og\n"
    .string "flottari, með yndislegt horn!$"

SixIsland_WaterPath_House1_Text_YourBagIsFull::
    .string "TASKAN þín er full. Verðlaunin mín\n"
    .string "komast ekki fyrir.$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches::
    .string "Stærsti HORNUXI sem ég hef séð\n"
    .string "hingað til mældist:\p"
    .string "{STR_VAR_3} tommur!$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort::
    .string "Þetta er einhvers konar autt\n"
    .string "yfirlit.\p"
    .string "Það hefur reiti til að skrá einhvers\n"
    .string "konar met.$"

