ViridianCity_Gym_Text_GiovanniIntro::
    .string "Fwahahaha! Velkomin/n í felustaðinn\n"
    .string "minn!\p"
    .string "Hann verður það þar til ég\n"
    .string "endurreisi ROCKET-GENGIÐ til fyrri\p"
    .string "dýrðar.\p"
    .string "En þú fannst mig aftur. Jæja þá. Í\n"
    .string "þetta sinn held ég engu aftur!\p"
    .string "Enn á ný skaltu mæta GIOVANNI,\n"
    .string "sterkasta\p"
    .string "ÞJÁLFARANUM!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "Ha! Þetta var sannarlega ákafur\n"
    .string "bardagi. Þú vannst!\p"
    .string "Til sönnunar færðu hér JARÐMERKIÐ!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Eftir tap sem þetta get ég ekki\n"
    .string "horfst í augu við fylgjendur mína.\p"
    .string "Ég brást trausti þeirra.\p"
    .string "Frá og með deginum í dag er\n"
    .string "ROCKET-GENGIÐ liðið undir lok!\p"
    .string "Sjálfur mun ég helga líf mitt\n"
    .string "þjálfun á ný.\p"
    .string "Við hittumst aftur einhvern dag!\n"
    .string "Vertu sæl/l!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "EARTHBADGE gerir Vasaskrímsli á\n"
    .string "hvaða stigi sem er hlýðin án\p"
    .string "spurninga.\p"
    .string "Það er sönnun á meistaraskap þínum\n"
    .string "sem Vasaskrímsla ÞJÁLFARI.\p"
    .string "Með því geturðu skorað á\n"
    .string "Vasaskrímsla DEILDINA.\p"
    .string "Taktu líka þetta TM.\p"
    .string "Líttu á það sem gjöf fyrir þína\n"
    .string "áskorun í Vasaskrímsla DEILDINNI.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} fékk TM26 frá GIOVANNI.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "TM26 inniheldur\n"
    .string "JARÐSKJÁLFTA.\n\nÞetta er öflug árás\p"
    .string "sem veldur\nmiklum skjálfta.\n\nÉg\n"
    .string "bjó hana til þegar ég rak\p"
    .string "SALINN\nhérna, fyrir löngu síðan…$"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "Þú hefur ekki pláss fyrir þetta!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh! Þú hlýtur að vera að verða\n"
    .string "orkulaus!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "Ég kláraði bensínið!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "Þú þarft kraft til að halda í við\n"
    .string "SALARLEIÐTOGANN okkar.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrr! Ég er að æsa mig upp í\n"
    .string "reiði!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Arrgh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "Ég er enn ekki verðugur!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "Vasaskrímslin mín og ég búum til\n"
    .string "yndislega tónlist saman!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "Þú ert í fullkomnu jafnvægi!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Veistu hver SALARLEIÐTOGINN\n"
    .string "okkar er?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Karate er fullkomnasta form\n"
    .string "bardagalista!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aía!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "Ef Vasaskrímslin mín væru jafn góð\n"
    .string "í karate og ég…$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "Hinir sannarlega hæfileikaríku vinna\n"
    .string "með stíl.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "Ég missti takið!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "LEIÐTOGINN skammar mig fyrir að\n"
    .string "tapa svona…$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "Ég er KARATEKÓNGURINN!\n"
    .string "Örlög þín eru í mínum höndum!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Aía!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "Vasaskrímsla-DEILDIN? Þú?\n"
    .string "Ekki verða of montinn!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "Vasaskrímslin þín skjálfa þegar\n"
    .string "svipan mín smellur!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "Ái! Svipuhögg!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "Bíddu! Ég var bara kærulaus!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "VIRIDIAN SALUR var lokaður lengi.\p"
    .string "En nú er LEIÐTOGINN okkar kominn\n"
    .string "aftur!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "Var ég sigraður?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "Þú getur haldið áfram í Vasaskrímsla\n"
    .string "DEILDINA aðeins með því að sigra\p"
    .string "SALUR\p"
    .string "LEIÐTOGA okkar!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Jæja! Verðandi meistari!\p"
    .string "Jafnvel ég veit ekki hver VIRIDIAN\n"
    .string "LEIÐTOGINN er.\p"
    .string "En eitt er víst. Þetta verður\n"
    .string "erfiðastur allra SALUR\p"
    .string "LEIÐTOGA.\p"
    .string "Einnig heyrði ég að ÞJÁLFARARNIR hér\n"
    .string "vilja JÖRÐ-gerð Vasaskrímsli.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Ég er orðlaus! GIOVANNI var\n"
    .string "SALARLEIÐTOGI VIRIDIAN?$"

ViridianCity_Gym_Text_GymStatue::
    .string "VIRIDIAN Vasaskrímsla SALUR\n"
    .string "LEIÐTOGI: ?\p"
    .string "SIGURVEGANDI ÞJÁLFARAR: {RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRIDIAN Vasaskrímsla SALUR\n"
    .string "LEIÐTOGI: GIOVANNI\p"
    .string "SIGURVEGANDI ÞJÁLFARAR: {RIVAL},\n"
    .string "{PLAYER}$"
