RocketHideout_B1F_Text_Grunt1Intro::
    .string "Hver ert þú? Hvernig komst þú hingað?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "Ái! Sigraður!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "Fjárinn… Þú ert að móðga\n"
    .string "ROCKET-GENGIÐ, er það ekki?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "Þú braust inn í aðgerð\n"
    .string "ROCKET-GENGISINS? Þvílíkt frekja!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "Búmm!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "Þú kemst ekki upp með þetta,\n"
    .string "krakki!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "Viðvörun! Innbrotsþjófur!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "Ég get þetta ekki!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "SILPH SCOPE? Hmpf! Ég veit ekki\n"
    .string "hvar það er.$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "Af hverju komst þú hingað?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "Þetta gengur ekki!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "Allt í lagi, ég tala… Taktu lyftuna\n"
    .string "til að hitta FORINGJANN minn.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "Ertu villtur, litla mús?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "Af hverju…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "Æi nei, þessi hávaði opnaði einhvern\n"
    .string "veginn dyrnar!$"
