SixIsland_PokemonCenter_1F_Text_SomethingHiddenOnThisIsland::
    .string "Í tíu ár hef ég leitað að RÚSTUM.\p"
    .string "Nei, gerðu það tuttugu ár.\p"
    .string "Ég hef á tilfinningunni að það sé\n"
    .string "eitthvað falið á þessari eyju.$"

SixIsland_PokemonCenter_1F_Text_SomeMonsEvolveByTradingWithHeldItem::
    .string "Þú veist um Vasaskrímsli sem þróast\n"
    .string "aðeins við skipti, já?\p"
    .string "En vissirðu að það eru fleiri dæmi?\p"
    .string "Sum Vasaskrímsli þróast aðeins þegar\n"
    .string "þau eru skipt á meðan þau halda á\p"
    .string "ákveðnum hlutum.$"

SixIsland_PokemonCenter_1F_Text_RivalImpossibleToGetAllMonsAroundHere::
    .string "{RIVAL}: Hey, {PLAYER}! Hvernig\n"
    .string "gengur að fylla VasaDEX?\p"
    .string "Það virðist ómögulegt að ná öllum\n"
    .string "Vasaskrímslum með því að hanga bara\p"
    .string "hér í kring.\p"
    .string "Kannski eru Vasaskrímsli sem við\n"
    .string "þekkjum ekki einhvers staðar langt í\p"
    .string "burtu.\p"
    .string "Jæja, ég fer að leita. Sjáumst!$"

