RocketHideout_B4F_Text_GiovanniIntro::
    .string "Jæja! Ég verð að segja að ég er\n"
    .string "hrifinn af því að þú komst hingað.\p"
    .string "ROCKET-GENGIÐ fangar Vasaskrímsli\n"
    .string "víðs vegar að úr heiminum.\p"
    .string "Þau eru mikilvæg verkfæri til að\n"
    .string "halda glæpastarfsemi okkar gangandi.\p"
    .string "Ég er leiðtoginn, GIOVANNI!\p"
    .string "Fyrir ósvífni þína færðu að finna\n"
    .string "fyrir sársauka!$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "HVAÐ! Þetta getur ekki verið!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "Ég sé að þú elur Vasaskrímsli upp\n"
    .string "af mikilli umhyggju.\p"
    .string "Barn eins og þú myndi aldrei skilja\n"
    .string "hvað ég vonast til að ná fram.\p"
    .string "Ég stíg til hliðar í þetta sinn!\p"
    .string "Ég vona að við hittumst aftur…$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "Ég þekki þig! Þú eyðilagðir áætlanir\n"
    .string "okkar á MT. MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "Brenndur aftur!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "Hefurðu eitthvað á móti\n"
    .string "ROCKET-GENGINU?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "Hvernig sérðu ekki fegurðina í\n"
    .string "illsku okkar?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "Æjæjæ!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "FORINGI! Fyrirgefðu að ég brást þér!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "Lyftan virkar ekki? Hver er með\n"
    .string "LIFT LYKILINN?$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "Nei!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "Ó nei! Ég missti LIFT LYKILINN!$"
