SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
    .string "Ég get ekki fundið út hvernig ég á\n"
    .string "að komast inn.$"

SixIsland_RuinValley_Text_IFoundThisPlace::
    .string "Leyfðu mér að segja þér, ég fann\n"
    .string "þennan stað.\p"
    .string "Ekki líta svona öfundsjúkur út, er\n"
    .string "það?$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
    .string "Hurðin hreyfist alls ekki. Athuga\n"
    .string "betur?$"

SixIsland_RuinValley_Text_LeftDoorAlone::
    .string "{PLAYER} lét hurðina í friði.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
    .string "Við nánari skoðun eru nokkrir\n"
    .string "punktar á hurðinni…$"

SixIsland_RuinValley_Text_DoorIsOpen::
    .string "Hurðin er opin.$"

SixIsland_RuinValley_Text_StanlyIntro::
    .string "Það virðast vera mörg leyndarmál enn\n"
    .string "óleyst í þessum heimi.$"

SixIsland_RuinValley_Text_StanlyDefeat::
    .string "Hmm...$"

SixIsland_RuinValley_Text_StanlyPostBattle::
    .string "Ég legg til að þú, líka, hugsir um\n"
    .string "leyndarmál og ráðgátur heimsins\p"
    .string "okkar einu sinni á dag.$"

SixIsland_RuinValley_Text_FosterIntro::
    .string "Ég er forvitinn, hvað fékk þig til\n"
    .string "að koma hingað?$"

SixIsland_RuinValley_Text_FosterDefeat::
    .string "Það er svo langt síðan ég barðist,\n"
    .string "eðlishvötin mín er úr lagi.$"

SixIsland_RuinValley_Text_FosterPostBattle::
    .string "Það eru nokkrar rústir á SEVII\n"
    .string "EYJUM.\p"
    .string "Meirihluti þeirra er mjög gamall.$"

SixIsland_RuinValley_Text_LarryIntro::
    .string "Sagt hefur verið að það séu\n"
    .string "dularfullir steinar á þessari eyju.\p"
    .string "Ég grunar að það tengist rústunum\n"
    .string "hér.$"

SixIsland_RuinValley_Text_LarryDefeat::
    .string "Ó, áhugavert.$"

SixIsland_RuinValley_Text_LarryPostBattle::
    .string "Þessar rústir þarna…\p"
    .string "Ég hef ekki haft neina heppni í að\n"
    .string "finna hvernig ég kemst inn.$"

SixIsland_RuinValley_Text_DarylIntro::
    .string "Bardagi við þig, svona hátt uppi!$"

SixIsland_RuinValley_Text_DarylDefeat::
    .string "Ó, þessi hjartasorg að tapa svona\n"
    .string "auðveldlega fyrir þér!$"

SixIsland_RuinValley_Text_DarylPostBattle::
    .string "Upplifðu gleðina við að klifra!$"

SixIsland_RuinValley_Text_HectorIntro::
    .string "Ég þekki landið hér um kring nokkuð\n"
    .string "vel.$"

SixIsland_RuinValley_Text_HectorDefeat::
    .string "Þú þarft ekki að vera svona ágengur.\n"
    .string "Ég mun glaður segja þér.$"

SixIsland_RuinValley_Text_HectorPostBattle::
    .string "Dyrnar að rústunum… Það eru undarleg\n"
    .string "mynstur rist utan á þær.\p"
    .string "Ég veit samt ekki hvað þau þýða.$"
