SafariZone_North_Text_RestHouse::
    .string "HVÍLDARHÚS$"

SafariZone_North_Text_SecretHouseStillAhead::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "LEYNIHÚSIÐ er enn fram undan.$"

SafariZone_North_Text_Area2::
    .string "SVÆÐI 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Vasaskrímsli fela sig í háu grasi.\p"
    .string "Farðu í sikksakk um graslendi til að\n"
    .string "hrekja þau fram.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Finndu LEYNIHÚSIÐ og vinnðu ókeypis\n"
    .string "HM.$"

