VictoryRoad_2F_Text_DawsonIntro::
    .string "Ef þú kemst hér í gegn geturðu farið\n"
    .string "að mæta ELÍTUFERNINGNUM.$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "Nei! Ótrúlegt!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "Ég get sigrað þig þegar kemur að\n"
    .string "þekkingu á Vasaskrímslum!$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "Þetta hér er SIGURVEGUR. Hann er\n"
    .string "lokapróf ÞJÁLFARA!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "Atsjú!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "Ef þú festist skaltu prófa að færa\n"
    .string "til nokkra steina.$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "Ah, svo þú vilt skora á\n"
    .string "ELÍTUFERNINGINN?$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "Þú náðir mér!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "{RIVAL} fór líka hér í gegn.$"

VictoryRoad_2F_Text_VincentIntro::
    .string "Komdu þá! Ég lúskra á þér!$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "Það var lúskrað á mér!$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "Þú vannst þér inn réttinn til að\n"
    .string "vera á SIGURVEGI…$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "Er SIGURVEGUR of erfiður?$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "Vel gert!$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "Margir ÞJÁLFARAR gefast upp á\n"
    .string "áskoruninni hér og fara heim.$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "GJÁÁÁ!$"
