SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
    .string "SAFARI SVÆÐIÐ er risastórt, er það\n"
    .string "ekki?\p"
    .string "SALARLEIÐTOGINN KOGA í FUCHSIA fer\n"
    .string "um svæðið öðru hverju.\p"
    .string "Honum að þakka getum við leikið\n"
    .string "okkur hér í öruggu skjóli.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .string "Að kasta STEINUM í Vasaskrímsli\n"
    .string "getur fengið þau til að flýja, en þá\p"
    .string "verður auðveldara að fanga þau.$"

SafariZone_West_Text_BaitMakesMonStickAround::
    .string "Ef þú notar BEITU eru Vasaskrímsli\n"
    .string "líklegri til að halda kyrru fyrir ef\p"
    .string "þau byrja að éta.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "I hiked a lot, but I didn't see any\n"
    .string "Vasaskrímsli I wanted.$"

