SSAnne_Deck_Text_ShipDepartingSoon::
    .string "Veislan er búin. Skipið leggur\n"
    .string "fljótlega af stað.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .string "Úff! Það er erfiðisvinna að skrúbba\n"
    .string "dekk!$"

SSAnne_Deck_Text_FeelSeasick::
    .string "Urr... mér líður illa...\p"
    .string "Ég varð sjóveikur, svo ég fór út til\n"
    .string "að fá loft...$"

SSAnne_Deck_Text_EdmondIntro::
    .string "Hæ, félagi!\p"
    .string "Dansum smá!$"

SSAnne_Deck_Text_EdmondDefeat::
    .string "Þú ert tilkomumikill!$"

SSAnne_Deck_Text_EdmondPostBattle::
    .string "Hversu margar gerðir vasaskrímsla\n"
    .string "heldurðu að séu í þessum stóra\p"
    .string "heimi?$"

SSAnne_Deck_Text_TrevorIntro::
    .string "Ahoy! Ertu sjóveikur?$"

SSAnne_Deck_Text_TrevorDefeat::
    .string "Ég var bara kærulaus!$"

SSAnne_Deck_Text_TrevorPostBattle::
    .string "Pabbi minn sagði að til væru 100\n"
    .string "gerðir vasaskrímsla. Ég held að þær\p"
    .string "séu fleiri.$"

