FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "LORELEI: Haltu skítugu höndunum\n"
    .string "þínum frá Vasaskrímslunum í\p"
    .string "hellinum!\p"
    .string "Gerðu eins og ég segi, annars þarftu\n"
    .string "að svara fyrir það gagnvart mér!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Æ, þegiðu, frú, og láttu okkur í\n"
    .string "friði.\p"
    .string "Passaðu að það komi ekki móða á\n"
    .string "gleraugun þín!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "LORELEI: {PLAYER}?! Hvað ertu að\n"
    .string "gera hér?\p"
    .string "Nei, við tölum saman síðar. Núna\n"
    .string "þarf ég hjálp þína.\p"
    .string "Hjálpaðu mér að reka þessa\n"
    .string "veiðiþjófa útaf áður en þeir gera\p"
    .string "meira.\p"
    .string "Þeir hafa verið að fanga\n"
    .string "Vasaskrímsli hér og selja þau svo\p"
    .string "annars staðar.$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "H-hvað?!\p"
    .string "Hver segir að við megum ekki gera\n"
    .string "það sem við viljum við Vasaskrímslin\p"
    .string "sem við föngum?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "Við höfðum ekki planað þetta!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "LORELEI: Hmph. Svo fyrirlitlega\n"
    .string "veikur.\p"
    .string "Þú! Segðu mér!\p"
    .string "Hvert hafið þið farið með fönguðu\n"
    .string "Vasaskrímslin?\p"
    .string "Ég mölva hringinn ykkar í eitt\n"
    .string "skipti fyrir öll!$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "N-nei, alls ekki! Ég segi þér það\n"
    .string "ekki!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "LORELEI: Ef þú játar ekki, frystum\n"
    .string "við þig í gegn.\p"
    .string "LAGARGANDAN mín er æf yfir því sem\n"
    .string "þið gerðuð vinum hennar.\p"
    .string "Áfram, LAGARGANDA! ICE BEAM…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "Vááá! Allt í lagi! Ég tala!\p"
    .string "Vasaskrímslin eru í ROCKET\n"
    .string "VÖRUHÚSINU á FIVE EYJU.\p"
    .string "Þarna! Ég sagði það! Við förum núna!\p"
    .string "…En ég efast um að þú komist nokkurn\n"
    .string "tíma inn í ROCKET VÖRUHÚSIÐ!\p"
    .string "Heheheheh!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, takk fyrir. En þetta er\n"
    .string "hræðilegt…\p"
    .string "Ég er fædd og uppalin hér á þessum\n"
    .string "eyjum.\p"
    .string "Ég hafði ekki hugmynd um að þessir\n"
    .string "hræðilegu glæpamenn væru lausir hér…$"

