CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "Þessir ömurlegu ROCKETAR!\p"
    .string "Sjáðu hvað þeir hafa gert við húsið\n"
    .string "mitt!\p"
    .string "Þeir stálu TM-i sem kennir\n"
    .string "vasaskrímslum að grafa holur með\p"
    .string "DIG!\p"
    .string "Ég ætlaði að nota það á SKAPKÖTT eða\n"
    .string "SANDSNJÁLD...\p"
    .string "Þetta kostaði mig skildinginn!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "Ég hugsa að það sem er glatað sé\n"
    .string "glatað.\p"
    .string "Ég ákvað að kenna GRAFLARA að nota\n"
    .string "DIG án TM.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "ROCKET-GENGIÐ hlýtur að vera að\n"
    .string "grafa sig inn í eitthvað misjafnt!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "ROCKET-GENGIÐ skildi eftir\n"
    .string "útgönguleið!$"

