LavenderTown_House1_Text_Cubone::
    .string "BEINFARI: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "Þessir hræðilegu ROCKET-liðar! Þeir\n"
    .string "eiga enga miskunn skilið!\p"
    .string "Aumingja móðir BEINFARA…\p"
    .string "Hún var drepin þegar hún reyndi að\n"
    .string "flýja frá ROCKET-GENGINU.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "Draugurinn í Vasaskrímsla TOWER er\n"
    .string "farinn!\p"
    .string "Einhver hlýtur að hafa sefað órólega\n"
    .string "önd hans!$"

