SaffronCity_House_Text_DontLookAtMyLetter::
    .string "…Takk fyrir að skrifa. Ég vona að\n"
    .string "við sjáumst fljótlega!\p"
    .string "…Hey! Ekki lesa bréfið mitt!$"

SaffronCity_House_Text_Pidgey::
    .string "DÚFUTETUR: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "COPYCAT er sæt! Ég ætla að kaupa\n"
    .string "VASa DÚKKU handa henni.$"

SaffronCity_House_Text_ExplainPPUp::
    .string "Ég fékk PP UP að gjöf.\p"
    .string "Það er notað til að hækka PP á\n"
    .string "hreyfingu Vasaskrímslis.\p"
    .string "Ég ætti að nota það á öfluga\n"
    .string "hreyfingu með fá PP.$"

