SSAnne_2F_Room2_Text_BrooksIntro::
    .string "Að keppa við unga fólkið heldur mér\n"
    .string "ungum.$"

SSAnne_2F_Room2_Text_BrooksDefeat::
    .string "Góður bardagi! Ah, mér finnst ég\n"
    .string "ungur aftur!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .string "Fyrir fimmtán árum hefði ég unnið!$"

SSAnne_2F_Room2_Text_DaleIntro::
    .string "Sjáðu hvað ég veiddi upp!$"

SSAnne_2F_Room2_Text_DaleDefeat::
    .string "Ég er búinn að missa allt!$"

SSAnne_2F_Room2_Text_DalePostBattle::
    .string "Veisla?\p"
    .string "Veislan á skemmtiferðaskipinu ætti\n"
    .string "að vera búin núna.$"

