FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .string "LORELEI: Það er eitthvað sem liggur\n"
    .string "þungt á mér.\p"
    .string "Ef eitthvað kæmi fyrir á eyjunni þar\n"
    .string "sem ég fæddist…\p"
    .string "Þá myndi ég ekki vita af því ef ég\n"
    .string "væri í Vasaskrímsla LEAGUE.\p"
    .string "Ég velti fyrir mér hvort það gerði\n"
    .string "mig ábyrgðarlausa gagnvart heimili\p"
    .string "mínu…$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
    .string "LORELEI: Þú náðir þá að leysa öll\n"
    .string "vandamálin hér?\p"
    .string "Það er frábært.\p"
    .string "Það þýðir að ég þarf ekki að vera\n"
    .string "hér allan tímann.\p"
    .string "Takk fyrir…\p"
    .string "Ég sný aftur í Vasaskrímsla LEAGUE\n"
    .string "eftir stutta stund.$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .string "Ég veit ekki hvað mun gerast í\n"
    .string "framtíðinni, en…\p"
    .string "Ég geri það sem ég get hér og nú.\n"
    .string "Það er allt sem ég get gert.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "Stuffed Vasaskrímsli dolls galore!$"

