Route4_Text_TrippedOverGeodude::
    .string "Ái! Ég hrasaði um grýtt\n"
    .string "vasaskrímsli, AURGAUR!$"

Route4_Text_CrissyIntro::
    .string "Ég kom til MT. MOON í leit að\n"
    .string "sveppavasaskrímslum.$"

Route4_Text_CrissyDefeat::
    .string "Eftir allt sem ég lagði á mig til að\n"
    .string "ná þeim!$"

Route4_Text_CrissyPostBattle::
    .string "Það eru kannski ekki fleiri sveppir\n"
    .string "hér.\p"
    .string "Ég held ég hafi náð þeim öllum.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON Gangainngangur$"

Route4_Text_RouteSign::
    .string "LEIÐ 4 MT. MOON - CERULEAN BORG$"

Text_MegaPunchTeach::
    .string "Högg af öskrandi hörku!\p"
    .string "Hlaðið eyðileggjandi krafti!\p"
    .string "Þegar allt er undir er MEGAHÖGG\n"
    .string "fullkomna árásin! Þú samþykkir það,\p"
    .string "ekki satt?\p"
    .string "Nú! Leyfðu mér að kenna\n"
    .string "vasaskrímslinu þínu það!$"

Text_MegaPunchDeclined::
    .string "Þú kemur aftur þegar þú skilur gildi\n"
    .string "MEGAHÖGGS.$"

Text_MegaPunchWhichMon::
    .string "Gott! Hvaða vasaskrímsli á að læra\n"
    .string "það?$"

Text_MegaPunchTaught::
    .string "Nú erum við félagar á vegi högganna!\p"
    .string "Þú ættir að fara áður en sá villti\n"
    .string "kjáni sem æfir bara spörk sér þig.$"

Text_MegaKickTeach::
    .string "Spark af grimmilegri hörku!\p"
    .string "Hlaðið eyðileggjandi krafti!\p"
    .string "Þegar öllu er á botninn hvolft er\n"
    .string "MEGASPARK fullkomna árásin! Ertu\p"
    .string "ekki sammála?\p"
    .string "Allt í lagi! Ég skal kenna\n"
    .string "vasaskrímslinu þínu það!$"

Text_MegaKickDeclined::
    .string "Þú skríður aftur þegar þú skilur\n"
    .string "gildi MEGASPARKS.$"

Text_MegaKickWhichMon::
    .string "Allt í lagi! Hvaða vasaskrímsli vill\n"
    .string "læra það?$"

Text_MegaKickTaught::
    .string "Nú erum við sálufélagar á vegi\n"
    .string "sparkanna!\p"
    .string "Þú ættir að hlaupa áður en sá\n"
    .string "ruglaði kjáni sem æfir bara einföld\p"
    .string "högg sér þig.$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Ó, vá, þetta er STEINMERKIÐ! Þú\n"
    .string "fékkst það frá BROCK, ekki satt?\p"
    .string "BROCK er flottur. Hann er ekki bara\n"
    .string "sterkur. Fólk kann vel við hann og\p"
    .string "ber virðingu fyrir honum.\p"
    .string "Ég vil verða SALSTJÓRI eins og hann.$"
