VermilionCity_Text_GrimerMultipliesInSludge::
    .string "Við gætum vel að mengun hér.\p"
    .string "Við höfum heyrt að DRULLUPOLL fjölgi\n"
    .string "sér í eitruðum eðju.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "Sástu S.S. ANNE liggja við akkeri í\n"
    .string "höfninni?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "Jæja, S.S. ANNE er farin?\p"
    .string "Hún verður aftur í VERMILION um\n"
    .string "þetta leyti á næsta ári.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "Ég er að reisa byggingu á þessari\n"
    .string "lóð. Ég á hana alla.\p"
    .string "Vasaskrímslið mitt þjappar\n"
    .string "jarðveginn undir grunninn.$"

VermilionCity_Text_Machop::
    .string "ÞREKANGI: Guoh! Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "ÞREKANGI stappar jarðveginn flatan.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "S.S. ANNE er frægt lúxus-\n"
    .string "skemmtiferðaskip.\p"
    .string "Hún kemur til VERMILION einu sinni á\n"
    .string "ári.$"

VermilionCity_Text_CitySign::
    .string "VERMILION BORG Höfnin þar sem\n"
    .string "sólarlagið glóir$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "TILKYNNING!\p"
    .string "VEGUR 12 gæti verið lokuð af sofandi\n"
    .string "vasaskrímsli.\p"
    .string "Farðu hjáleið um STEINA GÖNG til\n"
    .string "LAVENDER BORGAR.\p"
    .string "VERMILION LÖGREGLAN$"

VermilionCity_Text_PokemonFanClubSign::
    .string "VASASKRÍMSLA AÐDÁENDAKLÚBBUR Allir\n"
    .string "aðdáendur vasaskrímsla velkomnir!$"

VermilionCity_Text_GymSign::
    .string "VERMILION BORG VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: LT. SURGE Eldingamaðurinn\p"
    .string "frá Ameríku!$"

VermilionCity_Text_VermilionHarbor::
    .string "VERMILION HÖFN$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "Velkomin um borð í S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "Velkomin um borð í S.S. ANNE!\p"
    .string "Afsakið, ertu með miða?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER} sýndi S.S.\n"
    .string "MIÐANN!\p"
    .string "{FONT_MALE}Frábært! Velkomin um borð\n"
    .string "í S.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_NORMAL}{PLAYER} er ekki með\n"
    .string "nauðsynlega S.S. MIÐANN.\p"
    .string "{FONT_MALE}Afsakið!\p"
    .string "Þú þarft miða til að fara um borð.$"

VermilionCity_Text_TheShipSetSail::
    .string "Skipið lagði úr höfn.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "Ah, þú ert með ÞRÍPASSA.\p"
    .string "Viltu fara um borð í SEAGALLOP\n"
    .string "ferju?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Allt í lagi, allt er í röð og reglu.\p"
    .string "SEAGALLOP HI-SPEED 7 leggur strax af\n"
    .string "stað.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "Ah, þú ert með REGNBOGAPASSA.\p"
    .string "Viltu fara um borð í SEAGALLOP\n"
    .string "ferju?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Ó! Þetta er MYSTICMIÐI! Hann er\n"
    .string "sannarlega sjaldgæfur.\p"
    .string "Við flytjum þig glöð til NAVEL ROCK\n"
    .string "hvenær sem er.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Ó! Þetta er AURORAMIÐI! Hann er\n"
    .string "sannarlega sjaldgæfur.\p"
    .string "Við flytjum þig glöð til BIRTH\n"
    .string "ISLAND hvenær sem er.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Viltu fara um borð í SEAGALLOP\n"
    .string "ferju?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Allt í lagi, allt er klárt fyrir þig\n"
    .string "til að fara um borð í sérferju.\p"
    .string "SEAGALLOP HI-SPEED 10 leggur strax\n"
    .string "af stað.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Allt í lagi, allt er klárt fyrir þig\n"
    .string "til að fara um borð í sérferju.\p"
    .string "SEAGALLOP HI-SPEED 12 leggur strax\n"
    .string "af stað.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Ó, halló, {PLAYER}! Hvernig gengur?\p"
    .string "Þetta er ég, einn af AÐSTOÐARMÖNNUM\n"
    .string "Prófessor EIK.\p"
    .string "Hittirðu hinn AÐSTOÐARMANNINN?\p"
    .string "Hann var með pakka frá Prófessor EIK\n"
    .string "handa þér, {PLAYER}.\p"
    .string "Hann sagðist leita að þér í kringum\n"
    .string "VEGUR 2, {PLAYER}.\p"
    .string "Ef þú ert á VEGUR 2 svæðinu,\n"
    .string "vinsamlegast leitaðu að honum.$"
