@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
    .string "Halló!\p"
    .string "Velkomin/n í ÞJÁLFARATURNINN þar sem\n"
    .string "ÞJÁLFARAR alls staðar að koma saman!$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
    .string "ÞJÁLFARAR frá öllum heimshornum\n"
    .string "safnast hér saman til að berjast.\p"
    .string "Leyfðu mér að sjá…\p"
    .string "Núna eru aðeins ÞJÁLFARAR upp á hæð\n"
    .string "{STR_VAR_1}.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
    .string "Þjálfarar bíða áskorunar þinnar upp\n"
    .string "á áttundu hæð.$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
    .string "Viltu skora á biðjandi ÞJÁLFARA?$"

TrainerTower_Lobby_Text_StartClockGetSetGo::
    .string "Allt í lagi, ég set klukkuna af\n"
    .string "stað, svo gefðu allt sem þú átt.\p"
    .string "Á merki…\p"
    .string "Tilbúin/n…\p"
    .string "Áfram!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
    .string "Vinsamlegast heimsóttu okkur aftur!$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
    .string "Það var of slæmt.\p"
    .string "Ég held að þú hafir lagt mikið á þig\n"
    .string "í bardaganum þínum.\p"
    .string "Vinsamlegast komdu aftur og reyndu\n"
    .string "aftur!$"

TrainerTower_Lobby_Text_GiveItYourBest::
    .string "Ég vona að þú gerir þitt besta.$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
    .string "Þegar ÞJÁLFARAR skipta um stað getur\n"
    .string "hreyfingin verið óskipuleg.\p"
    .string "Til að forðast troðninginn færðum\n"
    .string "við móttökuborðið hingað.\p"
    .string "Ég biðst velvirðingar á óþægindunum.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
    .string "Halló…\p"
    .string "Ég er eigandi þessa TURNS…\p"
    .string "Hvernig himinninn gnæfir yfir þessu\n"
    .string "þaki…\p"
    .string "Hvernig vindurinn strýkur hér uppi…\p"
    .string "Allt er svo fullkomið…\p"
    .string "Hvernig þú barðist… Það var líka\n"
    .string "fullkomið…$"

TrainerTower_Roof_Text_ThisIsForYou::
    .string "Þetta er fyrir þig…$"

TrainerTower_Roof_Text_DoneItInRecordTime::
    .string "Ó! Stórkostlegt!\p"
    .string "Það er undravert hvað þú komst\n"
    .string "hingað upp fljótt.\p"
    .string "Staðreyndin er sú að þú gerðir það á\n"
    .string "mettíma…\p"
    .string "Ég læt skrá metið þitt við\n"
    .string "móttökuborðið.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
    .string "Þú virðist hafa tekið þinn sæta tíma\n"
    .string "til að komast hingað…$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
    .string "Það sem ég vil sjá er betri tími hjá\n"
    .string "þér…\p"
    .string "Ég treysti á þig.\p"
    .string "Þangað til, vertu sæl/l…$"

TrainerTower_Text_XMinYZSec::
    .string "{STR_VAR_1} mín.\n"
    .string "{STR_VAR_2}.{STR_VAR_3} sek.$"

TrainerTower_Lobby_Text_HereAreTheResults::
    .string "Hér eru úrslitin.$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
    .string "Þetta er tveir á móti tveimur\n"
    .string "bardagi.\p"
    .string "Þú mátt ekki berjast nema þú hafir\n"
    .string "að minnsta kosti tvö Vasaskrímsli.$"

TrainerTower_Lobby_Text_ExplainTrainerTower::
    .string "Hér í ÞJÁLFARATURNINUM er viðburður\n"
    .string "sem kallast TÍMAÁSKORUN.\p"
    .string "Það verður mælt hversu fljótt þú\n"
    .string "kemst frá móttökuborðinu til\p"
    .string "EIGANDANS á þakinu.\p"
    .string "Bestu tímarnir verða skráðir á\n"
    .string "Tímatöfluna.$"

TrainerTower_Lobby_Text_ThanksForCompeting::
    .string "Takk fyrir að keppa!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
    .string "Ég er hér til að sjá hversu góður ég\n"
    .string "er.\p"
    .string "Ég velti fyrir mér hvers konar\n"
    .string "ÞJÁLFARAR bíða mín?\p"
    .string "Það er taugaþrungin!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
    .string "Más, más… Más…\p"
    .string "Gleymdu bardögum! Þessar tröppur…\n"
    .string "Þær eru erfiðari en nokkur bardagi…$"

