PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "Vasaskrímsli læra ný brögð þegar þau\n"
    .string "vaxa.\p"
    .string "En sum brögð verða menn að kenna\n"
    .string "þeim.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "Auðveldara er að ná vasaskrímsli ef\n"
    .string "það er með ástandsvandamál.\p"
    .string "Svefn, eitrun, bruni eða lömun...\n"
    .string "Allt þetta virkar.\p"
    .string "En það er aldrei öruggt að ná\n"
    .string "vasaskrímsli!$"

