PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Velkomin í VASASKRÍMSLADEILDINA.\p"
    .string "Ég er LORELEI úr ELÍTUFERNINGNUM.\p"
    .string "Enginn stenst mér snúning þegar\n"
    .string "kemur að ís-Vasaskrímslum.\p"
    .string "Frystiárásir eru máttugar.\p"
    .string "Vasaskrímslin þín verða á valdi\n"
    .string "mínu þegar þau frjósa í gegn.\p"
    .string "Hahaha! Nú hefst\n"
    .string "þetta!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Velkomin í VASASKRÍMSLADEILDINA.\p"
    .string "Ég, LORELEI úr ELÍTUFERNINGNUM, er\n"
    .string "komin aftur!\p"
    .string "Þú veist hvernig þetta fer. Enginn\n"
    .string "stenst mér snúning í ís-\p"
    .string "Vasaskrímslum.\p"
    .string "Frystiárásir eru máttugar.\p"
    .string "Vasaskrímslin þín verða á valdi\n"
    .string "mínu þegar þau frjósa í gegn.\p"
    .string "Hahaha! Nú hefst\n"
    .string "þetta!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Þetta átti ekki að fara svona!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "Þú ert betri en ég hélt. Haltu\n"
    .string "áfram.\p"
    .string "Þú fékkst aðeins forsmekk af mætti\n"
    .string "VASASKRÍMSLADEILDARINNAR.$"
