CeladonCity_Gym_Text_ErikaIntro::
    .string "Halló… Dásamlegt veður, er það ekki?\n"
    .string "Það er svo notalegt…\p"
    .string "…Ó, góðan dag… Ég hlýt að hafa\n"
    .string "dottað. Velkomin.\p"
    .string "Nafn mitt er ERIKA. Ég er SALSTJÓRI\n"
    .string "CELADON-SALARINS.\p"
    .string "Ég stunda nám í listinni að raða\n"
    .string "blómum.\p"
    .string "Vasaskrímslin mín eru eingöngu af\n"
    .string "GRAS-gerð.\p"
    .string "…Ó, fyrirgefðu, ég hafði ekki\n"
    .string "hugmynd um að þú vildir skora á mig.\p"
    .string "Málið er dautt, en ég mun ekki\n"
    .string "tapa.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Ó! Ég játa mig sigraða. Styrkur þinn\n"
    .string "er aðdáunarverður.\p"
    .string "Ég verð að veita þér RAINBOWBADGE.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "Ertu að skrásetja vasaskrímsli? Ég\n"
    .string "verð að segja að ég er hrifin.\p"
    .string "Ég myndi aldrei safna vasaskrímslum\n"
    .string "ef þau væru óaðlaðandi.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "RAINBOWBADGE mun láta vasaskrímsli\n"
    .string "allt að Lv. 50 hlýða.\p"
    .string "Það gerir vasaskrímslum líka kleift\n"
    .string "að nota STRENGTH bæði innan og utan\p"
    .string "bardaga.\p"
    .string "Vinsamlegast taktu þetta líka með\n"
    .string "þér.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER} fékk TM19 frá ERIKA.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "TM19 inniheldur GIGA DRAIN.\p"
    .string "Helmingur skaðans sem það veldur\n"
    .string "rennur til baka og læknar\p"
    .string "vasaskrímslið þitt.\p"
    .string "Værirðu ekki sammála því að þetta sé\n"
    .string "dásamlegt bragð?$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "Þú þarft að búa til pláss fyrir\n"
    .string "þetta.$"

CeladonCity_Gym_Text_KayIntro::
    .string "Ég ætti að segja þér frá þessum\n"
    .string "LIÐSMEISTARASAL.\p"
    .string "Aðeins sannar dömur mega vera hér\n"
    .string "inni!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "Þetta var of harkalegt!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "Bleee! Ég vona að ERIKA rústi þér!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Ó, þú komst. Mér var farið að\n"
    .string "leiðast.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "Förðunin mín!$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "GRAS-gerðar vasaskrímsli standa vel\n"
    .string "gegn VATNS-gerðinni.\p"
    .string "Þau hafa líka yfirhöndina gagnvart\n"
    .string "STEIN- og JARÐAR-gerðar\p"
    .string "vasaskrímslum.$"

CeladonCity_Gym_Text_TinaIntro::
    .string "...Varstu ekki að gægjast hér inn\n"
    .string "áðan?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "Þú kemur á óvart!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "Ó, þú varst að horfa á ERIKU... Þú\n"
    .string "varst ekki að horfa á mig...$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "Sjáðu, sjáðu! Sjáðu vasaskrímslin\n"
    .string "mín!\p"
    .string "Mér líkar við GRAS-gerðina. Mér\n"
    .string "finnst þau auðveld í uppeldi.$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "Nei!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "Við notum aðeins GRAS-gerðar\n"
    .string "vasaskrímsli í salnum okkar.\p"
    .string "Af hverju? Við notum þau líka í\n"
    .string "blómaskreytingar!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "Ó, hæ!\p"
    .string "Okkur líkar ekki við SKORDÝ- eða\n"
    .string "ELDS-gerðar vasaskrímsli hér inni!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "Ó! Þú!$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "SALSTJÓRINN okkar, ERIKA, er kannski\n"
    .string "hljóðlát, en hún er fræg hér um\p"
    .string "slóðir.$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Gaman að kynnast þér. Áhugamálið\n"
    .string "mitt er vasaskrímslaþjálfun.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "Ó! Glæsilegt!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "Ég á stefnumót í blindni á næstunni.\n"
    .string "Ég þarf að læra að vera kurteis,\p"
    .string "sérstaklega ef ég þarf að berjast.$"

CeladonCity_Gym_Text_MaryIntro::
    .string "Velkomin í CELADON-SALINN!\p"
    .string "Þú skalt ekki vanmeta þessar indælu\n"
    .string "dömur.$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "Ó! Sigruð!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "Ég tók ekki bestu vasaskrímslin mín\n"
    .string "með. Bíddu bara þangað til næst!$"

CeladonCity_Gym_Text_GymStatue::
    .string "CELADON VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: ERIKA\p"
    .string "SIGURSÆLIR ÞJÁLFARAR: {RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "CELADON VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: ERIKA\p"
    .string "SIGURSÆLIR ÞJÁLFARAR: {RIVAL},\n"
    .string "{PLAYER}$"
