CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "Ég er þyrst! Mig langar í eitthvað\n"
    .string "að drekka!\p"
    .string "{FONT_NORMAL}Gefurðu henni drykk?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "Hvaða drykk viltu gefa henni?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "Jibbí!\p"
    .string "FERSKT VATN!\p"
    .string "Takk fyrir! Þú mátt fá þetta frá\n"
    .string "mér!$"

Text_ReceivedItemFromLittleGirl::
    .string "{PLAYER} fékk {STR_VAR_2} frá litlu\n"
    .string "stelpunni.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .string "TM16 inniheldur LIGHT SCREEN.\p"
    .string "Bragðið veikir kraft sérárása\n"
    .string "andstæðingsins.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "Jibbí!\p"
    .string "GOSDRYKKUR!\p"
    .string "Takk fyrir! Þú mátt fá þetta frá\n"
    .string "mér!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .string "TM20 inniheldur VERNDARHJÚP.\p"
    .string "Það er bragð sem kemur í veg fyrir\n"
    .string "ástandsvandamál hjá vasaskrímslunum\p"
    .string "þínum.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "Jibbí!\p"
    .string "SÍTRÓNULAÐI!\p"
    .string "Takk fyrir! Þú mátt fá þetta frá\n"
    .string "mér!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .string "TM33 inniheldur REFLECT.\p"
    .string "Bragðið veikir kraft líkamlegra\n"
    .string "árása andstæðingsins.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "Þú hefur ekki pláss fyrir þetta!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "Nei, takk! Ég er víst ekki þyrst\n"
    .string "lengur!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .string "Systir mín er ÞJÁLFARI, hvort sem þú\n"
    .string "trúir því eða ekki.\p"
    .string "En hún er svo óþroskuð að hún gerir\n"
    .string "mig alveg vitlausa!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "Ég er þyrst! Mig langar í eitthvað\n"
    .string "að drekka!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .string "ÞAKSVÆÐI: SJÁLFSALAR$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "Sjálfsali! Hvað er í honum?$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "Æ, ekki nægir peningar!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "Dós af {STR_VAR_1} datt út!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "Það er ekki meira pláss fyrir dót!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "Ekki þyrst!$"

