SSAnne_1F_Room2_Text_TylerIntro::
    .string "Ég elska vasaskrímsli! Gerir þú það?$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "Vá! Þú ert frábær!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "Heyrðu, heyrðu! Leyfðu mér að vera\n"
    .string "vinur þinn, allt í lagi?\p"
    .string "Þá getum við skipt á vasaskrímslum\n"
    .string "og gert allskonar.$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "Ég safnaði þessum vasaskrímslum frá\n"
    .string "öllum heimshornum!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "Ó, nei! Ég fór um allan heim fyrir\n"
    .string "þau!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "Þú meiddir greyið vasaskrímslin mín!\p"
    .string "Ég krefst þess að þú læknir þau í\n"
    .string "vasaskrímslamiðstöð!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "Við erum í siglingu um heiminn, ég\n"
    .string "og börnin mín.$"

