FuchsiaCity_House2_Text_DoYouLikeToFish::
    .string "Ég er eldri bróðir FISKIGÚRÚSINS.\p"
    .string "Ég einfaldlega elska að veiða! Ég\n"
    .string "get ekki verið án þess.\p"
    .string "Segðu mér, finnst þér gaman að\n"
    .string "veiða?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
    .string "Frábært! Mér líkar stíllinn þinn. Ég\n"
    .string "held að við getum orðið vinir.\p"
    .string "Taktu þetta og fiskaðu, ungi vinur!$"

FuchsiaCity_House2_Text_ReceivedGoodRod::
    .string "{PLAYER} fékk GOOD ROD frá bróður\n"
    .string "FISHING GURU.$"

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons::
    .string "Veiði er lífsstíll! Hún er eins og\n"
    .string "fínasta ljóðlist.\p"
    .string "Léleg GÖMUL STÖNG getur bara veitt\n"
    .string "GREYSLEPPU, ekki satt?\p"
    .string "En með GÓÐRI STÖNG geturðu veitt mun\n"
    .string "betri Vasaskrímsli.$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
    .string "Ó… Það eru vonbrigði…$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
    .string "Halló, {PLAYER}!\p"
    .string "Hvernig er fiskurinn að bíta?$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
    .string "Ó, nei!\p"
    .string "Ég átti gjöf handa þér, en þú hefur\n"
    .string "ekki pláss fyrir hana!$"

