IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Jæja! Verðandi meistari!\p"
    .string "Í VASASKRÍMSLADEILDINNI mætirðu\n"
    .string "öllum ELÍTUFERNINGNUM í röð.\p"
    .string "Ef þú tapar þarftu að byrja alveg\n"
    .string "upp á nýtt!\p"
    .string "Nú gildir það! Áfram!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "Héðan í frá mætirðu einum úr\n"
    .string "ELÍTUFERNINGNUM í einu.\p"
    .string "Ef þú vinnur opnast dyr að næsta\n"
    .string "ÞJÁLFARA. Gangi þér vel!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "Mér þykir það leitt, en ferðin\n"
    .string "hingað var til einskis.\p"
    .string "LORELEI úr ELÍTUFERNINGNUM er ekki\n"
    .string "við, sjáðu til.\p"
    .string "Þess vegna er VASASKRÍMSLADEILDIN\n"
    .string "lokuð um sinn.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "DRAUGA-gerðar Vasaskrímsli AGÖTHU\n"
    .string "eru hræðilega seig.\p"
    .string "Ég tók BARDAGA-gerðar Vasaskrímslin\n"
    .string "mín og þjálfaði þau í botn.\p"
    .string "Ég fór gegn AGÖTHU fullur\n"
    .string "sjálfstrausts, en hún rústaði okkur.\p"
    .string "Gamla konan er líka ansi\n"
    .string "skapbráð.\p"
    .string "Það þarf lítið til að fá þessa\n"
    .string "ógnvekjandi konu til að æpa.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Kannski er það í blóðinu að komast\n"
    .string "í ELÍTUFERNINGINN.\p"
    .string "Eftir því sem ég hef heyrt á LANCE\n"
    .string "frænku sem er SALSTJÓRI\p"
    .string "einhvers staðar langt í burtu.$"
