Text_MetronomeTeach::
    .string "Tsk-tsk-tsk! Ég skal kenna þér\n"
    .string "snjalla hreyfingu.\p"
    .string "Kenndu hana vasaskrímsli og horfðu á\n"
    .string "fjörið hefjast!\p"
    .string "Hún heitir TAKTMÆLIR. Líst þér á\n"
    .string "hana?$"

Text_MetronomeDeclined::
    .string "Ég segi þér, þetta er mjög\n"
    .string "skemmtilegt!$"

Text_MetronomeWhichMon::
    .string "Allt í lagi! Hvaða vasaskrímsli á ég\n"
    .string "að kenna?$"

Text_MetronomeTaught::
    .string "Tsk-tsk-tsk! Svona hljómar\n"
    .string "TAKTMÆLIR.\p"
    .string "Hann potar í heilann á\n"
    .string "vasaskrímslinu og lætur það nota\p"
    .string "hreyfingar sem það kann ekki einu\n"
    .string "sinni.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "Hæ!\p"
    .string "Ég er mikilvægur læknir. Já, mjög\n"
    .string "mikilvægur, sannarlega.\p"
    .string "Hér rannsaka ég sjaldgæfa\n"
    .string "vasaskrímslasteingervinga. Allan\p"
    .string "tímann rannsaka ég.\p"
    .string "Þú! Ertu með steingerving handa mér?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "Nei! Það er of slæmt!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "Þetta tekur smá tíma!\p"
    .string "Farðu og röltaðu aðeins um\n"
    .string "nágrennið!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "Þú seinn. Hvar varstu?\p"
    .string "Steingervingurinn þinn lifir aftur!\n"
    .string "Það var {STR_VAR_1}, eins og ég\p"
    .string "hélt!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER} fékk {STR_VAR_1} frá\n"
    .string "lækninum.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "Þú ert með of mörg vasaskrímsli!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "Ó! Þetta er {STR_VAR_2}, það er það!\p"
    .string "Þetta er steingervingur af\n"
    .string "{STR_VAR_1}, vasaskrímsli sem er\p"
    .string "þegar útdautt!\p"
    .string "Upprisuvélin mín mun láta þetta\n"
    .string "vasaskrímsli lifa aftur!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "Svo! Flýttu þér og gefðu mér þetta!\p"
    .string "{FONT_NORMAL}{PLAYER} afhenti\n"
    .string "skrýtna lækninum {STR_VAR_2}.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "Ég tek smá tíma! Þú ferð í göngutúr\n"
    .string "á meðan!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "Aiyah! Þú kemur aftur!$"

