Route21_North_Text_RonaldIntro::
	.string "Viltu vita hvort fiskarnir séu að\n"
	.string "bíta?$"

Route21_North_Text_RonaldDefeat::
	.string "Fjandinn!$"

Route21_North_Text_RonaldPostBattle::
	.string "Ég næ engu góðu. Ekki eitt gott\n"
	.string "vasaskrímsli að fá!$"

Route21_North_Text_WadeIntro::
	.string "Ég fékk stóran afla! Viltu reyna?$"

Route21_North_Text_WadeDefeat::
	.string "Heheh, GREYSLEPPUR standast ekki\n"
	.string "kröfurnar, er það nokkuð?$"

Route21_North_Text_WadePostBattle::
	.string "Ég virðist bara ná GREYSLEPPUM!$"

Route21_North_Text_SpencerIntro::
	.string "Sjórinn hreinsar líkama minn og sál!$"

Route21_North_Text_SpencerDefeat::
	.string "Aí!$"

Route21_North_Text_SpencerPostBattle::
	.string "Sjórinn er frábær og allt það, en\n"
	.string "mér líkar líka við fjöllin.$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "Ég kem nú stundum líka að synda!$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "Gwaa!$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "Heldurðu að ég fljóti auðveldlega?\n"
	.string "Þegiðu, það kemur þér ekkert við!$"
