Route15_Text_KindraIntro::
    .string "Ég fékk nýlega nokkur Vasaskrímsli í\n"
    .string "skiptum. Má ég prófa þau á þér?$"

Route15_Text_KindraDefeat::
    .string "Ekki nógu gott!$"

Route15_Text_KindraPostBattle::
    .string "Þú getur ekki breytt gælunafni\n"
    .string "Vasaskrímslis sem þú færð í skiptum.\p"
    .string "Aðeins upprunalegi ÞJÁLFARINN getur\n"
    .string "látið breyta gælunafninu.$"

Route15_Text_BeckyIntro::
    .string "Þú lítur mildilega út, svo ég held\n"
    .string "að ég geti sigrað þig.\p"
    .string "Ég ætla að reyna!$"

Route15_Text_BeckyDefeat::
    .string "Nei, rangt!$"

Route15_Text_BeckyPostBattle::
    .string "Ég er hrædd við BIKERS. Þeir líta\n"
    .string "svo illa og grimmilega út!$"

Route15_Text_EdwinIntro::
    .string "Þegar ég flauta get ég kallað til\n"
    .string "fugla-Vasaskrímsli.$"

Route15_Text_EdwinDefeat::
    .string "Æ! Það er hörmulegt!$"

Route15_Text_EdwinPostBattle::
    .string "Kannski er ég ekki gerður fyrir\n"
    .string "bardaga. Ég er ekki rétta týpan,\p"
    .string "held ég.$"

Route15_Text_ChesterIntro::
    .string "Hmm? Fuglarnir mínir skjálfa! Þú ert\n"
    .string "góður, er það ekki?$"

Route15_Text_ChesterDefeat::
    .string "Alveg eins og ég hélt!$"

Route15_Text_ChesterPostBattle::
    .string "Þetta er svo augljóst að þú ættir að\n"
    .string "vita það, en…\p"
    .string "Hreyfingar eins og EARTHQUAKE og\n"
    .string "FISSURE virka ekki á\p"
    .string "fugla-Vasaskrímsli.$"

Route15_Text_GraceIntro::
    .string "Ó, þú ert lítið krútt! Alveg eins og\n"
    .string "yndislegt Vasaskrímsli!$"

Route15_Text_GraceDefeat::
    .string "Þú leitst svo sæt út líka!$"

Route15_Text_GracePostBattle::
    .string "Ég fyrirgef þér. Ég þoli það. Ég er\n"
    .string "stór stelpa núna.$"

Route15_Text_OliviaIntro::
    .string "Ég ala upp Vasaskrímsli mér til\n"
    .string "verndar því ég bý ein.$"

Route15_Text_OliviaDefeat::
    .string "Vasaskrímsli snúast ekki um sigur\n"
    .string "eða tap fyrir mér.$"

Route15_Text_OliviaPostBattle::
    .string "I love having my Vasaskrímsli greet\n"
    .string "me when I get home.\p"
    .string "It's so reassuring.$"

Route15_Text_ErnestIntro::
    .string "Hey, kid! C'mon! I just got these\n"
    .string "off some loser!$"

Route15_Text_ErnestDefeat::
    .string "Af hverju ekki?$"

Route15_Text_ErnestPostBattle::
    .string "Lífið er of stutt. Það er flott að\n"
    .string "lifa sem útlagi. ROCKET-GENGIÐ\p"
    .string "RÆÐUR!$"

Route15_Text_AlexIntro::
    .string "Afhentu allan peninginn þinn þegar\n"
    .string "þú tapar fyrir mér, krakki!$"

Route15_Text_AlexDefeat::
    .string "Það getur ekki verið satt!$"

Route15_Text_AlexPostBattle::
    .string "Ég var bara að grínast með\n"
    .string "peningana. Ekki taka mér alvarlega.$"

Route15_Text_CeliaIntro::
    .string "Hvað er svalt og í gangi? Að skipta\n"
    .string "á Vasaskrímslum!$"

Route15_Text_CeliaDefeat::
    .string "Ég sagði skipta!$"

Route15_Text_CeliaPostBattle::
    .string "Ég skipti á Vasaskrímslum við vini\n"
    .string "mína allan tímann.$"

Route15_Text_YazminIntro::
    .string "Viltu leika við Vasaskrímslin mín?$"

Route15_Text_YazminDefeat::
    .string "Ég var of óþolinmóður!$"

Route15_Text_YazminPostBattle::
    .string "Ég ætla að fara að þjálfa mig með\n"
    .string "veikari fólki.$"

Route15_Text_RouteSign::
    .string "LEIÐ 15 Vestur til FUCHSIA BORG$"

Route15_Text_MyaIntro::
    .string "MYA: Þú ert fullkominn. Hjálparðu\n"
    .string "mér að þjálfa litla bróður minn?$"

Route15_Text_MyaDefeat::
    .string "MYA: RON, þú verður að einbeita þér!\n"
    .string "Einbeittu þér að því sem þú ert að\p"
    .string "gera!$"

Route15_Text_MyaPostBattle::
    .string "MYA: Allt í lagi, við munum auka\n"
    .string "álagið. Ég mun bæta við\p"
    .string "æfingamatseðilinn okkar!$"

Route15_Text_MyaNotEnoughMons::
    .string "MYA: Viltu skora á okkur? Þú þarft\n"
    .string "þó tvö Vasaskrímsli.$"

Route15_Text_RonIntro::
    .string "RON: Systir mín verður ógnvekjandi\n"
    .string "þegar við töpum.$"

Route15_Text_RonDefeat::
    .string "RON: Oh, no, no… Sis, I'm sorry!$"

Route15_Text_RonPostBattle::
    .string "RON: Ó, æ… Ég vildi að ég ætti góða\n"
    .string "systur…$"

Route15_Text_RonNotEnoughMons::
    .string "RON: Vildirðu berjast við mig og\n"
    .string "systur mína?\p"
    .string "Þá þarftu tvö Vasaskrímsli.$"
