CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .string "Velkomin!\p"
    .string "Þú getur skipt PENINGUM fyrir\n"
    .string "glæsilega vinninga í næsta húsi.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
    .string "Velkomin í ROCKET-SPILASALINN!\p"
    .string "Vantar þig leik-PENINGA? Viltu kaupa\n"
    .string "nokkra?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
    .string "Nei? Komdu endilega að spila seinna!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .string "Æ, fyrirgefðu. Þú ert ekki með\n"
    .string "PENINGAVESKI.$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .string "Úbbs! PENINGAVESKIÐ þitt er fullt.$"

CeladonCity_GameCorner_Text_CantAffordCoins::
    .string "Þú átt ekki fyrir PENINGUNUM.$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .string "Takk fyrir. Hér eru PENINGARNIR\n"
    .string "þínir!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .string "Hafðu þetta lágt.\p"
    .string "Sagt er að ROCKET-GENGIÐ reki þennan\n"
    .string "stað.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .string "Ég held að vélarnar hafi mismunandi\n"
    .string "vinningslíkur.$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .string "Heyrðu, krakki, viltu spila?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
    .string "{PLAYER} fékk 10 PENINGA frá\n"
    .string "manninum.$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
    .string "Þú þarft ekki á PENINGUNUM mínum að\n"
    .string "halda!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .string "Vinningar koma og fara. Ekkert er\n"
    .string "öruggt.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .string "Þessir spilakassar... Hvort maður\n"
    .string "vinnur eða tapar er bara heppni.$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .string "Hey!\p"
    .string "Þú hefur betri hlutum að sinna,\n"
    .string "verðandi meistari!\p"
    .string "SALSTJÓRI CELADON-SALARINS ER ERIKA.\p"
    .string "Hún notar GRAS-gerðar vasaskrímsli\n"
    .string "og er eitt með náttúrunni.\p"
    .string "Hún virðist kannski blíð vegna\n"
    .string "blómaskreytinganna…\p"
    .string "En það má alls ekki vanmeta hana!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
    .string "Þeir bjóða upp á sjaldgæf\n"
    .string "vasaskrímsli sem hægt er að fá í\p"
    .string "skiptum fyrir PENINGANA þína.\p"
    .string "En mér virðist hreinlega ganga illa\n"
    .string "að vinna!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .string "Spil eru varasöm! Það er svo auðvelt\n"
    .string "að ánetjast þeim!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
    .string "Hvað segirðu? Viltu PENINGA?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
    .string "{PLAYER} fékk 20 PENINGA frá\n"
    .string "vingjarnlega manninum.$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
    .string "Þú átt fullt af PENINGUM!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
    .string "Súrt! Ég þarf fleiri PENINGA fyrir\n"
    .string "vasaskrímslið sem mig langar í!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .string "Heyrðu, hvað? Þú truflar mig!\p"
    .string "Hér eru nokkrir PENINGAR, hypjaðu\n"
    .string "þig!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
    .string "{PLAYER} fékk 20 PENINGA frá\n"
    .string "manninum.$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .string "Þú átt nóg af eigin PENINGUM!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .string "Bragðið er að fylgjast vel með\n"
    .string "hjólunum.$"

CeladonCity_GameCorner_Text_GruntIntro::
    .string "Ég gæti þessa veggspjalds! Farðu\n"
    .string "burt, annars...$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "Ansans!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
    .string "Felustaður ROCKET-GENGISINS gæti\n"
    .string "uppgötvast!\p"
    .string "Ég verð að segja FORINGJANUM!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "Hey!\p"
    .string "Rofi bak við veggspjaldið!? Ýtum á\n"
    .string "hann!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .string "PENINGAVESKI er nauðsynlegt...$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "Úbbs! Ekkert PENINGAVESKI!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "Spilakassi! Viltu spila?$"

CeladonCity_GameCorner_Text_OutOfOrder::
    .string "BILAÐ Þessi er bilaður.$"

CeladonCity_GameCorner_Text_OutToLunch::
    .string "Í MATARHLÉI Þessi er frátekinn.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "Lyklar einhvers! Eigandinn kemur\n"
    .string "aftur.$"

