SixIsland_WaterPath_Text_RoseIntro::
    .string "Ég lét notalega gola leiða mig alla\n"
    .string "leið hingað.$"

SixIsland_WaterPath_Text_RoseDefeat::
    .string "Hlátur… Þú ert svo sætur þegar þú\n"
    .string "ert ákveðinn.$"

SixIsland_WaterPath_Text_RosePostBattle::
    .string "Mig langar að fara í skóginn þarna,\n"
    .string "en…\p"
    .string "Þar eru fullt af SKORDÝRA\n"
    .string "Vasaskrímslum. Þau hræða mig\p"
    .string "svolítið.$"

SixIsland_WaterPath_Text_EdwardIntro::
    .string "Ég er að æfa mig í leyni svo enginn\n"
    .string "sjáir mig.$"

SixIsland_WaterPath_Text_EdwardDefeat::
    .string "Enginn sá mig tapa, er það?$"

SixIsland_WaterPath_Text_EdwardPostBattle::
    .string "Sem listamaður vil ég ekki að fólk\n"
    .string "viti um vinnuna sem ég legg í þetta.$"

SixIsland_WaterPath_Text_SamirIntro::
    .string "Hvað, ertu að gefa í skyn að þú sért\n"
    .string "þreyttur á að sjá SUNDMENN eins og\p"
    .string "mig?\p"
    .string "Æi, ekki vera með svona leiðindi!$"

SixIsland_WaterPath_Text_SamirDefeat::
    .string "Ó, nei, nei, nei.$"

SixIsland_WaterPath_Text_SamirPostBattle::
    .string "Ég gat ekki losnað við stimpilinn að\n"
    .string "vera SUNDMAÐUR…$"

SixIsland_WaterPath_Text_DeniseIntro::
    .string "Kærastinn minn er alltaf upptekinn,\n"
    .string "svo ég kem að synda ein.$"

SixIsland_WaterPath_Text_DeniseDefeat::
    .string "Awww, ég vissi að þetta myndi\n"
    .string "gerast!$"

SixIsland_WaterPath_Text_DenisePostBattle::
    .string "Þegar ég get ekki verið með\n"
    .string "kærastanum mínum eyði ég tíma með\p"
    .string "Vasaskrímslinu sem hann gaf mér.$"

SixIsland_WaterPath_Text_EarlIntro::
    .string "Segðu mér, hvar eru fjöllin hér um\n"
    .string "kring?$"

SixIsland_WaterPath_Text_EarlDefeat::
    .string "Ég týndi leiðinni á meðan ég var\n"
    .string "upptekinn við að berjast!$"

SixIsland_WaterPath_Text_EarlPostBattle::
    .string "Eru engin fjöll hér um kring?$"

SixIsland_WaterPath_Text_MiuIntro::
    .string "MIU: Halló, Vasaskrímsli! Nú er\n"
    .string "kominn leiktími!$"

SixIsland_WaterPath_Text_MiuDefeat::
    .string "MIU: Ó, nei! Mamma!$"

SixIsland_WaterPath_Text_MiuPostBattle::
    .string "MIU: Ég verð alveg leið inni í mér\n"
    .string "þegar við töpum…$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
    .string "MIU: MIA og ég erum TVÍBURAR. Við\n"
    .string "viljum berjast saman.$"

SixIsland_WaterPath_Text_MiaIntro::
    .string "MIA: Halló, Vasaskrímsli! Það er\n"
    .string "kominn bardagatími!$"

SixIsland_WaterPath_Text_MiaDefeat::
    .string "MIA: Þú ert vondur! Þú ert vondur\n"
    .string "fyrir að vinna!$"

SixIsland_WaterPath_Text_MiaPostBattle::
    .string "MIA: Óó… Fyrirgefðu,\n"
    .string "Vasaskrímslið mitt…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
    .string "MIA: Ó, ertu bara með eitt\n"
    .string "Vasaskrímsli?\p"
    .string "Finnst þér það ekki einmanalegt?$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
    .string "Óskað eftir! Fullkomna horninu!$"

SixIsland_WaterPath_Text_RouteSign::
    .string "VATNALEIÐ Leiðir til RUIN VALLEY$"
