CinnabarIsland_Text_DoorIsLocked::
    .string "Hurðin er læst...$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "BLAINE úr CINNABAR SAL er ansi\n"
    .string "sérkennilegur náungi.\p"
    .string "Hann hefur búið á eyjunni síðan\n"
    .string "löngu áður en rannsóknarstofan var\p"
    .string "byggð.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Vísindamenn gera tilraunir í brunna\n"
    .string "húsinu.\p"
    .string "Þú veist, húsinu sem þeir kalla\n"
    .string "VASASKRÍMSLAHERRASETRIÐ.$"

CinnabarIsland_Text_IslandSign::
    .string "CINNABAR EYJA Eldheitur bær\n"
    .string "brennandi þráar$"

CinnabarIsland_Text_PokemonLab::
    .string "VASASKRÍMSLARANNSÓKNARSTOFA$"

CinnabarIsland_Text_GymSign::
    .string "CINNABAR EYJU VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: BLAINE Eldheiti\p"
    .string "spurningameistarinn!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "Ha? Heyrðu, er þetta ekki {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Sjáðu, þetta er ég, BILL. Langt\n"
    .string "síðan síðast!\p"
    .string "Ég vona að þú sért enn að nota\n"
    .string "tölvukerfið mitt.\p"
    .string "Heyrðu, fyrst við hittumst hér,\n"
    .string "hvernig væri að koma með mér?\p"
    .string "Það er lítil eyja langt í suðri sem\n"
    .string "heitir ONE ISLAND.\p"
    .string "Vinur minn bauð mér þangað, svo ég\n"
    .string "er á leiðinni.\p"
    .string "Hvað segirðu? Langar þig að koma\n"
    .string "með?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "Allt í lagi þá. Förum!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "Hvað, ertu of upptekinn?\p"
    .string "Jæja, allt í lagi. Báturinn er hvort\n"
    .string "eð er ekki kominn enn.\p"
    .string "Ég bíð í VASASKRÍMSLAMIÐSTÖÐINNI\n"
    .string "þarna.\p"
    .string "Komdu til mín þegar þú ert búinn með\n"
    .string "erindin þín hér.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Svo virðist sem bátur vinar míns sé\n"
    .string "líka kominn.\p"
    .string "Hann sendi hann sérstaklega hingað\n"
    .string "til CINNABAR að sækja mig.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Heyrðu, var þetta ekki löng sigling?\p"
    .string "Félagi minn CELIO virtist njóta\n"
    .string "félagsskapar þíns.\p"
    .string "Ég er viss um að hann tæki vel á\n"
    .string "móti þér ef þú heimsækir hann aftur.\p"
    .string "Ef þú ert með ÞRÍPASSA geturðu\n"
    .string "alltaf tekið ferju þangað frá\p"
    .string "VERMILION HÖFN.\p"
    .string "Jæja, takk fyrir félagsskapinn!$"

