OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "Hm! Haaaaaaaaaaah!\p"
    .string "Aaaah! Þetta er himneskt! Vatnið\n"
    .string "hitar mig inn að beini!\p"
    .string "Þú ættir að hoppa í líka.\p"
    .string "Farðu í miðjuna, slakaðu á, og fáðu\n"
    .string "þér góðan hita!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "Uppáhalds hluti minn af baði kemur\n"
    .string "strax á eftir þessu.\p"
    .string "Ég nýt skálar af fiskisúpu til að\n"
    .string "hita mig að innan, líka!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "Vatnið er fullkomlega heitt. Það er\n"
    .string "unaðslegt…\p"
    .string "{PLAYER} og Vasaskrímslin\n"
    .string "endurnærðust að fullu!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "Að liggja í heitum laugum er\n"
    .string "heilandi, segja menn.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "Skoðaðu andlitið mitt. Sérðu hversu\n"
    .string "slétt húðin mín er?\p"
    .string "Vatnið í hvernum heldur húðinni\n"
    .string "minni yngri en aldur minn.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "Eftir heiðarlegan æfingadag\n"
    .string "er\nekkert betra en að slaka á\p"
    .string "í\n\nheitri lauginni.\n\nBRUNO, sem\n"
    .string "er eldri og reyndari\nen ég, kemur\p"
    .string "stundum í LAUGINA.\n\nHann kemur til\n"
    .string "að jafna sig á\nmeiðslum, bæði sínum\p"
    .string "eigin og\nVasaskrímslanna sinna.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "Heitir hverir fara hönd í hönd með\n"
    .string "eldfjöllum.\p"
    .string "EMBER SPA hér, ja, ég gerði það\n"
    .string "fyrir mörgum árum.\p"
    .string "Ég höggvaði laugina beint úr\n"
    .string "risastórum steini með höndunum.\p"
    .string "Ég var að nota þetta á þeim tíma. Ég\n"
    .string "held að ég geti látið það af hendi.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "Það brýtur grjóthnullunga eins og\n"
    .string "þeir væru gerðir úr kexi.$"

