SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "ROCKET-GENGIÐ kom og tók yfir\n"
    .string "bygginguna!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "Jæja, best að fara aftur að vinna.$"

SilphCo_6F_Text_HelpMePlease::
    .string "Ó nei, ó nei. Hjálpaðu mér, vinsamlegast!$"

SilphCo_6F_Text_WeGotEngaged::
    .string "Við trúlofuðum okkur. Heheh!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "Maðurinn við hliðina á mér… Hann er\n"
    .string "þvílíkur hugleysingi!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "Hann er svo bjargarlaus að hann\n"
    .string "þurfti einhvern eins og mig til að gæta hans.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "ROCKET-GENGIÐ reynir að leggja\n"
    .string "heiminn undir sig með Vasaskrímslum.$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "ROCKET-GENGIÐ flúði, og það er allt\n"
    .string "þér að þakka!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "Þeir hljóta að hafa ráðist á SILPH\n"
    .string "vegna Vasaskrímsla-varanna okkar.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "Komdu að vinna hjá SILPH þegar þú\n"
    .string "verður eldri.$"

SilphCo_6F_Text_Grunt1Intro::
    .string "Ég er einn af fjórum\n"
    .string "ROCKET-BRÆÐRUM!$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "Eldurinn slokknaði!$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "Skiptir engu! Bræður mínir munu\n"
    .string "hefna mín!$"

SilphCo_6F_Text_TaylorIntro::
    .string "Þessi rotni FORSTJÓRI!\p"
    .string "Mátulegt á hann fyrir að senda mig\n"
    .string "í TIKSI ÚTIBÚIÐ!\p"
    .string "Þess vegna kom ROCKET-GENGIÐ á\n"
    .string "eftir okkur, ég er viss um það!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "Skotinn!$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "TIKSI ÚTIBÚIÐ? Það er á rússnesku\n"
    .string "engimannslandi!$"

SilphCo_6F_Text_Grunt2Intro::
    .string "Þorirðu að svíkja ROCKET-GENGIÐ?$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "Svikari!$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "Ef þú stendur með réttlætinu, þá\n"
    .string "svíkurðu okkur vondu kallana!$"

SilphCo_6F_Text_FloorSign::
    .string "SILPH CO. HÖFUÐSKRIFSTOFA 6H$"
