ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .string "Urrrrrrrrgggghhhh… Kwaaaaah!\p"
    .string "…Það er gagnslaust! Ég get ekki\n"
    .string "beygt þessa skeið með huganum.\p"
    .string "Kannski hef ég í alvöru enga\n"
    .string "sálarkrafta.$"

ThreeIsland_House2_Text_IAdmireSabrina::
    .string "Þú veist af stelpu sem er\n"
    .string "SALARLEIÐTOGI í SAFFRON BORG?\p"
    .string "Hún notar HUGAR-gerð Vasaskrímsli,\n"
    .string "er það ekki?\p"
    .string "Ég dái hana, virkilega.\p"
    .string "Ég hef heyrt að hún sé svöl og\n"
    .string "falleg líka.$"
