@ Text for this file was split weirdly, and is instead in FourIsland_PokemonCenter_1F/text.inc
@ Theres also an unused JP version of that text in this file instead

JPText_BodySlamTeach::
    .string "そーれ ぼよーん！ どっちが さきに へたばるか？ のしかかり しょうぶ\n"
    .string "してるんだ\p"
    .string "きみは なかまに はいったら つぶれそうだな‥ かわりに きみの\n"
    .string "ポケモンに のしかかり おしえて やろっか？$"

JPText_BodySlamDeclined::
    .string "また おいで ぼよーん！$"

JPText_BodySlamWhichMon::
    .string "どの ポケモンに おしえたい かい？$"

JPText_BodySlamTaught::
    .string "Boing!$"

FourIsland_House1_Text_YoureAwfullyHeavy::
    .string "Þarna! Boing! Þú ert ótrúlega\n"
    .string "þungur!$"

