FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "Þú verður ekki góður ÞJÁLFARI með\n"
    .string "aðeins eitt sterkt Vasaskrímsli.\p"
    .string "En það er heldur ekki auðvelt að ala\n"
    .string "mörg jafnt upp.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "Vestan við VIRIDIAN BORG er þröng\n"
    .string "leið.\p"
    .string "Hún liggur að HQ\n"
    .string "Vasaskrímsladeildar. HQ stjórnar\p"
    .string "öllum ÞJÁLFURUM.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "Ef þú ert að vinna í VasaDEX skaltu\n"
    .string "heimsækja SAFARI-SVÆÐIÐ.\p"
    .string "Þar lifa alls konar sjaldgæf\n"
    .string "Vasaskrímsli.$"

