CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "Þessi BILL!\p"
    .string "Ég heyrði að hann geri hvað sem er\n"
    .string "til að ná sjaldgæfum vasaskrímslum.\p"
    .string "Hann hikar víst ekki við alls konar\n"
    .string "hluti.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Hefurðu heyrt um BILL?\p"
    .string "Allir kalla hann SKRÍMSLASJÚKAN!\p"
    .string "Ég held samt að fólk öfundi BILL\n"
    .string "bara.\p"
    .string "Hver myndi ekki vilja monta sig af\n"
    .string "vasaskrímslunum sínum?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL á fullt af vasaskrímslum! Hann\n"
    .string "safnar líka sjaldgæfum!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "Af hverju ferðu ekki upp og prófar\n"
    .string "að skipta á vasaskrímslum við vini\p"
    .string "þína?\p"
    .string "Þú getur fengið miklu meiri\n"
    .string "fjölbreytni með skiptum.\p"
    .string "Vasaskrímslin sem þú færð í skiptum\n"
    .string "vaxa líka hratt.$"

