SaffronCity_Text_WhatDoYouWantGetLost::
    .string "Hvað viltu? Farðu!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
    .string "YFIRMAÐURINN sagði að hann myndi\n"
    .string "taka þennan bæ fyrir ROCKET-GENGIÐ!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .string "Ekki vera þrjóskur! Annars verð ég\n"
    .string "að meiða þig!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .string "SAFFRON tilheyrir ROCKET-GENGINU!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .string "Líf mitt sem glæpamaður lætur mér\n"
    .string "líða svo lifandi!$"

SaffronCity_Text_WatchWhereYoureWalking::
    .string "Æ! Passaðu þig hvar þú gengur!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .string "Með SILPH á okkar valdi getum við\n"
    .string "arðrænt Vasaskrímsli um allan heim!\p"
    .string "Við verðum moldrík, jáhá!$"

SaffronCity_Text_YouBeatTeamRocket::
    .string "Þú sigraðir ROCKET-GENGIÐ einn? Það\n"
    .string "er ótrúlegt!$"

SaffronCity_Text_SafeToGoOutAgain::
    .string "Já! ROCKET-GENGIÐ er farið! Það er\n"
    .string "óhætt að fara út aftur!$"

SaffronCity_Text_PeopleComingBackToSaffron::
    .string "Fólk flúði héðan í hrönnum þegar\n"
    .string "þessir ROCKETS komu.\p"
    .string "Þeir ættu að streyma aftur til\n"
    .string "SAFFRON núna.$"

SaffronCity_Text_FlewHereOnPidgeot::
    .string "Ég flaug hingað á DÚFNASTUR mínum\n"
    .string "þegar ég frétti af SILPH.\p"
    .string "Er þetta þegar búið? Ég missti af\n"
    .string "öllu fjölmiðlafárinu…$"

SaffronCity_Text_Pidgeot::
    .string "DÚFNASTUR: Bi bibii!$"

SaffronCity_Text_SawRocketBossEscaping::
    .string "Ég sá ROCKET YFIRMANNINN flýja\n"
    .string "byggingu SILPH.$"

SaffronCity_Text_ImASecurityGuard::
    .string "Ég er öryggisvörður.\p"
    .string "Grunsamleg börn leyfi ég ekki inn!$"

SaffronCity_Text_HesTakingASnooze::
    .string "… Snore…\p"
    .string "Hah! He's taking a snooze!$"

SaffronCity_Text_CitySign::
    .string "SAFFRON BORG Glitrandi, Gullna Land\n"
    .string "Verslunar$"

SaffronCity_Text_FightingDojo::
    .string "BARDAGADÓJÓ$"

SaffronCity_Text_GymSign::
    .string "SAFFRON BORG Vasaskrímslasalur\n"
    .string "LEIÐTOGI: SABRINA Meistari\p"
    .string "HUGAR-Vasaskrímsla!$"

SaffronCity_Text_FullHealCuresStatus::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "FULL HEAL læknar öll mein eins og\n"
    .string "bruna, lömun, eitrun, frost og\p"
    .string "svefn.\p"
    .string "Það kostar aðeins meira, en er\n"
    .string "þægilegra en að kaupa marga aðra\p"
    .string "hluti.$"

SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Nýi STÓRBOLTINN gefur betri\n"
    .string "fanglíkur.\p"
    .string "Prófaðu hann á Vasaskrímsli sem er\n"
    .string "erfitt að fanga.$"

SaffronCity_Text_SilphCoSign::
    .string "SKRIFSTOFUBYGGING SILPH CO.$"

SaffronCity_Text_MrPsychicsHouse::
    .string "HÚS HR. SÁLRÆNA$"

SaffronCity_Text_SilphsLatestProduct::
    .string "Nýjasta vara SILPH!\p"
    .string "Útgáfudagur verður tilkynntur\n"
    .string "síðar…$"

SaffronCity_Text_TrainerFanClubSign::
    .string "VASaSKRÍMSLAÞJÁLFARA AÐDÁENDAKLÚBBUR\p"
    .string "Margir ÞJÁLFARAR hafa krotað nöfnin\n"
    .string "sín á þetta skilti.$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .string "Þessi AÐDÁENDAKLÚBBUR… Enginn hér\n"
    .string "hefur hugmynd!\p"
    .string "Hvernig geta þau ekki séð snilldina\n"
    .string "sem er LANCE?\p"
    .string "Hann stendur fyrir réttlæti! Hann er\n"
    .string "svalur, en samt eldheitur! Hann er\p"
    .string "sá besti, LANCE!$"
