TwoIsland_Text_IslandSign::
    .string "TVÖ EYJA Gjafaeyja fyrir tvo$"

TwoIsland_Text_JoyfulGameCornerSign::
    .string "Stökk og nart! Gleðilegur\n"
    .string "LEIKJAKRÓKUR$"

TwoIsland_Text_DangerFastCurrent::
    .string "HÆTTA! HRAÐUR STRAUMUR! Veiðar og\n"
    .string "brimbrettasiglingar bannaðar!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
    .string "Ó! Halló, velkomin í búðina mína!\p"
    .string "Við opnuðum nýlega.\p"
    .string "Vöruúrvalið okkar er takmarkað, en\n"
    .string "ég vona að við getum þjónað þínum\p"
    .string "þörfum.$"

TwoIsland_Text_AddedMerchandiseForLostelle::
    .string "Ég get ekki sagt þér hversu\n"
    .string "þakklátur ég er fyrir björgun þína á\p"
    .string "LOSTELLE.\p"
    .string "Þökk sé afreki þínu hafa íbúar\n"
    .string "ÞRJÚ EYJU breytt viðhorfum sínum til\p"
    .string "KANTO fólks.\p"
    .string "Og ég er frá KANTO, skilurðu.\p"
    .string "Íbúar ÞRJÚ EYJU hjálpuðu mér að bæta\n"
    .string "við vöruúrvalið mitt.$"

TwoIsland_Text_HopeYouGiveItYourBest::
    .string "Hæ! Ég er að gera mitt besta hér. Ég\n"
    .string "vona að þú gerir það líka, {PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands::
    .string "Ó, halló, {PLAYER}! Velkomin!\p"
    .string "Ég hef byrjað að flytja inn hluti\n"
    .string "frá fjarlægum löndum.\p"
    .string "Ég hef líka fengið inn sjaldgæfa\n"
    .string "hluti. Vinsamlegast kíktu á þá!$"

TwoIsland_Text_FellowMovedFromCeladonCity::
    .string "Sá félagi þarna, hann flutti hingað\n"
    .string "frá CELADON BORG.\p"
    .string "Hann stofnaði búð með yngri bróður\n"
    .string "sínum.\p"
    .string "Maður veltir fyrir sér hvort hann\n"
    .string "vissi hvað hann var að fara út í.$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
    .string "Bróðir búðareigandans tók vinnu í\n"
    .string "LEIKJAKRÓKNUM.\p"
    .string "Hann er að reyna að safna peningum\n"
    .string "svo þau geti keypt meiri varning.$"

TwoIsland_Text_BrunoCameToIslandWhileBack::
    .string "Hlustaðu, hlustaðu. Vissirðu?\p"
    .string "Frægur ÞJÁLFARI kom til eyjunnar\n"
    .string "fyrir stuttu.\p"
    .string "Hann er einn úr ELÍTU 4. Hann\n"
    .string "heitir BRUNO.\p"
    .string "Hann fór vonsvikinn þegar hann komst\n"
    .string "að því að allt var uppselt.$"

TwoIsland_Text_BuyRareItemsHere::
    .string "Glöggi ÞJÁLFARINN veit að hér á að\n"
    .string "kaupa sjaldgæfa hluti!$"

TwoIsland_Text_OldWomanLivesOutOnCape::
    .string "Það býr gömul kona í kofa úti á\n"
    .string "tanganum.\p"
    .string "Hún starir á Vasaskrímsli. Það er\n"
    .string "svolítið óþægilegt.$"

TwoIsland_Text_HaveYouTriedJumpingGame::
    .string "Boing! Boing! Hefurðu prófað\n"
    .string "stökkleikinn?\p"
    .string "Vasaskrímslin sem þú getur skráð…\n"
    .string "Boing!\p"
    .string "Sum fara boing!\p"
    .string "Og sum fara boooooooing!\p"
    .string "Vissirðu það? Boing!$"
