TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner::
    .string "Hefurðu heimsótt LEIKJAHORNIÐ nú\n"
    .string "þegar?\p"
    .string "Það er ekki gott að fara ein/n. Þú\n"
    .string "þarft að taka vin með.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape::
    .string "Ekki margir búa á ANNARRI EYJU.\p"
    .string "Það er gömul kona sem býr úti á\n"
    .string "tanganum.\p"
    .string "Hún hefur verið þar frá því enginn\n"
    .string "man hvenær.$"

