FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .string "SELPHY: Ó? Þekki ég þig einhvers\n"
    .string "staðar frá?\p"
    .string "Ó, en það skiptir ekki máli.\p"
    .string "Mér leiðist óskaplega. Viltu hlusta\n"
    .string "á ósk mína?$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .string "Mig langar að sjá Vasaskrímsli.\n"
    .string "Yndislegt {STR_VAR_1}.\p"
    .string "Ég vil sjá það strax. Gerðu ósk mína\n"
    .string "að veruleika.$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .string "SELPHY: Ó, ég er orðin þreytt á\n"
    .string "þessu. Ég er þreytt á að bíða eftir\p"
    .string "þér.\p"
    .string "Ég fyrirgefi þér í þetta sinn, en\n"
    .string "vinsamlegast bregðstu mér ekki næst.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "SELPHY: Ó, sæll.\p"
    .string "Ó, minn guð. Þetta hlýtur að vera\n"
    .string "{STR_VAR_1} sem þú fangaðir fyrir\p"
    .string "mig.\p"
    .string "Hehe… Ég sé líkindi með ykkur.\p"
    .string "Þakka þér kærlega.\p"
    .string "… … … … … … Er eitthvað að?\p"
    .string "Þú mátt fara.\p"
    .string "… … … … … … Ó, jæja. Ég skil það\n"
    .string "núna.\p"
    .string "SEBASTIAN! Ég þarf þig hingað strax!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "Þjónn: Já, frú mín.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "SELPHY: Sjáðu til þess að þessi\n"
    .string "aðili fái þakklætisvott.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "Ráðsmaður: Ég mun gera eins og þú\n"
    .string "biður um, frú mín.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "Þjónn: Ég þakka þér innilega fyrir\n"
    .string "að gleðja frú SELPHY.\p"
    .string "Vinsamlegast þiggðu þetta sem\n"
    .string "þakklæti hennar…$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .string "Þjónn: TASKAN þín virðist því miður\n"
    .string "vera full.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .string "Oh… How disappointing.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "SELPHY: Ég óska þér alls hins besta.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "Ráðsmaður: Bros frú SELPHY hefur\n"
    .string "birtu sólarinnar.\p"
    .string "Vinsamlegast, ég bið þig að færa frú\n"
    .string "SELPHY gleði.$"

