Route16_Text_LaoIntro::
    .string "Hvað viltu?$"

Route16_Text_LaoDefeat::
    .string "Ekki voga þér að hlæja!$"

Route16_Text_LaoPostBattle::
    .string "Okkur finnst bara gott að hanga hér.\n"
    .string "Hvað kemur það þér við?$"

Route16_Text_KojiIntro::
    .string "Flott HJÓL! Láttu mig fá það!$"

Route16_Text_KojiDefeat::
    .string "Rot!$"

Route16_Text_KojiPostBattle::
    .string "Gleymdu því, hver þarf á HJÓLINU\n"
    .string "þínu að halda!$"

Route16_Text_LukeIntro::
    .string "Komdu út að leika, litla mús!$"

Route16_Text_LukeDefeat::
    .string "Þú litla rotta!$"

Route16_Text_LukePostBattle::
    .string "Ég hata að tapa! Farðu úr andlitinu\n"
    .string "á mér!$"

Route16_Text_HideoIntro::
    .string "Hey, þú rakst í mig!$"

Route16_Text_HideoDefeat::
    .string "Kabúmm!$"

Route16_Text_HideoPostBattle::
    .string "Við munum alltaf hanga hér, hvort\n"
    .string "sem þér líkar það eða ekki.\p"
    .string "Þú getur farið hjáleið til VERMILION\n"
    .string "frá FUCHSIA meðfram ströndinni.$"

Route16_Text_CamronIntro::
    .string "Ég er svangur og illur! Ég þarf\n"
    .string "kýlipoka!$"

Route16_Text_CamronDefeat::
    .string "Slæmt, slæmt, slæmt!$"

Route16_Text_CamronPostBattle::
    .string "Ef ég ætla að eiga vasaskrímsli mega\n"
    .string "þau alveg vera grimm.\p"
    .string "Ég myndi nota þau til að tæta óvini\n"
    .string "mína í sundur.$"

Route16_Text_RubenIntro::
    .string "Heyrðu þarna! Skemmtum okkur\n"
    .string "almennilega!$"

Route16_Text_RubenDefeat::
    .string "Ekki gera mig reiðan!$"

Route16_Text_RubenPostBattle::
    .string "Ég fæ mitt fjör úr því að angra fólk\n"
    .string "með stinkandi vasaskrímslunum mínum.\p"
    .string "Þau eru frábær til að hræða fólk. Og\n"
    .string "þau bíta líka.$"

Route16_Text_MonSprawledOutInSlumber::
    .string "Vasaskrímsli liggur endilangt í\n"
    .string "djúpum og notalegum svefni.$"

Route16_Text_CyclingRoadSign::
    .string "Njóttu brekkunnar! HJÓLAVEGURINN$"

Route16_Text_RouteSign::
    .string "LEIÐ 16 CELADON BORG - FUCHSIA BORG$"

Route16_Text_JedIntro::
    .string "JED: Ást okkar þekkir engin mörk.\n"
    .string "Við erum ástfangin og sýnum það!$"

Route16_Text_JedDefeat::
    .string "JED: Ó, nei! Ástin mín sá mig sem\n"
    .string "tapara!$"

Route16_Text_JedPostBattle::
    .string "JED: Hlustaðu, LEA. Þú þarft að\n"
    .string "hugsa aðeins minna um mig.$"

Route16_Text_JedNotEnoughMons::
    .string "JED: Þú átt bara eitt vasaskrímsli?\n"
    .string "Er engin ást í hjarta þínu?$"

Route16_Text_LeaIntro::
    .string "LEA: Stundum hræðir styrkur ástar\n"
    .string "okkar mig.$"

Route16_Text_LeaDefeat::
    .string "LEA: Óó! En JED er svalur jafnvel\n"
    .string "þegar hann tapar!$"

Route16_Text_LeaPostBattle::
    .string "LEA: Ehehe, fyrirgefðu. JED er svo\n"
    .string "svalur.$"

Route16_Text_LeaNotEnoughMons::
    .string "LEA: Ó, þú ert ekki með tvö\n"
    .string "vasaskrímsli með þér?\p"
    .string "Finnst þér það ekki einmanalegt\n"
    .string "fyrir þig eða vasaskrímslið þitt?$"
