Route6_Text_RickyIntro::
    .string "Hver er þarna? Hættu að hlusta á\n"
    .string "okkur!$"

Route6_Text_RickyDefeat::
    .string "Ég get bara ekki unnið!$"

Route6_Text_RickyPostBattle::
    .string "Whisper… Whisper…$"

Route6_Text_NancyIntro::
    .string "Afsakaðu! Þetta er einkasamtal!$"

Route6_Text_NancyDefeat::
    .string "Ugh! I hate losing.$"

Route6_Text_NancyPostBattle::
    .string "Whisper… Whisper…$"

Route6_Text_KeigoIntro::
    .string "Það eru ekki margar pöddur hérna\n"
    .string "úti.$"

Route6_Text_KeigoDefeat::
    .string "Nei! Þú hlýtur að vera að grínast!$"

Route6_Text_KeigoPostBattle::
    .string "Mér líkar við pöddur, svo ég fer\n"
    .string "aftur í VIRIDIAN-SKÓG.$"

Route6_Text_JeffIntro::
    .string "Ha? Viltu tala við mig?$"

Route6_Text_JeffDefeat::
    .string "Þetta er ömurlegt... Ég náði ekki að\n"
    .string "standast áskorunina þína...$"

Route6_Text_JeffPostBattle::
    .string "Ég ætti að taka fleiri vasaskrímsli\n"
    .string "með mér. Þá finnst mér ég öruggari.$"

Route6_Text_IsabelleIntro::
    .string "Ég? Jæja, allt í lagi. Ég skal\n"
    .string "leika!$"

Route6_Text_IsabelleDefeat::
    .string "Þetta gekk bara ekki upp…$"

Route6_Text_IsabellePostBattle::
    .string "Mig langar að verða sterkari. Hvert\n"
    .string "er leyndarmálið þitt?$"

Route6_Text_ElijahIntro::
    .string "Ég hef aldrei séð þig hér. Ertu\n"
    .string "góður?$"

Route6_Text_ElijahDefeat::
    .string "Þú ert of góður!$"

Route6_Text_ElijahPostBattle::
    .string "Eru vasaskrímslin mín veik? Eða er\n"
    .string "ég bara slæmur? Hvað heldurðu?$"

Route6_Text_UndergroundPathSign::
    .string "JARÐGÖNG CERULEAN BORG - VERMILION\n"
    .string "BORG$"

