CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Aðeins hæfir ÞJÁLFARAR geta safnað\n"
    .string "vasaskrímsla-MERKJUM.\p"
    .string "Ég sé að þú ert með að minnsta kosti\n"
    .string "eitt.\p"
    .string "Þessi MERKI geyma ótrúleg\n"
    .string "leyndarmál, vissirðu það?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Jæja...\p"
    .string "Hvaða af átta MERKJUNUM viltu að ég\n"
    .string "lýsi?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Komdu hvenær sem þú vilt.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "ÁRÁS gildi allra vasaskrímslanna\n"
    .string "þinna hækkar örlítið.\p"
    .string "Það leyfir þér líka að nota FLASH\n"
    .string "utan bardaga.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "Vasaskrímsli upp að Lv. 30 hlýða\n"
    .string "þér.\p"
    .string "Það gildir líka um þau sem þú færð í\n"
    .string "skiptum.\p"
    .string "Vasaskrímsli á hærri stigum verða þó\n"
    .string "óstýrilát í bardaga.\p"
    .string "Það leyfir þér líka að nota CUT utan\n"
    .string "bardaga.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "SPEED gildi allra vasaskrímslanna\n"
    .string "þinna hækkar örlítið.\p"
    .string "Það leyfir þér líka að nota FLY utan\n"
    .string "bardaga.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "Vasaskrímsli upp að Lv. 50 hlýða\n"
    .string "þér.\p"
    .string "Það gildir líka um þau sem þú færð í\n"
    .string "skiptum.\p"
    .string "Vasaskrímsli á hærri stigum verða þó\n"
    .string "óstýrilát í bardaga.\p"
    .string "Það leyfir þér líka að nota STRENGTH\n"
    .string "utan bardaga.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "DEFENSE gildi allra vasaskrímslanna\n"
    .string "þinna hækkar örlítið.\p"
    .string "Það leyfir þér líka að nota BRIM\n"
    .string "utan bardaga.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "Vasaskrímsli upp að Lv. 70 hlýða\n"
    .string "þér.\p"
    .string "Það gildir líka um þau sem þú færð í\n"
    .string "skiptum.\p"
    .string "Vasaskrímsli á hærri stigum verða þó\n"
    .string "óstýrilát í bardaga.\p"
    .string "Það leyfir þér líka að nota ROCK\n"
    .string "SMASH utan bardaga.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "SP. ATK og SP. DEF gildi allra\n"
    .string "vasaskrímslanna þinna hækka örlítið.\p"
    .string "Það leyfir þér líka að nota\n"
    .string "WATERFALL utan bardaga.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "Öll vasaskrímsli hlýða þér!$"
