ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Vinsamlegast notaðu tölvuna þarna í\n"
    .string "horninu.\p"
    .string "Móttökustúlkan sagði mér það. Hún er\n"
    .string "svo vinsamleg!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "Það er Vasaskrímslasetur í hverjum\n"
    .string "bæ héðan í frá.\p"
    .string "Þau rukka ekkert, svo ekki hika við\n"
    .string "að lækna Vasaskrímslin.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "Vasaskrímslasetur lækna þreytt,\n"
    .string "særð eða yfirliðin Vasaskrímsli.\p"
    .string "Þau koma öllum Vasaskrímslum í\n"
    .string "fulla heilsu.$"
