Route3_Text_TunnelFromCeruleanTiring::
    .string "Púff... ég ætti að hvíla mig...\n"
    .string "Styn...\p"
    .string "Göngin frá CERULEAN taka verulega á!$"

Route3_Text_ColtonIntro::
    .string "Hey! Ég sá þig í VIRIDIAN-SKÓGI!$"

Route3_Text_ColtonDefeat::
    .string "Þú vannst mig aftur!$"

Route3_Text_ColtonPostBattle::
    .string "Það eru til aðrar gerðir\n"
    .string "vasaskrímsla en þær sem þú finnur í\p"
    .string "skógum.$"

Route3_Text_BenIntro::
    .string "Hæ! Mér finnst stuttbuxur frábærar!\p"
    .string "Þær eru dásamlega þægilegar og\n"
    .string "auðveldar í notkun!$"

Route3_Text_BenDefeat::
    .string "Ég trúi þessu ekki!$"

Route3_Text_BenPostBattle::
    .string "Notarðu tölvu í vasaskrímslasetri til\n"
    .string "að geyma vasaskrímslin þín?\p"
    .string "Hver KASSI rúmar allt að 30\n"
    .string "vasaskrímsli.$"

Route3_Text_JaniceIntro::
    .string "Afsakaðu! Þú horfðir á mig, ekki\n"
    .string "satt?$"

Route3_Text_JaniceDefeat::
    .string "Þú ert vondur!$"

Route3_Text_JanicePostBattle::
    .string "Þú ættir ekki að stara ef þú vilt\n"
    .string "ekki berjast!$"

Route3_Text_GregIntro::
    .string "Ertu ÞJÁLFARI? Byrjum þá strax!$"

Route3_Text_GregDefeat::
    .string "Ef ég ætti ný vasaskrímsli hefði ég\n"
    .string "unnið!$"

Route3_Text_GregPostBattle::
    .string "Ef KASSI í tölvunni fyllist skaltu\n"
    .string "bara skipta yfir í annan KASSA.$"

Route3_Text_SallyIntro::
    .string "Þetta augnaráð sem þú gafst mér...\n"
    .string "Það er svo spennandi!$"

Route3_Text_SallyDefeat::
    .string "Vertu almennilegur!$"

Route3_Text_SallyPostBattle::
    .string "Þú getur forðast bardaga með því að\n"
    .string "láta ÞJÁLFARA ekki sjá þig.$"

Route3_Text_CalvinIntro::
    .string "Hey! Þú ert ekki í stuttbuxum! Hvað\n"
    .string "er að þér?$"

Route3_Text_CalvinDefeat::
    .string "Tapaði! Tapaði! Tapaði!$"

Route3_Text_CalvinPostBattle::
    .string "Ég geng alltaf í stuttbuxum, jafnvel\n"
    .string "á veturna. Það er mín regla.$"

Route3_Text_JamesIntro::
    .string "Ég berst við þig með vasaskrímslunum\n"
    .string "sem ég náði rétt áðan.$"

Route3_Text_JamesDefeat::
    .string "Kláraður eins og kvöldmatur!$"

Route3_Text_JamesPostBattle::
    .string "Þjálfuð vasaskrímsli eru sterkari en\n"
    .string "villt.$"

Route3_Text_RobinIntro::
    .string "Ííík! Snertirðu mig?$"

Route3_Text_RobinDefeat::
    .string "Var það allt?$"

Route3_Text_RobinPostBattle::
    .string "VEGUR 4 er við rætur MÁNAFJALLS.$"

Route3_Text_RouteSign::
    .string "VEGUR 3 MÁNAFJALL FRAMUNDAN$"
