SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
    .string "Vasaskrímsli hafa eigin\n"
    .string "persónuleika, alveg eins og fólk.\p"
    .string "LEIFTURSKO mín er með HASTY eðli,\n"
    .string "svo hún varð mjög hraðskreitt\p"
    .string "Vasaskrímsli.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
    .string "Jæja, undirbúningurinn er búinn. Nú\n"
    .string "kanna ég RÚSTIRNAR.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
    .string "Ég þarf að fiska á SJÖUNDU EYJU.\p"
    .string "Þá er veiðiferð minni um SEVII-EYJAR\n"
    .string "lokið.\p"
    .string "En fyrst þarf ég að birgja mig upp\n"
    .string "af Vasa boltum.$"

