Text_DoubleEdgeTeach::
    .string "Þú ættir að vera stolt af þér fyrir\n"
    .string "að hafa barist svo hugrakklega\p"
    .string "í gegnum SIGURVEG.\p"
    .string "Til viðurkenningar á afrekinu skal\n"
    .string "ég kenna þér TVÍEGGJAÐ.\p"
    .string "Viltu að ég kenni þessa\n"
    .string "tækni?$"

Text_DoubleEdgeDeclined::
    .string "Ég kenni þér tæknina\n"
    .string "hvenær sem er.$"

Text_DoubleEdgeWhichMon::
    .string "Hvaða Vasaskrímsli á ég að kenna\n"
    .string "TVÍEGGJAÐ?$"

Text_DoubleEdgeTaught::
    .string "Haltu þessum krafti gangandi fyrir\n"
    .string "VASASKRÍMSLADEILDINA!\p"
    .string "Ráðist á þau og sláið þau\n"
    .string "út!$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "Ég heyrði sögusagnir um undrabarn.$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "Sögusagnirnar voru sannar!$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "Svo það varst þú sem sigraðir\n"
    .string "GIOVANNI úr ROCKET-GENGINU?$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "ÞJÁLFARAR lifa til að leita að\n"
    .string "sterkari andstæðingum.$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "Ó! Þvílíkur styrkur!$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "Með því að berjast í hörðum bardögum\n"
    .string "verðurðu sterkari.$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "Ég skal sýna þér hvað í þér býr.\n"
    .string "Eða ekki!$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "Ég er brjáluð!$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "Þú sýndir mér hvað í mér bjó…$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "Aðeins hin útvöldu mega fara hér!$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "Ég trúi þessu ekki!$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "Allir ÞJÁLFARAR hér stefna í\n"
    .string "VASASKRÍMSLADEILDINA.\p"
    .string "Ekki slaka á verðinum.$"

VictoryRoad_3F_Text_RayIntro::
    .string "RAY: Saman erum við tvö\n"
    .string "sköpuð til mikilleika!$"

VictoryRoad_3F_Text_RayDefeat::
    .string "RAY: Fáránlegt! Þetta getur ekki verið!$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "RAY: Þú sigraðir okkur. Mikilleikinn\n"
    .string "rennur okkur úr greipum…$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "RAY: Saman stefnum við tvö\n"
    .string "á tindinn.\p"
    .string "Þú þarft að koma með tvö\n"
    .string "Vasaskrímsli í bardaga við okkur.$"

VictoryRoad_3F_Text_TyraIntro::
    .string "TYRA: Við ætlum að verða\n"
    .string "meistarar saman.$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "TYRA: Ó, en…$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "TYRA: Þú kenndir mér að kraftur\n"
    .string "getur birst í ótal myndum.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "TYRA: Þú getur ekki barist við\n"
    .string "okkur með bara eitt Vasaskrímsli.$"
