FiveIsland_Text_IslandSign::
    .string "FIVE EYJA Tímaeyja: Þar sem tíminn\n"
    .string "líður$"

FiveIsland_Text_WeirdBuildingInMeadow::
    .string "Ó, þetta er ömurlegt. Ég vildi leika\n"
    .string "mér á ENGINU.\p"
    .string "En þau settu upp undarlega byggingu\n"
    .string "á því, svo ég get ekki leikið mér\p"
    .string "þar.$"

FiveIsland_Text_BeenGettingBusierAroundHere::
    .string "Það hefur verið að verða fjölmennara\n"
    .string "hér um slóðir undanfarið.\p"
    .string "Mér hefur ekki gengið vel að veiða\n"
    .string "góðan fisk undanfarið heldur.$"

