ViridianForest_Text_FriendsItchingToBattle::
    .string "Ég kom hingað með vinum til að ná\n"
    .string "okkur í SKORDÝRA Vasaskrímsli!\p"
    .string "Þau eru öll spennt að komast í\n"
    .string "Vasaskrímsla bardaga!$"

ViridianForest_Text_RickIntro::
    .string "Hey! Þú átt Vasaskrímsli! Komdu!\n"
    .string "Berjumst!$"

ViridianForest_Text_RickDefeat::
    .string "Nei! CATERPIE ræður ekki við þetta!$"

ViridianForest_Text_RickPostBattle::
    .string "Suss! Þú hræðir pöddurnar burt.\n"
    .string "Seinna, allt í lagi?$"

ViridianForest_Text_DougIntro::
    .string "Jæja! Þú getur ekki slakað á ef þú\n"
    .string "ert Vasaskrímsla ÞJÁLFARI!$"

ViridianForest_Text_DougDefeat::
    .string "Ha? Ég varð uppiskroppa með\n"
    .string "Vasaskrímsli!$"

ViridianForest_Text_DougPostBattle::
    .string "Þetta er ömurlegt! Ég ætla að\n"
    .string "veiða mér sterkari!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, bíddu! Hvar er eldurinn? Af\n"
    .string "hverju liggur svona á?$"

ViridianForest_Text_SammyDefeat::
    .string "Ég gefst upp! Þú ert góður í þessu!$"

ViridianForest_Text_SammyPostBattle::
    .string "Stundum finnur maður hluti á\n"
    .string "jörðinni.\p"
    .string "Ég er að leita að því sem ég missti.\n"
    .string "Geturðu hjálpað mér?$"

ViridianForest_Text_AnthonyIntro::
    .string "Ég er kannski lítill, en mér líkar\n"
    .string "ekki ef þú ferð mjúkum höndum!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Ó, æi. Ekkert gekk upp.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "Ég tapaði hluta vasapeninganna…$"

ViridianForest_Text_CharlieIntro::
    .string "Vissirðu að Vasaskrímsli þróast?$"

ViridianForest_Text_CharlieDefeat::
    .string "Ó! Ég tapaði!$"

ViridianForest_Text_CharliePostBattle::
    .string "SKORDÝRA Vasaskrímsli þróast hratt.\n"
    .string "Þau eru ótrúlega skemmtileg!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "Ég var að kasta VASA BOLTUM til að\n"
    .string "ná Vasaskrímslum, og ég kláraði þá.\p"
    .string "Þess vegna geturðu aldrei átt of\n"
    .string "marga VASA BOLTA.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Ef Vasaskrímslin þín eru veik og þú\n"
    .string "vilt forðast bardaga, haltu þig frá\p"
    .string "grasflötum!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "Við eitrun skaltu nota MÓTEITUR!\n"
    .string "Fáðu það í Vasaskrímslabúð!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Notaðu tölvu til að ná sambandi við\n"
    .string "Prófessor EIK og fá VasaDEX metið!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Þú getur ekki náð Vasaskrímsli sem\n"
    .string "tilheyrir einhverjum öðrum.\p"
    .string "Kastaðu VASA BOLTUM aðeins á villt\n"
    .string "Vasaskrímsli til að ná þeim!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Veiktu Vasaskrímsli áður en þú\n"
    .string "reynir að ná þeim!\p"
    .string "Ef þau eru heilbrigð gætu þau\n"
    .string "sloppið!$"

ViridianForest_Text_LeavingViridianForest::
    .string "FER ÚT ÚR VIRIDIAN SKÓGI PEWTER BORG\n"
    .string "FRAMUNDAN$"
