ViridianForest_Text_FriendsItchingToBattle::
    .string "I came here with some friends to\n"
    .string "ná okkur í SKORDÝ Vasaskrímsli!\p"
    .string "They're all itching to get into some\n"
    .string "Vasaskrímsli battles!$"

ViridianForest_Text_RickIntro::
    .string "Hey! You have Vasaskrímsli! Come on!\n"
    .string "Let's battle 'em!$"

ViridianForest_Text_RickDefeat::
    .string "Nei! CATERPIE ræður ekki við þetta!$"

ViridianForest_Text_RickPostBattle::
    .string "Suss! Þú hræðir pöddurnar burt.\n"
    .string "Seinna, allt í lagi?$"

ViridianForest_Text_DougIntro::
    .string "Yo! You can't jam out if you're a\n"
    .string "Vasaskrímsli ÞJÁLFARI!$"

ViridianForest_Text_DougDefeat::
    .string "Huh? I ran out of Vasaskrímsli!$"

ViridianForest_Text_DougPostBattle::
    .string "Þetta er ömurlegt! Ég ætla að\n"
    .string "veiða mér sterkari!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, bíddu! Hver er flýtirinn? Af\n"
    .string "hverju er svona brátt?$"

ViridianForest_Text_SammyDefeat::
    .string "Ég gefst upp! Þú ert góður í þessu!$"

ViridianForest_Text_SammyPostBattle::
    .string "Stundum finnur maður hluti á\n"
    .string "jörðinni.\p"
    .string "Ég er að leita að því sem ég missti.\n"
    .string "Geturðu hjálpað mér?$"

ViridianForest_Text_AnthonyIntro::
    .string "Ég er kannski lítill, en mér líkar\n"
    .string "ekki ef þú ferð mjúkum höndum!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Ó, æi. Ekkert gekk upp.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "Ég tapaði hluta vasapeninganna…$"

ViridianForest_Text_CharlieIntro::
    .string "Did you know that Vasaskrímsli\n"
    .string "evolve?$"

ViridianForest_Text_CharlieDefeat::
    .string "Ó! Ég tapaði!$"

ViridianForest_Text_CharliePostBattle::
    .string "SKORDÝ Vasaskrímsli þróast hratt.\n"
    .string "They're a lot of fun!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "I was throwing VASA BOLTAR to catch\n"
    .string "Vasaskrímsli, and I ran out.\p"
    .string "That's why you can never have too\n"
    .string "many VASA BOLTAR.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "If your Vasaskrímsli are weak and\n"
    .string "you want to avoid battles, stay away\p"
    .string "from grassy areas!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "For poison, use ANTIDOTE! Get it at\n"
    .string "Vasaskrímsli MARTS!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Hafðu samband við Prófessor EIK í PC\n"
    .string "til að fá VasaDEX metið!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "You can't catch a Vasaskrímsli that\n"
    .string "belongs to someone else.\p"
    .string "Throw VASA BOLTAR only at wild\n"
    .string "Vasaskrímsli to catch them!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Weaken Vasaskrímsli before\n"
    .string "attempting capture!\p"
    .string "When healthy, they may escape!$"

ViridianForest_Text_LeavingViridianForest::
    .string "FER ÚT ÚR VIRIDIAN SKÓGI PEWTER BORG\n"
    .string "FRAMUNDAN$"
