SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .string "Ég lít kannski ekki út fyrir mikið\n"
    .string "núna, en þegar ég var yngri…\p"
    .string "Ég flaug út um allt og skoraði á\n"
    .string "ÞJÁLFARA hvar sem ég fann þá.\p"
    .string "Nú er eina ánægjan mín að rifja upp\n"
    .string "liðna tíð á meðan ég horfi á\p"
    .string "bardaga.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .string "Það er lítil gola sem blæs umhverfis\n"
    .string "kassann.$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
    .string "Ah! Velkomin/n, vinur minn!\p"
    .string "Leyfðu mér að segja þér eitt. Það er\n"
    .string "falið herbergi í kjallaranum.\p"
    .string "ÞJÁLFARI að nafni {STR_VAR_1} bíður\n"
    .string "þar núna.\p"
    .string "Segðu mér, þú komst til að skora á\n"
    .string "{STR_VAR_1}, er það ekki?$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
    .string "Ó… Þú ætlar ekki að berjast…\p"
    .string "Ég skil, ég skil. … …\p"
    .string "Jæja, ef þú skiptir um skoðun, komdu\n"
    .string "þá aftur.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
    .string "Ah! Þú ætlar að berjast fyrir mig?\p"
    .string "Þá var þess virði að færa kassann\n"
    .string "til hliðar.\p"
    .string "… … En það er eitt smávandamál.\p"
    .string "Þetta falda herbergi er ekki mjög\n"
    .string "traust.\p"
    .string "Geturðu takmarkað þetta við þrjú\n"
    .string "Vasaskrímsli á hvora hlið?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
    .string "Allt í lagi! Fyrir bardagann þinn,\n"
    .string "viltu vista leikinn þinn?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
    .string "Allt í lagi. Ekki halda aftur af þér!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
    .string "Leikurinn endaði jafntefli.$"

SevenIsland_House_Room1_Text_DrawWasIt::
    .string "Jafntefli, var það?\p"
    .string "Hins vegar, leyfðu mér að segja að\n"
    .string "það var verðugt sjónarspil.\p"
    .string "Ég myndi segja að þetta hafi verið\n"
    .string "dásamlegur bardagi með raunverulegri\p"
    .string "dýpt!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
    .string "Bravo!\p"
    .string "Bravo, sannarlega! Hvílíkur\n"
    .string "stórkostlegur bardagi!\p"
    .string "Hann var svo stórkostlegur, að hann\n"
    .string "fyllir augun mín tárum!\p"
    .string "Árásir og varnir af snilldarlega\n"
    .string "notuðum tækni!\p"
    .string "Árekstur krafts á kraft!\p"
    .string "Já! Þetta var hreinn glæsileiki!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
    .string "Leitt! Ég finn fyrir vonbrigðum\n"
    .string "þínum.\p"
    .string "En þessi vonbrigði munu gera þig\n"
    .string "betri.\p"
    .string "Nýttu þau, lærðu af þeim og láttu\n"
    .string "þau knýja þig til afreka.\p"
    .string "Gleymdu ekki þessum vonbrigðum, og\n"
    .string "tvöfaldaðu þjálfunina!$"
