FiveIsland_House1_JPText_HusbandWentOffFishing::
    .string "こんばんの おかずは ようい しなくて いいぞ！\p"
    .string "って だんなが つりに いったん だけど‥ しんじて いいのかねえ$"

FiveIsland_House1_Text_HusbandWentOffFishing::
    .string "Ekki hafa áhyggjur af því að kaupa\n"
    .string "eitthvað í kvöldmatinn!\p"
    .string "…Það sagði maðurinn minn þegar hann\n"
    .string "fór að veiða í dag.\p"
    .string "Ég er ekki viss um að ég geti treyst\n"
    .string "á að hann standi við það.$"

