MtMoon_B2F_Text_MiguelIntro::
    .string "Heyrðu, stoppaðu!\p"
    .string "Ég fann þessa steingervinga! Þeir\n"
    .string "eru báðir mínir!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Allt í lagi! Ég skal deila!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "Við tökum hvort sinn steingerving!\n"
    .string "Enga græðgi!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "Allt í lagi. Þá er þessi\n"
    .string "steingervingur minn!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Langt í burtu, á CINNABAR EYJU, er\n"
    .string "Vasaskrímsla-rannsóknarstofa.\p"
    .string "Þar er rannsakað hvernig endurlífga\n"
    .string "má steingervinga.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "Við, ROCKET-GENGIÐ, munum finna\n"
    .string "steingervingana!\p"
    .string "Ef við endurlífgum vasaskrímsli úr\n"
    .string "þeim græðum við stórfé!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "Urgh! Nú er ég reiður!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "Þú gerðir mig reiðan! ROCKET-GENGIÐ\n"
    .string "setur þig á svartan lista!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "Við í ROCKET-GENGINU erum glæpamenn\n"
    .string "vasaskrímslaheimsins! Við vekjum\p"
    .string "ótta með styrk okkar!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "Ég klúðraði þessu!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "Fjandinn hafi það! Félagar mínir\n"
    .string "sætta sig ekki við þetta!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "Við erum með stórt verk hér! Hypjaðu\n"
    .string "þig, krakki!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "Þú ert þá góður...$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "Ef þú finnur steingerving, láttu mig\n"
    .string "fá hann og hypjaðu þig!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "Lítil börn ættu ekki að flækjast í\n"
    .string "mál fullorðinna!\p"
    .string "Það gæti endað illa!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "Ég er brjálaður!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "Vasaskrímsli bjuggu hér löngu áður\n"
    .string "en menn komu.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "Viltu HVOLFGERVING?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "Viltu SPÍRALGERVING?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "Fékkst SPÍRALGERVING!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "Fékkst HVOLFGERVING!$"

