FiveIsland_LostCave_Room1_Text_LawsonIntro::
    .string "Aiyeeeeeh!\p"
    .string "Ég hélt að þetta væri fornar rústir.\n"
    .string "En það er fullt af draugum!$"

FiveIsland_LostCave_Room1_Text_LawsonDefeat::
    .string "Aiyeeeeeh! Miskunn!$"

FiveIsland_LostCave_Room1_Text_LawsonPostBattle::
    .string "Ég er að reyna að komast héðan út,\n"
    .string "en enda alltaf á sama stað.\p"
    .string "Kannski er fjöldi grjótanna\n"
    .string "vísbending…$"

