TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "Hvert skyldi LOSTELLE hafa farið í\n"
    .string "dag?\p"
    .string "Hún færir mér alltaf hádegismat um\n"
    .string "þetta leyti…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "Hm? Þú þarna! Ertu vinur LOSTELLE?\p"
    .string "Hefurðu séð LOSTELLE hér í kring? Ég\n"
    .string "veit ekki hvar hún gæti verið. Hún\p"
    .string "hefði átt að vera komin fyrir löngu.\p"
    .string "LOSTELLE er krútt - hún fékk útlitið\n"
    .string "frá mér - en hvað ef einhver…\p"
    .string "Hvað ef eitthvað hefur komið fyrir\n"
    .string "LOSTELLE mína?!\p"
    .string "Vinsamlegast hjálpaðu mér að finna\n"
    .string "hana! Leitaðu á ÞRJÚ EYJU!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "Ha? Hvað er þetta fyrir\n"
    .string "LEIKJAKRÓKUR? Getur þetta orðið\p"
    .string "ömurlegra?\p"
    .string "Þessir trúðar…\p"
    .string "Þeir sögðust bíða á eyjunni, svo\n"
    .string "hvar eru þeir?\p"
    .string "Hey, þú! Er þetta eina ÞRJÚ EYJAN\n"
    .string "hér í kring?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "Reyndu að vakna áður en þú skríður\n"
    .string "upp úr rúminu, bjáni.\p"
    .string "Þetta er TVÖ EYJA!\p"
    .string "Hafðu þig! Fáðu skítuga mótorhjólið\n"
    .string "þitt út úr staðnum mínum!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "Ha… Ó, ó, ég skil.\p"
    .string "Tsk… Þessar eyjar eru ruglingslegar…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "Sjáðu þetta! Þessi óþokki rispaði\n"
    .string "gólfið mitt.$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "Heyrðu samt! Ég grátbið þig, þú\n"
    .string "verður að fara til ÞRJÚ EYJU.\p"
    .string "Ef eitthvað kæmi fyrir LOSTELLE\n"
    .string "mína…\p"
    .string "Húsið mitt er með rauðu þaki á ÞRJÚ\n"
    .string "EYJU.\p"
    .string "Hún gæti bara komið seint hingað,\n"
    .string "svo ég get ekki hlaupið neitt.\p"
    .string "Þess vegna verð ég að biðja þig um\n"
    .string "þennan stóra greiða.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "Fyrirgefðu. Við erum ekki með neina\n"
    .string "leiki í dag.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "Við komum leikjunum bráðum í gang\n"
    .string "fyrir þig!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "Þú bjargaðir LOSTELLE? Hvernig get\n"
    .string "ég þakkað þér?\p"
    .string "LOSTELLE, elskan, fyrirgefðu!\p"
    .string "Pabbi vissi ekki að þú værir hrædd\n"
    .string "og í vanda!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "LOSTELLE: Það er í lagi, pabbi. Ég\n"
    .string "varð vinur {PLAYER}!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "Ó, hvað er þetta? Ertu að segja að\n"
    .string "þetta sé handa mér?\p"
    .string "Hvernig vissirðu að ég elska\n"
    .string "sjaldgæfa steina og gimsteina?\p"
    .string "Þú kannt sko að gleðja mann.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER} afhenti pabba LOSTELLE\n"
    .string "LOFTSTEININN.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "Ó, ég skil, þetta er frá BILL!\n"
    .string "Þakkaðu honum fyrir mig!\p"
    .string "Þú hefur verið frábær. Ég vil að þú\n"
    .string "eigir þetta.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "{PLAYER} fékk TUNGLSTEIN frá pabba\n"
    .string "LOSTELLE.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "TASKAN þín rúmar ekki meira…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "Allt í lagi, ég kem LEIKJAKRÓKNUM í\n"
    .string "gang strax.\p"
    .string "Þú verður að koma í heimsókn með\n"
    .string "vini.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "Heyrðu, heyrðu!\p"
    .string "Sýndu mér aftur hvað þú ert\n"
    .string "flott/ur!$"
