Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Hey! {PLAYER}!\p"
	.string "Ertu á leið í Vasaskrímsladeildina?\n"
	.string "Gleymdu því!\p"
	.string "Þú ert líklega ekki með nein MERKI,\n"
	.string "er það?\p"
	.string "Vörðurinn hleypir þér ekki í gegn án\n"
	.string "þeirra.\p"
	.string "Annars, eru Vasaskrímslin þín orðin\n"
	.string "eitthvað sterkari?$"

Route22_Text_EarlyRivalDefeat::
	.string "Awww! Þú varst bara heppinn!$"

Route22_Text_EarlyRivalPostBattle::
	.string "Ég heyrði að Vasaskrímsladeildin\n"
	.string "væri full af hörðum ÞJÁLFURUM.\p"
	.string "Ég þarf að finna leið fram hjá þeim.\p"
	.string "Þú ættir að hætta að hangsast og\n"
	.string "koma þér af stað!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 Vasaskrímsli? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}'なんだ？ ポケモン 2ひきも もってるの なぜか\n"
	.string "だって？\p"
	.string "おまえも つかまえれば いい じゃん！$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: Hvað? {PLAYER}! Það kemur á\n"
	.string "óvart að sjá þig hér!\p"
	.string "Svo þú ert á leið í\n"
	.string "Vasaskrímsladeildina?\p"
	.string "Þú safnaðir líka öllum MERKJUNUM?\n"
	.string "Flott!\p"
	.string "Þá rústa ég þér, {PLAYER}, sem\n"
	.string "upphitun fyrir Vasaskrímsladeildina!\p"
	.string "Komdu!$"

Route22_Text_LateRivalDefeat::
	.string "Hvað!?\p"
	.string "Ég var bara kærulaus, þú!$"

Route22_Text_LateRivalPostBattle::
	.string "Þetta kom mér í gang. Ég er tilbúinn\n"
	.string "í Vasaskrímsladeildina!\p"
	.string "{PLAYER}, þú þarft meiri æfingu.\p"
	.string "En þú veist það sjálf/ur! Ég er\n"
	.string "farinn. Sjáumst!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}'ひゃははッ {PLAYER}ー！ それで\n"
	.string "がんばってるのかよ！ おれの さいのうに くらべりゃ {PLAYER}は\p"
	.string "まだまだ だな！\p"
	.string "もっと れんしゅう こいよ！ あははーッ！$"

Route22_Text_LeagueGateSign::
	.string "VASASKRÍMSLADEILDARHLIÐ$"
