OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "Að liggja aftur, vaggandi af\n"
    .string "öldunum… Það er stórkostlegt.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "Ég tapaði… Það er hræðileg tilfinning.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "Sjórinn er notalega hlýr hér um\n"
    .string "slóðir.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "Góðir hlutir skola upp á þessa\n"
    .string "strönd með sjávarstraumnum.\p"
    .string "Þess vegna kem ég oft hingað til að\n"
    .string "leita að strandgóssi.$"
