SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "FORSTJÓRI: Ó, kæri drengur! Takk\n"
    .string "fyrir að bjarga SILPH.\p"
    .string "Ég gleymi aldrei að þú bjargaðir\n"
    .string "okkur á hættustundu.\p"
    .string "Ég verð að þakka þér á einhvern hátt.\p"
    .string "Þar sem ég er ríkur get ég gefið\n"
    .string "þér hvað sem er.\p"
    .string "Hér, kannski dugar þetta.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "FORSTJÓRI: Ó, kæra stúlka! Takk\n"
    .string "fyrir að bjarga SILPH.\p"
    .string "Ég gleymi aldrei að þú bjargaðir\n"
    .string "okkur á hættustundu.\p"
    .string "Ég verð að þakka þér á einhvern hátt.\p"
    .string "Þar sem ég er ríkur get ég gefið\n"
    .string "þér hvað sem er.\p"
    .string "Hér, kannski dugar þetta.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} fékk MEISTARABOLTA frá\n"
    .string "FORSTJÓRANUM!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "FORSTJÓRI: Þetta er hvergi hægt\n"
    .string "að kaupa.\p"
    .string "Þetta er leynilega frumgerð okkar,\n"
    .string "MEISTARABOLTI.\p"
    .string "Hann fangar hvaða Vasaskrímsli sem\n"
    .string "er, án þess að bregðast!\p"
    .string "Þú ættir samt að hafa hljótt um\n"
    .string "notkun hans.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "Þú hefur ekki pláss fyrir þetta.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "RITARI: Takk fyrir að bjarga\n"
    .string "okkur öllum.\p"
    .string "Við, allt frá FORSTJÓRANUM og niður,\n"
    .string "stöndum í þakkarskuld við þig.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "Ah, {PLAYER}! Við hittumst aftur!\p"
    .string "FORSTJÓRINN og ég erum að ræða\n"
    .string "afar mikilvægt viðskiptamál.\p"
    .string "Haltu nefinu frá málefnum fullorðinna…\p"
    .string "Annars kynnistu sársauka!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "Arrgh!! Ég tapaði aftur!?$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "Fjárinn hafi það! Þú eyðilagðir\n"
    .string "áætlanir okkar um SILPH!\p"
    .string "En ROCKET-GENGIÐ mun aldrei falla!\p"
    .string "{PLAYER}! Gleymdu aldrei að öll\n"
    .string "Vasaskrímsli eru til fyrir ROCKET-GENGIÐ!\p"
    .string "Ég verð að fara, en ég mun snúa aftur!$"

SilphCo_11F_Text_Grunt2Intro::
    .string "Stansaðu þarna! Ekki hreyfa þig!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "Ekki… Vinsamlegast!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "Svo þú vilt hitta FORINGJANN minn?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "Stans! Átt þú bókaðan tíma\n"
    .string "hjá FORINGJANUM mínum?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "Gaah! Tættur í sundur!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Passaðu þig… FORINGINN minn vill\n"
    .string "Vasaskrímslin sín hörð!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "Það eru Vasaskrímsli á skjánum!$"

SilphCo_11F_Text_FloorSign::
    .string "SILPH CO. HÖFUÐSKRIFSTOFA 11H$"
