PokemonMansion_Text_PressSecretSwitch::
    .string "Leynirofi!\p"
    .string "Ýta á hann?$"

PokemonMansion_Text_WhoWouldnt::
    .string "Hver myndi ekki gera það?$"

PokemonMansion_Text_NotQuiteYet::
    .string "Ekki alveg strax!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "Ég kemst ekki út! Þessi gamli staður\n"
    .string "er ein stór þraut.$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "Ó, nei! Ránsfengspokinn minn!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "Rofarnir hér opna og loka til\n"
    .string "skiptis mismunandi dyrum.$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "Dagbók: 5. júlí Guyana,\n"
    .string "Suður-Ameríka\p"
    .string "Nýtt vasaskrímsli fannst djúpt inni\n"
    .string "í frumskóginum.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "Dagbók: 10. júlí Við nefndum\n"
    .string "nýfundna vasaskrímslið MÝTU.$"

