CinnabarIsland_Gym_Text_BlaineIntro::
    .string "Hah!\p"
    .string "Ég er BLAINE, eldheiti SALSTJÓRINN í\n"
    .string "CINNABAR SAL!\p"
    .string "Eldheitu vasaskrímslin mín eru öll\n"
    .string "grimm og tilbúin með brennandi hita!\p"
    .string "Þau brenna alla áskorendur til ösku!\p"
    .string "Hah! Þú ættir að hafa\n"
    .string "BRUNALYF!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "Ég hef brunnið niður í ekkert! Ekki\n"
    .string "einu sinni aska er eftir!\p"
    .string "Þú hefur unnið ELDFJALLSMERKIÐ.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "ELDGOS er fullkomna eldtæknin.\p"
    .string "Ekki eyða henni á\n"
    .string "VATNS-vasaskrímsli.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "Hah!\p"
    .string "ELDFJALLSMERKIÐ hækkar SPECIAL tölur\n"
    .string "vasaskrímslanna þinna.\p"
    .string "Hér, þú mátt fá þetta líka!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER} fékk TM38 frá BLAINE.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "TM38 inniheldur ELDGOS. Kenndu það\n"
    .string "ELD-gerðar vasaskrímslum.\p"
    .string "HALATÓFA eða KAMELDLJÓN væru\n"
    .string "fullkomin fyrir þessa hreyfingu.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "Búðu til pláss fyrir þetta, barn!$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "Veistu hversu heitur eldandinn hjá\n"
    .string "vasaskrímslum getur orðið?$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "Ái! Heitt, heitt, heitt!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "Eldur, eða nánar tiltekið bruni...\p"
    .string "...Súrefni í loftinu... Bla, bla,\n"
    .string "bla, bla...$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "Ég var þjófur, en gerðist\n"
    .string "heiðarlegur sem ÞJÁLFARI.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "Ég gefst upp!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "Ég fæ óstöðvandi löngun til að stela\n"
    .string "vasaskrímslum annarra.$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "Ég hef rannsakað vasaskrímsli í\n"
    .string "þaula. Þú getur ekki unnið!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "Váá! Rannsóknir mínar dugðu ekki!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "Kenningar mínar eru of flóknar til\n"
    .string "að þú skiljir þær.$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "Mér líkar að nota ELD-gerðar\n"
    .string "vasaskrímsli. Bara þannig er það.$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "Of heitt til að höndla!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "Ég vildi að til væri\n"
    .string "þjófa-vasaskrímsli. Ég myndi nota\p"
    .string "það!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "Ég veit af hverju BLAINE varð\n"
    .string "ÞJÁLFARI.$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "Ái!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "SALSTJÓRINN okkar, BLAINE, villtist\n"
    .string "einu sinni í fjöllunum.\p"
    .string "Nótt skall á þegar eldheitt\n"
    .string "fugla-vasaskrímsli birtist.\p"
    .string "Ljósið frá því leyfði BLAINE að\n"
    .string "finna örugga leið niður.$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "Ég hef komið í marga SALI, en þessi\n"
    .string "passar best við minn stíl.$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "Vá! Of heitt!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "LOGALD, NÍRÓFA... Þau eru vinsæl\n"
    .string "ELD-vasaskrímsli.$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "Eldur er veikur gegn H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "Ó! Slökktur!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "Vatn sigrar eld, auðvitað.\p"
    .string "En eldur bræðir ís, svo ELD-gerðin\n"
    .string "sigrar ÍS-gerðar vasaskrímsli.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "Jæja! Verðandi meistari!\p"
    .string "Eldheiti BLAINE er sérfræðingur í\n"
    .string "ELD-vasaskrímslum.\p"
    .string "Slökktu baráttuvilja hans með vatni!\p"
    .string "Þú ættir líka að taka BRUNALYF.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}! Þú sigraðir þennan\n"
    .string "eldhaus!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "CINNABAR VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: BLAINE\p"
    .string "SIGRANDI ÞJÁLFARAR: {RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "CINNABAR VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: BLAINE\p"
    .string "SIGRANDI ÞJÁLFARAR: {RIVAL},\n"
    .string "{PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "Vasaskrímsla-spurningakeppni!\p"
    .string "Svaraðu rétt og dyrnar opnast í\n"
    .string "næsta herbergi.\p"
    .string "Svaraðu rangt og mættu ÞJÁLFARA!\p"
    .string "Ef þú vilt spara vasaskrímslin þín\n"
    .string "fyrir SALSTJÓRANN...\p"
    .string "Þá skaltu svara rétt! Byrjum!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "Þróast LIRFINGUR í PÚPISTI?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "Eru níu opinber VASASKRÍMSLADEILDAR\n"
    .string "MERKI?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "Þróast POTTGORMUR þrisvar?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "Virka rafmagnshreyfingar vel á\n"
    .string "JARÐ-gerðar vasaskrímsli?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "Eru vasaskrímsli af sömu tegund og\n"
    .string "sama stigi ekki eins?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "Inniheldur TM28 GRAFSTEIN?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "Þú hefur algjörlega rétt fyrir þér!\p"
    .string "Haltu áfram inn!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "Fyrirgefðu! Rangt svar!$"

