PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "Hvað!?\p"
    .string "ROCKET-GENGIÐ er á MT. MOON? Ha?\p"
    .string "Ég er í símanum! Hypjaðu þig!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "KRÚTTÍPÚTT: Púú pupúú!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Geisp!\p"
    .string "Þegar KRÚTTÍPÚTT syngur verða\n"
    .string "vasaskrímsli syfjuð...\p"
    .string "...Ég líka... Hrot...$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "Mig langar virkilega í LEIFTURSKO,\n"
    .string "svo ég ætla að skipta BLEIKÁLFUR\p"
    .string "mínum fyrir LEIFTURSKO.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "Ég er að skipta á vasaskrímslum við\n"
    .string "krakkann þarna.\p"
    .string "Ég átti tvö LEIFTURSKO, svo mér\n"
    .string "fannst eins gott að skipta öðru\p"
    .string "þeirra.$"

