SSAnne_B1F_Room1_Text_PhillipIntro::
    .string "Félagi, þú gengur plankann ef þú\n"
    .string "tapar!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .string "Argh! Beaten by a kid!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .string "Þegar við erum úti á sjó reka\n"
    .string "marglyttu-vasaskrímsli stundum hjá.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
    .string "Halló, ókunnugi!\p"
    .string "Ég veit ekki hvort þú ert frá sjónum\n"
    .string "eða fjöllunum, en stoppaðu og\p"
    .string "spjallaðu.\p"
    .string "Öll vasaskrímslin mín eru úr sjónum.$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .string "Fjandinn! Ég lét þennan sleppa!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .string "Ég ætlaði líka að gera þig að\n"
    .string "aðstoðarmanni mínum!$"

