Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "Hæ! Ég er vasaskrímsli... ...Nei, ég\n"
    .string "er það ekki!\p"
    .string "Kallaðu mig BILL! Ég er sannkallaður\n"
    .string "SKRÍMSLASJÚKUR!\p"
    .string "Hey! Hvað á þetta tortryggna\n"
    .string "augnaráð að þýða?\p"
    .string "Ég er ekki að plata þig, félagi.\p"
    .string "Ég klúðraði tilraun og sameinaðist\n"
    .string "vasaskrímsli!\p"
    .string "Svo, hvað segirðu? Hjálpaðu mér hér!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "Hæ! Ég er vasaskrímsli... ...Nei, ég\n"
    .string "er það ekki!\p"
    .string "Kallaðu mig BILL! Ég er sannkallaður\n"
    .string "SKRÍMSLASJÚKUR!\p"
    .string "Hey! Hvað á þetta tortryggna\n"
    .string "augnaráð að þýða?\p"
    .string "Ég er ekki að plata þig, dama.\p"
    .string "Ég klúðraði tilraun og sameinaðist\n"
    .string "vasaskrímsli!\p"
    .string "Svo, hvað segirðu? Hjálpaðu mér hér!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "Bíddu þar til ég er kominn inn í\n"
    .string "TELEPORTER.\p"
    .string "Þegar ég er kominn inn skaltu fara í\n"
    .string "PC-inn minn og keyra frumuskiljuna.$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "Nei!? Vertu nú ekki svona kaldur!\p"
    .string "Komdu nú, þú verður að hjálpa manni\n"
    .string "í verulegum vandræðum!\p"
    .string "Hvað segirðu, stjóri? Plís? Allt í\n"
    .string "lagi? Jæja!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "Nei!? Vertu nú ekki svona köld!\p"
    .string "Komdu nú, þú verður að hjálpa manni\n"
    .string "í verulegum vandræðum!\p"
    .string "Hvað segirðu, dama? Plís? Allt í\n"
    .string "lagi? Jæja!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "BILL: Jááá! Takk, vinur! Ég skulda\n"
    .string "þér greiða!\p"
    .string "Komstu þá til að sjá\n"
    .string "vasaskrímslasafnið mitt?\p"
    .string "Ekki? Það er svekkjandi.\p"
    .string "Ég verð samt að þakka þér... Ó, hér,\n"
    .string "kannski dugar þetta.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "BILL: Jááá! Takk, vinkona! Ég skulda\n"
    .string "þér greiða!\p"
    .string "Komstu þá til að sjá\n"
    .string "vasaskrímslasafnið mitt?\p"
    .string "Ekki? Það er svekkjandi.\p"
    .string "Ég verð samt að þakka þér... Ó, hér,\n"
    .string "kannski dugar þetta.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER} fékk S.S. MIÐA frá BILL.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "Þú ert með of mikið dót!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "Skemmtiferðaskipið S.S. ANNE er í\n"
    .string "VERMILION BORG.\p"
    .string "Ég heyri að margir ÞJÁLFARAR séu\n"
    .string "líka um borð.\p"
    .string "Þeir buðu mér í partíið sitt, en ég\n"
    .string "þoli ekki fín boð.\p"
    .string "Af hverju ferð þú ekki í staðinn\n"
    .string "fyrir mig? Farðu og skemmtu þér vel.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "BILL: Viltu skoða nokkur af\n"
    .string "sjaldgæfu vasaskrímslunum mínum á\p"
    .string "PC-inum?\p"
    .string "Endilega, skoðaðu PC-inn minn.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "TELEPORTER birtist á PC skjánum.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} ræsti frumuskilju\n"
    .string "TELEPORTER-sins.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "Uppáhalds vasaskrímslalisti BILL!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "Hvaða vasaskrímsli viltu sjá?$"

