@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "Aska Vasaskrímslisins míns er geymd\n"
    .string "í VASASKRÍMSLATURNI.\p"
    .string "Þú mátt eiga þessa TM. Ég þarf hana\n"
    .string "ekki lengur…$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "Aska Vasaskrímslisins míns er geymd\n"
    .string "í VASASKRÍMSLATURNI.\p"
    .string "Þú mátt eiga þessa TM. Ég þarf hana\n"
    .string "ekki lengur…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .string "{PLAYER} fékk TM27 frá lítilli\n"
    .string "stelpu.$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .string "TM27 er hreyfing sem heitir RETURN…\p"
    .string "Ef þú kemur vel fram við\n"
    .string "Vasaskrímslið þitt endurgeldur það\p"
    .string "ást þína með\p"
    .string "að leggja sig allt fram í bardaga.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "Þú hefur ekki pláss fyrir þetta.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "Sjáum hvað sjónaukinn hefur að sýna…\p"
    .string "Það er maður að veiða!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "Sjáum hvað sjónaukinn sýnir…\p"
    .string "Það er VASASKRÍMSLATURN!$"
