CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "Ég kom að heimsækja CINNABAR SAL, en\n"
    .string "dyrnar eru kyrfilega læstar.\p"
    .string "Það hlýtur að vera lykill að þeim\n"
    .string "einhvers staðar.\p"
    .string "Gæti hann verið í brunna\n"
    .string "herrasetrinu?\p"
    .string "Vinur SALSTJÓRANS bjó þar víst áður.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "Áttu marga vini?\p"
    .string "Það er auðvitað gaman að tengjast\n"
    .string "gömlu vinunum.\p"
    .string "En hvernig væri að heimsækja\n"
    .string "SAMKOMUHERBERGIÐ öðru hvoru?\p"
    .string "Hver veit, kannski eignastu nýja\n"
    .string "vini.\p"
    .string "Ég held það sé vel þess virði að\n"
    .string "skoða SAMKOMUHERBERGIÐ.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "Vasaskrímsli geta enn lært tækni\n"
    .string "eftir að þróun er stöðvuð.\p"
    .string "Þróun getur beðið þar til nýjar\n"
    .string "hreyfingar hafa lærst.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "BILL: Heyrðu, þú lést mig bíða!\n"
    .string "Tilbúin/n að sigla til EIN EYJU?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "Ó, ertu ekki alveg búinn enn?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "Jæja, þá er það komið. Förum!$"
