PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: Hey, {PLAYER}! Hvað færir\n"
    .string "þig hingað? Er Vasaskrímslið þitt\p"
    .string "dautt?\p"
    .string "Hey! Það er lifandi!\p"
    .string "Ég get að minnsta kosti látið þau\n"
    .string "líða út af! Byrjum!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "Hvað? Þú skítur!\p"
    .string "Ég tók því rólega með þér líka!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}'あーあ‥！ ほんとに くたばっちまったぞ！ よわいなー！\n"
    .string "もっと ちゃんと そだてて やれよ$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "Hvernig gengur með VasaDEX? Ég var\n"
    .string "að fanga BEINFARA!\p"
    .string "Ég finn ekki stærri HNAUSKÚPU. Hvar\n"
    .string "gætu þær verið?\p"
    .string "Ég veðja að það eru engar eftir!\p"
    .string "Jæja, ég ætti að fara. Ég hef margt\n"
    .string "að gera, ólíkt þér.\p"
    .string "Sjáumst seinna!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Jafnvel við gátum ekki borið kennsl\n"
    .string "á villandi draugana.\p"
    .string "SILPH SCOPE gæti afhjúpað þá.$"

