SSAnne_1F_Corridor_Text_LeStrongSilentType::
    .string "Bonjour! Ég er le þjónninn á þessu\n"
    .string "skipi!\p"
    .string "Ég þjóna þér með gleði hverju sem þú\n"
    .string "vilt!\p"
    .string "... ... Ah! Le sterka þögla týpan!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
    .string "Farþegarnir eru órólegir eftir þessa\n"
    .string "löngu siglingu.\p"
    .string "Þeir leiðari gætu skorað á þig!$"

