Route5_SouthEntrance_Text_ThirstyOnGuardDuty::
    .string "Ég er á varðgæslu. Úff, ég er samt\n"
    .string "þyrstur!\p"
    .string "Ó, bíddu, vegurinn er lokaður.$"

Route5_SouthEntrance_Text_ThatTeaLooksTasty::
    .string "Ó, þetta TE... Það lítur hrikalega\n"
    .string "girnilega út...$"

Route5_SouthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Ha? Má ég fá þennan drykk? Úff,\n"
    .string "takk! ... ... Glugg, glugg... ...\p"
    .string "... Kyng... Ef þú vilt fara til\n"
    .string "SAFFRON BORGAR... ... ... Þú mátt\p"
    .string "fara í gegn.\p"
    .string "Ég deili þessu TE með hinum\n"
    .string "vörðunum!$"

Route5_SouthEntrance_Text_HiHowsItGoing::
    .string "Hæ, hvernig gengur?$"

