CeruleanCity_Gym_Text_MistyIntro::
    .string "Hæ, nýtt andlit!\p"
    .string "Aðeins þeir ÞJÁLFARAR sem hafa\n"
    .string "stefnu um vasaskrímsli geta orðið\p"
    .string "atvinnumenn.\p"
    .string "Hver er þín nálgun þegar þú nærð og\n"
    .string "þjálfar vasaskrímsli?\p"
    .string "Mín stefna er sókn af fullum krafti\n"
    .string "með VATNS-gerðar\p"
    .string "vasaskrímslum!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 kennir VATNSBYLGJU.\p"
    .string "Notaðu hana á vatnavasaskrímsli!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "FOSSMERKIÐ lætur öll vasaskrímsli\n"
    .string "upp að Lv. 30 hlýða.\p"
    .string "Það gildir líka um þau sem þú færð í\n"
    .string "skiptum.\p"
    .string "Og fleira: nú geturðu notað CUT\n"
    .string "hvenær sem er, jafnvel utan bardaga.\p"
    .string "Þú getur notað CUT til að fella\n"
    .string "lítil tré og opna nýjar leiðir.\p"
    .string "Þú mátt líka fá uppáhalds TM-ið\n"
    .string "mitt.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} fékk TM03 frá MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "Þú þarft að gera pláss fyrir þetta!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Vá! Þú ert alltof góður!\p"
    .string "Allt í lagi!\p"
    .string "Þú mátt fá FOSSMERKIÐ til marks um\n"
    .string "að þú hafir sigrað mig.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "Hvað? Þú? Ég duga meira en vel fyrir\n"
    .string "þig!\p"
    .string "MISTY þarf ekki að hafa fyrir þessu.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "Þú kaffærðir mig!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "Þú verður að mæta öðrum ÞJÁLFURUM\n"
    .string "til að sjá hversu góður þú ert.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Skvamp!\p"
    .string "Ég er fyrstur! Byrjum!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "Það getur ekki verið!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY er ÞJÁLFARI sem á eftir að\n"
    .string "halda áfram að bæta sig.\p"
    .string "Hún tapar ekki fyrir einhverjum eins\n"
    .string "og þér!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Yo! Verðandi meistari!\p"
    .string "Leyfðu mér að gefa þér ráð!\p"
    .string "SALSTJÓRINN, MISTY, er atvinnukona\n"
    .string "sem notar VATNS-gerðar vasaskrímsli.\p"
    .string "Þú getur sogið allt vatnið úr þeim\n"
    .string "með GRAS-gerðar vasaskrímslum.\p"
    .string "Eða þú getur notað RAFMAGNS-gerðar\n"
    .string "vasaskrímsli og lostið þau!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "Þú vannst MISTY! Sérðu, hvað sagði\n"
    .string "ég?\p"
    .string "Við tvö, krakki, erum ansi gott\n"
    .string "teymi!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "CERULEAN VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: MISTY\p"
    .string "SIGURÞJÁLFARAR: {RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "CERULEAN VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: MISTY\p"
    .string "SIGURÞJÁLFARAR: {RIVAL}, {PLAYER}$"

