FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Óli gerði mig atvinnulausan…\p"
    .string "Nú einbeiti ég mér að ræktinni!\p"
    .string "En ég get enn látið Vasaskrímsli\n"
    .string "gleyma brögðum.\p"
    .string "Viltu að ég geri það?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "Hvaða Vasaskrímsli á að gleyma\n"
    .string "hreyfingu?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "Hvaða hreyfingu á að gleyma?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{STR_VAR_1} virðist aðeins kunna\n"
    .string "eina hreyfingu…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Hm! {STR_VAR_1}, {STR_VAR_2}? Á að\n"
    .string "gleyma þessari hreyfingu?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "Það virkaði fullkomlega!\p"
    .string "{STR_VAR_1} hefur gleymt {STR_VAR_2}\n"
    .string "alveg.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Komdu aftur ef það eru aðrar\n"
    .string "hreyfingar til að gleyma.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "Hvað? Ekkert EGG ætti að kunna\n"
    .string "hreyfingar.$"
