Text_DreamEaterTeach::
    .string "Geisp! Ég hlýt að hafa dottað í\n"
    .string "sólinni.\p"
    .string "Mig dreymdi skrýtinn draum um DÁVI\n"
    .string "sem át drauminn minn.\p"
    .string "Og... Ég lærði að éta drauma...\p"
    .string "Úff, þetta er allt of hrollvekjandi!\p"
    .string "Leyfðu mér að kenna vasaskrímsli\n"
    .string "þetta svo ég geti gleymt því!$"

Text_DreamEaterDeclined::
    .string "...Hrot...$"

Text_DreamEaterWhichMon::
    .string "Hvaða vasaskrímsli vill læra\n"
    .string "DRAUMAÆTA?$"

Text_DreamEaterTaught::
    .string "...ZZZ... Ég... get ekki étið...\n"
    .string "meira...$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "BLEIKÁLFUR kom frá tunglinu. Það er\n"
    .string "orðrómurinn.\p"
    .string "Þau birtust eftir að TUNGLSTEINAR\n"
    .string "féllu á MT. MOON.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "Það eru ekki margir alvarlegir\n"
    .string "vasaskrímslaþjálfarar hér.\p"
    .string "Flestir eru eins og PÖDDUVEIÐARAR,\n"
    .string "bara áhugafólk.\p"
    .string "En BROCK í PEWTER-SALNUM er alls\n"
    .string "ekki þannig.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "Skoðaðirðu SAFNIÐ?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "Voru steingervingarnir frá MT. MOON\n"
    .string "ekki stórkostlegir?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Í alvöru? Þú verður endilega að\n"
    .string "fara!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "Þetta er SAFNIÐ.\p"
    .string "Það kostar að fara inn, en það er\n"
    .string "þess virði. Sjáumst!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst! Veistu hvað ég er að gera?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "Rétt! Þetta er erfið vinna!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "Ég úða REPEL til að halda villtum\n"
    .string "vasaskrímslum frá garðinum mínum!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "Þú ert ÞJÁLFARI, ekki satt?\p"
    .string "BROCK leitar að nýjum áskorendum.\n"
    .string "Fylgdu mér!$"

PewterCity_Text_GoTakeOnBrock::
    .string "Ef þú hefur það sem þarf skaltu\n"
    .string "skora á BROCK!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Öll vasaskrímsli sem birtast í\n"
    .string "bardaga, þó stutt sé, fá EXP stig.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "TILKYNNING!\p"
    .string "Þjófar hafa verið að stela\n"
    .string "steingervingum vasaskrímsla úr MT.\p"
    .string "MOON.\p"
    .string "Vinsamlegast hafið samband við\n"
    .string "PEWTER-LÖGREGLUNA ef þið hafið\p"
    .string "upplýsingar.$"

PewterCity_Text_MuseumOfScience::
    .string "PEWTER VÍSINDASAFN$"

PewterCity_Text_GymSign::
    .string "PEWTER BORGAR VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: BROCK Steinharði\p"
    .string "vasaskrímslaþjálfarinn!$"

PewterCity_Text_CitySign::
    .string "PEWTER BORG Steingrá borg$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "Ha! Þetta SALMERKI... Ótrúlegt,\n"
    .string "vannstu BROCK?\p"
    .string "Ég er svo snortinn að ég skal gefa\n"
    .string "þér fjársjóðinn minn!$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "Það eru BER inni í þessu.\p"
    .string "Sum þeirra koma að gagni, svo notaðu\n"
    .string "þau varlega!$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "Ef vasaskrímsli heldur á BERI notar\n"
    .string "það það sjálfkrafa í bardaga.\p"
    .string "Það er einfaldara og þægilegra en\n"
    .string "SÁRALYF eða EITURMÓTEFNI, ekki satt?$"

PewterCity_Text_OhPlayer::
    .string "Ó, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "Gott að ég náði þér. Ég er\n"
    .string "AÐSTOÐARMAÐUR Prófessor EIK.\p"
    .string "Ég var beðinn um að afhenda þetta,\n"
    .string "svo gjörðu svo vel.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} fékk HLAUPASKÓNA frá\n"
    .string "AÐSTOÐARMANNINUM.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} skipti yfir í HLAUPASKÓNA.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Ýttu á B-hnappinn til að hlaupa. En\n"
    .string "bara þar sem er pláss til að hlaupa!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Jæja, ég verð að fara aftur í\n"
    .string "RANNSÓKNARSTOFUNA.\p"
    .string "Bæ-bæ!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "Bréf er fest við...\p"
    .string "Kæri {PLAYER},\p"
    .string "Hér eru HLAUPASKÓR fyrir minn\n"
    .string "ástkæra áskoranda.\p"
    .string "Mundu, ég mun alltaf hvetja þig\n"
    .string "áfram! Gefstu aldrei upp!\p"
    .string "Frá mömmu$"
