PokemonTower_3F_Text_HopeIntro::
    .string "Urrg… Awaa… Huhu… Graa…$"

PokemonTower_3F_Text_HopeDefeat::
    .string "Ha! Mér var bjargað!$"

PokemonTower_3F_Text_HopePostBattle::
    .string "Draugana má bera kennsl á með\n"
    .string "SILPH-SJÁNNI.$"

PokemonTower_3F_Text_CarlyIntro::
    .string "Kekeke… Kwaaah!$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "Hmm? Hvað er ég að gera?$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "Fyrirgefðu! Ég var haldinn!$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "Burt með þig! Illi andi!$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "Púff! Andinn fór!$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "Hinir fyrir ofan… Þeir hljóta að\n"
    .string "hafa verið andsetnir.$"
