Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "Hæ! Manstu eftir mér? Ég er einn af\n"
    .string "AÐSTOÐARMÖNNUM Prófessor EIK.\p"
    .string "Ef VasaDEX-ið þitt er með full gögn\n"
    .string "um {STR_VAR_1} tegundir, á ég að\p"
    .string "gefa þér verðlaun.\p"
    .string "Prófessor EIK fól mér {STR_VAR_2}\n"
    .string "handa þér.\p"
    .string "Svo, {PLAYER}, leyfðu mér að spyrja.\p"
    .string "Hefurðu safnað gögnum um að minnsta\n"
    .string "kosti {STR_VAR_1} tegundir\p"
    .string "Vasaskrímsla?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "Frábært! Þú hefur fangað eða átt\n"
    .string "{STR_VAR_3} tegundir Vasaskrímsla!\p"
    .string "Til hamingju! Gjörðu svo vel!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "{PLAYER} fékk {STR_VAR_2} frá\n"
    .string "AÐSTOÐARMANNINUM.$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "EXP. SHARE er hlutur sem\n"
    .string "Vasaskrímsli getur haldið á.\p"
    .string "Vasaskrímslið fær hlut af EXP.\n"
    .string "stigum án þess að þurfa að berjast.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "Sjáum hvað sjónaukinn hefur að sýna…\p"
    .string "Stór, skínandi fugl flýgur í átt að\n"
    .string "sjónum.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "Sjáum hvað sést í sjónaukanum…\p"
    .string "Það lítur út eins og lítil eyja við\n"
    .string "sjóndeildarhringinn!$"
