SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "Þú lítur þreytt út. Þú ættir að fá\n"
    .string "þér stuttan blund.$"

SilphCo_9F_Text_DontGiveUp::
    .string "Ekki gefast upp!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "Kærar þakkir.$"

SilphCo_9F_Text_Grunt1Intro::
    .string "Vasaskrímslin þín virðast dá þig,\n"
    .string "krakki!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "Gaaaah!$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "Ef ég hefði byrjað sem ÞJÁLFARI á\n"
    .string "þínum aldri…$"

SilphCo_9F_Text_EdIntro::
    .string "Vasaskrímslin þín hafa veika punkta!\n"
    .string "Ég get hitt þá!$"

SilphCo_9F_Text_EdDefeat::
    .string "Þú lamdir mig niður!$"

SilphCo_9F_Text_EdPostBattle::
    .string "Að nýta veikleika virkar.\n"
    .string "Hugsaðu um gerðaryfirburði.$"

SilphCo_9F_Text_Grunt2Intro::
    .string "Ég er einn af fjórum\n"
    .string "ROCKET-BRÆÐRUM!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "Varg! Bræður, ég tapaði!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "Bræður mínir munu hefna mín!$"

SilphCo_9F_Text_FloorSign::
    .string "SILPH CO. HÖFUÐSKRIFSTOFA 9H$"
