SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
    .string "Ah, já, ég hef séð nokkur\n"
    .string "vasaskrímsli ferja fólk yfir vatnið!$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
    .string "Lítil tré má höggva niður með\n"
    .string "hreyfingunni CUT.\p"
    .string "En mundu þetta! CUT er HM tækni.\p"
    .string "Þegar hún hefur lærst er ekki\n"
    .string "auðvelt að losa sig við hana.$"

