Route25_Text_JoeyIntro::
    .string "ÞJÁLFARAR hér í nágrenninu koma\n"
    .string "hingað að æfa sig.$"

Route25_Text_JoeyDefeat::
    .string "Þú ert sæmilegur.$"

Route25_Text_JoeyPostBattle::
    .string "Öll vasaskrímsli hafa veikleika.\n"
    .string "Jafnvel þau sterkustu.\p"
    .string "Þess vegna er best að þjálfa\n"
    .string "vasaskrímsli af ólíkum gerðum.$"

Route25_Text_DanIntro::
    .string "Pabbi fór með mig í frábært partí á\n"
    .string "S.S. ANNE í VERMILION BORG.$"

Route25_Text_DanDefeat::
    .string "Ég er ekki reiður!$"

Route25_Text_DanPostBattle::
    .string "Á S.S. ANNE sá ég ÞJÁLFARA frá öllum\n"
    .string "heiminum.$"

Route25_Text_FlintIntro::
    .string "Ég er svalur gaur. Ég á kærustu!$"

Route25_Text_FlintDefeat::
    .string "Æ, bölvað...$"

Route25_Text_FlintPostBattle::
    .string "Jæja. Kærastan mín hressir mig við.$"

Route25_Text_KelseyIntro::
    .string "Hæ! Kærastinn minn er svalur!$"

Route25_Text_KelseyDefeat::
    .string "Formið mitt er ekki upp á það\n"
    .string "besta...$"

Route25_Text_KelseyPostBattle::
    .string "Ég vildi að kærastinn minn væri jafn\n"
    .string "góður og þú.$"

Route25_Text_ChadIntro::
    .string "Ég fékk þessa tilfinningu... Ég\n"
    .string "vissi að ég þyrfti að berjast við\p"
    .string "þig!$"

Route25_Text_ChadDefeat::
    .string "Ég vissi líka að ég myndi tapa!$"

Route25_Text_ChadPostBattle::
    .string "Ef vasaskrímslið þitt ruglast skaltu\n"
    .string "skipta því út.\p"
    .string "Það er góð aðferð.$"

Route25_Text_HaleyIntro::
    .string "Vinkona mín á mörg sæt vasaskrímsli.\n"
    .string "Ég er svo öfundsjúk!$"

Route25_Text_HaleyDefeat::
    .string "Ég er ekkert svo öfundsjúk!$"

Route25_Text_HaleyPostBattle::
    .string "Komstu frá MT. MOON? Má ég fá\n"
    .string "BLEIKÁLF?$"

Route25_Text_FranklinIntro::
    .string "Ég var að koma niður af MT. MOON, en\n"
    .string "ég á enn bensín á tanknum!$"

Route25_Text_FranklinDefeat::
    .string "Þú lagðir hart að þér!$"

Route25_Text_FranklinPostBattle::
    .string "Fjandinn! BLAKILDI beit mig þarna\n"
    .string "inni í hellinum.$"

Route25_Text_NobIntro::
    .string "Ég er á leið að sjá safn hjá\n"
    .string "SKRÍMSLASJÚKUM úti á höfðanum.$"

Route25_Text_NobDefeat::
    .string "Þú náðir mér, og það rækilega!$"

Route25_Text_NobPostBattle::
    .string "SKRÍMSLASJÚKI gaurinn stendur svo\n"
    .string "sannarlega undir nafninu.\p"
    .string "Safnið hans inniheldur margar\n"
    .string "sjaldgæfar tegundir vasaskrímsla.$"

Route25_Text_WayneIntro::
    .string "Þú ætlar að hitta BILL? Fyrst\n"
    .string "berjumst við!$"

Route25_Text_WayneDefeat::
    .string "Þú ert nokkuð magnaður.$"

Route25_Text_WaynePostBattle::
    .string "Stígurinn fyrir neðan er stytting\n"
    .string "til CERULEAN BORGAR.$"

Route25_Text_SeaCottageSign::
    .string "SJÁVARHÚSIÐ BILL býr hér!$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "Þessi höfði er frægur\n"
    .string "stefnumótastaður.\p"
    .string "MISTY, SALSTJÓRINN, bindur miklar\n"
    .string "vonir við þennan stað.$"

Route25_Text_AreYouHereAlone::
    .string "Halló, ertu hér án fylgdar?\p"
    .string "Ef þú ferð út á höfðann við\n"
    .string "CERULEAN... Þá ætti það að vera í\p"
    .string "pari.$"

