ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "Við erum KANTO RIDER FEDERATION!\n"
    .string "Vroom! Vavavavooom! Vroom!\p"
    .string "Hjólið mitt er veikt, svo ég þarf að\n"
    .string "búa til útblásturshljóðin sjálfur!$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "Hey, hey, kona! Afhentu smá\n"
    .string "vasapeninga!$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "Aiií!\p"
    .string "Hv-hver ert þú?! Ég… Ég hringi á\n"
    .string "lögregluna!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "Þessir MÓTORHJÓLAMENN… Eru þeir\n"
    .string "farnir?\p"
    .string "Ó, sem betur fer! Þeir hræddu mig\n"
    .string "svo sannarlega!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "Þessir BIKERS hlupu í burtu, og\n"
    .string "LOSTELLE fannst heil á húfi.\p"
    .string "Allt endaði vel!$"

