PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: Hvað, það er bara {PLAYER}?\n"
    .string "Afi er ekki hér.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: Afi! Ég er orðinn leiður\n"
    .string "á að bíða!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: Ha! Afi! Þetta er ekkert\n"
    .string "sanngjarnt! Hvað með mig?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Heh, ég þarf ekki að vera\n"
    .string "gráðugur eins og þú. Ég er\p"
    .string "þroskaður!\p"
    .string "Farðu á undan og veldu, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: Ég tek þennan, þá!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} fékk {STR_VAR_1} frá PRÓF.\n"
    .string "EIK!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: VASaSKRÍMSLIÐ mitt lítur\n"
    .string "miklu sterkari út en þitt.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Bíddu, {PLAYER}! Við skulum\n"
    .string "kíkja á VASaSKRÍMSLI okkar!\p"
    .string "Komdu, ég tek þig!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "HA? Ótrúlegt! Ég valdi rangt\n"
    .string "VASaSKRÍMSLI!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: Já! Er ég frábær eða hvað?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: Allt í lagi! Ég mun berjast\n"
    .string "með VASaSKRÍMSLIÐ mitt til að herða\p"
    .string "það!\p"
    .string "{PLAYER}! Afi! Sjáumst seinna!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: Afi!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: Ég gleymdi næstum! Til\n"
    .string "hvers hringdirðu í mig?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: Allt í lagi, afi! Leyfðu\n"
    .string "mér það allt!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, ég hata að segja það, en\n"
    .string "þú verður ekki nauðsynlegur fyrir\p"
    .string "þetta.\p"
    .string "Ég veit! Ég fæ lánað BÆJARKORT hjá\n"
    .string "systur minni!\p"
    .string "Ég skal segja henni að lána þér\n"
    .string "ekki, {PLAYER}! Hahaha!\p"
    .string "Nenni ekki að koma til mín eftir\n"
    .string "þetta!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "EIK: {RIVAL}? Leyfðu mér að hugsa…\p"
    .string "Ó, það er rétt, ég sagði þér að\n"
    .string "koma! Bíddu bara!\p"
    .string "Hér, {PLAYER}.\p"
    .string "Það eru þrjú VASaSKRÍMSLI hér.\p"
    .string "Haha!\p"
    .string "VASaSKRÍMSLI eru geymd inni í þessum\n"
    .string "VASA BOLTUM.\p"
    .string "Þegar ég var ungur var ég alvöru\n"
    .string "VASaSKRÍMSLAÞJÁLFARI.\p"
    .string "En nú á ég bara þrjú eftir. Þú mátt\n"
    .string "fá eitt. Veldu!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "EIK: Vertu þolinmóður, {RIVAL}. Þú\n"
    .string "getur líka fengið einn!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "EIK: Nú, {PLAYER}.\p"
    .string "Í þessum þremur VASA BOLTUM eru\n"
    .string "VASaSKRÍMSLI.\p"
    .string "Hvaða félaga velur þú?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "EIK: Hæ! Ekki fara í burtu ennþá!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Ah! GLÓÐMANDRA er valið þitt.\n"
    .string "Þjálfaðu hann af þolinmæði.\p"
    .string "Svo, {PLAYER}, viltu velja ELDUR\n"
    .string "VASaSKRÍMSLIÐ GLÓÐMÖNDRU?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Hm! SPRAUTILL er valið þitt.\n"
    .string "Hann á eftir að reynast vel.\p"
    .string "Svo, {PLAYER}, viltu velja VATN\n"
    .string "VASaSKRÍMSLIÐ SPRAUTIL?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "Ég sé! LAUKEÐLA er valið þitt.\n"
    .string "Hún er auðveld í þjálfun.\p"
    .string "Svo, {PLAYER}, viltu velja GRAS\n"
    .string "VASaSKRÍMSLIÐ LAUKEÐLU?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "Þetta VASaSKRÍMSLI er í raun ansi\n"
    .string "orkumikill!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} fékk {STR_VAR_1} frá PRÓF.\n"
    .string "EIK!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "EIK: Ef villtur VASaSKRÍMSLI birtist\n"
    .string "getur VASaSKRÍMSLI þinn barist við\p"
    .string "það.\p"
    .string "Með hann við hliðina ættirðu að geta\n"
    .string "náð næsta bæ.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "EIK: {PLAYER}, ala upp unga\n"
    .string "VASaSKRÍMSLI með því að láta hann\p"
    .string "berjast.\p"
    .string "Það þarf að berjast fyrir því að það\n"
    .string "vaxi.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "EIK: Ó, {PLAYER}! Hvernig er gamla\n"
    .string "VASaSKRÍMSLI minn?\p"
    .string "Jæja, það virðist vera að festast\n"
    .string "meira við þig.\p"
    .string "Þú verður að vera hæfileikaríkur sem\n"
    .string "VASaSKRÍMSLI ÞJÁLFARI.\p"
    .string "Hvað er það? Ertu með eitthvað handa\n"
    .string "mér?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} afhenti PAKKA EIKS.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Ah! Það er sérsniðinn VASA BOLTI!\p"
    .string "Ég var með það á pöntun. Þakka þér\n"
    .string "fyrir!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "EIK: Ó, rétt! Ég er með beiðni fyrir\n"
    .string "ykkur tvö.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "Á skrifborðinu er uppfinningin mín,\n"
    .string "VasaDEX!\p"
    .string "Það skráir sjálfkrafa gögn á\n"
    .string "VASaSKRÍMSLI sem þú hefur séð eða\p"
    .string "fangað.\p"
    .string "Það er hátækni alfræðiorðabók!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "EIK: {PLAYER} og {RIVAL}. Taktu\n"
    .string "þessar með þér.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} fékk VasaDEX frá Prófessor\n"
    .string "EIK.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "EIK: Þú getur ekki fengið nákvæmar\n"
    .string "upplýsingar um VASaSKRÍMSLI með því\p"
    .string "að sjá þau.\p"
    .string "Þú verður að fanga þau til að fá\n"
    .string "fullkomin gögn.\p"
    .string "Svo, hér eru nokkur tæki til að\n"
    .string "fanga villt VASaSKRÍMSLI.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} fékk fimm VASA BOLTA.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "Þegar villtur VASaSKRÍMSLI birtist\n"
    .string "er það sanngjarn leikur.\p"
    .string "Hentu bara VASA BOLTI í það og\n"
    .string "reyndu að fanga það!\p"
    .string "Þetta mun þó ekki alltaf virka.\p"
    .string "Heilbrigt VASaSKRÍMSLI getur\n"
    .string "sloppið. Þú verður að vera heppinn!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "Til að búa til heildarhandbók um\n"
    .string "alla VASaSKRÍMSLI í heiminum ...\p"
    .string "Það var draumurinn minn!\p"
    .string "En ég er of gamall. Ég get ekki\n"
    .string "unnið verkið.\p"
    .string "Svo ég vil að þið tvö uppfyllið\n"
    .string "drauminn minn fyrir mig.\p"
    .string "Farðu að hreyfa þig, þið tvö.\p"
    .string "Þetta er frábært verkefni í sögu\n"
    .string "VASaSKRÍMSLI!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "VASaSKRÍMSLI um allan heim bíða\n"
    .string "eftir þér, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}! Hvernig er VasaDEX\n"
    .string "þinn að mótast?\p"
    .string "{RIVAL} hefur þegar náð nokkrum\n"
    .string "VASaSKRÍMSLI og bætt við gögnin.\p"
    .string "Svo, {PLAYER}, skulum kíkja á\n"
    .string "VasaDEX. þinn\p"
    .string "…Hvað er að? Þú hefur alls ekki bætt\n"
    .string "við nýjum gögnum.\p"
    .string "Ég skal gefa þér þessar, svo reyndu\n"
    .string "aðeins betur.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "EIK: Komdu og hittu mig einhvern\n"
    .string "tíma.\p"
    .string "Eftir allt saman vil ég vita hvernig\n"
    .string "VasaDEX þinn kemur.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "Þetta er eins og alfræðiorðabók, en\n"
    .string "síðurnar eru auðar.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Þetta eru VASA BOLTAR. Þeir\n"
    .string "innihalda VASaSKRÍMSLI!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "Það er síðasta VASaSKRÍMSLIÐ frá\n"
    .string "EIK.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Ýttu á START til að opna VALMYNDINA!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "VISTA-valkosturinn er í VALMYND.\n"
    .string "Notaðu hann reglulega.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "Allar VASaSKRÍMSLI gerðir hafa\n"
    .string "sterka og veika punkta gegn öðrum.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "Það er tölvupóstur hér.\p"
    .string "…\p"
    .string "Loksins! Sterkustu ÞJÁLFARAR\n"
    .string "VASaSKRÍMSLADEILDARINNAR eru\p"
    .string "tilbúnir að taka á móti öllum!\p"
    .string "Komdu með besta VASaSKRÍMSLIÐ þitt\n"
    .string "og sjáðu hvar þú stendur sem\p"
    .string "ÞJÁLFARI!\p"
    .string "VASaSKRÍMSLADEILD HQ INDIGO PLATEAU\p"
    .string "Prófessor EIK, vinsamlegast kíktu\n"
    .string "við!$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Ég rannsaka VASaSKRÍMSLI sem\n"
    .string "aðstoðarmaður Prófessor EIK.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hæ, {PLAYER}. Ég veðja að þú sért\n"
    .string "orðin/n góður vinur VASaSKRÍMSLISINS\p"
    .string "þíns.\p"
    .string "Annars, vissirðu af DAISY?\p"
    .string "Ef þú sýnir DAISY VASaSKRÍMSLIÐ þitt\n"
    .string "getur hún sagt hversu mikið því\p"
    .string "líkar við þig.\p"
    .string "Stundum snyrtir hún jafnvel\n"
    .string "VASaSKRÍMSLI fyrir þig!$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "Prófessor EIK fær bráðum sinn eigin\n"
    .string "útvarpsþátt.\p"
    .string "Þátturinn heitir Prófessors EIKS\n"
    .string "VASaSKRÍMSLANÁMSKEIÐ.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "Prófessor EIK lítur kannski ekki út\n"
    .string "fyrir það, en hann er helsti\p"
    .string "sérfræðingurinn um VASaSKRÍMSLI.\p"
    .string "Margir VASaSKRÍMSLAÞJÁLFARAR bera\n"
    .string "mikla virðingu fyrir honum.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, nú er þetta frábært!\p"
    .string "{PLAYER}, ég hef annan mikilvægan\n"
    .string "greiða að biðja þig um.\p"
    .string "Ég þarf að hlusta vel.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Nýlega hafa sést margar sjaldgæfar\n"
    .string "VASaSKRÍMSLI tegundir.\p"
    .string "Ég er að tala um VASaSKRÍMSLI sem\n"
    .string "hafa aldrei sést í KANTO.\p"
    .string "Ég myndi elska að fara að skoða\n"
    .string "hlutina sjálfur, en ég er allt of\p"
    .string "gamall.\p"
    .string "Þar sem ég get það ekki, {PLAYER},\n"
    .string "vil ég að þú farir í minn stað.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey, ég heyrði það!\p"
    .string "Afi, hvað er að því að hygla\n"
    .string "{PLAYER} fram yfir mig allan tímann?\p"
    .string "Ég fór og safnaði meira\n"
    .string "VASaSKRÍMSLI, og hraðar líka.\p"
    .string "Þú ættir bara að leyfa mér að sjá um\n"
    .string "allt.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "EIK: Ég veit, ég veit. Auðvitað þarf\n"
    .string "ég líka hjálp þína.\p"
    .string "Nú þarf ég að sjá bæði VasaDEXIN.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "Prófessor EIK tók báðar VasaDEX\n"
    .string "einingarnar.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … … … … …\p"
    .string "… … … … … …\p"
    .string "…Og það er búið!\p"
    .string "Nú geta þessar einingar skráð gögn á\n"
    .string "miklu fleiri VASaSKRÍMSLI.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "VasaDEX frá {PLAYER} var uppfærður!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Nú, {PLAYER} og {RIVAL}!\p"
    .string "Að þessu sinni verður þú virkilega\n"
    .string "að vinna að því að fylla VasaDEXES.\p"
    .string "þinn\p"
    .string "Ég hvet þig til að gera þá bestu og\n"
    .string "fullkomnustu allra tíma!\p"
    .string "Sannarlega, þetta er stórkostlegt\n"
    .string "verkefni í sögu VASaSKRÍMSLI!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Afi, rólegur. Vertu ekki\n"
    .string "svona æstur.\p"
    .string "Ég klára VasaDEX, engar áhyggjur.\p"
    .string "Ég held ég skoði EIN EYJU fyrst…\p"
    .string "Allavega, ég er farinn!$"
