FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .string "Hér ólst upp mikill og öflugur\n"
    .string "ÞJÁLFARI.\p"
    .string "Ég veðja að jafnvel þú þekkir hana.\n"
    .string "Það er LORELEI úr ELITE FOUR!\p"
    .string "Þegar LORELEI var bara krakki kenndi\n"
    .string "ég henni um Vasaskrímsli.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "SEVII ISLANDS eru almennt á hlýju\n"
    .string "svæði.\p"
    .string "En það er ein undantekning sem þú\n"
    .string "þarft að vita um.\p"
    .string "ICEFALL CAVE er ískaldur vegna\n"
    .string "Vasaskrímslanna sem búa þar.$"

