@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}{KUN}の バッグ いっぱい みたい だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "Finnst þér ekki erfitt að finna góð\n"
    .string "nöfn fyrir vasaskrímsli?\p"
    .string "Sérstaklega ef þú hefur náð heilum\n"
    .string "helling?\p"
    .string "Í LAVENDER BORG er maður sem metur\n"
    .string "gælunöfn vasaskrímsla.\p"
    .string "Hann getur jafnvel hjálpað þér að\n"
    .string "endurnefna vasaskrímslin þín.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "Ef þú stefnir á LAVENDER BORG skaltu\n"
    .string "fara um ROCK TUNNEL.\p"
    .string "Þú kemst að ROCK TUNNEL frá CERULEAN\n"
    .string "BORG.$"

