Route9_Text_AliciaIntro::
    .string "Þú ert með vasaskrímsli með þér! Þú\n"
    .string "ert mín!$"

Route9_Text_AliciaDefeat::
    .string "Þú blekktir mig...$"

Route9_Text_AliciaPostBattle::
    .string "Göngin framundan eru kolniðamyrk að\n"
    .string "innan.\p"
    .string "Þú þarft LEIFTUR til að komast í\n"
    .string "gegnum þau.$"

Route9_Text_ChrisIntro::
    .string "Hver gengur þarna með þessi flottu\n"
    .string "vasaskrímsli?$"

Route9_Text_ChrisDefeat::
    .string "Slökktur eins og ljós!$"

Route9_Text_ChrisPostBattle::
    .string "Haltu áfram að ganga!$"

Route9_Text_DrewIntro::
    .string "Ég fer um ROCK TUNNEL til að komast\n"
    .string "til LAVENDER...$"

Route9_Text_DrewDefeat::
    .string "Ég stóðst ekki samanburð...$"

Route9_Text_DrewPostBattle::
    .string "Ertu líka á leið í ROCK TUNNEL?$"

Route9_Text_CaitlinIntro::
    .string "Ekki voga þér að líta niður á mig!$"

Route9_Text_CaitlinDefeat::
    .string "Nei! Þú ert of mikið.$"

Route9_Text_CaitlinPostBattle::
    .string "Þú ert augljóslega hæfileikaríkur.\n"
    .string "Gangi þér vel!$"

Route9_Text_JeremyIntro::
    .string "Bwahaha! Frábært! Mér leiddist, ha!$"

Route9_Text_JeremyDefeat::
    .string "Haltu þessu áfram, ha!\p"
    .string "Ó bíddu. Ég er uppiskroppa með\n"
    .string "vasaskrímsli!$"

Route9_Text_JeremyPostBattle::
    .string "Þú hafðir greinilega kjark til að\n"
    .string "standa uppi í hárinu á mér, ha?$"

Route9_Text_BriceIntro::
    .string "Hahaha! Ertu ekki svolítið harður af\n"
    .string "þér!$"

Route9_Text_BriceDefeat::
    .string "Hvað er þetta?$"

Route9_Text_BricePostBattle::
    .string "Hahaha! Krakkar eiga að vera harðir!$"

Route9_Text_BrentIntro::
    .string "Ég vaknaði snemma á hverjum degi til\n"
    .string "að ala vasaskrímslin mín úr púpunum!$"

Route9_Text_BrentDefeat::
    .string "HVAÐ?\p"
    .string "Hvílík tímasóun!$"

Route9_Text_BrentPostBattle::
    .string "Ég þarf að safna fleiru en pöddum\n"
    .string "til að verða sterkari...$"

Route9_Text_AlanIntro::
    .string "Hahahaha! Komdu með það!$"

Route9_Text_AlanDefeat::
    .string "Hahahaha! Þú vannst mig heiðarlega!$"

Route9_Text_AlanPostBattle::
    .string "Hahahaha! Við hraustu gaurarnir\n"
    .string "hlæjum alltaf!$"

Route9_Text_ConnerIntro::
    .string "Áfram, ofur PÖDDU-vasaskrímslin mín!$"

Route9_Text_ConnerDefeat::
    .string "Pöddurnar mínar...$"

Route9_Text_ConnerPostBattle::
    .string "Ef þér líkar ekki við\n"
    .string "PÖDDU-vasaskrímsli, þá pirrarðu mig!$"

Route9_Text_RouteSign::
    .string "LEIÐ 9 CERULEAN BORG - BERGJARGÖNG$"

