FiveIsland_PokemonCenter_1F_Text_OnMyWayToPrepareMeal::
    .string "Ég er á leiðinni til að útbúa máltíð\n"
    .string "fyrir ákveðna háttsetta persónu.$"

FiveIsland_PokemonCenter_1F_Text_YoureOnQuestToCatchEveryMon::
    .string "Ertu í leiðangri til að fanga hverja\n"
    .string "einustu tegund Vasaskrímsla?\p"
    .string "…Hversu ótrúlegt. Láttu mig vita ef\n"
    .string "þú fangar sterkt eitt!$"

