Route24_Text_JustEarnedFabulousPrize::
    .string "Til hamingju! Þú sigraðir fimm\n"
    .string "keppnis-ÞJÁLFARANA okkar!\p"
    .string "Þú vannst stórkostleg verðlaun!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer::
    .string "{PLAYER} fékk GULLKLUMP frá\n"
    .string "dularfulla ÞJÁLFARANUM!$"

Route24_Text_YouDontHaveAnyRoom::
    .string "Þú hefur ekkert pláss!$"

Route24_Text_JoinTeamRocket::
    .string "Að öðru leyti, hvernig litist þér á\n"
    .string "að ganga í ROCKET-GENGIÐ?\p"
    .string "Við erum hópur atvinnuglæpamanna sem\n"
    .string "sérhæfir sig í vasaskrímslum!\p"
    .string "Viltu ganga í liðið?\p"
    .string "Ertu viss?\p"
    .string "Komdu nú, gakktu til liðs við okkur!\p"
    .string "Ég segi þér að ganga í liðið!\p"
    .string "...Allt í lagi, þú þarft\n"
    .string "sannfæringu!\p"
    .string "Ég geri þér tilboð sem þú getur ekki\n"
    .string "hafnað!$"

Route24_Text_RocketDefeat::
    .string "Arrgh! Þú ert góður!$"

Route24_Text_YoudBecomeTopRocketLeader::
    .string "Með hæfileikum þínum gætirðu orðið\n"
    .string "toppleiðtogi í ROCKET-GENGINU.\p"
    .string "Komdu nú, hugsaðu um tækifærið! Ekki\n"
    .string "láta þetta fara til spillis.$"

Route24_Text_ShaneIntro::
    .string "Ég sá afrekið þitt úr grasinu!$"

Route24_Text_ShaneDefeat::
    .string "Ég hélt það ekki!$"

Route24_Text_ShanePostBattle::
    .string "Ég faldi mig því fólkið á brúnni\n"
    .string "hræddi mig.$"

Route24_Text_EthanIntro::
    .string "Allt í lagi! Ég er nr. 5! Ég stappa\n"
    .string "þig niður!$"

Route24_Text_EthanDefeat::
    .string "Vá! Of mikið!$"

Route24_Text_EthanPostBattle::
    .string "Ég gerði mitt besta. Ég sé ekki\n"
    .string "eftir neinu!$"

Route24_Text_ReliIntro::
    .string "Ég er nr. 4! Ertu orðinn þreyttur?$"

Route24_Text_ReliDefeat::
    .string "Ég tapaði líka!$"

Route24_Text_ReliPostBattle::
    .string "Ég gerði mitt besta, svo ég sé ekki\n"
    .string "eftir neinu!$"

Route24_Text_TimmyIntro::
    .string "Hér kemur nr. 3! Ég verð ekki\n"
    .string "auðveldur!$"

Route24_Text_TimmyDefeat::
    .string "Ái! Flattur út!$"

Route24_Text_TimmyPostBattle::
    .string "Ég gerði mitt besta. Ég sé ekki\n"
    .string "eftir neinu!$"

Route24_Text_AliIntro::
    .string "Ég er númer tvö! Nú er alvara!$"

Route24_Text_AliDefeat::
    .string "Hvernig gat ég tapað?$"

Route24_Text_AliPostBattle::
    .string "Ég gerði mitt besta. Ég sé ekki\n"
    .string "eftir neinu!$"

Route24_Text_CaleIntro::
    .string "Fólk kallar þetta GULLBRÚNA!\p"
    .string "Sigraðu okkur fimm ÞJÁLFARA og\n"
    .string "vinndu frábær verðlaun!\p"
    .string "Heldurðu að þú getir það?$"

Route24_Text_CaleDefeat::
    .string "Úhú! Vel gert!$"

Route24_Text_CalePostBattle::
    .string "Ég gerði mitt besta. Ég sé ekki\n"
    .string "eftir neinu!$"
