ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
    .string "Er það satt?\p"
    .string "CELADON DEPT. STORE er margfalt\n"
    .string "stærri en þessi búð?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
    .string "Ég kaupi stundum lyf hér.\p"
    .string "En margir lækna Vasaskrímsli með\n"
    .string "BERJUM úr BERJA SKÓGI.\p"
    .string "Þegar allt kemur til alls eru BER\n"
    .string "ókeypis og klárast aldrei.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
    .string "Þessir MÓTORHJÓLAMENN ætluðu að\n"
    .string "rústa þessari Vasaskrímslabúð.\p"
    .string "Ég er fegin/n að þeir ákváðu að\n"
    .string "fara!$"
