ThreeIsland_BondBridge_Text_NikkiIntro::
    .string "Salt angan hafsins… Hún kitlar\n"
    .string "hjartað mitt.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
    .string "…Sniff, sniff… Something smells\n"
    .string "unpleasant…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
    .string "Kannski er þessi fýla líkamslyktin\n"
    .string "af sveittu Vasaskrímslunum þínum…$"

ThreeIsland_BondBridge_Text_VioletIntro::
    .string "Hvert ertu að fara í svona miklum\n"
    .string "flýti?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
    .string "Þú ert að ala upp dásamleg\n"
    .string "Vasaskrímsli.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
    .string "Ef þú heldur áfram þessa leið nærðu\n"
    .string "að lokum BERJA SKÓGI.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
    .string "Mamma mín sagði að ég geti ekki synt\n"
    .string "án flotbaugsins míns.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
    .string "Vááá! Vááá!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
    .string "Í ár ætla ég loksins að læra að\n"
    .string "synda!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
    .string "Yay, yay! Vasaskrímsli!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
    .string "Hvað gerist núna?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
    .string "Vann ég bara? Eða tapaði ég?$"

ThreeIsland_BondBridge_Text_TishaIntro::
    .string "Ó, nei, ekki koma hingað!\n"
    .string "Vinsamlegast, haltu þér frá mér!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
    .string "Allt í lagi, þú hefur unnið! Viltu\n"
    .string "núna vinsamlegast fara?$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
    .string "Vasaskrímsli beit í gegnum sundfötin\n"
    .string "mín.\p"
    .string "Ég kemst ekki upp úr vatninu!$"

ThreeIsland_BondBridge_Text_JoyIntro::
    .string "JOY: Við kennum þér hvað uppáhalds\n"
    .string "Vasaskrímslið okkar er!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
    .string "JOY: Ohh… MEG!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
    .string "JOY: Var þetta ekki skemmtilegt? Ég\n"
    .string "vona að við getum barist aftur!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
    .string "JOY: Mig langar virkilega að berjast\n"
    .string "með MEG.\p"
    .string "Eitt Vasaskrímsli er ekki nóg.$"

ThreeIsland_BondBridge_Text_MegIntro::
    .string "MEG: Við sýnum þér uppáhalds\n"
    .string "Vasaskrímslið okkar.$"

ThreeIsland_BondBridge_Text_MegDefeat::
    .string "MEG: Ohh… JOY!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
    .string "MEG: JOY, var þetta ekki\n"
    .string "skemmtilegt?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
    .string "MEG: Ég vil berjast saman með JOY.\p"
    .string "Eitt Vasaskrímsli er ekki nóg.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .string "BERJASKÓGUR FRAMUNDAN$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .string "BOND BRÚ Vinsamlegast hafið hljótt\n"
    .string "þegar þið farið yfir.\p"
    .string "BERJA SKÓGUR FRAMUNDAN$"
