FiveIsland_ResortGorgeous_Text_DaisyIntro::
    .string "Með þessum höndum mun ég skapa sigur\n"
    .string "minn!$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
    .string "Skömmin af þessu… Ég roðna…$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
    .string "Úff, málningartúburnar mínar hafa\n"
    .string "dreifst um allt!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro::
    .string "Afsakið! Ég er að reyna að mála.\n"
    .string "Vinsamlegast haldið ykkur frá mér!$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
    .string "Þetta tap… Mér líður eins og ég sé\n"
    .string "að líða út af…$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
    .string "GILLIAN? Hallaðu höfðinu aðeins…\n"
    .string "Svona! Þetta er svipurinn sem ég\p"
    .string "vil!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro::
    .string "Hmm… Hornið er ekki alveg rétt…$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
    .string "Ó… Tilfinningar mínar eru bláar…$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
    .string "Himinninn og hafið… Þau eru svo\n"
    .string "hverful.\p"
    .string "Breytileg svipbrigði þeirra gera þau\n"
    .string "erfið að fanga.$"

FiveIsland_ResortGorgeous_Text_JackiIntro::
    .string "Ég er að heimsækja sumarbústað vinar\n"
    .string "míns, ef þú verður að vita.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat::
    .string "Ó, minn, svo sterkur.$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
    .string "Mér finnst það ánægjulegt að berjast\n"
    .string "á rólegan hátt í mildri sjávargolu.$"

FiveIsland_ResortGorgeous_Text_GillianIntro::
    .string "Ég er að hugsa um að láta gera laug\n"
    .string "sérstaklega fyrir Vasaskrímsli.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat::
    .string "Ó, minn góður!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
    .string "Sundlaug væri fín, en ég verð að\n"
    .string "sjá, sólstofa gæti verið\p"
    .string "stórkostleg.$"

FiveIsland_ResortGorgeous_Text_DestinIntro::
    .string "Ég er góður hlaupari. Ég er mjög\n"
    .string "hraður!$"

FiveIsland_ResortGorgeous_Text_DestinDefeat::
    .string "Úps! Ég flýtti mér of mikið!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
    .string "Þegar ég hleyp með vindinum, líður\n"
    .string "mér eins og ég gæti flogið!$"

FiveIsland_ResortGorgeous_Text_TobyIntro::
    .string "Ég segi, þetta sjávarlíf hér á\n"
    .string "þessum dvalarstað hentar mér vel.$"

FiveIsland_ResortGorgeous_Text_TobyDefeat::
    .string "Þetta er áfall! Þú hlýtur að vera að\n"
    .string "grínast.$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
    .string "Að taka þetta svona alvarlega…\n"
    .string "Þvílík vitleysa.$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
    .string "SELPHY: Takk fyrir.\p"
    .string "Þú mátt fara núna.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse::
    .string "HÚS SELPHY$"

