CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "REPEL heldur ekki bara pöddum frá,\n"
    .string "það virkar líka á veik vasaskrímsli.\p"
    .string "Settu sterkasta vasaskrímslið þitt\n"
    .string "fremst á vasaskrímsla-LISTANN.\p"
    .string "Ef fyrsta vasaskrímslið þitt er\n"
    .string "sterkt verður áhrif REPEL meiri.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Veistu um RARE CANDY? Það er ekki\n"
    .string "selt í búðum.\p"
    .string "Ég held að það láti vasaskrímsli\n"
    .string "vaxa mjög hratt allt í einu.$"

