Route11_Text_HugoIntro::
    .string "Vinna, tapa eða jafntefli!$"

Route11_Text_HugoDefeat::
    .string "Atcha! Þetta fór ekki eins og ég\n"
    .string "vildi!$"

Route11_Text_HugoPostBattle::
    .string "Vasaskrímsli eru lífið! Og að lifa\n"
    .string "er að spila leiki!$"

Route11_Text_JasperIntro::
    .string "Keppni! Ég fæ aldrei nóg!$"

Route11_Text_JasperDefeat::
    .string "Ég átti möguleika!$"

Route11_Text_JasperPostBattle::
    .string "Þú mátt ekki vera huglaus í heimi\n"
    .string "vasaskrímsla!$"

Route11_Text_EddieIntro::
    .string "Byrjum, en ekki svindla!$"

Route11_Text_EddieDefeat::
    .string "Ha? Þetta er ekki rétt!$"

Route11_Text_EddiePostBattle::
    .string "Ég gerði mitt besta. Ég sé ekki\n"
    .string "eftir neinu.$"

Route11_Text_BraxtonIntro::
    .string "Varlega! Ég er að leggja kapla!$"

Route11_Text_BraxtonDefeat::
    .string "Þetta var rafmagnað!$"

Route11_Text_BraxtonPostBattle::
    .string "Dreifðu boðskapnum um að spara orku!$"

Route11_Text_DillonIntro::
    .string "Ég varð nýlega ÞJÁLFARI. En ég held\n"
    .string "að ég geti unnið.$"

Route11_Text_DillonDefeat::
    .string "Vasaskrímslin mín gátu ekki unnið...\n"
    .string "Hafa þau ekki vaxið nóg?$"

Route11_Text_DillonPostBattle::
    .string "Hvað nú? Láttu mig í friði!$"

Route11_Text_DirkIntro::
    .string "Fwahaha! Ég hef aldrei tapað!$"

Route11_Text_DirkDefeat::
    .string "Fyrsta tapið mitt!$"

Route11_Text_DirkPostBattle::
    .string "Þú varst bara heppinn, það er allt.$"

Route11_Text_DarianIntro::
    .string "Ég hef aldrei unnið áður...$"

Route11_Text_DarianDefeat::
    .string "Ég sá þetta fyrir...$"

Route11_Text_DarianPostBattle::
    .string "Ég var óheppinn, eins og alltaf.$"

Route11_Text_YasuIntro::
    .string "Ég er bestur í bekknum mínum. Ég æfi\n"
    .string "á hverjum morgni.$"

Route11_Text_YasuDefeat::
    .string "Fjandinn! Vasaskrímslin mín þurfa að\n"
    .string "verða sterkari!$"

Route11_Text_YasuPostBattle::
    .string "Það er feitlagið vasaskrímsli sem\n"
    .string "kemur niður úr fjöllunum.\p"
    .string "Ég veðja að það væri sterkt ef þú\n"
    .string "næðir því.$"

Route11_Text_BernieIntro::
    .string "Varastu spennusetta víra!$"

Route11_Text_BernieDefeat::
    .string "Vá! Þú litla kveikjukerti!$"

Route11_Text_BerniePostBattle::
    .string "Jæja, best að fara aftur að vinna.$"

Route11_Text_DaveIntro::
    .string "Ég ól vasaskrímslin mín vandlega\n"
    .string "upp. Þau ættu að vera tilbúin núna!$"

Route11_Text_DaveDefeat::
    .string "Bæ-bæ! Takk fyrir og bless!$"

Route11_Text_DavePostBattle::
    .string "Tsk... Ég ætti að fara og finna\n"
    .string "sterkari.$"

Route11_Text_DiglettsCave::
    .string "GRAFLARAHELLIR$"

