CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "Hehehe!\p"
    .string "Spilakassarnir moka inn peningum,\n"
    .string "heldur betur!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "FORINGI!\p"
    .string "Við sendum aftur tvö þúsund\n"
    .string "vasaskrímsli í vinninga fyrir\p"
    .string "spilakassana í dag!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "Ekki snerta veggspjaldið í\n"
    .string "SPILASALNUM!\p"
    .string "Það er enginn leynirofi bak við það!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "Þetta er búddískt altari...$"
