SixIsland_OutcastIsland_Text_RocketIntro::
    .string "Það eru engin sjaldgæf Vasaskrímsli\n"
    .string "á þessum slóðum! Ekki eitt einasta!\p"
    .string "Það fer í taugarnar á mér, maður. Ég\n"
    .string "læt það bitna á þér!$"

SixIsland_OutcastIsland_Text_RocketDefeat::
    .string "…Ha?$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
    .string "Svo hlustaðu, þú hefur ekki séð nein\n"
    .string "sjaldgæf Vasaskrímsli, er það\p"
    .string "nokkuð?$"

SixIsland_OutcastIsland_Text_TylorIntro::
    .string "Ég er alls ekki heppinn. Bardagi\n"
    .string "væri breyting á hraða!$"

SixIsland_OutcastIsland_Text_TylorDefeat::
    .string "Nei, engin heppni yfirleitt…$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
    .string "Ég get varla farið heim án þess að\n"
    .string "veiða eitthvað, samt.$"

SixIsland_OutcastIsland_Text_MymoIntro::
    .string "Más… Más…\p"
    .string "Ég synti hingað frá SIX ISLE HÖFN í\n"
    .string "einni lotu.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
    .string "Gasp… Gasp…$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
    .string "Ég er bara hálfnuð… Ég er búin á\n"
    .string "því…$"

SixIsland_OutcastIsland_Text_NicoleIntro::
    .string "Það er ekki svo auðvelt að senda\n"
    .string "Vasaskrímsli út á meðan maður\p"
    .string "syndir, veistu?$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
    .string "Ég tapaði ekki fyrir þér í sundi.\n"
    .string "Þetta truflar mig ekki.$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
    .string "Ertu á leiðinni á eyjuna upp fyrir\n"
    .string "hér?\p"
    .string "Ég sá ekkert áhugavert þar.$"

SixIsland_OutcastIsland_Text_AvaIntro::
    .string "AVA: Eigum við tveggja á móti\n"
    .string "tveimur sjávarbardaga!$"

SixIsland_OutcastIsland_Text_AvaDefeat::
    .string "AVA: Ó, þú ert ótrúlegur! Enn betra,\n"
    .string "þú ert einn!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
    .string "AVA: Veistu, ég kýs sjóinn fram yfir\n"
    .string "allar sundlaugar.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
    .string "AVA: Ertu að skora á okkur í\n"
    .string "bardaga?\p"
    .string "Þú þarft að minnsta kosti tvö\n"
    .string "Vasaskrímsli ef þú vilt gera það.$"

SixIsland_OutcastIsland_Text_GebIntro::
    .string "GEB: Stóra systir, hjálp!\n"
    .string "Vinsamlegast berjist með mér!$"

SixIsland_OutcastIsland_Text_GebDefeat::
    .string "GEB: Vá, stóra systir, þessi\n"
    .string "manneskja er virkilega góð!$"

SixIsland_OutcastIsland_Text_GebPostBattle::
    .string "GEB: Ég held í systur mína af því ég\n"
    .string "næ ekki niður.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
    .string "GEB: Berstu við mig og systur mína,\n"
    .string "gerðu það!\p"
    .string "…Ó, þú ert ekki með tvö\n"
    .string "Vasaskrímsli?$"
