Route14_Text_CarterIntro::
    .string "Þú þarft að nota TM til að kenna\n"
    .string "Vasaskrímslum góðar hreyfingar.$"

Route14_Text_CarterDefeat::
    .string "Ekki nógu gott ennþá.$"

Route14_Text_CarterPostBattle::
    .string "Þú átt einhver HM, ekki satt?\n"
    .string "Vasaskrímsli gleyma slíkum\p"
    .string "hreyfingum ekki auðveldlega.$"

Route14_Text_MitchIntro::
    .string "Fugla-Vasaskrímslin mín ættu að vera\n"
    .string "tilbúin í bardaga.$"

Route14_Text_MitchDefeat::
    .string "Ekki tilbúinn ennþá!$"

Route14_Text_MitchPostBattle::
    .string "Fugla-Vasaskrímslin mín þurfa að\n"
    .string "læra betri hreyfingar.$"

Route14_Text_BeckIntro::
    .string "Þeir eru með TMs á útsölu í CELADON\n"
    .string "DEPT. STORE.\p"
    .string "TMs eru ekki mjög sjaldgæfir, en\n"
    .string "ekki margir eiga HMs.$"

Route14_Text_BeckDefeat::
    .string "Æi, leiðinlegt!$"

Route14_Text_BeckPostBattle::
    .string "Reyndu að kenna Vasaskrímsli\n"
    .string "hreyfingu sem er af sömu gerð og\p"
    .string "það.\p"
    .string "Það á víst að auka kraft\n"
    .string "hreyfingarinnar.$"

Route14_Text_MarlonIntro::
    .string "Hefurðu kennt fugla-Vasaskrímslinu\n"
    .string "þínu að FLY?\p"
    .string "Þá geturðu svifið með því upp í\n"
    .string "himininn!$"

Route14_Text_MarlonDefeat::
    .string "Skotinn niður í logum!$"

Route14_Text_MarlonPostBattle::
    .string "Fugla-Vasaskrímsli eru mín eina\n"
    .string "sanna ást. Ég vil ekki ala upp neitt\p"
    .string "annað.$"

Route14_Text_DonaldIntro::
    .string "Hefurðu heyrt söguna um vængjuðu\n"
    .string "hillingarnar?$"

Route14_Text_DonaldDefeat::
    .string "Af hverju? Af hverju tapaði ég?$"

Route14_Text_DonaldPostBattle::
    .string "Jæja, vængjuðu hillingarnar eru\n"
    .string "goðsagnakenndu fugla-Vasaskrímslin.\p"
    .string "Þau eru þrjú: ÉLJASKARFU, ÞÓRSHANI\n"
    .string "og BLOSSAGAUK.$"

Route14_Text_BennyIntro::
    .string "Ég er ekki hrifinn af því, en allt í\n"
    .string "lagi. Förum!$"

Route14_Text_BennyDefeat::
    .string "Ég vissi það!$"

Route14_Text_BennyPostBattle::
    .string "Að vinna, tapa… Það er ómerkilegt\n"
    .string "undir þessum risastóra himni.$"

Route14_Text_LukasIntro::
    .string "Komdu, komdu. Förum, förum, förum!$"

Route14_Text_LukasDefeat::
    .string "Arrg! Tapaði! Hverfðu!$"

Route14_Text_LukasPostBattle::
    .string "Hvað, hvað, hvað? Hvað viltu ennþá?$"

Route14_Text_IsaacIntro::
    .string "Ég þarf að drepa tímann. Þegiðu og\n"
    .string "berstu.$"

Route14_Text_IsaacDefeat::
    .string "Hvað? Þú!?$"

Route14_Text_IsaacPostBattle::
    .string "Að ala upp Vasaskrímsli er\n"
    .string "leiðinlegt, maður.$"

Route14_Text_GeraldIntro::
    .string "Við hjólum hér vegna hinna opnu\n"
    .string "svæða.$"

Route14_Text_GeraldDefeat::
    .string "Út af!$"

Route14_Text_GeraldPostBattle::
    .string "Það er flott að þú gerðir\n"
    .string "Vasaskrímslin þín svona sterk.\p"
    .string "Máttur ræður! Og þú veist það!$"

Route14_Text_MalikIntro::
    .string "Vasaskrímsla bardagi? Svalt! Slagur!$"

Route14_Text_MalikDefeat::
    .string "Fokið burt!$"

Route14_Text_MalikPostBattle::
    .string "Þú veist hver myndi vinna, þú og ég\n"
    .string "einn á móti einum!$"

Route14_Text_RouteSign::
    .string "LEIÐ 14 Vestur til FUCHSIA BORG$"

Route14_Text_KiriIntro::
    .string "KIRI: JAN, reynum virkilega,\n"
    .string "virkilega hart saman.$"

Route14_Text_KiriDefeat::
    .string "KIRI: Snökt… Við töpuðum, er það ekki?$"

Route14_Text_KiriPostBattle::
    .string "KIRI: Töpuðum við vegna mín?$"

Route14_Text_KiriNotEnoughMons::
    .string "KIRI: Við getum barist ef þú átt tvö\n"
    .string "Vasaskrímsli.$"

Route14_Text_JanIntro::
    .string "JAN: KIRI, hér förum við! Við verðum\n"
    .string "að reyna hart!$"

Route14_Text_JanDefeat::
    .string "JAN: Eeeeh! Ósanngjarnt!$"

Route14_Text_JanPostBattle::
    .string "JAN: KIRI, ekki gráta! Við reynum\n"
    .string "bara harðar næst.$"

Route14_Text_JanNotEnoughMons::
    .string "JAN: Viltu berjast? Þú átt ekki nóg\n"
    .string "af Vasaskrímslum.$"
