ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Úff! Ég er að reyna að leggja\n"
    .string "allar glósurnar á minnið.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Allt í lagi!\p"
    .string "Lestu það sem stendur á\n"
    .string "töflunni vandlega!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Skoðum minnisbókina.\p"
    .string "Fyrsta síða…\p"
    .string "VASA BOLTAR eru notaðir til að fanga\n"
    .string "Vasaskrímsli.\p"
    .string "Allt að sex Vasaskrímsli geta verið\n"
    .string "með í hópnum þínum.\p"
    .string "Fólk sem ræktar og berst með\n"
    .string "Vasaskrímslum er kallað ÞJÁLFARAR.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Önnur síða…\p"
    .string "Heilbrigt Vasaskrímsli getur verið\n"
    .string "erfitt að fanga, svo veiktu það\p"
    .string "fyrst.\p"
    .string "Eitraðu, brenndu, eða valdaðu öðru\n"
    .string "stöðuvandamáli til að veikja það.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Þriðja síða…\p"
    .string "Vasaskrímsli ÞJÁLFARAR leita annarra\n"
    .string "til að taka þátt í Vasaskrímsli\p"
    .string "bardögum.\p"
    .string "Fyrir ÞJÁLFARAR er bragðið af sigri\n"
    .string "sætt, sannarlega.\p"
    .string "Bardagar eru stöðugt háðir í\n"
    .string "Vasaskrímsli GYMS alls staðar.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fjórða síða…\p"
    .string "Endanlegt markmið allra Vasaskrímsla\n"
    .string "ÞJÁLFARA er einfalt.\p"
    .string "Það er að sigra efstu átta\n"
    .string "Vasaskrímsla SALUR LEIÐTOGA.\p"
    .string "Gerðu það til að öðlast réttinn til\n"
    .string "að mæta…\p"
    .string "ELITE FOUR í Vasaskrímsla DEILDINNI!$"

ViridianCity_School_Text_TurnThePage::
    .string "Fletta blaðsíðu?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "STÚLKA: Hæ! Ekki horfa á glósurnar\n"
    .string "mínar!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "Töflan sýnir Vasaskrímsli STATUS\n"
    .string "vandamál í bardögum.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Hvaða efni viltu lesa um?$"

ViridianCity_School_Text_ExplainSleep::
    .string "Vasaskrímsli getur ekki ráðist ef\n"
    .string "það er sofandi.\p"
    .string "Vasaskrímsli mun vera sofandi\n"
    .string "jafnvel eftir bardaga.\p"
    .string "Notaðu AWAKENING til að vekja það úr\n"
    .string "svefni.$"

ViridianCity_School_Text_ExplainBurn::
    .string "Bruni dregur úr ÁRÁS krafti. Hann\n"
    .string "veldur einnig viðvarandi HP tapi.\p"
    .string "Bruni er eftir bardaga. Notaðu BURN\n"
    .string "HEAL til að lækna bruna.$"

ViridianCity_School_Text_ExplainPoison::
    .string "Þegar eitrað, lækkar heilsa\n"
    .string "Vasaskrímslis stöðugt.\p"
    .string "Eitur er eftir bardaga. Notaðu\n"
    .string "ANTIDOTE til að lækna eitur!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "Frosið Vasaskrímsli verður\n"
    .string "hjálparlaust óhreyfanlegt.\p"
    .string "Það helst frosið jafnvel eftir að\n"
    .string "bardaganum lýkur.\p"
    .string "Notaðu ICE HEAL til að þíða þjáða\n"
    .string "Vasaskrímslið.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Lömun dregur úr SPEED og getur komað\n"
    .string "í veg fyrir að Vasaskrímslið\p"
    .string "hreyfi sig.\p"
    .string "Lömun er eftir bardaga. Notaðu\n"
    .string "PARLYZ HEAL til meðferðar.$"
