SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "Þetta skip, hún er lúxusskip fyrir\n"
    .string "ÞJÁLFARA heimsins!\p"
    .string "Í hverri höfn höldum við veislur með\n"
    .string "boðnum ÞJÁLFURUM.$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{RIVAL}: Bonjour! {PLAYER}!\p"
    .string "Hugsa sér að sjá þig hér! {PLAYER},\n"
    .string "var þér í alvöru boðið?\p"
    .string "Hvernig gengur með VasaDEX-ið þitt?\p"
    .string "Ég hef þegar náð 40 tegundum,\n"
    .string "félagi. Mismunandi tegundir eru alls\p"
    .string "staðar.\p"
    .string "Skriðu um graslendi og leitaðu vel\n"
    .string "að þeim.$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "Hmph!\p"
    .string "Að minnsta kosti ertu að ala upp\n"
    .string "vasaskrímslin þín!$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！ ふなよい してるのか！\p"
    .string "もっと からだ きたえた ほうが いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "{RIVAL}: Ég heyrði að það væri\n"
    .string "CUT-meistari um borð.\p"
    .string "En hann var bara sjóveikur gamall\n"
    .string "maður!\p"
    .string "CUT sjálft er mjög gagnlegt. Já, það\n"
    .string "mun koma sér vel.\p"
    .string "Þú ættir líka að fara að hitta hann.\n"
    .string "Sjáumst!$"

