Route10_Text_MarkIntro::
    .string "Vá, komstu alla leið hingað? Kannski\n"
    .string "ertu líka SKRÍMSLASJÚKUR? Viltu\p"
    .string "sjá safnið mitt?$"

Route10_Text_MarkDefeat::
    .string "Hmph. Ég er ekki reiður!$"

Route10_Text_MarkPostBattle::
    .string "Ég á fleiri sjaldgæf vasaskrímsli\n"
    .string "heima!$"

Route10_Text_ClarkIntro::
    .string "Ha-hahaha-ha-ha!$"

Route10_Text_ClarkDefeat::
    .string "Ha-haha! Ekki að hlæja! Ha-hay\n"
    .string "fever! Haha-ha-tjí!$"

Route10_Text_ClarkPostBattle::
    .string "Haha-ha-tjí! Ha-tjí! Snökt! Snökt!$"

Route10_Text_HermanIntro::
    .string "Hæ, krakki! Viltu sjá vasaskrímslið\n"
    .string "mitt?$"

Route10_Text_HermanDefeat::
    .string "Ó, nei! Vasaskrímslið mitt!$"

Route10_Text_HermanPostBattle::
    .string "Mér líkar ekki við þig. Mér líkar\n"
    .string "ekki við neinn sem er betri en ég!$"

Route10_Text_HeidiIntro::
    .string "Ég hef nokkrum sinnum komið út úr\n"
    .string "vasaskrímsla-SAL.\p"
    .string "...En ég tapa alltaf.$"

Route10_Text_HeidiDefeat::
    .string "Óó! Eftir alla þjálfunina!$"

Route10_Text_HeidiPostBattle::
    .string "Ég tók eftir nokkrum SKRÍMSLASJÚKUM\n"
    .string "á ráfi.\p"
    .string "Geturðu ímyndað þér það? Þau? Hér\n"
    .string "uppi í fjöllunum?$"

Route10_Text_TrentIntro::
    .string "Ah! Þetta fjallaloft er ljúffengt!$"

Route10_Text_TrentDefeat::
    .string "Þetta hreinsaði höfuðið!$"

Route10_Text_TrentPostBattle::
    .string "Ég er útþaninn af fjallalofti!$"

Route10_Text_CarolIntro::
    .string "Mér er dálítið yfirliða. Ég hef ekki\n"
    .string "gengið á fjöll lengi.$"

Route10_Text_CarolDefeat::
    .string "Ég er of þreytt. Ég var ekki tilbúin\n"
    .string "í þetta.$"

Route10_Text_CarolPostBattle::
    .string "Vasaskrímslin hér í fjöllunum eru\n"
    .string "svo þybbin...\p"
    .string "Ég vildi að til væru bleik\n"
    .string "vasaskrímsli með blómamynstri!$"

Route10_Text_RockTunnelDetourToLavender::
    .string "STEINA GÖNG Hjáleið til LAVENDER\n"
    .string "BORGAR$"

Route10_Text_RockTunnel::
    .string "STEINA GÖNG$"

Route10_Text_PowerPlant::
    .string "ORKUVER$"
