LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "Ég flutti nýlega í þennan bæ.\p"
    .string "Ég heyri að MR. FUJI sé ekki\n"
    .string "upprunalega héðan heldur.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "Þetta er skrítið, MR. FUJI er ekki\n"
    .string "hér. Hvert fór hann?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "MR. FUJI hafði verið að biðja einn\n"
    .string "fyrir móður BEINFARI.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "Þetta er í raun húsið hans MR. FUJI.\p"
    .string "Hann er mjög góður.\p"
    .string "Hann sér um yfirgefin og munaðarlaus\n"
    .string "Vasaskrímsli.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "Það er svo hlýtt! Það er svo gott að\n"
    .string "knúsa Vasaskrímsli.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "NÁLHERRA: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "MÍGRENDI: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "MR. FUJI: {PLAYER}…\p"
    .string "VasaDEX-leiðangurinn þinn krefst\n"
    .string "mikillar einurðar.\p"
    .string "Án djúprar ástar á Vasaskrímslum\n"
    .string "gæti leiðangurinn mistekist.\p"
    .string "Ég veit ekki hvort þetta hjálpar, en\n"
    .string "ég vil að þú eigir það.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} fékk VASAFLAUTU frá MR.\n"
    .string "FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "Þegar VASAFLAUTAN hljómar vakna\n"
    .string "sofandi Vasaskrímsli strax.\p"
    .string "Prófaðu hana á Vasaskrímsli sem sofa\n"
    .string "og loka leiðinni.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "Þú verður að gera pláss fyrir þetta!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "MR. FUJI: Hefur VASAFLAUTAN mín\n"
    .string "hjálpað þér?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "Mánaðarlegur aðalvinningur\n"
    .string "VASASKRÍMSLA AÐDÁENDABLAÐSINS!\p"
    .string "Umsóknarblaðið er…\p"
    .string "Farið! Það hefur verið klippt út.\n"
    .string "Einhver hefur þegar sótt um.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "Vasaskrímslatímarit standa í\n"
    .string "hillunni.\p"
    .string "VASASKRÍMSLA INNSÝN…\p"
    .string "VASASKRÍMSLA AÐDÁANDI…$"

