RockTunnel_1F_Text_LennyIntro::
    .string "Þessi göng ná langt, krakki!$"

RockTunnel_1F_Text_LennyDefeat::
    .string "Doh! Þú vinnur!$"

RockTunnel_1F_Text_LennyPostBattle::
    .string "Passaðu þig á GRÁNAMAÐKU. Þær\n"
    .string "birtast bara öðru hvoru.\p"
    .string "Þær á háu stigi geta kreist þig\n"
    .string "rækilega!$"

RockTunnel_1F_Text_OliverIntro::
    .string "Hmm. Kannski er ég týndur hér\n"
    .string "inni...$"

RockTunnel_1F_Text_OliverDefeat::
    .string "Slakaðu á! Hvað er ég að gera? Hver\n"
    .string "er leiðin út?$"

RockTunnel_1F_Text_OliverPostBattle::
    .string "Þetta sofandi vasaskrímsli á VEGUR\n"
    .string "12 neyddi mig til að taka þessa\p"
    .string "hjáleið.$"

RockTunnel_1F_Text_LucasIntro::
    .string "Utanaðkomandi eins og þú þurfa að\n"
    .string "sýna mér smá virðingu!$"

RockTunnel_1F_Text_LucasDefeat::
    .string "Ég gefst upp!$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "Þú ert nógu hæfileikaríkur til að\n"
    .string "ganga fjöll!$"

RockTunnel_1F_Text_AshtonIntro::
    .string "Vasaskrímsli berjast! Tilbúin,\n"
    .string "byrja!$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "Leik lokið!$"

RockTunnel_1F_Text_AshtonPostBattle::
    .string "Jæja, ég næ mér í BLAKILDA á\n"
    .string "leiðinni!$"

RockTunnel_1F_Text_LeahIntro::
    .string "Ííík!\p"
    .string "Ekki reyna neitt skrýtið í myrkrinu!$"

RockTunnel_1F_Text_LeahDefeat::
    .string "Það var of dimmt...$"

RockTunnel_1F_Text_LeahPostBattle::
    .string "Ég sá ÞREKANGA í þessum göngum.$"

RockTunnel_1F_Text_DanaIntro::
    .string "Ég kom alla þessa leið í leit að\n"
    .string "villtum vasaskrímslum.$"

RockTunnel_1F_Text_DanaDefeat::
    .string "Ég er uppiskroppa með vasaskrímsli!$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "Þú leitst út fyrir að vera sætur og\n"
    .string "meinlaus. Þar hafði ég heldur betur\p"
    .string "rangt fyrir mér!$"

RockTunnel_1F_Text_ArianaIntro::
    .string "Þú ert með vasaskrímsli! Byrjum!$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "Þú spilar hart!$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "Úff! Ég er orðin öll sveitt.$"

RockTunnel_1F_Text_RouteSign::
    .string "ROCK TUNNEL CERULEAN BORG - LAVENDER\n"
    .string "BORG$"

