CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "Hæ!\p"
    .string "Því miður, við erum í pásu núna.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "Vasaskrímslin mín eru veikburða, svo\n"
    .string "ég þarf oft að fara í LYFJABÚÐINA.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "Psst! Ég heyri að það sé kjallari\n"
    .string "undir SPILASALNUM.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Namm...\p"
    .string "Maðurinn við borðið tapaði öllu í\n"
    .string "spilakössunum.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "Gjörðu svo vel! Hlæðu bara! Ég er\n"
    .string "gjörsamlega blankur!\p"
    .string "Engir fleiri spilakassar fyrir mig!\n"
    .string "Ég ætla að taka mig á!\p"
    .string "Hér! Ég þarf ekki á þessu að halda\n"
    .string "lengur!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER} fékk PENINGAVESKI frá\n"
    .string "manninum.$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "Búðu til pláss fyrir þetta!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "Ég hélt alltaf að ég myndi vinna\n"
    .string "þetta til baka...$"

