TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Ég er HREYFINGASJÚKUR Vasaskrímsla.\p"
    .string "Ég þekki hverja einustu hreyfingu\n"
    .string "sem Vasaskrímsli læra þegar þau\p"
    .string "vaxa.\p"
    .string "Ég er líka sveppasjúkur.\p"
    .string "Komdu með tvo TINYMUSHROOMS eða einn\n"
    .string "BIG MUSHROOM.\p"
    .string "Ef þú gerir það fyrir mig kenni ég\n"
    .string "Vasaskrímsli hreyfingu.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Sniff, sniff… Hm! Þú lyktar af\n"
    .string "SVEPPUM!\p"
    .string "Viltu að ég kenni einu\n"
    .string "Vasaskrímslinu þínu hreyfingu?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Hvaða Vasaskrímsli þarf kennslu?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Hvaða hreyfingu á ég að kenna?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Fyrirgefðu…\p"
    .string "Það virðist ekki vera nein hreyfing\n"
    .string "sem ég get kennt þessu Vasaskrímsli.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Þá þarf ég einn eða tvo SVEPPI. Hvað\n"
    .string "ætlarðu að gefa mér?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} afhenti tvo TINYMUSHROOMS í\n"
    .string "staðinn.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} afhenti einn STÓRAN SVEPP í\n"
    .string "skiptum.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "Ef Vasaskrímslið þitt þarf að læra\n"
    .string "hreyfingu þarf ég SVEPP eða tvo.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Ha? Það er ekki ein einasta hreyfing\n"
    .string "sem ég get kennt EGGI.$"

