SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire::
    .string "{PLAYER} fann SAFÍR!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou::
    .string "Fufu… Fufufufu… Ég giskaði rétt.\p"
    .string "Það var rétt hjá mér að elta þig!$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword::
    .string "Ég vissi að hér væri SAFÍR, svo hann\n"
    .string "tilheyrir mér!\p"
    .string "Ég sel hann ROCKET-GENGINU fyrir\n"
    .string "fullt af peningum.\p"
    .string "…E-ekki stara svona á mig!\p"
    .string "Ef þú vilt hann aftur, farðu þá að\n"
    .string "ná í hann!\p"
    .string "Ég skal meira að segja segja þér\n"
    .string "lykilorðið að ROCKET-GEYMSLUNNI.\p"
    .string "Annað lykilorðið er: 'Já, nei,\n"
    .string "SÆLEGG.'$"

