FiveIsland_MemorialPillar_Text_MiloIntro::
    .string "Ég er elstur FUGLABRÆÐRANNA.\p"
    .string "Það besta við fugla… Það hlýtur að\n"
    .string "vera goggurinn.$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
    .string "Ó, svo beitt!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
    .string "Þú getur flogið héðan til FOUR EYJU.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
    .string "Ég er miðjubarn FUGLABRÆÐRANNA.\p"
    .string "Það besta við fugla… Það hlýtur að\n"
    .string "vera vængirnir.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
    .string "Blaka, blaka!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
    .string "Það var mjög alvarlegur gaur þarna\n"
    .string "hjá.$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
    .string "Ég er yngstur FUGLABRÆÐRANNA.\p"
    .string "Það besta við fugla… Það hlýtur að\n"
    .string "vera dúnninn.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
    .string "Dúnn er svo mjúkur… Hann gerir mig\n"
    .string "syfjaðan…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
    .string "Það fyllir mig gleði þegar\n"
    .string "fugla-Vasaskrímsli leika sér og\p"
    .string "biðja um athygli…$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
    .string "Skrúbba, skrúbba…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
    .string "Halló… Vasaskrímslin þín virðast\n"
    .string "heilbrigð…$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
    .string "Hér jarðaði ég GRÁNAMAÐKU mína… Hún\n"
    .string "hét TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
    .string "'Hér hvílir TECTONIX' er grafið á\n"
    .string "stórgrýti.\p"
    .string "LEMONADE stendur sem fórnargjöf\n"
    .string "fyrir framan gröfina.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
    .string "Viltu skilja eftir aðra LEMONADE sem\n"
    .string "fórn?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
    .string "{PLAYER} setti dós af LEMONADE fyrir\n"
    .string "framan gröfina.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
    .string "Þ-þakka þér…\p"
    .string "Þetta var uppáhaldsdrykkurinn hans\n"
    .string "TECTONIX…\p"
    .string "Ég þekki þig ekki einu sinni, en\n"
    .string "góðvildin þín…\p"
    .string "Hún lyfti mér aðeins upp.\p"
    .string "Viltu taka þetta sem þakklætisvott?$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
    .string "Vertu líka góður við Vasaskrímslin\n"
    .string "þín.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
    .string "Ef þú hefur ekki pláss fyrir það,\n"
    .string "mun ég geyma það fyrir þig til næst.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
    .string "Ó, það ert þú frá því síðast…\p"
    .string "Ég á enn hlutinn sem ég vildi gefa\n"
    .string "þér sem þakklæti.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
    .string "Scrub, scrub…\p"
    .string "… … … TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
    .string "Stórgrýti og steinar eru snyrtilega\n"
    .string "hlaðin upp sem varða.\p"
    .string "'Hér hvílir TECTONIX' er grafið á\n"
    .string "stórgrýti.$"

