Text_UltimateMoveThatMon::
    .string "Ég fullkomnaði öflugustu hreyfingu\n"
    .string "sinnar gerðar…\p"
    .string "En ætlar enginn að taka hana til\n"
    .string "framtíðarnota?\p"
    .string "…Hm? Hmmm!\p"
    .string "Þ-þú… Þ-þessi {STR_VAR_1}…$"

Text_JustMistaken::
    .string "…Nei… Ég hafði bara rangt fyrir mér.$"

Text_AllowMeToTeachMonUltimateMove::
    .string "Ó! Þetta er það! Þetta er\n"
    .string "Vasaskrímslið!\p"
    .string "Þetta {STR_VAR_1} er verðugt þess að\n"
    .string "læra fullkomnu hreyfinguna mína!\p"
    .string "Leyfirðu það?\p"
    .string "Leyfirðu {STR_VAR_1} þínu að læra\n"
    .string "{STR_VAR_2} mína?$"

Text_YouRejectIt::
    .string "Gaah! Hafnarðu því? Nei, ég læt ekki\n"
    .string "telja mig af því!$"

Text_LetMeConferUltimateMove::
    .string "Leyfirðu það?\p"
    .string "Þá skal ég veita þínu {STR_VAR_1}\n"
    .string "mína fullkomnu {STR_VAR_2}.\p"
    .string "Ggggrah-awooo!$"

Text_TaughtMove::
    .string "Andvarp, andvarp, andvarp…\p"
    .string "Ég hélt ég gæti ekki kennt þessa\n"
    .string "hreyfingu meðan ég lifði enn…$"

Text_MakeBestUseOfMove::
    .string "Ég bið þig að nýta þessa hreyfingu\n"
    .string "sem best og eflast!$"

Text_PassedOnEverythingIKnow::
    .string "Más, más, más…\p"
    .string "Ég sé ekki eftir neinu núna. Ég hef\n"
    .string "miðlað öllu sem ég veit.\p"
    .string "Nú get ég lifað lífinu vitandi að\n"
    .string "verki mínu er lokið.$"

Text_FeelRejuvenated::
    .string "Eftir að ég miðlaði þér þekkingu\n"
    .string "minni létti mér mjög.\p"
    .string "Reyndar líður mér endurnærðum, eins\n"
    .string "og ég sé yngri á ný!$"
