Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hæ! Ég vinn í Vasaskrímsla-búð.\p"
    .string "Hún er hluti af þægilegri keðju sem\n"
    .string "selur alls konar hluti.\p"
    .string "Kíktu til okkar í VIRIDIAN BORG.\p"
    .string "Heyrðu, ég gef þér prufu. Gjörðu svo\n"
    .string "vel!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Komdu endilega til okkar ef þig\n"
    .string "vantar VASA BOLTA til að fanga\p"
    .string "Vasaskrímsli.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} setti SEYÐI í HLUTAHÓLFIÐ\n"
    .string "í TÖSKUNNI.$"

Route1_Text_CanJumpFromLedges::
    .string "Sérðu þessar brúnir meðfram veginum?\p"
    .string "Það er svolítið ógnvekjandi, en þú\n"
    .string "getur hoppað niður af þeim.\p"
    .string "Þú kemst fljótlegra aftur til PALLET\n"
    .string "BÆJAR þannig.$"

Route1_Text_RouteSign::
    .string "VEGUR 1 PALLET BÆR - VIRIDIAN BORG$"
