PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "Komdu, barn! Ég hef hreinsað þetta\n"
    .string "rými. Þú getur hvílt þig hér.$"

PokemonTower_5F_Text_TammyIntro::
    .string "Gefðu… mér… allt…$"

PokemonTower_5F_Text_TammyDefeat::
    .string "Stunnt!$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "Ég var haldin.$"

PokemonTower_5F_Text_RuthIntro::
    .string "Þú… munt… ganga… til liðs við okkur…$"

PokemonTower_5F_Text_RuthDefeat::
    .string "Hvílík martröð!$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "Ég var haldin.$"

PokemonTower_5F_Text_KarinaIntro::
    .string "Uppvakningar!$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "Ha?$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "Ég náði áttum aftur.$"

PokemonTower_5F_Text_JanaeIntro::
    .string "Urgah… Urff…$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "Úff!$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "Ég féll fyrir illum öndum þrátt\n"
    .string "fyrir þjálfun mína í fjöllunum…$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "Fórst inn á hreinsað og verndað\n"
    .string "svæði.\p"
    .string "Vasaskrímsli {PLAYER} voru læknuð að\n"
    .string "fullu.$"

