Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
    .string "Gangandi vegfarendur eru ekki\n"
    .string "leyfðir á HJÓLAVEGINUM!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
    .string "HJÓLAVEGURINN er niðurleið við sjóinn.\n"
    .string "Það er frábær ferð.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .string "Afsakaðu! Bíddu aðeins!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
    .string "Hvernig komst þú inn? Vel gert!$"
