Route12_FishingHouse_Text_DoYouLikeToFish::
    .string "Ég er yngri bróðir VEIÐIGÚRÚSINS.\p"
    .string "Ég einfaldlega elska að veiða! Ég\n"
    .string "get ekki verið án þess.\p"
    .string "Segðu mér, líkar þér að veiða?$"

Route12_FishingHouse_Text_TakeThisAndFish::
    .string "Frábært! Mér líkar stíllinn þinn. Ég\n"
    .string "held að við getum verið vinir.\p"
    .string "Taktu þetta og veiddu, ungi vinur!$"

Route12_FishingHouse_Text_ReceivedSuperRod::
    .string "{PLAYER} fékk SUPER ROD frá bróður\n"
    .string "FISKIGÚRÚSINS.$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe::
    .string "Veiði er lífsstíll! Hún er eins og\n"
    .string "fínasta ljóðlist.\p"
    .string "Frá sjó til áa, farðu út og veiddu\n"
    .string "stóra, vinur minn.\p"
    .string "Nú, ég hef beiðni.\p"
    .string "Ef þú veiðir stóran GREYSLEPPA með\n"
    .string "þessari STÖNG, vil ég sjá hann.\p"
    .string "Jafn mikið og ég elska að veiða,\n"
    .string "elska ég líka að sjá risastóra\p"
    .string "GREYSLEPPA.$"

Route12_FishingHouse_Text_OhThatsDisappointing::
    .string "Ó… Það eru vonbrigði…$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
    .string "Halló, {PLAYER}! Hefurðu verið að\n"
    .string "veiða?\p"
    .string "Prófaðu að veiða með SUPER ROD í\n"
    .string "hvaða vatni sem er.\p"
    .string "Þú finnur ólík Vasaskrímsli á ólíkum\n"
    .string "stöðum.\p"
    .string "Ó, og ekki gleyma að koma með\n"
    .string "GREYSLEPPU ef þú færð eina!$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
    .string "Ó? {PLAYER}? Þetta er þá\n"
    .string "GREYSLEPPA!\p"
    .string "Leyfðu mér að sjá hana, fljótt!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
    .string "… … …Vá! {STR_VAR_2} tommur!\p"
    .string "Þú kannt sjaldgæft að meta hina\n"
    .string "fínu, ljóðrænu hlið veiðinnar!\p"
    .string "Þú verður að taka þetta. Ég heimta\n"
    .string "það!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
    .string "Ég hlakka til að sjá betri árangur\n"
    .string "frá þér!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
    .string "Ha? {STR_VAR_2} tommur?\p"
    .string "Þetta er sama stærð og sá sem ég sá\n"
    .string "áður.$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
    .string "Hmm… Þessi er {STR_VAR_2} tommur á\n"
    .string "lengd.\p"
    .string "Hann stenst ekki samanburð við þann\n"
    .string "{STR_VAR_3} tommu sem þú færðir\p"
    .string "áður.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
    .string "Uh… Þetta líkist ekki mikið\n"
    .string "GREYSLEPPU.$"

Route12_FishingHouse_Text_NoRoomForGift::
    .string "Ó, nei!\p"
    .string "Ég átti gjöf handa þér, en þú hefur\n"
    .string "ekki pláss fyrir hana.$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
    .string "Stærsta GREYSLEPPA sem ég hef nokkru\n"
    .string "sinni séð…\p"
    .string "{STR_VAR_3} tommur!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort::
    .string "Þetta er einhvers konar autt kort.\p"
    .string "Það hefur rými fyrir skráningu\n"
    .string "einhvers konar gagna.$"
