CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "Það er ekkert sem ég veit ekki,\n"
    .string "alveg eins og ég skrifaði á töfluna.\p"
    .string "Ég veit allt um heim vasaskrímsla í\n"
    .string "GAME BOY ADVANCE tækinu þínu!\p"
    .string "Hittu vini þína og njóttu þess að\n"
    .string "skiptast á vasaskrímslum!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} fékk SNIÐDÝR!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "Það er fullt af vasaskrímslum.\n"
    .string "Skiptu um BOX og komdu aftur.$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "Vasaskrímsla-fyrirlestur\p"
    .string "Spilað með þráðlausa millistykkinu$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "Hvaða fyrirsögn viltu lesa?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "VASASKRÍMSLA-ÞRÁÐLAUSI KLÚBBURINN er\n"
    .string "uppi á hæð á öllum\p"
    .string "VASASKRÍMSLA-MIÐSTÖÐVUM.\p"
    .string "Hittu vin til að tengjast með\n"
    .string "þráðlausa millistykkinu þínu.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "Til að tengjast aðeins við einn vin,\n"
    .string "farðu í BEINA HORNIÐ.\p"
    .string "Það er hægri afgreiðslan hjá\n"
    .string "VASASKRÍMSLA-ÞRÁÐLAUSA KLÚBBUNUM.\p"
    .string "Farðu í SKIPTIHORNIÐ eða LEIKVANGINN\n"
    .string "með vini þínum.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "Til að tengjast og eiga samskipti\n"
    .string "við hvern sem er, farðu í\p"
    .string "SAMKOMUSALINN.\p"
    .string "Það er vinstri afgreiðslan hjá\n"
    .string "VASASKRÍMSLA-ÞRÁÐLAUSA KLÚBBUNUM.\p"
    .string "Farðu í SAMKOMUSALINN og njóttu þess\n"
    .string "að hitta aðra ÞJÁLFARA.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "Þetta er bæklingur um TM-brögð.\p"
    .string "... ...\p"
    .string "Alls eru fimmtíu TM-brögð.\p"
    .string "Það eru líka sjö HM-brögð sem má\n"
    .string "nota aftur og aftur.\p"
    .string "SILPH CO.$"

