CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
    .string "Mér líst ansi vel á þessa GRAFÍKJU!\n"
    .string "En það er erfitt að vinna í\p"
    .string "spilakössunum!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
    .string "Gahaha! Ég rakaði inn vinninga í\n"
    .string "dag! Ef bara hver dagur væri\p"
    .string "svona...$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
    .string "PENINGAVESKI er nauðsynlegt...$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
    .string "Við skiptum PENINGUM fyrir vinninga.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
    .string "Hvaða vinning viltu?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
    .string "Gjörðu svo vel.$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
    .string "Þannig að þú vilt {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
    .string "Allt í lagi, þú vilt TM með\n"
    .string "{STR_VAR_2}?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
    .string "Því miður, þú þarft fleiri PENINGA\n"
    .string "en það.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
    .string "Þú getur ekki borið meira, vinur.$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
    .string "Jæja, þá það.$"

