SixIsland_PatternBush_Text_BethanyIntro::
    .string "Ég er forvitin, hvernig elurðu upp\n"
    .string "Vasaskrímslin þín?$"

SixIsland_PatternBush_Text_BethanyDefeat::
    .string "Þú elur Vasaskrímslin þín upp með\n"
    .string "heilmikilli ást!$"

SixIsland_PatternBush_Text_BethanyPostBattle::
    .string "Á sama hátt og mamma þín ól þig upp\n"
    .string "með ást, ættirðu að ala\p"
    .string "Vasaskrímslin þín upp.$"

SixIsland_PatternBush_Text_AllisonIntro::
    .string "Ég vinn að því að varðveita\n"
    .string "náttúrulegt vistkerfi Vasaskrímsla\p"
    .string "hér.$"

SixIsland_PatternBush_Text_AllisonDefeat::
    .string "Ó, fyrir einhvern svona ungan, ertu\n"
    .string "frábær!$"

SixIsland_PatternBush_Text_AllisonPostBattle::
    .string "Ég er ekki að segja að fólk eigi\n"
    .string "ekki að fanga Vasaskrímsli.\p"
    .string "Ég vil bara að fólk ali\n"
    .string "Vasaskrímslin sín upp af ábyrgð.$"

SixIsland_PatternBush_Text_GarretIntro::
    .string "Ég fangaði SKORDÝRA Vasaskrímsli sem\n"
    .string "lifir aðeins hér í kring!$"

SixIsland_PatternBush_Text_GarretDefeat::
    .string "Heheh… Er Vasaskrímslið mitt ekki\n"
    .string "geggjað?$"

SixIsland_PatternBush_Text_GarretPostBattle::
    .string "Það er stelpa nálægt BUSH sem mælir\n"
    .string "HORNUXI fyrir ÞJÁLFARA.$"

SixIsland_PatternBush_Text_JonahIntro::
    .string "Veistu, mér finnst þetta bara ekki\n"
    .string "rétt ef ég nota ekki SKORDÝRA\p"
    .string "Vasaskrímsli.$"

SixIsland_PatternBush_Text_JonahDefeat::
    .string "Það er allt í lagi, að tapa er líka\n"
    .string "skemmtilegur hluti af aðdráttarafli\p"
    .string "Vasaskrímsla.$"

SixIsland_PatternBush_Text_JonahPostBattle::
    .string "Annars er orðið 'aðdráttarafl'\n"
    .string "svolítið skrítið þegar maður hugsar\p"
    .string "út í það.\p"
    .string "Er það eins og maður dragi eitthvað\n"
    .string "að sér? Eða er það bara eitthvað\p"
    .string "flott?$"

SixIsland_PatternBush_Text_VanceIntro::
    .string "Já, já, já! Sjáðu öll SKORDÝRA\n"
    .string "Vasaskrímslin!$"

SixIsland_PatternBush_Text_VanceDefeat::
    .string "Ég var sigraður á meðan ég var enn\n"
    .string "upptekinn við að fagna!$"

SixIsland_PatternBush_Text_VancePostBattle::
    .string "Ég ætla að koma með litla bróður\n"
    .string "minn hingað næst.$"

SixIsland_PatternBush_Text_NashIntro::
    .string "Sjáðu, sjáðu! Það eru fyndin mynstur\n"
    .string "á jörðinni.$"

SixIsland_PatternBush_Text_NashDefeat::
    .string "Ofur frábært!$"

SixIsland_PatternBush_Text_NashPostBattle::
    .string "Fyndnu mynstrin á jörðinni…\p"
    .string "Þau líta út eins og mynstrin á fötum\n"
    .string "afa míns.$"

SixIsland_PatternBush_Text_CordellIntro::
    .string "Ég veðja að þú heldur að ég sé bara\n"
    .string "einhver gaur, er það ekki, ha?$"

SixIsland_PatternBush_Text_CordellDefeat::
    .string "Ég veðja að þú heldur að ég sé\n"
    .string "veikur, er það ekki, ha?$"

SixIsland_PatternBush_Text_CordellPostBattle::
    .string "Jájá, þið bæjarbúarnir mætið\nalltaf\n"
    .string "svo fín með svona\p"
    .string "glæsilegan\nhatt…\n\nHvernig væri að\n"
    .string "gefa mér hann?$"

SixIsland_PatternBush_Text_DaliaIntro::
    .string "Dragðu djúpt andann. Er loftið ekki\n"
    .string "ljúffengt?$"

SixIsland_PatternBush_Text_DaliaDefeat::
    .string "Ef þú vilt, get ég kennt þér hvernig\n"
    .string "á að anda rétt.$"

SixIsland_PatternBush_Text_DaliaPostBattle::
    .string "Fyrst, andaðu frá þér. Blástu öllu\n"
    .string "út.\p"
    .string "Þegar þú getur ekki andað frá þér\n"
    .string "meira, andaðu að þér hreinu lofti!\p"
    .string "Er það ekki hressandi?$"

SixIsland_PatternBush_Text_JoanaIntro::
    .string "Ég elska SKORDÝRA Vasaskrímsli. Þess\n"
    .string "vegna er ég hér allan tímann.\p"
    .string "Er ég eina stelpan sem er svona?$"

SixIsland_PatternBush_Text_JoanaDefeat::
    .string "Ég tapaði, en ég er enn að hlæja. Er\n"
    .string "ég eina stelpan svona?$"

SixIsland_PatternBush_Text_JoanaPostBattle::
    .string "Ég ætla að halda áfram að safna\n"
    .string "SKORDÝRA Vasaskrímslum.\p"
    .string "Er ég eina stelpan sem er svona?$"

SixIsland_PatternBush_Text_RileyIntro::
    .string "Þetta er góður staður. Ég ætla að\n"
    .string "setja upp tjaldið mitt hér.$"

SixIsland_PatternBush_Text_RileyDefeat::
    .string "Varaðist…$"

SixIsland_PatternBush_Text_RileyPostBattle::
    .string "Ég ætla að fylgjast með\n"
    .string "næturhimninum hér.$"

SixIsland_PatternBush_Text_MarcyIntro::
    .string "Ó, fyndið! Ég held að skordýr hafi\n"
    .string "stungið mig!$"

SixIsland_PatternBush_Text_MarcyDefeat::
    .string "Það var ekki skordýr. Ég skar\n"
    .string "sköflunginn minn á einhverju grasi.$"

SixIsland_PatternBush_Text_MarcyPostBattle::
    .string "Svona lítil rispa… Smá munnvatn\n"
    .string "dugar til að lækna hana!$"

SixIsland_PatternBush_Text_LaytonIntro::
    .string "Hefurðu tekið eftir einhverju\n"
    .string "undarlegu við þessa staði?$"

SixIsland_PatternBush_Text_LaytonDefeat::
    .string "Hefurðu skoðað vel í kringum fæturna\n"
    .string "á þér?$"

SixIsland_PatternBush_Text_LaytonPostBattle::
    .string "Það eru staðir hér í MYNSTURRUNNA\n"
    .string "þar sem gras vex ekki.\p"
    .string "Hver gæti verið orsök slíks\n"
    .string "fyrirbæris?$"
