SilphCo_10F_Text_GruntIntro::
    .string "Velkomin á 10H! Fallegt af þér að\n"
    .string "slást í för með mér!$"

SilphCo_10F_Text_GruntDefeat::
    .string "Ég er steinhissa!$"

SilphCo_10F_Text_GruntPostBattle::
    .string "Góð tilraun, en stjórnarherbergið er\n"
    .string "einni hæð ofar.$"

SilphCo_10F_Text_TravisIntro::
    .string "Nóg af þessum kjánalegu leikjum!$"

SilphCo_10F_Text_TravisDefeat::
    .string "Engin framhöld eftir!$"

SilphCo_10F_Text_TravisPostBattle::
    .string "Ertu sátt við að hafa sigrað mig?\n"
    .string "Farðu þá heim!$"

SilphCo_10F_Text_WaaaImScared::
    .string "Vaaaa! Ég er hrædd!$"

SilphCo_10F_Text_KeepMeCryingASecret::
    .string "Varðandi grátinn minn… Hafðu það\n"
    .string "leyndarmál, vinsamlegast.$"

SilphCo_10F_Text_FloorSign::
    .string "SILPH CO. HÖFUÐSKRIFSTOFA 10H$"
