SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "{PLAYER}: Hæ! Finnst þér\n"
    .string "Vasaskrímsli skemmtileg?\p"
    .string "{PLAYER}: Æ, nei, ég spurði þig\n"
    .string "bara.\p"
    .string "{PLAYER}: Ha? Þú ert skrýtin/n!\p"
    .string "COPYCAT: Hmm? Hætta að herma? En það\n"
    .string "er uppáhaldsáhugamálið mitt!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "{PLAYER}: Hæ. Þú hlýtur að fíla\n"
    .string "Vasaskrímsli.\p"
    .string "{PLAYER}: Nei, ekki ég. Ég spurði\n"
    .string "þig.\p"
    .string "{PLAYER}: Fyrirgefðu? Þú ert\n"
    .string "skrýtin/n!\p"
    .string "COPYCAT: Hmm? Hætta að herma? En það\n"
    .string "er uppáhaldsáhugamálið mitt!$"

Text_MimicTeach::
    .string "Vá! VASa DÚKKA!\p"
    .string "Handa mér? Takk!\p"
    .string "Veistu hvað? Ég get kennt\n"
    .string "hreyfinguna MIMIC.$"

Text_MimicDeclined::
    .string "Líkar þér ekki við MIMIC?$"

Text_MimicWhichMon::
    .string "I really love MIMIC! Who's going to\n"
    .string "learn it?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: Hæ! Takk fyrir áðan!\p"
    .string "{PLAYER}: Fyrirgefðu?\p"
    .string "{PLAYER}: Er það svona skemmtilegt\n"
    .string "að herma eftir hverri hreyfingu\p"
    .string "minni?\p"
    .string "HERMIR: Já, algjörlega! Það er\n"
    .string "æðislegt!$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: Hæ! Takk fyrir það sem þú\n"
    .string "gerðir fyrir okkur.\p"
    .string "{PLAYER}: Fyrirgefðu?\p"
    .string "{PLAYER}: Er það virkilega svona\n"
    .string "skemmtilegt að herma eftir því sem\p"
    .string "ég segi og geri?\p"
    .string "HERMIR: Já, algjörlega! Það er\n"
    .string "æðislegt!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "にもつが いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "{PLAYER}'やあ！ こんにちは！ きみ ポケモン すきかい？\p"
    .string "{PLAYER}'ぼく じゃなくって きみに きいてるんだ けど\p"
    .string "{PLAYER}'‥‥ えー なんだよ！ ヘンな やつ だなあ！\p"
    .string "モノマネむすめ'‥‥ なに？ ひとの マネ すんなって？\p"
    .string "だって あたし ものまね しゅみ なんだ もん！'$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "{PLAYER}'こんにちは！ ポケモン すきなのね？\p"
    .string "{PLAYER}'わたし じゃなくって あなたに きいてるんだ けど\p"
    .string "{PLAYER}'‥ えー なんなの！ おかしなこ ねー！\p"
    .string "モノマネむすめ'‥ なに？ ひとの マネ すんなって？\p"
    .string "だって あたし ものまね しゅみ なんだ もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "PARFUGL: Giiih!\p"
    .string "FALLEGI SPEGILL HORFÐU Á MIG, SJÁÐU\n"
    .string "HVERSU FALLEG ÉG GET VERIÐ?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "Þetta er sjaldgæft Vasaskrímsli! Ha?\n"
    .string "Þetta er bara dúkka!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "Leikur með MARIO með fötu á höfðinu!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "…\p"
    .string "My Secrets!\p"
    .string "Skill: Mimicry! Hobby: Collecting\n"
    .string "dolls! Favorite Vasaskrímsli:\p"
    .string "BLEIKÁLFUR!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "？ みえないぞ‥$"
