PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "Mamma: … Rétt. Allir strákar fara að\n"
    .string "heiman einhvern tíma. Það sagði svo\p"
    .string "í sjónvarpinu.\p"
    .string "Ó, já. Prófessor EIK, í næsta húsi,\n"
    .string "var að leita að þér.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "Mamma: … Rétt. Allar stelpur dreymir\n"
    .string "um að ferðast. Það sagði svo í\n"
    .string "sjónvarpinu.\p"
    .string "Ó, já. Prófessor EIK, í næsta húsi,\n"
    .string "var að leita að þér.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "Mamma: {PLAYER}! Þú ættir að hvíla þig\n"
    .string "snögglega.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "Mamma: Ó, gott! Þú og VASaSKRÍMSLI\n"
    .string "þinn lítur vel út. Farðu varlega\p"
    .string "núna!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Það er kvikmynd í sjónvarpinu.\n"
    .string "Fjórir strákar\n"
    .string "ganga á járnbrautarteinum.\p"
    .string "… það er best að ég fari líka.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Það er bíómynd í sjónvarpinu.\n"
    .string "Stúlka með\n"
    .string "hárið í grísum gengur upp\p"
    .string "múrsteinsvegi.\p"
    .string "… það er best að ég fari líka.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Úps, röng hlið…$"
