LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "Halló, halló! Ég er opinberi\n"
    .string "NAFNADÓMARINN!\p"
    .string "Viltu að ég meti gælunöfn\n"
    .string "Vasaskrímslanna þinna?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "Hvaða Vasaskrímslis gælunafn á ég að\n"
    .string "meta?$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "{STR_VAR_1}, er það? Það er ágætt\n"
    .string "viðurnefni!\p"
    .string "En, viltu að ég gefi því fínna nafn?\p"
    .string "Hvað segirðu?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Ah, gott. Hvað á nýja gælunafnið þá\n"
    .string "að vera?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "Búið! Héðan í frá skal þetta\n"
    .string "Vasaskrímsli kallast {STR_VAR_1}!\p"
    .string "Það er betra nafn en áður! Þú ert\n"
    .string "heppinn!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "I see. Do come visit again.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "Búið! Héðan í frá skal þetta\n"
    .string "Vasaskrímsli kallast {STR_VAR_1}!\p"
    .string "Það lítur ekkert öðruvísi út en\n"
    .string "áður, en samt er þetta miklu betra!\p"
    .string "Þú ert heppinn!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "{STR_VAR_1}, er það? Það er\n"
    .string "sannarlega óaðfinnanlegt nafn!\p"
    .string "Hafðu góða umhyggju fyrir\n"
    .string "{STR_VAR_1}!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "Nú, nú. Þetta er bara EGG!$"

