RocketHideout_B3F_Text_Grunt1Intro::
    .string "Hættu að skipta þér af málum\n"
    .string "ROCKET-GENGISINS, annars…!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "Úff! Felldur!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "SILPH SCOPE? Ó, vélin sem\n"
    .string "FORINGINN stal.\p"
    .string "Hún er hér einhvers staðar.$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "Við fengum boð að ofan um að þú\n"
    .string "værir á leiðinni!$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "Hvað? Ég tapaði? Nei!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "Farðu þá bara!\p"
    .string "En þú getur ekki notað lyftuna\n"
    .string "án LIFT LYKILS.$"
