SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
    .string "Vaxtarhraði Vasaskrímsla er\n"
    .string "mismunandi eftir tegundum.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
    .string "SILPH CO. er víða þekkt af öllum.\p"
    .string "Það er fórnarlamb eigin frægðar -\n"
    .string "það dró að sér ROCKET-GENGIÐ.$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .string "Andvarp… Væri það ekki frábært?\p"
    .string "Ef ELÍTA 4 kæmi og klessti\n"
    .string "ROCKET-GENGIÐ?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
    .string "ROCKET-GENGIÐ fór! Við getum farið\n"
    .string "út aftur í öruggu skjóli! Frábært!$"
