Route16_House_Text_FoundMySecretRetreat::
    .string "Ó, góði minn. Þú fannst leynistaðinn\n"
    .string "minn.\p"
    .string "Vinsamlegast segðu engum að ég sé\n"
    .string "hér. Ég bæti þér það upp með þessu!$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} fékk HM02 frá stúlkunni.$"

Route16_House_Text_ExplainHM02::
    .string "HM02 er FLUG. Þetta er dásamlega\n"
    .string "hentug hreyfing.\p"
    .string "Notaðu hana vel, gerðu það.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "Þú hefur ekkert pláss fyrir þetta.$"

Route16_House_Text_Fearow::
    .string "GEIGHEGRI: Kyueen!$"

