PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "VASASKRÍMSLATURN var reistur til\n"
    .string "minningar um Vasaskrímsli sem\p"
    .string "dóu.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Komstu til að votta virðingu þína?\p"
    .string "Blessað sé Vasaskrímslaelskandi\n"
    .string "hjarta þitt, sonur.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Komstu til að votta virðingu þína?\p"
    .string "Blessað sé Vasaskrímslaelskandi\n"
    .string "hjarta þitt, stúlka.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Ég kom til að biðja fyrir mínum kæra\n"
    .string "horfna BLEIKÁLFI.\p"
    .string "Snökt! Ég er að drukkna í tárum…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "BLYSRAKKINN minn… Af hverju dóstu?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "Ég er MIÐILL.\p"
    .string "Það eru andar að gera óþekkt. Ég\n"
    .string "skynja þá hátt í TURNINUM.$"
