FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "Við kölluðum VÖRÐINN 'SLJÓN.'\p"
    .string "Þú veist, hann er með tóma svipinn\n"
    .string "eins og SLJÓN.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "VÖRÐURINN SLJÓN veit mjög mikið um\n"
    .string "Vasaskrímsli.\p"
    .string "Hann á meira að segja steingervinga\n"
    .string "af sjaldgæfum, útdauðum\p"
    .string "Vasaskrímslum.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "VÖRÐURINN SLJÓN kom inn, en ég\n"
    .string "skildi hann ekki.\p"
    .string "Ég held að hann eigi erfitt með mál!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "VÖRÐURINN SLJÓN stendur nú fyrir\n"
    .string "kynningarátaki.\p"
    .string "Reyndu að komast í fjarlægasta horn\n"
    .string "SAFARI SVÆÐISINS.\p"
    .string "Ef þér tekst það færðu mjög\n"
    .string "nytsamleg verðlaun.$"

