Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "Gerðir vasaskrímsla virka ólíkt hver\n"
    .string "gagnvart annarri.\p"
    .string "Hver gerð er sterkari en sumar\n"
    .string "gerðir og veikari en aðrar.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "GULLKLUMPUR nýtist mér ekkert. Svo\n"
    .string "ég seldi hann fyrir ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "Ég heyrði að draugar ásæki LAVENDER\n"
    .string "BORG.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Ó... {PLAYER}! Ég hef verið að leita\n"
    .string "að þér!\p"
    .string "Þetta er ég, einn af síviðstöddum\n"
    .string "AÐSTOÐARMÖNNUM Prófessor EIK.\p"
    .string "Ef VasaDEX-ið þitt er með full gögn\n"
    .string "um tuttugu tegundir á ég að gefa þér\p"
    .string "verðlaun frá Prófessor EIK.\p"
    .string "Hann fól mér þennan EILÍFSTEIN.\p"
    .string "Svo, {PLAYER}, leyfðu mér að spyrja.\p"
    .string "Hefurðu safnað gögnum um að minnsta\n"
    .string "kosti tuttugu gerðir vasaskrímsla?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Frábært! Þú hefur náð eða átt\n"
    .string "{STR_VAR_3} gerðir vasaskrímsla!\p"
    .string "Til hamingju! Gjörðu svo vel!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} fékk EILÍFSTEIN frá\n"
    .string "AÐSTOÐARMANNINUM.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "Að láta vasaskrímsli þróast getur\n"
    .string "vissulega bætt við VasaDEX-ið.\p"
    .string "En stundum viltu kannski ekki að\n"
    .string "ákveðið vasaskrímsli þróist.\p"
    .string "Þá skaltu gefa því EILÍFSTEIN.\p"
    .string "Hann kemur í veg fyrir þróun, að\n"
    .string "sögn PRÓFESSORSINS.$"

