SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
    .string "Leiktu mikið við Vasaskrímsli og\n"
    .string "lifðu lengi!\p"
    .string "Taktu AGATHA sem dæmi.\p"
    .string "Hún setti met sem elsti meðlimur\n"
    .string "ELITE FOUR frá upphafi.\p"
    .string "Hún hvetur mig til að gera stærri\n"
    .string "hluti.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
    .string "Ég ætti að kaupa BRÉFPAPPÍR og\n"
    .string "skrifa honum bréf…$"

