CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: Jæja! {PLAYER}!\p"
    .string "Ertu enn að puða hér aftar?\p"
    .string "Mér gengur frábærlega! Ég náði fullt\n"
    .string "af sterkum og klókum vasaskrímslum!\p"
    .string "Komdu, sýndu mér hvað þú hefur náð,\n"
    .string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
    .string "Hey! Slakaðu á! Þú vannst nú þegar!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: Hey, veistu hvað?\p"
    .string "Ég fór til BILL og fékk hann til að\n"
    .string "sýna mér sjaldgæfu vasaskrímslin\p"
    .string "sín.\p"
    .string "Það bætti helling af síðum í\n"
    .string "VasaDEX-ið mitt!\p"
    .string "Enda er BILL heimsfrægur\n"
    .string "SKRÍMSLASJÚKUR.\p"
    .string "Hann fann líka upp geymslukerfið\n"
    .string "fyrir vasaskrímsli á PC.\p"
    .string "Þar sem þú notar kerfið hans ættirðu\n"
    .string "að fara og þakka honum.\p"
    .string "Jæja, ég þarf að rúlla! Sjáumst\n"
    .string "seinna!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Ó, já, rétt.\p"
    .string "Ég vorkenni þér. Í alvöru. Þú ert\n"
    .string "alltaf að dragast á eftir mér.\p"
    .string "Svo hér, ég gef þér smá gjöf sem\n"
    .string "greiða.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "Slúðurkjaftur eins og þú... Þetta\n"
    .string "tæki er fullkomið.\p"
    .string "Ég þarf það ekki því mér er alveg\n"
    .string "sama um aðra.\p"
    .string "Jæja, nú er ég í alvöru farinn.\n"
    .string "Sjáumst!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "Auðvitað! Ég er nefnilega\n"
    .string "snillingur!$"

CeruleanCity_Text_GruntIntro::
    .string "Hey! Haltu þig frá! Þetta er ekki\n"
    .string "garðurinn þinn!\p"
    .string "...Ha? Ég?\p"
    .string "Ég er saklaus vegfarandi! Trúirðu\n"
    .string "mér\p"
    .string "ekki?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat::
    .string "LIÐI: Hættu! Ég gefst upp! Ég fer\n"
    .string "hljóðlega!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "...Allt í lagi. Ég skila TM-inu sem\n"
    .string "ég stal.$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER} endurheimti TM28 frá\n"
    .string "ROCKET-LIÐANUM.$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "Ég ætti að koma mér af stað! Bæ!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "Gerðu pláss fyrir þetta! Ég kemst\n"
    .string "ekki burt fyrr en ég gef þér það!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "Ert þú líka ÞJÁLFARI?\p"
    .string "Að safna, berjast... Þetta er erfitt\n"
    .string "líf, ekki satt?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "Vissirðu að þú getur notað CUT á\n"
    .string "lítil tré?\p"
    .string "Jafnvel litla tréð fyrir framan\n"
    .string "búðina má CUT-a niður.\p"
    .string "Ég held samt að það sé leið í kring.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "Ef SLJÓNATAN væri ekki þarna gætirðu\n"
    .string "notað CUT á litla tréð.\p"
    .string "Þannig kæmistu hinum megin.\p"
    .string "Ég held samt að það sé leið í kring.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "Ertu að búa til alfræðirit um\n"
    .string "vasaskrímsli? Það hljómar\p"
    .string "skemmtilega.$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "Fólkið hér varð fyrir ráni.\p"
    .string "Það er augljóst að ROCKET-GENGIÐ\n"
    .string "stendur á bak við þetta ódæðisverk!\p"
    .string "Jafnvel LÖGREGLAN okkar á í\n"
    .string "vandræðum með ROCKET-GENGIÐ!$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "Allt í lagi! SLJÓNATAN! Notaðu\n"
    .string "SONICBOOM!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "Komdu nú, SLJÓNATAN, fylgstu með!$"

CeruleanCity_Text_SlowbroPunch::
    .string "SLJÓNATAN, punch!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "Nei! Þú klúðraðir þessu aftur!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "SLJÓNATAN, SKELVÖRN!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "Nei! Þetta er rangt! Það er svo\n"
    .string "erfitt að stjórna vasaskrímslum!\p"
    .string "Hlýðni vasaskrímslisins þíns fer\n"
    .string "eftir hæfni þinni sem ÞJÁLFARI.$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLJÓNATAN took a snooze…$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLJÓNATAN er að slóra...$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLJÓNATAN turned away…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLJÓNATAN ignored orders…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "Mig langar í skærrautt reiðhjól.\p"
    .string "Ég geymi það heima svo það verði\n"
    .string "ekki skítugt.$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "Þetta er CERULEAN HELLIR.\p"
    .string "Hræðilega sterk vasaskrímsli búa þar\n"
    .string "inni.\p"
    .string "Aðeins mjög sérstakur ÞJÁLFARI fær\n"
    .string "að fara þar inn.\p"
    .string "Til að byrja með þarftu að vera nógu\n"
    .string "sterkur til að verða MEISTARI\p"
    .string "Vasaskrímsla-deildarinnar.\p"
    .string "Og þú þarft að hafa unnið mikið\n"
    .string "afrek.$"

CeruleanCity_Text_CitySign::
    .string "CERULEAN BORG Dularfullur blár ljómi\n"
    .string "umlykur hana$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Vasaskrímsli getur haldið á hlut.\p"
    .string "Sumir hlutir geta jafnvel nýst\n"
    .string "vasaskrímslinu sem heldur á þeim í\p"
    .string "bardaga.$"

CeruleanCity_Text_BikeShopSign::
    .string "Gras og hellar verða auðveldir!\n"
    .string "HJÓLABÚÐ$"

CeruleanCity_Text_GymSign::
    .string "CERULEAN BORG VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: MISTY Hressilega\p"
    .string "hafmeyjan!$"
