CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .string "Halló! Velkomin í HJÓLABÚÐINA.\p"
    .string "Við eigum einmitt REIÐHJÓLIÐ fyrir\n"
    .string "þig!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .string "Afsakið! Þú hefur ekki efni á því!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .string "Ó, þetta er...\p"
    .string "REIÐHJÓLSMIÐI!\p"
    .string "Allt í lagi! Gjörðu svo vel!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .string "{PLAYER} skipti REIÐHJÓLSMIÐA fyrir\n"
    .string "REIÐHJÓL.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .string "Takk fyrir! Komdu aftur seinna!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .string "Hvernig líkar þér nýja REIÐHJÓLIÐ?\n"
    .string "Rennur það vel?\p"
    .string "Þú getur farið með það á\n"
    .string "HJÓLAVEGINN og jafnvel inn í hella!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .string "Þú þarft að gera pláss fyrir\n"
    .string "REIÐHJÓLIÐ!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .string "Venjulegt borgarhjól nægir mér.\p"
    .string "Enda er ekki hægt að setja\n"
    .string "innkaupakörfu á fjallahjól.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .string "Þessi hjól eru flott, en þau eru\n"
    .string "hrikalega dýr!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .string "Vá. REIÐHJÓLIÐ þitt er virkilega\n"
    .string "flott!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
    .string "Loksins komið á markað!\p"
    .string "Þýskt hágæða samanbrjótanlegt\n"
    .string "reiðhjól!$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .string "Gljáandi nýtt REIÐHJÓL!$"
