FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "Mörg Vasaskrímsli eru læst inni\n"
    .string "í gerðinu…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "Dyrnar á gerðinu eru ólæstar.\n"
    .string "Vasaskrímslin virðast hafa flúið.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "Komstu hingað vitandi að þetta er\n"
    .string "VÖRUHÚS ROCKET-GENGISINS?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "Hvað heldurðu að þú sért að gera?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "ROCKET-GENGIÐ hætti? Frá hvaða\n"
    .string "plánetu kemur þú?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "Ó, nú líta Vasaskrímslin þín út\n"
    .string "fyrir að vera sterk. Viltu selja þau?\p"
    .string "Ó? Vildirðu berjast?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "Ó, en… Of mikið!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "Við getum boðið frábært verð. Seldu\n"
    .string "okkur Vasaskrímslin þín!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "Ég fékk fréttir af þér frá\n"
    .string "hinum.\p"
    .string "En það er engin leið að krakki eins\n"
    .string "og þú þekki FORINGJANN okkar GIOVANNI!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "Ekki… dirfast… að… hlæja…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "Ekki skipta þér af verkum fullorðinna,\n"
    .string "þú montni smákrakki!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "Ég veit ekki og kæri mig ekki um\n"
    .string "hvort það sem ég geri sé rétt eða rangt…\p"
    .string "Ég treysti bara GIOVANNI og geri\n"
    .string "eins og mér er sagt.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "Ég… ég er brotin…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "Þú gerir hluti eftir eigin trú og\n"
    .string "siðferði.\p"
    .string "Ég skil það núna…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "Ég hef gert þér kleift að koma aftur\n"
    .string "inn þarna í gegn.\p"
    .string "Af hverju hvílirðu þig ekki og\n"
    .string "safnar kröftum fyrir það sem bíður?\p"
    .string "STJÓRNANDINN á eftir mér er miklu\n"
    .string "ofar mér sem ÞJÁLFARI.\p"
    .string "Þú skalt herða þig fyrir eina\n"
    .string "harða áskorun.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "Nú er nóg komið af hetjuleiknum\n"
    .string "þínum, krakki.\p"
    .string "Að dreifa lygum um að ROCKET-GENGIÐ\n"
    .string "hafi verið leyst upp…\p"
    .string "Þetta er augljós tilraun til að\n"
    .string "valda ruglingi í röðum okkar.\p"
    .string "Sem betur fer erum við ekki svo\n"
    .string "fáfróð að trúa lygum barns!\p"
    .string "Og nú skal ég sýna þér hversu\n"
    .string "ógnvekjandi reiður fullorðinn getur verið!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "Urgh… Þú varst of öflug…\p"
    .string "… Þ-þetta er MERKIÐ hans GIOVANNI!\p"
    .string "Svo það er satt? ROCKET-GENGIÐ hefur\n"
    .string "í alvöru verið leyst upp?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "Við yfirgefum þetta VÖRUHÚS…\p"
    .string "En ekki halda að þessu sé lokið.\n"
    .string "Ég læt þetta ekki vera endinn.\p"
    .string "Ég mun finna GIOVANNI. Og ég mun\n"
    .string "endurvekja ROCKET-GENGIÐ! Ég mun…\p"
    .string "Þangað til, bless!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "Skýrsla með gröfum og texta er á\n"
    .string "tölvuskjánum.\p"
    .string "'Áhrif segulbylgna á þróun\n"
    .string "Vasaskrímsla'…\p"
    .string "… … … … … …\p"
    .string "Hún er of erfið til að skilja…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "Mér tókst næstum að selja\n"
    .string "SAFÍRINN fyrir stórfé…\p"
    .string "Svo varðst þú að birtast og\n"
    .string "sprengja allan samninginn!\p"
    .string "Fufu… Fufufufu… Þér verður ekki\n"
    .string "fyrirgefið!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "Gah! Fjárinn! Fjárinn! Fjárinn!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "Ef ég get ekki selt hann er hann einskis virði!\n"
    .string "Gjörðu svo vel, taktu hann!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "Hvað viltu núna? Farðu burt,\n"
    .string "láttu mig í friði.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "Hvað, þú aftur?\p"
    .string "Þú… Þú ert ekki barnið hans GIOVANNI,\n"
    .string "er það?\p"
    .string "Nei, það getur ekki verið rétt!\n"
    .string "Barn GIOVANNI er með rautt hár.\p"
    .string "Þú hefur enga ástæðu til að angra\n"
    .string "mig. Láttu mig í friði!$"
