#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("Líkamleg árás\n afhent með a\nlong tail eða a\nforeleg osfrv.");
const u8 gMoveDescription_KarateChop[] = _("Ráðist er á óvininn\n með skörpum höggum.");
const u8 gMoveDescription_DoubleSlap[] = _("Óvinurinn er sleginn\n ítrekað, aftur\n og til baka, tvisvar til\n fimm sinnum.");
const u8 gMoveDescription_CometPunch[] = _("Óvinurinn verður fyrir barðinu á\n af höggi\n sem slá tvisvar til\n fimm sinnum.");
const u8 gMoveDescription_MegaPunch[] = _("Óvinurinn er sleginn\n með höggi\n með vöðvafylltu\n krafti.");
const u8 gMoveDescription_PayDay[] = _("Fjölmörgum myntum er\n hrundið að óvininum.");
const u8 gMoveDescription_FirePunch[] = _("Óvinurinn er kýldur\n með brennandi hnefa.");
const u8 gMoveDescription_IcePunch[] = _("Óvinurinn er kýldur\n með ísköldum hnefa.");
const u8 gMoveDescription_ThunderPunch[] = _("Óvinurinn er kýldur\n með rafmögnum\n hnefa. Það gæti skilið\n óvininn eftir lamaðan.");
const u8 gMoveDescription_Scratch[] = _("Harðar, oddhvassar og\nskarpar klær raka\n óvininn.");
const u8 gMoveDescription_ViceGrip[] = _("Risastórt, áhrifamikið\npincers grip og\n kreista andstæðinginn.");
const u8 gMoveDescription_Guillotine[] = _("Grimmileg rífa\nárás með töngum.\nFandvinurinn mun dofna\n ef hann lendir.");
const u8 gMoveDescription_RazorWind[] = _("Vindblöð slógu\n á óvininn í 2.\nbeygjunni. Það hefur hátt\ncritical högg hlutfall.");
const u8 gMoveDescription_SwordsDance[] = _("Trylltur bardagadans.\nHann hækkar SÓKN\nverulega.");
const u8 gMoveDescription_Cut[] = _("Grunnárás.\nÞað er hægt að nota til að\nklippa niður þunn tré\nog gras.");
const u8 gMoveDescription_Gust[] = _("Slær óvininn\n með vindhviðu\n sem\nwings slær upp.");
const u8 gMoveDescription_WingAttack[] = _("Óvinurinn verður fyrir barðinu á\n með stórum, hrífandi\nwings sem dreifast víða.");
const u8 gMoveDescription_Whirlwind[] = _("Óvinurinn er látinn\nswitch út með an\nally. Í náttúrunni lýkur\n bardaganum.");
const u8 gMoveDescription_Fly[] = _("Tveggja snúninga hreyfing sem\n slær á 2.\nbeygjuna. Notaðu það til að fljúga\n til hvaða bæjar sem er þekktur.");
const u8 gMoveDescription_Bind[] = _("Langur líkami eða\n tentacles eru notaðar\n til að binda óvininn fyrir\n tvær í fimm beygjur.");
const u8 gMoveDescription_Slam[] = _("Óvinurinn er sleginn\n með löngum hala,\n vínum o.s.frv.");
const u8 gMoveDescription_VineWhip[] = _("Óvinurinn er sleginn\n með mjóum, svipu-\n-líkum vínviðum.");
const u8 gMoveDescription_Stomp[] = _("Óvinurinn er stappaður\n með stórum fæti.");
const u8 gMoveDescription_DoubleKick[] = _("Tveir fætur eru notaðir\n til að sparka fljótt í\nóvininn tvisvar í einni\numferð.");
const u8 gMoveDescription_MegaKick[] = _("Ráðist er á óvininn\n með spyrnu\n með vöðvafylltu\n krafti.");
const u8 gMoveDescription_JumpKick[] = _("Notandinn hoppar upp\nhátt, þá sparkar.\nEf hann missir, meiðir\nnotandinn sjálfan sig.");
const u8 gMoveDescription_RollingKick[] = _("Snöggt spark frá\nrúllandi snúningi.\nÞað gæti fengið\nóvininn til að hrökklast við.");
const u8 gMoveDescription_SandAttack[] = _("Mikið af sandi er\n hrundið í\n andlit óvinarins, sem dregur úr\n nákvæmni hans.");
const u8 gMoveDescription_Headbutt[] = _("Notandinn stingur\n hausnum út og hrútar.");
const u8 gMoveDescription_HornAttack[] = _("Óvinurinn er stunginn\n með skarpt\n-odduðu horn til að\nvalda skemmdum.");
const u8 gMoveDescription_FuryAttack[] = _("Óvinurinn er stunginn\n ítrekað með a\nhorn eða goggi tvisvar til\n fimm sinnum.");
const u8 gMoveDescription_HornDrill[] = _("Horninu er snúið\n eins og bor til að hrinda.\n Óvinurinn mun dofna\n ef hann lendir.");
const u8 gMoveDescription_Tackle[] = _("Líkamleg árás\nþar sem notandinn\n ræðst, fullum líkama,\ninn í óvininn.");
const u8 gMoveDescription_BodySlam[] = _("Notandinn sleppir\n fullum líkama sínum á\nóvininn. Það gæti skilið\n óvininn eftir lamaðan.");
const u8 gMoveDescription_Wrap[] = _("Langur líkami eða\nvín eru notaðir til að\n vefja andstæðinginn fyrir\n tvær til fimm beygjur.");
const u8 gMoveDescription_TakeDown[] = _("Kærulaus, full-\nlíkams hleðsluárás\n sem særir\nnotandann líka svolítið.");
const u8 gMoveDescription_Thrash[] = _("Notandinn slær\nabout í tvær til\nþrjár beygjur, þá verður\n ruglaður.");
const u8 gMoveDescription_DoubleEdge[] = _("Kærulaus, lífshættuleg tækling sem\n skaðar einnig notandann\n lítið.");
const u8 gMoveDescription_TailWhip[] = _("Notandinn vaggar\n hala sínum sætt, sem gerir\n óvininum til að lækka\nDEFENSE stöðu sína.");
const u8 gMoveDescription_PoisonSting[] = _("Óvinurinn er stunginn\n með eitruðum gadda,\netc. Það getur eitrað\n fyrir óvininn.");
const u8 gMoveDescription_Twineedle[] = _("Óvinurinn er stunginn\n tvisvar með framfótum\nstingers. Það gæti\n eitrað óvininn.");
const u8 gMoveDescription_PinMissile[] = _("Skarpar nálar eru skotnar\ná óvininn tvisvar til\nfimm sinnum í röð.");
const u8 gMoveDescription_Leer[] = _("Óvininum er gefið\nindrepandi útlit\nsem lækkar\nDEFENSE stöðu sína.");
const u8 gMoveDescription_Bite[] = _("Notandinn bítur með\n grimmum vígtönnum.");
const u8 gMoveDescription_Growl[] = _("Notandinn urrar krúttlega og\nlækkar SÓKN óvinarins.");
const u8 gMoveDescription_Roar[] = _("Óvinurinn er látinn\nswitch út með an\nally. Í náttúrunni lýkur\n bardaganum.");
const u8 gMoveDescription_Sing[] = _("Róandi lag\ní róandi rödd\n dregur óvininn í\n djúpan blund.");
const u8 gMoveDescription_Supersonic[] = _("Notandinn býr til\nsérkennilegar hljóðbylgjur.\nÞað gæti ruglað\nóvininn.");
const u8 gMoveDescription_SonicBoom[] = _("Óvinurinn er sleginn með\na höggbylgju sem\n veldur alltaf 20-\nHP skaða.");
const u8 gMoveDescription_Disable[] = _("Í nokkrar umferðir kemur\nþað í veg fyrir að óvinurinn geti notað hreyfinguna\nsem síðast var notuð.");
const u8 gMoveDescription_Acid[] = _("Óvinurinn er úðaður\n með sterkri, húð-\n-bræðslusýru sem\n gæti lækkað DEFENSE.");
const u8 gMoveDescription_Ember[] = _("Ráðist er á óvininn\n með litlum eldi.\n Óvinurinn gæti orðið fyrir\na bruna.");
const u8 gMoveDescription_Flamethrower[] = _("Óvinurinn er sviðinn\n með miklum logum.\n Óvinurinn gæti orðið fyrir\na bruna.");
const u8 gMoveDescription_Mist[] = _("Bandamannaflokkurinn er\n verndaður af\nþoku sem kemur í veg fyrir minnkandi\ntölfræði.");
const u8 gMoveDescription_WaterGun[] = _("Óvinurinn er sleginn\n með miklu vatni\n rekinn með valdi\n úr munninum.");
const u8 gMoveDescription_HydroPump[] = _("Mikið magn af\nvatni er sprengt á\n andstæðinginn undir miklum\nþrýstingi.");
const u8 gMoveDescription_Surf[] = _("Stór bylgja hrynur\n niður á óvininn.\n Einnig er hægt að nota\n til að fara yfir vatn.");
const u8 gMoveDescription_IceBeam[] = _("Óvinurinn er sleginn\n með ísköldum geisla.\nÞað gæti frjósa\nfoeinn fast.");
const u8 gMoveDescription_Blizzard[] = _("Óvinurinn er sprengdur\n með snjóstormi.\n Það gæti fryst\nóvininn fast.");
const u8 gMoveDescription_Psybeam[] = _("Sérkennilegur geisli er\nskot á óvininn.\nÞað gæti valdið ruglingi hjá\nóvininum.");
const u8 gMoveDescription_BubbleBeam[] = _("Buna af loftbólum\nskellur á óvininum.\nGæti lækkað HRAÐA\nóvinarins.");
const u8 gMoveDescription_AuroraBeam[] = _("Regnbogalitaður\nárásargeisli.\nGæti lækkað SÓKN\nóvinarins.");
const u8 gMoveDescription_HyperBeam[] = _("Alvarlega skaðleg\nárás sem gerir\n notandanum til að hvíla sig á\n í næstu beygju.");
const u8 gMoveDescription_Peck[] = _("Óvinurinn er stunginn\n með skarpt\nodddan gogg eða\nhorn.");
const u8 gMoveDescription_DrillPeck[] = _("Korktappa\nárás með\nsharpa goggnum sem virkar\nas bor.");
const u8 gMoveDescription_Submission[] = _("Kærulaus, full-\nlíkams kastárás\n sem særir\nnotandann líka svolítið.");
const u8 gMoveDescription_LowKick[] = _("Lágt, hrífandi spark\n sem veldur meiri\n skaða á þyngri\n andstæðinga.");
const u8 gMoveDescription_Counter[] = _("Hefndaraðgerðir\n sem vinnur gegn hvaða\n líkamlegu höggi sem er með\n tvöfalda skaðann.");
const u8 gMoveDescription_SeismicToss[] = _("Þyngdarafl-fóðrað kast\n sem veldur skemmdum\n sem passar við\n-stig notandans.");
const u8 gMoveDescription_Strength[] = _("Óvinurinn er sleginn\nmeð hámarksafli.\nEinnig hægt að nota\ntil að færa steina.");
const u8 gMoveDescription_Absorb[] = _("Árás sem\n gleypir hálfan\n skaðann sem hún olli\n til að endurheimta HP.");
const u8 gMoveDescription_MegaDrain[] = _("Erfið árás sem\n tæmir helminginn af\n skaðanum sem hún olli\n til að endurheimta HP.");
const u8 gMoveDescription_LeechSeed[] = _("Fræi er plantað\n á óvininn til að stela\neinhverju HP fyrir\nnotandann í hverri umferð.");
const u8 gMoveDescription_Growth[] = _("Líkami notandans er\n neyddur til að vaxa,\n hækkar SP.\nATK tölfræðina.");
const u8 gMoveDescription_RazorLeaf[] = _("Óvinurinn er sleginn með\na skurðblaði.\nÞað hefur hátt\n gagnrýna högghlutfall.");
const u8 gMoveDescription_SolarBeam[] = _("Tveggja snúninga hreyfing sem\n sprengir andstæðinginn með\n frásoginni orku í\n í 2. beygju.");
const u8 gMoveDescription_PoisonPowder[] = _("Ský af eitruðu\n ryki er á víð og dreif.\nÞað getur eitrað\nfoeina.");
const u8 gMoveDescription_StunSpore[] = _("Lamaryk er\n dreift villt.\nÞað getur lamað\n óvininn.");
const u8 gMoveDescription_SleepPowder[] = _("Svefnvaldandi\n ryk er dreift\ní miklu magni\n í kringum óvininn.");
const u8 gMoveDescription_PetalDance[] = _("Notandinn ræðst á\n með krónublöðum í tvær\n í þrjár beygjur,\n þá ruglast hann.");
const u8 gMoveDescription_StringShot[] = _("Óvinurinn er bundinn\n með strengjum sem eru skotnir\n úr munni til\n minnka SPEED hans.");
const u8 gMoveDescription_DragonRage[] = _("Óvinurinn er sleginn með\na höggbylgju sem\n veldur alltaf 40-\nHP skaða.");
const u8 gMoveDescription_FireSpin[] = _("Óvinurinn er fastur\n í ákafanum spíral\n eldi sem geisar\n tvær til fimm beygjur.");
const u8 gMoveDescription_ThunderShock[] = _("Raflost\nárás sem gæti\n líka skilið óvininn eftir\n lamaðan.");
const u8 gMoveDescription_Thunderbolt[] = _("Sterk rafmagns\nárás sem gæti\n líka skilið óvininn eftir lamaðan.");
const u8 gMoveDescription_ThunderWave[] = _("Veikt rafmagnsstuð\n sem er viss um að\n valdi lömun\n ef það lendir.");
const u8 gMoveDescription_Thunder[] = _("Hrottaleg elding\nárás sem gæti\n líka skilið óvininn eftir lamaðan.");
const u8 gMoveDescription_RockThrow[] = _("Ráðist er á óvininn\n með sturtu af\n litlum steinum sem auðveldlega\n kastast.");
const u8 gMoveDescription_Earthquake[] = _("Jarðskjálfti sem\n lendir á öllum Vasaskrímslum\ní bardaga, að undanskildum\n notandanum.");
const u8 gMoveDescription_Fissure[] = _("Óvinurinn er látinn falla\ní sprungu.\n Óvinurinn dofnar ef hann\n slær.");
const u8 gMoveDescription_Dig[] = _("Árás sem lendir á\n í 2. beygju.\n Einnig er hægt að nota\n til að fara út úr dýflissum.");
const u8 gMoveDescription_Toxic[] = _("Hreyfing sem\n eitrar óvininn illa.\n Eitrunarskemmdir hennar\n versnar í hverri umferð.");
const u8 gMoveDescription_Confusion[] = _("Veik fjarskipti\nárás sem gæti\n líka skilið óvininn eftir\n ringlaður.");
const u8 gMoveDescription_Psychic[] = _("Sterk hugarorku-\nárás. Það gæti líka\nlækkað\nSP. DEF tölfræði óvinarins.");
const u8 gMoveDescription_Hypnosis[] = _("Svefnlyfjauppástunga\n er notuð til að láta\nóvininn falla í\ndjúpan svefn.");
const u8 gMoveDescription_Meditate[] = _("Notandinn hugleiðir\ntil að vekja kraft sinn\nog hækka SÓKN.");
const u8 gMoveDescription_Agility[] = _("Notandinn slakar á\n og léttir\n líkamann sinn til að auka\n verulega\n.");
const u8 gMoveDescription_QuickAttack[] = _("Næstum ósýnilega\n hröð árás sem\n er viss um að slá\n fyrst.");
const u8 gMoveDescription_Rage[] = _("Árás sem\n verður sterkari\nÍ hvert sinn sem notandinn\n verður fyrir bardaga.");
const u8 gMoveDescription_Teleport[] = _("Notaðu það til að flýja frá\nhvaða villtu Vasaskrímsli sem er.\nEinnig til að undiðst til\nsíðasta VASaSKRÍMSLA MIÐSTÖÐVARINNAR.");
const u8 gMoveDescription_NightShade[] = _("Árás með a\nmirage sem veldur\n skaða sem samsvarar\n stigi notandans.");
const u8 gMoveDescription_Mimic[] = _("Notandinn afritar\nhreyfinguna sem síðast var notuð af\n óvininum fyrir\n restina af bardaganum.");
const u8 gMoveDescription_Screech[] = _("eyrnakljúfandi\n öskur er gefið frá sér\n til að draga verulega úr\n andstæðingsins DEFENSE.");
const u8 gMoveDescription_DoubleTeam[] = _("Notandinn býr til\nillusory afrit af\nitself til að auka\nevasiveness þess.");
const u8 gMoveDescription_Recover[] = _("Sjálfgræðandi hreyfing\n sem endurheimtir HP um\n allt að helmingi af hámarks HP\nnotandans.");
const u8 gMoveDescription_Harden[] = _("Notandinn stífnar\n alla vöðvana í\n líkamanum til að hækka\nits DEFENSE stöðuna.");
const u8 gMoveDescription_Minimize[] = _("Notandinn þjappar\n öllum frumunum í\n líkama sínum til að auka\nevasiveness þess.");
const u8 gMoveDescription_Smokescreen[] = _("Óljóst ský\n af reyk eða bleki\n dregur úr\n nákvæmni óvinarins.");
const u8 gMoveDescription_ConfuseRay[] = _("Óvinurinn verður\n fyrir ógnvænlegum geisla\n sem kallar á\n rugling.");
const u8 gMoveDescription_Withdraw[] = _("Notandinn dregur\nlíkamann inn í harða\nskel og hækkar\nVÖRN sína.");
const u8 gMoveDescription_DefenseCurl[] = _("Notandinn krullar\n upp til að leyna veika\n bletti og hækka\nDEFENSE stöðu sína.");
const u8 gMoveDescription_Barrier[] = _("Notandinn býr til\n traustan vegg sem\n hækkar verulega\nDEFENSE stöðuna sína.");
const u8 gMoveDescription_LightScreen[] = _("Ljósveggur\n klippir skemmdir frá\nSP. ATK ræðst á\n í fimm beygjur.");
const u8 gMoveDescription_Haze[] = _("Eyðir öllum tölfræði-\nbreytingum meðal allra\nVasaskrímsla sem taka þátt í\nbardaga.");
const u8 gMoveDescription_Reflect[] = _("Ljósveggur\n sker skemmdir frá\n líkamlegum árásum\n í fimm veltur.");
const u8 gMoveDescription_FocusEnergy[] = _("Notandinn andar djúpt og\n einbeitir sér að því að hækka\n gagnrýna högghlutfallið.");
const u8 gMoveDescription_Bide[] = _("Notandinn þolir\nárásir í tvær\nbeygjur og slær síðan\nback tvöfalt.");
const u8 gMoveDescription_Metronome[] = _("Veltir fingri\n og örvar\n heilann til að nota hvaða\nhreyfingu sem er af handahófi.");
const u8 gMoveDescription_MirrorMove[] = _("Notandinn mælir\n hreyfinguna sem síðast var notuð\n af óvininum með\n sömu hreyfingu.");
const u8 gMoveDescription_SelfDestruct[] = _("Notandinn sprengir\n í loft upp til að valda alvarlegum\n skaða, jafnvel\n gerir sig daufa.");
const u8 gMoveDescription_EggBomb[] = _("Stóru eggi er\n hrundið með miklum\n krafti að óvininum til að\n valda skemmdum.");
const u8 gMoveDescription_Lick[] = _("Óvinurinn er sleiktur\n og sleginn með langri\ntungu. Það gæti\n líka lamað.");
const u8 gMoveDescription_Smog[] = _("Óvinurinn verður fyrir árás\n með útblásturslofti.\nÞað gæti einnig eitrað fyrir\n fyrir óvininn.");
const u8 gMoveDescription_Sludge[] = _("Eitrað seyru er\n hrundið að óvininum.\nÞað getur eitrað\nmarkmiðið.");
const u8 gMoveDescription_BoneClub[] = _("Óvinurinn er klúbbaður\n með beini sem haldið er í\nhand. Það gæti fengið\n óvininn til að hrökklast við.");
const u8 gMoveDescription_FireBlast[] = _("Óvinurinn verður fyrir höggi með\nan sterkum loga.\nÞað gæti farið frá\nmarkmiðinu með bruna.");
const u8 gMoveDescription_Waterfall[] = _("Öflug hleðslu-\nárás. Það er líka hægt að nota\n til að klifra\nfossinn.");
const u8 gMoveDescription_Clamp[] = _("Óvinurinn er klemmdur\n og kreistur af\n skel notandans fyrir\n tvær til fimm beygjur.");
const u8 gMoveDescription_Swift[] = _("Stjörnulaga geislar\n sem aldrei missa af eru\n skotnir á alla óvini í\nbardaga.");
const u8 gMoveDescription_SkullBash[] = _("Notandinn hækkar\nDEFENSE sitt í 1st\nbeygjunni og ræðst síðan á\n í 2. beygju.");
const u8 gMoveDescription_SpikeCannon[] = _("Skörpum toppum er\n skotið á óvininn til að\n slá tvö til fimm\n sinnum.");
const u8 gMoveDescription_Constrict[] = _("Ráðist er á óvininn\n með löngum tentacles\neða vínviðum. Það gæti\nlækkað SPEED.");
const u8 gMoveDescription_Amnesia[] = _("Gleymir\neitthvað og\n hækkar\nSP skarpt. DEF.");
const u8 gMoveDescription_Kinesis[] = _("Notandinn truflar\n óvininn með því að beygja\na skeið. Það gæti\n lægri nákvæmni.");
const u8 gMoveDescription_SoftBoiled[] = _("Læknar notandann með\nup upp í helming sinn\nHP. Það er hægt að nota\n til að lækna bandamann.");
const u8 gMoveDescription_HiJumpKick[] = _("Sterkt stökk\nhnéspark. Ef it\nmissar er notandinn\nhurt.");
const u8 gMoveDescription_Glare[] = _("Notandinn hræðir\n óvininn með\n-hönnuninni á maganum\n til að valda lömun.");
const u8 gMoveDescription_DreamEater[] = _("Gleypir hálfa\n skaðann sem hann olli\n á sofandi fjanda\n til að endurheimta HP.");
const u8 gMoveDescription_PoisonGas[] = _("Óvininum er úðað\n með skýi af\n eitruðu gasi sem gæti\n eitrað óvininn.");
const u8 gMoveDescription_Barrage[] = _("Kringlóttum hlutum er\n hrint að óvininum\n til að slá tvisvar til\n fimm sinnum.");
const u8 gMoveDescription_LeechLife[] = _("Árás sem\n gleypir hálfan\n skaðann sem hún olli\n til að endurheimta HP.");
const u8 gMoveDescription_LovelyKiss[] = _("Notandinn neyðir\nkoss á óvininn\n með skelfilegu andliti\n sem framkallar svefn.");
const u8 gMoveDescription_SkyAttack[] = _("Árás í 2. beygju\nhreyfing með háu\n gagnrýni högghlutfalli.\n Óvinurinn gæti hrökklast við.");
const u8 gMoveDescription_Transform[] = _("Notandinn umbreytir\n í afrit af\nóvininum með jafnvel\n sama hreyfisettinu.");
const u8 gMoveDescription_Bubble[] = _("Buna af loftbólum\nskellur á óvininum.\nGæti lækkað HRAÐA\nóvinarins.");
const u8 gMoveDescription_DizzyPunch[] = _("Óvinurinn verður fyrir barðinu á\na taktföstu höggi\n sem gæti skilið hann\n ringlaður.");
const u8 gMoveDescription_Spore[] = _("Notandinn dreifir\n straumum af fínum\n gróum sem framkalla\n svefn.");
const u8 gMoveDescription_Flash[] = _("Ljósblástur\n sem dregur úr\n nákvæmni óvinarins. Það\nLýsir einnig hella.");
const u8 gMoveDescription_Psywave[] = _("Ráðist er á óvininn\n með skrýtinni, heitri\nenergy bylgju sem\n er mismunandi að styrkleika.");
const u8 gMoveDescription_Splash[] = _("Notandinn floppar bara\n og skvettir í kringum\n án þess að hafa nein\n áhrif.");
const u8 gMoveDescription_AcidArmor[] = _("Notandinn breytir\n frumum sínum til að vökva\nitself og\n hækka DEFENSE verulega.");
const u8 gMoveDescription_Crabhammer[] = _("Stór kló er\nnotuð til að hamra\nóvininn. Það hefur hátt\nkrítískt högg hlutfall.");
const u8 gMoveDescription_Explosion[] = _("Notandinn springur\n til að valda hræðilegum\n skaða jafnvel á meðan\n deyfir sig.");
const u8 gMoveDescription_FurySwipes[] = _("Óvininum er rakað\n með beittum klóm eða\n tvisvar til fimm\n sinnum.");
const u8 gMoveDescription_Bonemerang[] = _("Notandinn kastar\nbeini sem hittir\nóvininn einu sinni, svo einu sinni\nenn þegar það kemur aftur.");
const u8 gMoveDescription_Rest[] = _("Notandinn sefur fyrir\ntwo snýr sér að fullu\nrestore HP og lækna\nany stöðuvandamál.");
const u8 gMoveDescription_RockSlide[] = _("Stórum steinum er\n hrint að óvininum.");
const u8 gMoveDescription_HyperFang[] = _("Ráðist er á óvininn\n með beittum vígtönnum.");
const u8 gMoveDescription_Sharpen[] = _("Notandinn skerpir\nbrúnir sínar og\nhækkar SÓKN.");
const u8 gMoveDescription_Conversion[] = _("Notandinn breytir\nits gerð til að passa við\n gerð einnar af\nits hreyfingum.");
const u8 gMoveDescription_TriAttack[] = _("Samtímis\n3-geislaárás sem\n gæti lama, brenna,\neða frysta óvininn.");
const u8 gMoveDescription_SuperFang[] = _("Notandinn ræðst á\n með beittum vígtennum\n og helmingar\nHP óvinarins.");
const u8 gMoveDescription_Slash[] = _("Óvinurinn er skorinn\n með klóm o.s.frv.\n Hann hefur hátt\n gagnrýna högghlutfall.");
const u8 gMoveDescription_Substitute[] = _("Notandinn býr til a\ndecoy með því að nota einn\n fjórðung af fullum\nHP.");
const u8 gMoveDescription_Struggle[] = _("Árás sem er\n aðeins notuð ef\n er engin PP. Það líka\nharts notandann.");
const u8 gMoveDescription_Sketch[] = _("Þessi hreyfing afritar\n hreyfingin sem síðast var notuð\n af óvininum, þá hverfur\n.");
const u8 gMoveDescription_TripleKick[] = _("Þriggja sparka árás\n sem verður\n öflugri með hverju\n höggi á eftir.");
const u8 gMoveDescription_Thief[] = _("Árás sem gæti\n tekið\nhlut óvinarins ef notandinn\n er ekki með hann.");
const u8 gMoveDescription_SpiderWeb[] = _("Fylgir óvininn\n með klístruðu strengi\n svo hann flýi ekki\n eða skiptist út.");
const u8 gMoveDescription_MindReader[] = _("Notandinn spáir fyrir um\n aðgerðir óvinarins til að\n tryggja að næsta\nárás hans hittir.");
const u8 gMoveDescription_Nightmare[] = _("Sofandi óvinur er\n sýnd martröð\n sem veldur\n skaða í hverri beygju.");
const u8 gMoveDescription_FlameWheel[] = _("Notandinn gerir\neldheita hleðslu á\nóvininn. Það getur valdið\nbruna.");
const u8 gMoveDescription_Snore[] = _("Árás sem hægt er að nota\n aðeins meðan\n er í svefni. Það gæti\n valdið hikandi.");
const u8 gMoveDescription_Curse[] = _("Hreyfing sem virkar\n öðruvísi fyrir\nDRAUG-gerðina og allar\n aðrar tegundir.");
const u8 gMoveDescription_Flail[] = _("Örvæntingarfull árás\n sem verður\n öflugri því minna\nHP sem notandinn hefur.");
const u8 gMoveDescription_Conversion2[] = _("Notandinn breytir\ngerð til að gera sig\n ónæm fyrir\n síðustu árásinni sem hann tók.");
const u8 gMoveDescription_Aeroblast[] = _("Lofthringur er\nskot á óvininn.\nÞað hefur hátt\n gagnrýna högghlutfall.");
const u8 gMoveDescription_CottonSpore[] = _("Bómullarlík gró\n loða við óvininn,\n dregur verulega úr\nits SPEED stöðu.");
const u8 gMoveDescription_Reversal[] = _("Alhliða árás\n sem verður\n öflugri því minna\nHP sem notandinn hefur.");
const u8 gMoveDescription_Spite[] = _("Hreyfing sem sker\n2 til 5 PP frá\nhreyfingunni sem var síðast notuð af\n óvininum.");
const u8 gMoveDescription_PowderSnow[] = _("Sprengir andstæðinginn með\na snævi vindhviðum.\nÞað getur valdið\nfrystingu.");
const u8 gMoveDescription_Protect[] = _("Gerir notandanum kleift að\nforðast allar árásir.\nÞað gæti mistekist ef notað er\ní röð.");
const u8 gMoveDescription_MachPunch[] = _("Kýla kastað á\n blindandi hraða.\nÞað er víst að\n slá fyrst.");
const u8 gMoveDescription_ScaryFace[] = _("Hræðir óvininn\n með skelfilegu andliti\n til að draga verulega úr\nits SPEED.");
const u8 gMoveDescription_FaintAttack[] = _("Notandinn dregur\n nálægt óvininum\n afvopnandi, þá slær\n án árangurs.");
const u8 gMoveDescription_SweetKiss[] = _("Notandinn kyssir\n óvininn með sætum\n sætleika sem\n veldur ruglingi.");
const u8 gMoveDescription_BellyDrum[] = _("Notandinn hámarkar\nSÓKN sína á kostnað\nhelmings af fullu HP.");
const u8 gMoveDescription_SludgeBomb[] = _("Óhreinum seyru er\n hrundið að óvininum.\nÞað getur eitrað\nmarkmiðið.");
const u8 gMoveDescription_MudSlap[] = _("Leðju er kastað í andlit óvinarins til að\n valda skemmdum og\n lækka nákvæmni hans.");
const u8 gMoveDescription_Octazooka[] = _("Blek er sprengt í\n andlit óvinarins eða\neyes til að skemma og\n minni nákvæmni.");
const u8 gMoveDescription_Spikes[] = _("Gaddagildra er\n lögð í kringum flokk\nóvinanna til að skaða\nóvini sem skiptast inn.");
const u8 gMoveDescription_ZapCannon[] = _("Rafmagnssprengja er\nkveikt eins og fallbyssu\n til að valda skemmdum\n og lama.");
const u8 gMoveDescription_Foresight[] = _("Neitar algjörlega viðleitni óvinarins til að\n auka getu hans\n til að komast hjá.");
const u8 gMoveDescription_DestinyBond[] = _("Ef notandinn fellur yfir,\n óvinurinn sem skilar\n lokahögginu\nfaints.");
const u8 gMoveDescription_PerishSong[] = _("Allir bardagamenn sem\n heyra þetta falla í yfirlið\ní þrjár beygjur\nnema hann skiptir.");
const u8 gMoveDescription_IcyWind[] = _("Kaldandi vindur er\n Notaður til að ráðast á.\nÞað lækkar einnig\nSPEED stöðuna.");
const u8 gMoveDescription_Detect[] = _("Gerir notandanum kleift að\nforðast allar árásir.\nÞað gæti mistekist ef notað er\ní röð.");
const u8 gMoveDescription_BoneRush[] = _("Notandinn slær\n óvininn með bein\ní hendi tvisvar til fimm\n sinnum.");
const u8 gMoveDescription_LockOn[] = _("Notandinn læsir\n við óvininn, sem gerir\n næsta skref öruggt að\n hitti.");
const u8 gMoveDescription_Outrage[] = _("Notandinn slær\nabout í tvær til\nþrjár beygjur, þá verður\n ruglaður.");
const u8 gMoveDescription_Sandstorm[] = _("5 snúnings sandstormur\n sem skemmir allar\n gerðir nema STEINN,\nJÖRÐ og STÁL.");
const u8 gMoveDescription_GigaDrain[] = _("Hörð árás sem\n gleypir hálfa\n skaðann sem hún olli\n til að endurheimta HP.");
const u8 gMoveDescription_Endure[] = _("Notandinn þolir\nany högg með 1 HP\nleft. Það gæti mistekist ef\n er notað í röð.");
const u8 gMoveDescription_Charm[] = _("Óvinurinn heillast\naf sjarma notandans,\nsem lækkar SÓKN\nhans verulega.");
const u8 gMoveDescription_Rollout[] = _("5 umferða\nárás sem verður\nsterkari í hvert sinn sem\nhún hittir.");
const u8 gMoveDescription_FalseSwipe[] = _("Aðhaldssöm árás\n sem skilur alltaf\n óvininn eftir með að\nminnsta kosti 1 HP.");
const u8 gMoveDescription_Swagger[] = _("Hreyfing sem ruglar\nóvininn, en hækkar\neinnig SÓKN hans\nverulega.");
const u8 gMoveDescription_MilkDrink[] = _("Læknar notandann með\nup upp í helming sinn\nHP. Það er hægt að nota\n til að lækna bandamann.");
const u8 gMoveDescription_Spark[] = _("Rafmagnuð\n tækling sem\n gæti líka lamað\n óvininn.");
const u8 gMoveDescription_FuryCutter[] = _("Árás sem\n verður sterkari á\neach í röð\nhit.");
const u8 gMoveDescription_SteelWing[] = _("Óvinurinn verður fyrir höggi með\n vængi úr stáli.\nÞað gæti einnig hækkað\n notandans DEFENSE.");
const u8 gMoveDescription_MeanLook[] = _("Óvinurinn er fastur\n með venjulegu útliti\n sem kemur í veg fyrir að hann\n sleppi.");
const u8 gMoveDescription_Attract[] = _("Ef það er hitt\nkynið, er óvinurinn\n gjörður ástfanginn og\n ólíklegt að gera árás.");
const u8 gMoveDescription_SleepTalk[] = _("Meðan hann er sofandi notar\nnotandinn af handahófi\neina af hreyfingunum sem hann\n þekkir.");
const u8 gMoveDescription_HealBell[] = _("Róandi bjalla\nchimes til að lækna\n stöðuvandamál\nall bandamanna.");
const u8 gMoveDescription_Return[] = _("Þessi árás hreyfist\n vex öflugri\nþví meira sem notandanum\n líkar við ÞJÁLFARINN sinn.");
const u8 gMoveDescription_Present[] = _("Óvininum er gefin gjöf sem er í gildru\n.\n Það endurheimtir HP\n þó stundum.");
const u8 gMoveDescription_Frustration[] = _("Þessi árásarhreyfing\n vex öflugri\nþví minna sem notandanum\n líkar við ÞJÁLFARINN sinn.");
const u8 gMoveDescription_Safeguard[] = _("Það verndar aðila\nnotandans fyrir\nöllum stöðuvandamálum\n í fimm umferðir.");
const u8 gMoveDescription_PainSplit[] = _("Notandinn bætir\nHP sínu við HP,\n andstæðingsins og deilir síðan\n heildar HP jafnt.");
const u8 gMoveDescription_SacredFire[] = _("Dularfull og\n öflug eld\nárás sem gæti\n valdið bruna.");
const u8 gMoveDescription_Magnitude[] = _("Jarðhristandi\nárás gegn öllum\nstandandi Vasaskrímsli.\n Kraftur hennar er mismunandi.");
const u8 gMoveDescription_DynamicPunch[] = _("Óvinurinn er kýldur\n með fullu\n krafti notandans. Það ruglar\n óvininn ef hann lendir.");
const u8 gMoveDescription_Megahorn[] = _("Hrottaleg rammárás\nárás veitt\n með hörku og\náhrifamiklu horni.");
const u8 gMoveDescription_DragonBreath[] = _("Óvinurinn verður fyrir barðinu á\nan ótrúlegum sprengingu\n andardrætti sem gæti\n líka lama.");
const u8 gMoveDescription_BatonPass[] = _("Notandinn skiptir\nút, framhjá\nhvaða tölfræðibreytingum sem er\n í nýja bardagakappann.");
const u8 gMoveDescription_Encore[] = _("Gerir óvininum til að nota\n að færa hann síðast\n Notað ítrekað fyrir\n tvær til sex beygjur.");
const u8 gMoveDescription_Pursuit[] = _("Árásarhreyfing sem\n virkar sérstaklega\nwell á óvini sem\n er að skipta út.");
const u8 gMoveDescription_RapidSpin[] = _("Árás sem\n leysir notandann frá\nBIND, WRAP, LEECH\nSEED og SPIKES.");
const u8 gMoveDescription_SweetScent[] = _("Töfrar óvininn til að\n draga úr undanskotum.\nÞað laðar einnig að\nvillt Vasaskrímsli.");
const u8 gMoveDescription_IronTail[] = _("Árás með stálhörðum\nhala. Gæti lækkað\nVÖRN óvinarins.");
const u8 gMoveDescription_MetalClaw[] = _("Ráðist er á óvininn\nmeð stálklóm.\nGæti einnig hækkað\nSÓKN notandans.");
const u8 gMoveDescription_VitalThrow[] = _("Gerir notandann\nráðast á eftir\nóvininum. Í staðinn mun\nhún ekki missa af.");
const u8 gMoveDescription_MorningSun[] = _("Endurheimtir\nHP notandans. Magn\nHP sem er endurheimt er mismunandi\n eftir veðri.");
const u8 gMoveDescription_Synthesis[] = _("Endurheimtir\nHP notandans. Magn\nHP sem er endurheimt er mismunandi\n eftir veðri.");
const u8 gMoveDescription_Moonlight[] = _("Endurheimtir\nHP notandans. Magn\nHP sem er endurheimt er mismunandi\n eftir veðri.");
const u8 gMoveDescription_HiddenPower[] = _("Árás sem\n er breytileg í gerð og\n styrkleiki eftir\n af notandanum.");
const u8 gMoveDescription_CrossChop[] = _("Óvinurinn er sleginn með\n tvöföldum höggum.");
const u8 gMoveDescription_Twister[] = _("Grimmilegur snúningsmaður\n ræðst á óvininn.\nÞað gæti orðið til þess að\nóandinn kippist við.");
const u8 gMoveDescription_RainDance[] = _("Mikil rigning fellur\n í fimm umferðir,\n ýtir undir hreyfingar VATN-\ngerðar.");
const u8 gMoveDescription_SunnyDay[] = _("Sólin logar fyrir\n fimm beygjur og knýr\nup ELDUR-gerð\nmoves.");
const u8 gMoveDescription_Crunch[] = _("Óvinurinn er kraminn\n með beittum vígtönnum.\n Það gæti lækkað\nSP. DEF óvinarins.");
const u8 gMoveDescription_MirrorCoat[] = _("Hefndaraðgerð\n sem endurgreiðir sérstaka árás\nóvininum\ntvöfalt.");
const u8 gMoveDescription_PsychUp[] = _("Notandinn dáleiðir\nsig til að afrita\nhvaða tölfræðibreytingu sem er\n sem óvinurinn gerði.");
const u8 gMoveDescription_ExtremeSpeed[] = _("Blindandi hröð\nhleðsluárás sem\n fer alltaf á undan\n öllum öðrum.");
const u8 gMoveDescription_AncientPower[] = _("Forn kraftur er\n notaður til að ráðast á. Það\ngæti einnig hækkað allar\ntölfræði notandans.");
const u8 gMoveDescription_ShadowBall[] = _("Skuggalegur klumpur er\n hrundi að óvininum.\n Getur einnig lækkað\nSP. DEF óvinarins.");
const u8 gMoveDescription_FutureSight[] = _("Tveimur snúningum eftir að\n þessi hreyfing er notuð,\n er ráðist á andstæðinginn\n andlega.");
const u8 gMoveDescription_RockSmash[] = _("Árás sem gæti\n líka skorið DEFENSE.\nÞað getur líka brotið\n sprungna steina.");
const u8 gMoveDescription_Whirlpool[] = _("Óvinurinn er fastur\n í hröðum, illvígum\nwhirlpool í tvær\n til fimm beygjur.");
const u8 gMoveDescription_BeatUp[] = _("Allir flokkar Vasaskrímsli\n taka þátt í árásinni.\nÞví fleiri bandamenn,\nþví meiri skaði.");
const u8 gMoveDescription_FakeOut[] = _("Árás sem lendir fyrst á\n og veldur því að\n hrökklast. Notanleg\nonly í 1. beygju.");
const u8 gMoveDescription_Uproar[] = _("Notandinn ræðst á\nan uppnám sem\n kemur í veg fyrir svefn fyrir\n tvær til fimm beygjur.");
const u8 gMoveDescription_Stockpile[] = _("Notandinn rukkar\nup afl fyrir notkun\nlater. Það er hægt að\nnota þrisvar sinnum.");
const u8 gMoveDescription_SpitUp[] = _("Krafturinn sem er byggður\n með því að nota STOCKPILE er\n gefinn út í einu\n fyrir árás.");
const u8 gMoveDescription_Swallow[] = _("Orkan sem það byggði\n með því að nota STOCKPILE er\n frásoguð til að endurheimta\nHP.");
const u8 gMoveDescription_HeatWave[] = _("Notandinn andar frá sér\nhituðum andardrætti til\nárásar. Það gæti líka\n valdið bruna.");
const u8 gMoveDescription_Hail[] = _("Haglél sem varir\nfimm breytir skaða\nall Vasaskrímsli nema\n af ÍS-gerðinni.");
const u8 gMoveDescription_Torment[] = _("Það reitir óvininn til reiði,\n gerir það ófært\n að nota sömu\nhreyfinguna í röð.");
const u8 gMoveDescription_Flatter[] = _("Smjaður er notað til að\n rugla óvininn,\n en SP hans. ATK\n hækkar líka.");
const u8 gMoveDescription_WillOWisp[] = _("Óheiðarlegur, bláleitur\nhvítur logi er skotinn\nþar sem óvinurinn er\ntil að valda bruna.");
const u8 gMoveDescription_Memento[] = _("Notandinn örmagnast,\nen lækkar verulega\nSÓKN og SÉR. SÓKN\nóvinarins.");
const u8 gMoveDescription_Facade[] = _("Árás sem er\nboost ef notandi er\nbrenndur, eitraður,\neða lamaður.");
const u8 gMoveDescription_FocusPunch[] = _("Árás sem er\n framkvæmd síðast.\nNotandinn hrökklast\nif við höggi fyrirfram.");
const u8 gMoveDescription_SmellingSalt[] = _("Tvöfalt áhrifaríkt á\na lamaðan óvin,\n en það læknar líka\n lömun óvinarins.");
const u8 gMoveDescription_FollowMe[] = _("Notandinn dregur\nathygli að sjálfum sér,\n gerir óvini árás\nAðeins notandann.");
const u8 gMoveDescription_NaturePower[] = _("Árás sem\n breytir gerð\n eftir staðsetningu\nnotandans.");
const u8 gMoveDescription_Charge[] = _("Notandinn safnar\nkrafti til að auka\nRAFMAGN hreyfinguna sem hann\nnotar næst.");
const u8 gMoveDescription_Taunt[] = _("Óvinurinn er hæddur\n í reiði sem\n leyfir honum að nota\neins árásarhreyfingar.");
const u8 gMoveDescription_HelpingHand[] = _("Hreyfing sem eykur\n kraftinn í árás\nbandamanns í\nbardaga.");
const u8 gMoveDescription_Trick[] = _("Hreyfing sem tælir\n andstæðinginn inn í\n að versla hluti\n með notandanum.");
const u8 gMoveDescription_RolePlay[] = _("Notandinn líkir algjörlega eftir\nóvininum og\n afritar\n getu óvinarins.");
const u8 gMoveDescription_Wish[] = _("Sjálfgræðandi hreyfing\n sem endurheimtir hálfa\n fulla HP í\n næstu beygju.");
const u8 gMoveDescription_Assist[] = _("Notandinn af handahófi\n velur og notar\nhreyfingu af bandamanni\nVasaskrímsli.");
const u8 gMoveDescription_Ingrain[] = _("Notandinn leggur rætur\n sem endurheimta HP á\n í hverri beygju.\nÞað getur ekki skipt út.");
const u8 gMoveDescription_Superpower[] = _("Öflug árás, en hún\nlækkar líka SÓKN og\nVÖRN notandans.");
const u8 gMoveDescription_MagicCoat[] = _("Endurspeglar LECH SEED\nóvininum og hvers kyns stöðu-\nskemmandi hreyfingu.");
const u8 gMoveDescription_Recycle[] = _("Hreyfing sem\n endurnýtir notaðan\nhlut til notkunar einu sinni\nenn.");
const u8 gMoveDescription_Revenge[] = _("Árásarhreyfing sem\n eykst í styrkleika ef\n skotmarkið hefur skaðað\n notandann.");
const u8 gMoveDescription_BrickBreak[] = _("Árás sem\n brýtur líka hvaða hindrun sem er\n eins og LIGHT SCREEN\n og REFLECT.");
const u8 gMoveDescription_Yawn[] = _("Risastórt geisp vaggar\n óvininn inn í að sofna\n í næstu\nbeygju.");
const u8 gMoveDescription_KnockOff[] = _("Snýr niður hlut\nóvininum til að\n koma í veg fyrir notkun hans\n meðan á bardaga stendur.");
const u8 gMoveDescription_Endeavor[] = _("Fær kraft\n færri HP sem notandinn\n hefur samanborið við\n óvininn.");
const u8 gMoveDescription_Eruption[] = _("Því hærra sem\nHP notandans er, því\n öflugri verður þessi\nárás.");
const u8 gMoveDescription_SkillSwap[] = _("Notandinn notar\n sinn sálræna kraft\n til að skipta um hæfileika\n við óvininn.");
const u8 gMoveDescription_Imprison[] = _("Kemur í veg fyrir að óvinir\n noti hvaða hreyfingu sem er\n sem er einnig þekkt\n af notandanum.");
const u8 gMoveDescription_Refresh[] = _("Sjálfgræðandi hreyfing\n sem læknar notandann\n af eitrun,\nbruna eða lömun.");
const u8 gMoveDescription_Grudge[] = _("Ef notandinn fellur í yfirlið eyðir\n þessi hreyfing\n PP hreyfingarinnar\n sem lauk henni.");
const u8 gMoveDescription_Snatch[] = _("Stelur áhrifum\n af\n-heilun óvinarins eða stöðu-\n-breytandi hreyfingu.");
const u8 gMoveDescription_SecretPower[] = _("Árás sem gæti\n haft auka\n áhrif sem eru mismunandi\n eftir landslagi.");
const u8 gMoveDescription_Dive[] = _("Notandinn kafar\n neðansjávar í\n fyrstu beygju og\n slær næstu beygju.");
const u8 gMoveDescription_ArmThrust[] = _("Snögg bylgja af\n beint-arm\n höggum sem slógu\n tvisvar til fimm sinnum.");
const u8 gMoveDescription_Camouflage[] = _("Breytir\n-gerð notandans eftir\p landslagi staðarins.");
const u8 gMoveDescription_TailGlow[] = _("Notandinn blikkar\nljósi sem verulega\n hækkar SP. ATK\ntölfræði þess.");
const u8 gMoveDescription_LusterPurge[] = _("Ljóskast\n særir óvininn. Það\n gæti einnig lækkað\nSP. DEF óvinarins.");
const u8 gMoveDescription_MistBall[] = _("Fylgi af dún\n lendir á óvininum. Það\n gæti einnig lækkað\nSP. ATK óvinarins.");
const u8 gMoveDescription_FeatherDance[] = _("Óvinurinn er þakinn\ndúnmassa sem lækkar\nSÓKN hans verulega.");
const u8 gMoveDescription_TeeterDance[] = _("Vaggandi dans\n sem ruglar alla\n og Vasaskrímsli í\n bardaga.");
const u8 gMoveDescription_BlazeKick[] = _("Eldfjörugt spark með a\nhigh gagnrýni-högg\nratio. Það gæti líka\nbrennt óvininn.");
const u8 gMoveDescription_MudSport[] = _("Veikir RAFMAGNS-\ngerð árásir á meðan\n notandinn er í\nbardaga.");
const u8 gMoveDescription_IceBall[] = _("5 umferða\nárás sem verður\nsterkari í hvert sinn sem\nhún rúllar.");
const u8 gMoveDescription_NeedleArm[] = _("Árás með\nþyrnum stráðum örmum.\nÞað gæti fengið\nóvininn til að hrökklast við.");
const u8 gMoveDescription_SlackOff[] = _("Notandinn slakar á\n og endurheimtir HP\nby helming sinn\nHP.");
const u8 gMoveDescription_HyperVoice[] = _("Notandinn lætur losa\nhræðilega hátt\nhróp með\nkrafti til að skemma.");
const u8 gMoveDescription_PoisonFang[] = _("Óvinurinn er bitinn\n með eitruðum vígtönnum.\nÞað gæti líka\n eitrað óvininn illa.");
const u8 gMoveDescription_CrushClaw[] = _("Ráðist er á óvininn\n með beittum klóm.\nÞað gæti líka lækkað\n óvinarins DEFENSE.");
const u8 gMoveDescription_BlastBurn[] = _("Óvinurinn verður fyrir höggi með\n mikilli sprengingu.\nNotandinn getur ekki hreyft\n í næstu beygju.");
const u8 gMoveDescription_HydroCannon[] = _("Óvinurinn er laminn með\na vatnsbyssu.\nNotandinn getur ekki hreyft\n í næstu beygju.");
const u8 gMoveDescription_MeteorMash[] = _("Óvinurinn fær hart og\nhraðskreitt högg.\nGæti einnig hækkað\nSÓKN notandans.");
const u8 gMoveDescription_Astonish[] = _("Árás með a\n óvænt hróp.\nÞað getur líka fengið\n óvininn til að hrökkva við.");
const u8 gMoveDescription_WeatherBall[] = _("Árás sem\n er mismunandi að krafti og\n gerð eftir\n veðrinu.");
const u8 gMoveDescription_Aromatherapy[] = _("Róandi lykt er\n gefin út til að lækna\nöll stöðuvandamál\ní partýi notandans.");
const u8 gMoveDescription_FakeTears[] = _("Notandinn þykist\n gráta verulega\nlækka\nSP óvinarins. DEF tölfræði.");
const u8 gMoveDescription_AirCutter[] = _("Óvinurinn verður fyrir höggi með\nrazor-líkum vindi.\nÞað hefur hátt\n gagnrýna högghlutfall.");
const u8 gMoveDescription_Overheat[] = _("Ákafur árás\nsem einnig\n dregur verulega úr\nSP notanda. ATK tölfræði.");
const u8 gMoveDescription_OdorSleuth[] = _("Neitar algjörlega viðleitni óvinarins til að\n auka getu hans\n til að komast hjá.");
const u8 gMoveDescription_RockTomb[] = _("Grjóti er kastað\ná óvininn. Það\n lækkar líka\nHRAÐA óvinarins ef það lendir.");
const u8 gMoveDescription_SilverWind[] = _("Ráðist er á óvininn\n með silfurryki.\nÞað gæti hækkað alla\n tölfræði notandans.");
const u8 gMoveDescription_MetalSound[] = _("Hræðilegt málmískt\nöskur er notað til að\n lækka\nSP. DEF óvinarins verulega.");
const u8 gMoveDescription_GrassWhistle[] = _("Skemmtilegt lag\n er spilað til að vagga\n óvininum í djúpan\n svefn.");
const u8 gMoveDescription_Tickle[] = _("Óvinurinn er kitlaður\ntil að hlæja, sem\nlækkar SÓKN og VÖRN\nhans.");
const u8 gMoveDescription_CosmicPower[] = _("Notandinn gleypir a\nmystic kraft til að\nhækka DEFENSE\n og SP. DEF.");
const u8 gMoveDescription_WaterSpout[] = _("Því hærra sem\nHP notandans er, því\n öflugri verður þessi\nárás.");
const u8 gMoveDescription_SignalBeam[] = _("Óvinurinn verður fyrir höggi með\na blikkandi geisla\n sem gæti líka valdið ruglingi.");
const u8 gMoveDescription_ShadowPunch[] = _("Notandinn kastar a\npunch frá\nshadows. Það er ekki hægt að komast hjá\n.");
const u8 gMoveDescription_Extrasensory[] = _("Notandinn ræðst á\n með undarlegum krafti\n sem gæti fengið\nóvininn til að hrökklast við.");
const u8 gMoveDescription_SkyUppercut[] = _("Notandinn ræðst á\n með efri skurði\n kastað til himins\n með krafti.");
const u8 gMoveDescription_SandTomb[] = _("Óvinurinn er fastur\n inni í sársaukafullum\nsandstormi í tvær\n til fimm beygjur.");
const u8 gMoveDescription_SheerCold[] = _("Ráðist er á óvininn\n með fullkomnum kulda\n sem veldur yfirliði\n ef hann lendir.");
const u8 gMoveDescription_MuddyWater[] = _("Notandinn ræðst á\n með drulluvatni.\nÞað gæti einnig lækkað nákvæmni óvinarins.");
const u8 gMoveDescription_BulletSeed[] = _("Notandinn skýtur\nfræ á óvininn.\nTvö til fimm fræ\neru skot í einu.");
const u8 gMoveDescription_AerialAce[] = _("Mjög hröð\nárás gegn einu\nmarkmiði. Það er ekki hægt að\nforðast.");
const u8 gMoveDescription_IcicleSpear[] = _("Beittum grýlukertum er\n skotið á óvininn.\nÞað slær tvisvar til\n fimm sinnum.");
const u8 gMoveDescription_IronDefense[] = _("Notandinn herðir\n yfirborð líkamans\n til að hækka verulega\nDEFENSE stöðu hans.");
const u8 gMoveDescription_Block[] = _("Notandinn hindrar leið\nóvininum með útbreiddum\nörmum til að\n koma í veg fyrir flótta.");
const u8 gMoveDescription_Howl[] = _("Notandinn vælir til\nað efla andann og\nhækka SÓKN sína.");
const u8 gMoveDescription_DragonClaw[] = _("Skarpar, risastórar klær\nhöggva og klippa\nóvininn hratt og\n af miklum krafti.");
const u8 gMoveDescription_FrenzyPlant[] = _("Óvinurinn verður fyrir höggi með\n stórri grein.\nNotandinn getur ekki hreyft\n í næstu beygju.");
const u8 gMoveDescription_BulkUp[] = _("Notandinn stækkar\nlíkamann og hækkar\nbæði SÓKN og VÖRN.");
const u8 gMoveDescription_Bounce[] = _("Notandinn skoppar\n á óvininn í\n2. beygjunni. Það gæti\n lama óvininn.");
const u8 gMoveDescription_MudShot[] = _("Notandinn ræðst á\nóvininn með leðju.\nÞað lækkar einnig\nHRAÐA óvinarins.");
const u8 gMoveDescription_PoisonTail[] = _("Árás með a\nhigh critical-hit\nratio. Það gæti líka\n eitrað óvininn.");
const u8 gMoveDescription_Covet[] = _("Krúttlega framkvæmd\nárás sem\n stelur líka\nhlut óvinarins.");
const u8 gMoveDescription_VoltTackle[] = _("Notandinn kastar\nelectrified tæklingu.\nÞað særir notandann\na lítið.");
const u8 gMoveDescription_MagicalLeaf[] = _("Ráðist er á óvininn\n með undarlegu laufblaði\n sem ekki er hægt að\nevade.");
const u8 gMoveDescription_WaterSport[] = _("Veikir ELDUR-gerð\nárásir á meðan\nnotandinn er í\nbardaga.");
const u8 gMoveDescription_CalmMind[] = _("Notandinn einbeitir\n hug sinn til að hækka\nSP. ATK og\nSP. DEF tölfræði.");
const u8 gMoveDescription_LeafBlade[] = _("Óvinurinn er skorinn\n með beittu laufblaði.\n Hann hefur hátt\n gagnrýna högghlutfall.");
const u8 gMoveDescription_DragonDance[] = _("Dularfullur, kröftugur\ndans sem hækkar SÓKN\nog HRAÐA notandans.");
const u8 gMoveDescription_RockBlast[] = _("Notandinn kastar tveimur\n til fimm hörðum steinum\nað óvininum í\nárás.");
const u8 gMoveDescription_ShockWave[] = _("Hröð rafbylgja\nskellur á\nóvininum. Það er\nógerlegt að forðast.");
const u8 gMoveDescription_WaterPulse[] = _("Árás með\npúlsandi vatnssprengingu.\nHún gæti líka\nruglað óvininn.");
const u8 gMoveDescription_DoomDesire[] = _("Hreyfing sem ræðst á\n óvininn með\n sprengingu af léttum tveimur\nbeygjum eftir notkun.");
const u8 gMoveDescription_PsychoBoost[] = _("Ákafur árás\nsem einnig\n dregur verulega úr\nSP notanda. ATK tölfræði.");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_DOUBLE_SLAP   - 1] = gMoveDescription_DoubleSlap,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_VICE_GRIP     - 1] = gMoveDescription_ViceGrip,
    [MOVE_GUILLOTINE    - 1] = gMoveDescription_Guillotine,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_SLAM          - 1] = gMoveDescription_Slam,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_HORN_ATTACK   - 1] = gMoveDescription_HornAttack,
    [MOVE_FURY_ATTACK   - 1] = gMoveDescription_FuryAttack,
    [MOVE_HORN_DRILL    - 1] = gMoveDescription_HornDrill,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_TWINEEDLE     - 1] = gMoveDescription_Twineedle,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_SUPERSONIC    - 1] = gMoveDescription_Supersonic,
    [MOVE_SONIC_BOOM    - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_ACID          - 1] = gMoveDescription_Acid,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_ICE_BEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_BLIZZARD      - 1] = gMoveDescription_Blizzard,
    [MOVE_PSYBEAM       - 1] = gMoveDescription_Psybeam,
    [MOVE_BUBBLE_BEAM   - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_LOW_KICK      - 1] = gMoveDescription_LowKick,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLAR_BEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_DANCE   - 1] = gMoveDescription_PetalDance,
    [MOVE_STRING_SHOT   - 1] = gMoveDescription_StringShot,
    [MOVE_DRAGON_RAGE   - 1] = gMoveDescription_DragonRage,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_THROW    - 1] = gMoveDescription_RockThrow,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_CONFUSION     - 1] = gMoveDescription_Confusion,
    [MOVE_PSYCHIC       - 1] = gMoveDescription_Psychic,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_MEDITATE      - 1] = gMoveDescription_Meditate,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_BIDE          - 1] = gMoveDescription_Bide,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_MIRROR_MOVE   - 1] = gMoveDescription_MirrorMove,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_EGG_BOMB      - 1] = gMoveDescription_EggBomb,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_SLUDGE        - 1] = gMoveDescription_Sludge,
    [MOVE_BONE_CLUB     - 1] = gMoveDescription_BoneClub,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_CLAMP         - 1] = gMoveDescription_Clamp,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_SPIKE_CANNON  - 1] = gMoveDescription_SpikeCannon,
    [MOVE_CONSTRICT     - 1] = gMoveDescription_Constrict,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_KINESIS       - 1] = gMoveDescription_Kinesis,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_GLARE         - 1] = gMoveDescription_Glare,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_POISON_GAS    - 1] = gMoveDescription_PoisonGas,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS   - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_SPORE         - 1] = gMoveDescription_Spore,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_ACID_ARMOR    - 1] = gMoveDescription_AcidArmor,
    [MOVE_CRABHAMMER    - 1] = gMoveDescription_Crabhammer,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_BONEMERANG    - 1] = gMoveDescription_Bonemerang,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_HYPER_FANG    - 1] = gMoveDescription_HyperFang,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_SUPER_FANG    - 1] = gMoveDescription_SuperFang,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_TRIPLE_KICK   - 1] = gMoveDescription_TripleKick,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_MIND_READER   - 1] = gMoveDescription_MindReader,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_POWDER_SNOW   - 1] = gMoveDescription_PowderSnow,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_FAINT_ATTACK  - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_SLUDGE_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_OCTAZOOKA     - 1] = gMoveDescription_Octazooka,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_ZAP_CANNON    - 1] = gMoveDescription_ZapCannon,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_BONE_RUSH     - 1] = gMoveDescription_BoneRush,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_CHARM         - 1] = gMoveDescription_Charm,
    [MOVE_ROLLOUT       - 1] = gMoveDescription_Rollout,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_MILK_DRINK    - 1] = gMoveDescription_MilkDrink,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_MEAN_LOOK     - 1] = gMoveDescription_MeanLook,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_RETURN        - 1] = gMoveDescription_Return,
    [MOVE_PRESENT       - 1] = gMoveDescription_Present,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_MEGAHORN      - 1] = gMoveDescription_Megahorn,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_SWEET_SCENT   - 1] = gMoveDescription_SweetScent,
    [MOVE_IRON_TAIL     - 1] = gMoveDescription_IronTail,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_MORNING_SUN   - 1] = gMoveDescription_MorningSun,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_MOONLIGHT     - 1] = gMoveDescription_Moonlight,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_TWISTER       - 1] = gMoveDescription_Twister,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_FUTURE_SIGHT  - 1] = gMoveDescription_FutureSight,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_BEAT_UP       - 1] = gMoveDescription_BeatUp,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_UPROAR        - 1] = gMoveDescription_Uproar,
    [MOVE_STOCKPILE     - 1] = gMoveDescription_Stockpile,
    [MOVE_SPIT_UP       - 1] = gMoveDescription_SpitUp,
    [MOVE_SWALLOW       - 1] = gMoveDescription_Swallow,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_FLATTER       - 1] = gMoveDescription_Flatter,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_FOLLOW_ME     - 1] = gMoveDescription_FollowMe,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_ROLE_PLAY     - 1] = gMoveDescription_RolePlay,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_GRUDGE        - 1] = gMoveDescription_Grudge,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_DIVE          - 1] = gMoveDescription_Dive,
    [MOVE_ARM_THRUST    - 1] = gMoveDescription_ArmThrust,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_TAIL_GLOW     - 1] = gMoveDescription_TailGlow,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_MUD_SPORT     - 1] = gMoveDescription_MudSport,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_POISON_FANG   - 1] = gMoveDescription_PoisonFang,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_BLAST_BURN    - 1] = gMoveDescription_BlastBurn,
    [MOVE_HYDRO_CANNON  - 1] = gMoveDescription_HydroCannon,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_CUTTER    - 1] = gMoveDescription_AirCutter,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_ODOR_SLEUTH   - 1] = gMoveDescription_OdorSleuth,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_METAL_SOUND   - 1] = gMoveDescription_MetalSound,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_COSMIC_POWER  - 1] = gMoveDescription_CosmicPower,
    [MOVE_WATER_SPOUT   - 1] = gMoveDescription_WaterSpout,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_SKY_UPPERCUT  - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_SHEER_COLD    - 1] = gMoveDescription_SheerCold,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_AERIAL_ACE    - 1] = gMoveDescription_AerialAce,
    [MOVE_ICICLE_SPEAR  - 1] = gMoveDescription_IcicleSpear,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_DRAGON_CLAW   - 1] = gMoveDescription_DragonClaw,
    [MOVE_FRENZY_PLANT  - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_TAIL   - 1] = gMoveDescription_PoisonTail,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_WATER_SPORT   - 1] = gMoveDescription_WaterSport,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_DRAGON_DANCE  - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_DOOM_DESIRE   - 1] = gMoveDescription_DoomDesire,
    [MOVE_PSYCHO_BOOST  - 1] = gMoveDescription_PsychoBoost,
};
