#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("Óvinurinn er sleginn\nmeð hala, framfæti\neða öðrum\nlíkamshluta.");
const u8 gMoveDescription_KarateChop[] = _("Óvinurinn er höggvinn\nmeð beittu handarhöggi.\nGæfuhögg eru líklegri.");
const u8 gMoveDescription_DoubleSlap[] = _("Óvininum er löðrungað\ná víxl tvisvar til\nfimm sinnum.");
const u8 gMoveDescription_CometPunch[] = _("Höggjahríð skellur á\nóvininum tvisvar til\nfimm sinnum.");
const u8 gMoveDescription_MegaPunch[] = _("Óvinurinn fær hnefahögg\nknúið miklu vöðvaafli.");
const u8 gMoveDescription_PayDay[] = _("Myntum er kastað í\nóvininn. Peningar fást\neftir bardagann.");
const u8 gMoveDescription_FirePunch[] = _("Óvinurinn er kýldur\nmeð eldheitum hnefa.\nGæti valdið bruna.");
const u8 gMoveDescription_IcePunch[] = _("Óvinurinn er kýldur\nmeð ísköldum hnefa.\nGæti fryst óvininn.");
const u8 gMoveDescription_ThunderPunch[] = _("Óvinurinn er kýldur\nmeð rafmögnuðum hnefa.\nGæti valdið lömun.");
const u8 gMoveDescription_Scratch[] = _("Harðar, oddhvassar og\nbeittar klær klóra\nóvininn.");
const u8 gMoveDescription_ViceGrip[] = _("Óvinurinn er gripinn\nog kraminn með\nstórum, sterkum\ntöngum.");
const u8 gMoveDescription_Guillotine[] = _("Grimmileg árás með\ntöngum. Óvinurinn fellur\ní yfirlið ef hún hittir.");
const u8 gMoveDescription_RazorWind[] = _("Vindblöð hæfa\nóvininn í næstu\numferð. Gæfuhögg eru\nlíklegri.");
const u8 gMoveDescription_SwordsDance[] = _("Trylltur bardagadans.\nHann hækkar ÁRÁS\nverulega.");
const u8 gMoveDescription_Cut[] = _("Grunnárás.\nÞað er hægt að nota til að\nklippa niður þunn tré\nog gras.");
const u8 gMoveDescription_Gust[] = _("Óvinurinn er sleginn\nmeð sterkri vindhviðu\nfrá vængjum\nnotandans.");
const u8 gMoveDescription_WingAttack[] = _("Óvinurinn er sleginn\nmeð stórum, breiðum\nvængjum.");
const u8 gMoveDescription_Whirlwind[] = _("Feykir óvininum út\nog kallar fram annan.\nLýkur bardaga gegn\nvilltu skrímsli.");
const u8 gMoveDescription_Fly[] = _("Tveggja umferða bragð\nsem hittir í þeirri síðari.\nNotað til að fljúga\ntil þekkts bæjar.");
const u8 gMoveDescription_Bind[] = _("Langur líkami eða\nfálmar binda óvininn\ní tvær til fimm\numferðir.");
const u8 gMoveDescription_Slam[] = _("Óvinurinn er sleginn\nmeð löngum hala,\nvínviðum o.fl.");
const u8 gMoveDescription_VineWhip[] = _("Mjóir, svipulíkir\nvínviðir slá óvininn.");
const u8 gMoveDescription_Stomp[] = _("Óvinurinn er troðinn\nundir stórum fæti.\nGæti hrokkið við.");
const u8 gMoveDescription_DoubleKick[] = _("Tveir fætur eru notaðir\ntil að sparka fljótt í\nóvininn tvisvar í einni\numferð.");
const u8 gMoveDescription_MegaKick[] = _("Óvinurinn er sparkaður\naf miklu vöðvaafli.");
const u8 gMoveDescription_JumpKick[] = _("Notandinn stekkur hátt\nog sparkar. Ef bragðið\ngeigar meiðist notandinn.");
const u8 gMoveDescription_RollingKick[] = _("Snöggt spark úr\nsnúningi. Óvinurinn\ngæti hrokkið við.");
const u8 gMoveDescription_SandAttack[] = _("Sand er kastað í andlit\nóvinarins og NÁKVÆMNI\nhans lækkar.");
const u8 gMoveDescription_Headbutt[] = _("Notandinn skallar\nóvininn. Hann gæti\nhrokkið við.");
const u8 gMoveDescription_HornAttack[] = _("Óvinurinn er stunginn\nmeð beittu horni.");
const u8 gMoveDescription_FuryAttack[] = _("Óvinurinn er stunginn\nmeð horni eða goggi\ntvisvar til fimm\nsinnum.");
const u8 gMoveDescription_HornDrill[] = _("Horninu er snúið eins\nog bor. Óvinurinn fellur\ní yfirlið ef bragðið hittir.");
const u8 gMoveDescription_Tackle[] = _("Notandinn ræðst með\nöllum líkamanum á\nóvininn.");
const u8 gMoveDescription_BodySlam[] = _("Notandinn skellir öllum\nlíkamanum á óvininn.\nGæti valdið lömun.");
const u8 gMoveDescription_Wrap[] = _("Langur líkami eða\nvínviðir vefjast um\nóvininn í tvær til\nfimm umferðir.");
const u8 gMoveDescription_TakeDown[] = _("Kærulaus atlaga með\nöllum líkamanum sem\nmeiðir líka notandann\nlítillega.");
const u8 gMoveDescription_Thrash[] = _("Notandinn hamast\ní tvær til þrjár\numferðir og ruglast\nsíðan.");
const u8 gMoveDescription_DoubleEdge[] = _("Kærulaus, lífshættuleg\ntækling sem meiðir\nnotandann líka lítillega.");
const u8 gMoveDescription_TailWhip[] = _("Notandinn vaggar\nhalanum krúttlega og\nlækkar VÖRN\nóvinarins.");
const u8 gMoveDescription_PoisonSting[] = _("Óvinurinn er stunginn\nmeð eitruðum broddi.\nÞað gæti eitrað\nhann.");
const u8 gMoveDescription_Twineedle[] = _("Óvinurinn er stunginn\ntvisvar með broddum.\nÞað gæti eitrað\nhann.");
const u8 gMoveDescription_PinMissile[] = _("Skarpar nálar eru skotnar\ná óvininn tvisvar til\nfimm sinnum í röð.");
const u8 gMoveDescription_Leer[] = _("Ógnvekjandi augnaráð\nlækkar VÖRN óvinarins.");
const u8 gMoveDescription_Bite[] = _("Notandinn bítur með\ngrimmum vígtönnum.\nÓvinurinn gæti\nhrokkið við.");
const u8 gMoveDescription_Growl[] = _("Notandinn urrar krúttlega og\nlækkar ÁRÁS óvinarins.");
const u8 gMoveDescription_Roar[] = _("Fælir óvininn út\nog kallar fram annan.\nLýkur bardaga gegn\nvilltu skrímsli.");
const u8 gMoveDescription_Sing[] = _("Blíður söngur svæfir\nóvininn djúpum svefni.");
const u8 gMoveDescription_Supersonic[] = _("Notandinn býr til\nsérkennilegar hljóðbylgjur.\nÞað gæti ruglað\nóvininn.");
const u8 gMoveDescription_SonicBoom[] = _("Höggbylgja sem\nveldur alltaf\n20 HP skaða.");
const u8 gMoveDescription_Disable[] = _("Í nokkrar umferðir má\nóvinurinn ekki nota\nsíðasta bragð sitt.");
const u8 gMoveDescription_Acid[] = _("Óvinurinn er úðaður\nmeð ætandi sýru sem\ngæti lækkað\nVÖRN hans.");
const u8 gMoveDescription_Ember[] = _("Litlum logum er\nvarpað á óvininn.\nÞeir gætu brennt\nhann.");
const u8 gMoveDescription_Flamethrower[] = _("Öflugum logum er\nblásið á óvininn.\nÞeir gætu brennt\nhann.");
const u8 gMoveDescription_Mist[] = _("Þoka verndar lið\nnotandans gegn lækkun\neiginleikagilda.");
const u8 gMoveDescription_WaterGun[] = _("Vatni er spýtt af krafti\núr munni á óvininn.");
const u8 gMoveDescription_HydroPump[] = _("Miklu vatni er skotið\nundir háum þrýstingi\ná óvininn.");
const u8 gMoveDescription_Surf[] = _("Stór bylgja hrynur\nniður á óvininn.\nEinnig er hægt að nota\ntil að fara yfir vatn.");
const u8 gMoveDescription_IceBeam[] = _("Ísköldum geisla er\nskotið á óvininn.\nHann gæti frosið.");
const u8 gMoveDescription_Blizzard[] = _("Snjóstormur skellur á\nóvininum og gæti\ngaddfryst hann.");
const u8 gMoveDescription_Psybeam[] = _("Sérkennilegum geisla er\nskotið á óvininn.\nGæti ruglað hann.");
const u8 gMoveDescription_BubbleBeam[] = _("Buna af loftbólum\nskellur á óvininum.\nGæti lækkað HRAÐA\nóvinarins.");
const u8 gMoveDescription_AuroraBeam[] = _("Regnbogalitaður\nárásargeisli.\nGæti lækkað ÁRÁS\nóvinarins.");
const u8 gMoveDescription_HyperBeam[] = _("Gífurlega öflug árás\nsem neyðir notandann\ntil að hvíla sig í\nnæstu umferð.");
const u8 gMoveDescription_Peck[] = _("Beittum goggi eða horni\ner stungið í óvininn.");
const u8 gMoveDescription_DrillPeck[] = _("Snúningsárás með\nbeittum goggi sem\nvirkar eins og bor.");
const u8 gMoveDescription_Submission[] = _("Kærulaust kast með\nöllum líkamanum sem\nmeiðir líka notandann\nlítillega.");
const u8 gMoveDescription_LowKick[] = _("Lágt spark sem fellir\nóvininn. Þyngri óvinir\nskaðast meira.");
const u8 gMoveDescription_Counter[] = _("Hefndarbragð sem svarar\nlíkamlegu höggi með\ntvöföldum skaða.");
const u8 gMoveDescription_SeismicToss[] = _("Kast sem nýtir\nþyngdaraflið og veldur\nskaða á við stig\nnotandans.");
const u8 gMoveDescription_Strength[] = _("Óvinurinn er sleginn\nmeð hámarksafli.\nEinnig hægt að nota\ntil að færa steina.");
const u8 gMoveDescription_Absorb[] = _("Árás sem endurheimtir\nHP sem nemur helmingi\nskaðans sem hún veldur.");
const u8 gMoveDescription_MegaDrain[] = _("Öflug árás sem sýgur\nHP sem nemur helmingi\nskaðans sem hún veldur.");
const u8 gMoveDescription_LeechSeed[] = _("Fræi er plantað á\nóvininn og flytur HP\nfrá honum til notandans\ní hverri umferð.");
const u8 gMoveDescription_Growth[] = _("Líkami notandans\nvex og SÉR. ÁRÁS\nhans hækkar.");
const u8 gMoveDescription_RazorLeaf[] = _("Beitt laufblað sker\nóvininn. Gæfuhögg\neru líklegri.");
const u8 gMoveDescription_SolarBeam[] = _("Tveggja umferða bragð\nsem safnar orku og\nskýtur henni á óvininn\ní síðari umferð.");
const u8 gMoveDescription_PoisonPowder[] = _("Eitruðu ryki er\ndreift yfir óvininn.\nÞað gæti eitrað\nhann.");
const u8 gMoveDescription_StunSpore[] = _("Lamandi ryki er dreift\nvíða. Það gæti lamað\nóvininn.");
const u8 gMoveDescription_SleepPowder[] = _("Svefnvaldandi ryki er\ndreift kringum óvininn.");
const u8 gMoveDescription_PetalDance[] = _("Notandinn ræðst á með\nkrónublöðum í tvær til\nþrjár umferðir og\nruglast svo.");
const u8 gMoveDescription_StringShot[] = _("Óvinurinn er bundinn\nmeð þráðum úr munni\nnotandans sem lækka\nHRAÐA hans.");
const u8 gMoveDescription_DragonRage[] = _("Höggbylgja sem\nveldur alltaf\n40 HP skaða.");
const u8 gMoveDescription_FireSpin[] = _("Óvinurinn festist í\neldhring sem geisar í\ntvær til fimm umferðir.");
const u8 gMoveDescription_ThunderShock[] = _("Raflost sem gæti\nlamað óvininn.");
const u8 gMoveDescription_Thunderbolt[] = _("Sterk rafárás sem gæti\nlamað óvininn.");
const u8 gMoveDescription_ThunderWave[] = _("Veikt rafstuð sem lamar\nóvininn ef það hittir.");
const u8 gMoveDescription_Thunder[] = _("Hrottaleg eldingarárás\nsem gæti lamað óvininn.");
const u8 gMoveDescription_RockThrow[] = _("Smásteinaregni skellur\ná óvininum.");
const u8 gMoveDescription_Earthquake[] = _("Jarðskjálfti hittir öll\nVasaskrímsli í bardaga\nnema notandann.");
const u8 gMoveDescription_Fissure[] = _("Óvininum er varpað í\nsprungu og hann fellur í\nyfirlið ef bragðið hittir.");
const u8 gMoveDescription_Dig[] = _("Hittir í 2. umferð.\nMá einnig nota til\nað yfirgefa hella.");
const u8 gMoveDescription_Toxic[] = _("Eitrar óvininn\nilla. Eiturskaðinn\nversnar með hverri\numferð.");
const u8 gMoveDescription_Confusion[] = _("Veik fjarhugarárás\nsem gæti ruglað\nóvininn.");
const u8 gMoveDescription_Psychic[] = _("Sterk hugarárás\nsem gæti einnig\nlækkað SÉR. VÖRN\nóvinarins.");
const u8 gMoveDescription_Hypnosis[] = _("Dáleiðandi sefjun\nleggur óvininn í\ndjúpan svefn.");
const u8 gMoveDescription_Meditate[] = _("Notandinn hugleiðir\ntil að vekja kraft sinn\nog hækka ÁRÁS.");
const u8 gMoveDescription_Agility[] = _("Notandinn léttir\nlíkamann og hækkar\nHRAÐA sinn\nverulega.");
const u8 gMoveDescription_QuickAttack[] = _("Næstum ósýnilega\nhröð árás sem\ner viss um að slá\nfyrst.");
const u8 gMoveDescription_Rage[] = _("Árás sem styrkist\ní hvert sinn sem\nnotandinn verður\nfyrir höggi.");
const u8 gMoveDescription_Teleport[] = _("Flýr villtan bardaga.\nFlytur líka á síðasta\nVasaskrímslasetur.");
const u8 gMoveDescription_NightShade[] = _("Ógnvekjandi\nskuggamynd veldur\nskaða sem jafngildir\nstigi notandans.");
const u8 gMoveDescription_Mimic[] = _("Notandinn afritar\nsíðasta bragð\nóvinarins það sem\neftir er bardagans.");
const u8 gMoveDescription_Screech[] = _("Eyrnakljúfandi\nöskur sem lækkar\nVÖRN óvinarins\nverulega.");
const u8 gMoveDescription_DoubleTeam[] = _("Býr til blekkingar\nsem gera erfiðara\nað hitta notandann.");
const u8 gMoveDescription_Recover[] = _("Læknar allt að hálft\nhámarks-HP\nnotandans.");
const u8 gMoveDescription_Harden[] = _("Notandinn stífnar\nalla vöðva líkamans\ntil að hækka\nVÖRN sína.");
const u8 gMoveDescription_Minimize[] = _("Þjappar frumum\nlíkamans saman og\nhækkar undanskot\nnotandans.");
const u8 gMoveDescription_Smokescreen[] = _("Reyk- eða blekský\nlækkar NÁKVÆMNI\nóvinarins.");
const u8 gMoveDescription_ConfuseRay[] = _("Ógnvænlegur geisli\nruglar óvininn.");
const u8 gMoveDescription_Withdraw[] = _("Notandinn dregur\nlíkamann inn í harða\nskel og hækkar\nVÖRN sína.");
const u8 gMoveDescription_DefenseCurl[] = _("Notandinn hniprar\nsig saman, felur\nveika bletti og\nhækkar VÖRN sína.");
const u8 gMoveDescription_Barrier[] = _("Notandinn myndar\ntraustan vegg sem\nhækkar VÖRN hans\nverulega.");
const u8 gMoveDescription_LightScreen[] = _("Ljósveggur minnkar\nskaða frá brögðum\nsem nota SÉR. ÁRÁS\ní fimm umferðir.");
const u8 gMoveDescription_Haze[] = _("Eyðir öllum\nhækkunum og\nlækkunum allra í\nbardaganum.");
const u8 gMoveDescription_Reflect[] = _("Ljósveggur minnkar\nskaða líkamlegra\nbragða í fimm\numferðir.");
const u8 gMoveDescription_FocusEnergy[] = _("Notandinn einbeitir\nsér og eykur líkur\ná Gæfuhöggi.");
const u8 gMoveDescription_Bide[] = _("Þolir högg í tvær\numferðir og skilar\nsvo tvöföldum\nskaða.");
const u8 gMoveDescription_Metronome[] = _("Veifar fingri og\nnotar eitthvert\nbragð af handahófi.");
const u8 gMoveDescription_MirrorMove[] = _("Endurtekur síðasta\nbragð óvinarins gegn\nhonum sjálfum.");
const u8 gMoveDescription_SelfDestruct[] = _("Notandinn springur,\nveldur miklum skaða\nog fellur sjálfur í\nyfirlið.");
const u8 gMoveDescription_EggBomb[] = _("Stóru eggi er\nkastað af miklu afli\ní óvininn.");
const u8 gMoveDescription_Lick[] = _("Löng tunga sleikir\nog slær óvininn.\nGæti lamað hann.");
const u8 gMoveDescription_Smog[] = _("Útblástursloft\nskaðar óvininn og\ngæti eitrað hann.");
const u8 gMoveDescription_Sludge[] = _("Eitruðu seyru er\nkastað í óvininn.\nGæti eitrað hann.");
const u8 gMoveDescription_BoneClub[] = _("Slær óvininn með\nbeini. Gæti látið\nhann hrökkva við.");
const u8 gMoveDescription_FireBlast[] = _("Öflugur logi skellur\ná óvininum og gæti\nbrennt hann.");
const u8 gMoveDescription_Waterfall[] = _("Öflug atlaga sem má\neinnig nota til að\nklífa fossa.");
const u8 gMoveDescription_Clamp[] = _("Skel notandans\nklemmir óvininn í\ntvær til fimm\numferðir.");
const u8 gMoveDescription_Swift[] = _("Stjörnulaga geislar\nsem aldrei missa af eru\nskotnir á alla óvini í\nbardaga.");
const u8 gMoveDescription_SkullBash[] = _("Notandinn hækkar\nVÖRN sína í fyrri\numferð og ræðst á\ní þeirri næstu.");
const u8 gMoveDescription_SpikeCannon[] = _("Beittum broddum er\nskotið tvisvar til\nfimm sinnum í\nóvininn.");
const u8 gMoveDescription_Constrict[] = _("Langir fálmarar eða\nvafningsjurtir lemja\nóvininn. Gæti lækkað\nHRAÐA hans.");
const u8 gMoveDescription_Amnesia[] = _("Gleymir einhverju\nog hækkar SÉR. VÖRN\nsína verulega.");
const u8 gMoveDescription_Kinesis[] = _("Beygir skeið til að\ntrufla óvininn.\nGæti lækkað\nNÁKVÆMNI hans.");
const u8 gMoveDescription_SoftBoiled[] = _("Læknar allt að hálft\nhámarks-HP notandans.\nMá líka lækna\nbandamann.");
const u8 gMoveDescription_HiJumpKick[] = _("Öflugt hnéspark úr\nstökki. Ef það\ngeigar meiðist\nnotandinn.");
const u8 gMoveDescription_Glare[] = _("Ógnandi mynstur á\nmaga notandans\nlamar óvininn.");
const u8 gMoveDescription_DreamEater[] = _("Gleypir helming\nskaðans gegn sofandi\nóvini og læknar HP.");
const u8 gMoveDescription_PoisonGas[] = _("Óvininum er úðað\nmeð skýi af\neitruðu gasi sem gæti\neitrað óvininn.");
const u8 gMoveDescription_Barrage[] = _("Kringlóttum hlutum\ner kastað tvisvar til\nfimm sinnum í\nóvininn.");
const u8 gMoveDescription_LeechLife[] = _("Gleypir helming\nskaðans sem bragðið\nveldur og læknar HP.");
const u8 gMoveDescription_LovelyKiss[] = _("Kyssir óvininn með\nógnvekjandi svip og\nsvæfir hann.");
const u8 gMoveDescription_SkyAttack[] = _("Ræðst í 2. umferð.\nGæfuhögg er líklegt.\nÓvinurinn gæti\nhrökkvað við.");
const u8 gMoveDescription_Transform[] = _("Breytir notandanum\ní afrit óvinarins,\nmeð sömu brögðum.");
const u8 gMoveDescription_Bubble[] = _("Buna af loftbólum\nskellur á óvininum.\nGæti lækkað HRAÐA\nóvinarins.");
const u8 gMoveDescription_DizzyPunch[] = _("Taktfast högg sem\ngæti ruglað\nóvininn.");
const u8 gMoveDescription_Spore[] = _("Fíngerð gró eru\ndreifð og svæfa\nóvininn.");
const u8 gMoveDescription_Flash[] = _("Sterkt ljós lækkar\nNÁKVÆMNI óvinarins\nog lýsir upp hella.");
const u8 gMoveDescription_Psywave[] = _("Undarleg orkubylgja\nveldur breytilegum\nskaða.");
const u8 gMoveDescription_Splash[] = _("Notandinn hoppar og\nskvettir án nokkurra\náhrifa.");
const u8 gMoveDescription_AcidArmor[] = _("Notandinn gerir\nfrumur sínar fljótandi\nog hækkar VÖRN\nsína verulega.");
const u8 gMoveDescription_Crabhammer[] = _("Stór kló lemur\nóvininn. Miklar líkur\neru á Gæfuhöggi.");
const u8 gMoveDescription_Explosion[] = _("Notandinn springur,\nveldur gífurlegum\nskaða og fellur\nsjálfur í yfirlið.");
const u8 gMoveDescription_FurySwipes[] = _("Beittar klær eða\nljáir rífa óvininn\ntvisvar til fimm\nsinnum.");
const u8 gMoveDescription_Bonemerang[] = _("Kastar beini sem\nhittir einu sinni á\nútleið og aftur á\nbakaleið.");
const u8 gMoveDescription_Rest[] = _("Sefur í tvær\numferðir, fyllir HP\nog læknar öll\nstöðuvandamál.");
const u8 gMoveDescription_RockSlide[] = _("Stórum hnullungum\ner kastað í óvininn.\nGæti látið hann\nhrökkva við.");
const u8 gMoveDescription_HyperFang[] = _("Ræðst á með beittum\nvígtönnum. Gæti\nlátið óvininn\nhrökkva við.");
const u8 gMoveDescription_Sharpen[] = _("Notandinn skerpir\nbrúnir sínar og\nhækkar ÁRÁS.");
const u8 gMoveDescription_Conversion[] = _("Breytir gerð\nnotandans í gerð eins\naf brögðum hans.");
const u8 gMoveDescription_TriAttack[] = _("Þrír geislar skella\nsamtímis á óvininum.\nGæti lamað, brennt\neða fryst hann.");
const u8 gMoveDescription_SuperFang[] = _("Beittar vígtennur\nlækka HP óvinarins\num helming.");
const u8 gMoveDescription_Slash[] = _("Klær o.fl. skera\nóvininn. Gæfuhögg\ner líklegt.");
const u8 gMoveDescription_Substitute[] = _("Býr til tálbeitu\nfyrir fjórðung af\nhámarks-HP\nnotandans.");
const u8 gMoveDescription_Struggle[] = _("Notað aðeins þegar\nPP eru uppurin.\nSkaðar einnig\nnotandann.");
const u8 gMoveDescription_Sketch[] = _("Afritar síðasta bragð\nóvinarins varanlega.");
const u8 gMoveDescription_TripleKick[] = _("Þriggja sparka árás\nsem verður\nöflugri með hverju\nhöggi á eftir.");
const u8 gMoveDescription_Thief[] = _("Gæti stolið haldnum\nhlut óvinarins ef\nnotandinn heldur ekki\ná hlut.");
const u8 gMoveDescription_SpiderWeb[] = _("Flækir óvininn í\nklístruðum þræði svo\nhann flýi ekki eða\nskipti út.");
const u8 gMoveDescription_MindReader[] = _("Notandinn les hreyfingar\nóvinarins og tryggir að\nnæsta bragð notandans\nhitti.");
const u8 gMoveDescription_Nightmare[] = _("Sofandi óvinur er\nsýnd martröð\nsem veldur skaða í\nhverri umferð.");
const u8 gMoveDescription_FlameWheel[] = _("Notandinn ræðst á í\neldhjúpi. Gæti brennt\nóvininn.");
const u8 gMoveDescription_Snore[] = _("Notað aðeins í\nsvefni. Gæti látið\nóvininn hrökkva við.");
const u8 gMoveDescription_Curse[] = _("Bragð sem virkar\nöðruvísi fyrir\nDRAUG-gerðina og allar\naðrar tegundir.");
const u8 gMoveDescription_Flail[] = _("Örvæntingarfull árás\nsem verður\nöflugri því minna\nHP sem notandinn hefur.");
const u8 gMoveDescription_Conversion2[] = _("Breytir gerð til að\nveita mótstöðu gegn\nsíðasta bragði sem\nhitti.");
const u8 gMoveDescription_Aeroblast[] = _("Lofthvirfli er\nskotið á óvininn.\nGæfuhögg er líklegt.");
const u8 gMoveDescription_CottonSpore[] = _("Bómullarlík gró\nloða við óvininn og\nlækka HRAÐA hans\nverulega.");
const u8 gMoveDescription_Reversal[] = _("Öflug árás sem\nstyrkist eftir því sem\nHP notandans lækkar.");
const u8 gMoveDescription_Spite[] = _("Dregur 2 til 5 PP af\nsíðasta bragði\nóvinarins.");
const u8 gMoveDescription_PowderSnow[] = _("Snjóhviða skellur á\nóvininum. Hann gæti\nfrosið.");
const u8 gMoveDescription_Protect[] = _("Ver notandann gegn\nöllum árásum. Getur\nmistekist ef notað\ner aftur.");
const u8 gMoveDescription_MachPunch[] = _("Notandinn slær\nhnefahögg á\nleifturhraða og er\nalltaf á undan.");
const u8 gMoveDescription_ScaryFace[] = _("Hræðir óvininn\nmeð skelfilegu andliti\nog lækkar HRAÐA hans\nverulega.");
const u8 gMoveDescription_FaintAttack[] = _("Notandinn læðist að\nóvininum og hittir\nalltaf.");
const u8 gMoveDescription_SweetKiss[] = _("Notandinn kyssir\nóvininn krúttlega og\nruglar hann.");
const u8 gMoveDescription_BellyDrum[] = _("Notandinn hámarkar\nÁRÁS sína en fórnar\nhelmingi hámarks-HP.");
const u8 gMoveDescription_SludgeBomb[] = _("Óhreinni seyru er\nkastað á óvininn.\nHún gæti eitrað hann.");
const u8 gMoveDescription_MudSlap[] = _("Leðju er kastað í\nandlit óvinarins. Hún\nskaðar og lækkar\nNÁKVÆMNI hans.");
const u8 gMoveDescription_Octazooka[] = _("Bleki er skotið í\nandlit óvinarins. Það\ngæti lækkað\nNÁKVÆMNI hans.");
const u8 gMoveDescription_Spikes[] = _("Gaddagildra er lögð\nvið lið óvinarins og\nskaðar þá sem koma\ninn í bardagann.");
const u8 gMoveDescription_ZapCannon[] = _("Rafhleðslu er skotið\nsem úr fallbyssu. Hún\nskaðar og lamar\nóvininn.");
const u8 gMoveDescription_Foresight[] = _("Ógildir tilraunir\nóvinarins til að auka\nundankomu sína.");
const u8 gMoveDescription_DestinyBond[] = _("Falli notandinn í\nyfirlið fellur sá sem\nveitir lokahöggið\neinnig í yfirlið.");
const u8 gMoveDescription_PerishSong[] = _("Allir sem heyra þetta\nfalla í yfirlið eftir\nþrjár umferðir nema\nskipt sé út.");
const u8 gMoveDescription_IcyWind[] = _("Ískaldur vindur\nskellur á óvininum\nog lækkar HRAÐA\nhans.");
const u8 gMoveDescription_Detect[] = _("Ver notandann gegn\nöllum árásum. Getur\nmistekist ef notað\ner aftur.");
const u8 gMoveDescription_BoneRush[] = _("Notandinn slær\nóvininn með beini\ntvisvar til fimm\nsinnum.");
const u8 gMoveDescription_LockOn[] = _("Notandinn miðar á\nóvininn og tryggir að\nnæsta bragð hitti.");
const u8 gMoveDescription_Outrage[] = _("Notandinn hamast\ní tvær til þrjár\numferðir og ruglast\nsíðan.");
const u8 gMoveDescription_Sandstorm[] = _("Sandstormur geisar í\nfimm umferðir og skaðar\nekki STEINN-, JARÐ- né\nSTÁL-gerðir.");
const u8 gMoveDescription_GigaDrain[] = _("Öflug árás sem gleypir\nhelming skaðans til að\nendurheimta HP\nnotandans.");
const u8 gMoveDescription_Endure[] = _("Notandinn þolir högg\nmeð minnst 1 HP eftir.\nGetur brugðist við\nendurtekna notkun.");
const u8 gMoveDescription_Charm[] = _("Krúttleiki notandans\nheillar óvininn og\nlækkar ÁRÁS hans\nverulega.");
const u8 gMoveDescription_Rollout[] = _("5 umferða\nárás sem verður\nsterkari í hvert sinn sem\nhún hittir.");
const u8 gMoveDescription_FalseSwipe[] = _("Aðhaldssöm árás\nsem skilur alltaf\nóvininn eftir með að\nminnsta kosti 1 HP.");
const u8 gMoveDescription_Swagger[] = _("Ruglar óvininn en\nhækkar jafnframt ÁRÁS\nhans verulega.");
const u8 gMoveDescription_MilkDrink[] = _("Endurheimtir allt að\nhelming HP notandans.\nMá einnig lækna\nbandamann utan bardaga.");
const u8 gMoveDescription_Spark[] = _("Rafmagnuð\ntækling sem\ngæti líka lamað\nóvininn.");
const u8 gMoveDescription_FuryCutter[] = _("Árás sem verður\nsterkari með hverju\nsamfelldu höggi.");
const u8 gMoveDescription_SteelWing[] = _("Óvinurinn er sleginn\nmeð stálvængjum.\nGæti einnig hækkað\nVÖRN notandans.");
const u8 gMoveDescription_MeanLook[] = _("Óvinurinn er festur\nmeð illu augnaráði og\ngetur ekki sloppið.");
const u8 gMoveDescription_Attract[] = _("Ef óvinurinn er af\nhinu kyninu verður\nhann ástfanginn og\nræðst síður á.");
const u8 gMoveDescription_SleepTalk[] = _("Í svefni notar\nnotandinn af handahófi\neitt af brögðunum sem\nhann kann.");
const u8 gMoveDescription_HealBell[] = _("Róandi bjölluhljómur\nlæknar öll\nstöðuvandamál\nliðsins.");
const u8 gMoveDescription_Return[] = _("Bragðið eflist eftir\nþví sem notandanum\nlíkar betur við\nÞJÁLFARANN sinn.");
const u8 gMoveDescription_Present[] = _("Gjöf með gildru er\ngefin óvininum. Hún\nendurheimtir þó\nstundum HP.");
const u8 gMoveDescription_Frustration[] = _("Bragðið eflist eftir\nþví sem notandanum\nlíkar verr við\nÞJÁLFARANN sinn.");
const u8 gMoveDescription_Safeguard[] = _("Verndar lið notandans\ngegn öllum\nstöðuvandamálum í\n5 umferðir.");
const u8 gMoveDescription_PainSplit[] = _("HP notandans og\nóvinarins eru lögð\nsaman og skipt jafnt\ná milli þeirra.");
const u8 gMoveDescription_SacredFire[] = _("Dulræn og öflug\neldárás sem gæti\nbrennt óvininn.");
const u8 gMoveDescription_Magnitude[] = _("Jarðskjálftaárás á\nöll Vasaskrímsli sem\nstanda á jörðinni.\nKrafturinn er misjafn.");
const u8 gMoveDescription_DynamicPunch[] = _("Óvinurinn er kýldur af\nfullum krafti. Höggið\nruglar hann ef það\nhittir.");
const u8 gMoveDescription_Megahorn[] = _("Hrottaleg árás með\nhörðu og glæsilegu\nhorni.");
const u8 gMoveDescription_DragonBreath[] = _("Óvinurinn er sleginn\nmeð öflugum andardrætti\nsem gæti lamað hann.");
const u8 gMoveDescription_BatonPass[] = _("Notandinn skiptir út\nog flytur hækkanir og\nlækkanir yfir á þann\nnæsta.");
const u8 gMoveDescription_Encore[] = _("Neyðir óvininn til að\nendurtaka síðasta\nbragð sitt í tvær til\nsex umferðir.");
const u8 gMoveDescription_Pursuit[] = _("Ræðst á óvin sem\nreynir að skipta út.\nÞá tvöfaldast\nkrafturinn.");
const u8 gMoveDescription_RapidSpin[] = _("Árás sem leysir\nnotandann úr BINDA,\nVAFNINGI, BLÓÐSUGURFRÆI\nog BRODDUM.");
const u8 gMoveDescription_SweetScent[] = _("Lokkar óvininn og\nlækkar undankomu hans.\nLaðar einnig að villt\nVasaskrímsli.");
const u8 gMoveDescription_IronTail[] = _("Árás með stálhörðum\nhala. Gæti lækkað\nVÖRN óvinarins.");
const u8 gMoveDescription_MetalClaw[] = _("Ráðist er á óvininn\nmeð stálklóm.\nGæti einnig hækkað\nÁRÁS notandans.");
const u8 gMoveDescription_VitalThrow[] = _("Notandinn ræðst á\neftir óvininum en\nhittir alltaf.");
const u8 gMoveDescription_MorningSun[] = _("Endurheimtir HP\nnotandans. Magnið fer\neftir veðri.");
const u8 gMoveDescription_Synthesis[] = _("Endurheimtir HP\nnotandans. Magnið fer\neftir veðri.");
const u8 gMoveDescription_Moonlight[] = _("Endurheimtir HP\nnotandans. Magnið fer\neftir veðri.");
const u8 gMoveDescription_HiddenPower[] = _("Árás með gerð og\nstyrk sem ráðast af\nnotandanum.");
const u8 gMoveDescription_CrossChop[] = _("Tvö handarhögg lenda\ná óvininum. Líkur á\nGæfuhöggi eru miklar.");
const u8 gMoveDescription_Twister[] = _("Hvass hvirfilvindur\nræðst á óvininn og gæti\nfengið hann til að\nhrökkva við.");
const u8 gMoveDescription_RainDance[] = _("Steypiregn fellur í\nfimm umferðir og eflir\nbragð af VATN-gerð.");
const u8 gMoveDescription_SunnyDay[] = _("Sólin skín í fimm\numferðir og styrkir\nbrögð af ELDUR-gerð.");
const u8 gMoveDescription_Crunch[] = _("Óvinurinn er bitinn\nmeð beittum tönnum.\nGæti lækkað\nSÉR. VÖRN hans.");
const u8 gMoveDescription_MirrorCoat[] = _("Skilar tvöföldum skaða\nfrá sérstakri árás\nóvinarins.");
const u8 gMoveDescription_PsychUp[] = _("Notandinn dáleiðir sig\nog afritar allar\nbreytingar á gildum\nóvinarins.");
const u8 gMoveDescription_ExtremeSpeed[] = _("Blindandi hröð\nhleðsluárás sem\nfer alltaf á undan\nöllum öðrum.");
const u8 gMoveDescription_AncientPower[] = _("Árás með fornum krafti\nsem gæti hækkað alla\neiginleika notandans.");
const u8 gMoveDescription_ShadowBall[] = _("Skuggakúlu er kastað\ná óvininn. Hún gæti\neinnig lækkað\nSÉR. VÖRN hans.");
const u8 gMoveDescription_FutureSight[] = _("Tveimur umferðum eftir\nað bragðið er notað\nverður óvinurinn fyrir\nhugarárás.");
const u8 gMoveDescription_RockSmash[] = _("Árás sem gæti\nlækkað VÖRN. Hún\ngetur einnig brotið\nsprungna steina.");
const u8 gMoveDescription_Whirlpool[] = _("Óvinurinn festist í\nillvígum hringiðu í\ntvær til fimm\numferðir.");
const u8 gMoveDescription_BeatUp[] = _("Öll Vasaskrímsli í\nliðinu taka þátt.\nFleiri bandamenn auka\nskaðann.");
const u8 gMoveDescription_FakeOut[] = _("Forgangsárás sem fær\nóvininn til að hrökkva\nvið. Virkar aðeins í\nfyrstu umferð.");
const u8 gMoveDescription_Uproar[] = _("Notandinn gerir uppnám\ní tvær til fimm\numferðir og kemur í\nveg fyrir svefn.");
const u8 gMoveDescription_Stockpile[] = _("Safnar krafti til\nsíðari nota. Má safna\nallt að þrisvar.");
const u8 gMoveDescription_SpitUp[] = _("Krafturinn sem safnaðist\nmeð BIRGÐASÖFNUN er\nleystur úr læðingi\ní einni árás.");
const u8 gMoveDescription_Swallow[] = _("Orkan sem safnaðist\nmeð BIRGÐASÖFNUN er\nnotuð til að\nendurheimta HP.");
const u8 gMoveDescription_HeatWave[] = _("Notandinn ræðst á með\nheitum andardrætti sem\ngæti valdið bruna.");
const u8 gMoveDescription_Hail[] = _("Haglél geisar í fimm\numferðir og skaðar\nalla nema skrímsli\naf ÍS-gerð.");
const u8 gMoveDescription_Torment[] = _("Reitir óvininn til\nreiði svo hann getur\nekki notað sama bragð\ntvisvar í röð.");
const u8 gMoveDescription_Flatter[] = _("Smjaður ruglar\nóvininn en hækkar\neinnig SÉR. ÁRÁS\nhans.");
const u8 gMoveDescription_WillOWisp[] = _("Notandinn skýtur\nóhugnanlegum bláhvítum\nloga á óvininn og\nbrennir hann.");
const u8 gMoveDescription_Memento[] = _("Notandinn fellur í\nyfirlið en lækkar\nÁRÁS og SÉR. ÁRÁS\nóvinarins verulega.");
const u8 gMoveDescription_Facade[] = _("Krafturinn tvöfaldast\nef notandinn er\nbrenndur, eitraður\neða lamaður.");
const u8 gMoveDescription_FocusPunch[] = _("Öflugt högg sem\nmistekst ef notandinn\nverður fyrir árás áður\nen hann slær.");
const u8 gMoveDescription_SmellingSalt[] = _("Tvöfaldur kraftur gegn\nlömuðum óvini, en\nlömun hans læknast.");
const u8 gMoveDescription_FollowMe[] = _("Notandinn beinir allri\nathygli að sér svo\nóvinir ráðist aðeins á\nhann.");
const u8 gMoveDescription_NaturePower[] = _("Árás sem\nbreytir gerð\neftir staðsetningu\nnotandans.");
const u8 gMoveDescription_Charge[] = _("Notandinn safnar orku\nog eflir næsta bragð\nsitt af RAFM-gerð.");
const u8 gMoveDescription_Taunt[] = _("Óvinurinn er hæddur\nsvo hann reiðist og má\naðeins nota\nárásarbrögð.");
const u8 gMoveDescription_HelpingHand[] = _("Bragð sem eykur kraft\nárásar bandamanns í\nbardaga.");
const u8 gMoveDescription_Trick[] = _("Notandinn blekkir\nóvininn til að skiptast\ná haldnum hlutum.");
const u8 gMoveDescription_RolePlay[] = _("Notandinn hermir\nfullkomlega eftir\nóvininum og afritar\ngetu hans.");
const u8 gMoveDescription_Wish[] = _("Ósk endurheimtir\nhelming hámarks-HP í\nnæstu umferð.");
const u8 gMoveDescription_Assist[] = _("Notandinn velur og notar\naf handahófi bragð\neins liðsfélaga.");
const u8 gMoveDescription_Ingrain[] = _("Notandinn festir rætur,\nendurheimtir HP í hverri\numferð en getur ekki\nskipt út.");
const u8 gMoveDescription_Superpower[] = _("Öflug árás, en hún\nlækkar líka ÁRÁS og\nVÖRN notandans.");
const u8 gMoveDescription_MagicCoat[] = _("Endurvarpar\nBLÓÐSUGURFRÆI og öllum\nskaðlegum stöðubragðum\ntil óvinarins.");
const u8 gMoveDescription_Recycle[] = _("Endurheimtir notaðan\nhlut svo nota megi\nhann aftur.");
const u8 gMoveDescription_Revenge[] = _("Árásarbragð sem eflist\nef óvinurinn hefur\nskaðað notandann.");
const u8 gMoveDescription_BrickBreak[] = _("Árás sem brýtur líka\nhindranir eins og\nLJÓSSKJÓL og\nENDURVARP.");
const u8 gMoveDescription_Yawn[] = _("Mikið geisp svæfir\nóvininn í næstu\numferð.");
const u8 gMoveDescription_KnockOff[] = _("Slær haldinn hlut af\nóvininum svo ekki megi\nnota hann í bardaganum.");
const u8 gMoveDescription_Endeavor[] = _("Lækkar HP óvinarins\nniður í sama gildi og\nHP notandans.");
const u8 gMoveDescription_Eruption[] = _("Því hærra sem\nHP notandans er, því\nöflugri verður þessi\nárás.");
const u8 gMoveDescription_SkillSwap[] = _("Notandinn beitir\nhugarkrafti til að\nskipta um getu við\nóvininn.");
const u8 gMoveDescription_Imprison[] = _("Kemur í veg fyrir að\nóvinir noti bragð sem\nnotandinn þekkir líka.");
const u8 gMoveDescription_Refresh[] = _("Sjálfgræðandi bragð\nsem læknar eitrun,\nbruna eða lömun\nnotandans.");
const u8 gMoveDescription_Grudge[] = _("Ef notandinn fellur\ntæmast öll PP úr\nbragðinu sem felldi\nhann.");
const u8 gMoveDescription_Snatch[] = _("Stelur áhrifum\nlækningar- eða\nstöðubreytandi bragðs\nóvinarins.");
const u8 gMoveDescription_SecretPower[] = _("Árás sem getur haft\nviðbótaráhrif eftir\nlandslaginu.");
const u8 gMoveDescription_Dive[] = _("Notandinn kafar\nneðansjávar í fyrstu\numferð og slær í\nþeirri næstu.");
const u8 gMoveDescription_ArmThrust[] = _("Snögg hrina högga með\nútréttri hönd sem hitta\ntvisvar til fimm\nsinnum.");
const u8 gMoveDescription_Camouflage[] = _("Breytir gerð notandans\neftir landslagi\nstaðarins.");
const u8 gMoveDescription_TailGlow[] = _("Notandinn leiftrar ljósi\nsem hækkar SÉR. ÁRÁS\nhans verulega.");
const u8 gMoveDescription_LusterPurge[] = _("Ljósbylgja særir\nóvininn og gæti\nlækkað SÉR. VÖRN\nhans.");
const u8 gMoveDescription_MistBall[] = _("Hrina af dúni hittir\nóvininn og getur\nlækkað SÉR. ÁRÁS\nhans.");
const u8 gMoveDescription_FeatherDance[] = _("Óvinurinn er þakinn\ndúnmassa sem lækkar\nÁRÁS hans verulega.");
const u8 gMoveDescription_TeeterDance[] = _("Vaggandi dans sem\nruglar öll\nVasaskrímsli í\nbardaganum.");
const u8 gMoveDescription_BlazeKick[] = _("Eldspark sem getur\nbrennt óvininn.\nGæfuhögg eru\nlíklegri.");
const u8 gMoveDescription_MudSport[] = _("Veikir árásarbrögð af\nRAFM-gerð meðan\nnotandinn er í\nbardaganum.");
const u8 gMoveDescription_IceBall[] = _("Rúlluárás í fimm\numferðir sem eflist í\nhvert sinn sem hún\nrúllar.");
const u8 gMoveDescription_NeedleArm[] = _("Þyrnóttir armar ráðast\ná óvininn og geta\nfengið hann til að\nhrökkva við.");
const u8 gMoveDescription_SlackOff[] = _("Notandinn slakar á og\nendurheimtir helming\naf hámarks-HP sínu.");
const u8 gMoveDescription_HyperVoice[] = _("Notandinn gefur frá sér\nógurlega hátt öskur\nsem veldur skaða.");
const u8 gMoveDescription_PoisonFang[] = _("Eitraðar vígtennur\nbíta óvininn og geta\nvaldið alvarlegri\neitrun.");
const u8 gMoveDescription_CrushClaw[] = _("Ráðist er á óvininn\nmeð beittum klóm.\nGæti einnig lækkað\nVÖRN hans.");
const u8 gMoveDescription_BlastBurn[] = _("Gífurleg sprenging\nskellur á óvininum.\nNotandinn getur ekkert\ngert í næstu umferð.");
const u8 gMoveDescription_HydroCannon[] = _("Vatnskanóna skellur\ná óvininum. Notandinn\ngetur ekkert gert í\nnæstu umferð.");
const u8 gMoveDescription_MeteorMash[] = _("Hart og snöggt\nhnefahögg sem getur\neinnig hækkað ÁRÁS\nnotandans.");
const u8 gMoveDescription_Astonish[] = _("Árás með skyndilegu\nöskri sem getur fengið\nóvininn til að\nhrökkva við.");
const u8 gMoveDescription_WeatherBall[] = _("Árásarbragð sem breytir\nkrafti og gerð eftir\nveðrinu.");
const u8 gMoveDescription_Aromatherapy[] = _("Róandi ilmur læknar\nöll stöðuvandamál í\nliði notandans.");
const u8 gMoveDescription_FakeTears[] = _("Notandinn þykist gráta\nog lækkar SÉR. VÖRN\nóvinarins verulega.");
const u8 gMoveDescription_AirCutter[] = _("Beitt vindhviða hittir\nóvininn. Gæfuhögg\neru líklegri.");
const u8 gMoveDescription_Overheat[] = _("Áköf árás sem lækkar\nSÉR. ÁRÁS notandans\nverulega.");
const u8 gMoveDescription_OdorSleuth[] = _("Ógildir tilraunir\nóvinarins til að bæta\nundanbrögð sín.");
const u8 gMoveDescription_RockTomb[] = _("Grjóthnullungum er\nkastað á óvininn. Ef\nþeir hitta lækkar HRAÐI\nhans.");
const u8 gMoveDescription_SilverWind[] = _("Silfurlitað ryk ræðst\ná óvininn og getur\nhækkað öll gildi\nnotandans.");
const u8 gMoveDescription_MetalSound[] = _("Óþægilegt málmhljóð\nsem lækkar SÉR. VÖRN\nóvinarins verulega.");
const u8 gMoveDescription_GrassWhistle[] = _("Ljúft lag vaggar\nóvininum í djúpan\nsvefn.");
const u8 gMoveDescription_Tickle[] = _("Óvinurinn er kitlaður\ntil að hlæja, sem\nlækkar ÁRÁS og VÖRN\nhans.");
const u8 gMoveDescription_CosmicPower[] = _("Notandinn drekkur í\nsig dulrænan kraft og\nhækkar VÖRN og\nSÉR. VÖRN sína.");
const u8 gMoveDescription_WaterSpout[] = _("Því hærra sem\nHP notandans er, því\nöflugri verður þessi\nárás.");
const u8 gMoveDescription_SignalBeam[] = _("Blikkandi geisli hittir\nóvininn og getur\neinnig ruglað hann.");
const u8 gMoveDescription_ShadowPunch[] = _("Notandinn slær úr\nskugganum. Ekki er\nhægt að forðast\nhöggið.");
const u8 gMoveDescription_Extrasensory[] = _("Undarlegur kraftur\nræðst á óvininn. Hann\ngæti hrökklað við.");
const u8 gMoveDescription_SkyUppercut[] = _("Notandinn ræðst á með\nöflugu upphöggi til\nhimins.");
const u8 gMoveDescription_SandTomb[] = _("Sársaukafullur\nsandbylur fangar\nóvininn í tvær til\nfimm umferðir.");
const u8 gMoveDescription_SheerCold[] = _("Ofurkuldi hittir\nóvininn og fellir hann\nef bragðið heppnast.");
const u8 gMoveDescription_MuddyWater[] = _("Notandinn ræðst á með\ndrulluvatni sem getur\nlækkað NÁKVÆMNI\nóvinarins.");
const u8 gMoveDescription_BulletSeed[] = _("Notandinn skýtur\nfræ á óvininn.\nTvö til fimm fræ\neru skot í einu.");
const u8 gMoveDescription_AerialAce[] = _("Ofurhröð árás á eitt\nskotmark. Ekki er hægt\nað forðast bragðið.");
const u8 gMoveDescription_IcicleSpear[] = _("Beittum grýlukertum er\nskotið á óvininn.\nÞað slær tvisvar til\nfimm sinnum.");
const u8 gMoveDescription_IronDefense[] = _("Notandinn herðir\nyfirborð líkamans og\nhækkar VÖRN sína\nverulega.");
const u8 gMoveDescription_Block[] = _("Notandinn lokar leið\nóvinarins með útréttum\nörmum og hindrar flótta.");
const u8 gMoveDescription_Howl[] = _("Notandinn vælir til\nað efla andann og\nhækka ÁRÁS sína.");
const u8 gMoveDescription_DragonClaw[] = _("Stórar, beittar klær\nkrækja í óvininn og\ntæta hann af miklu\nafli.");
const u8 gMoveDescription_FrenzyPlant[] = _("Gífurleg grein hittir\nóvininn. Notandinn\ngetur ekkert gert í\nnæstu umferð.");
const u8 gMoveDescription_BulkUp[] = _("Notandinn stækkar\nlíkamann og hækkar\nbæði ÁRÁS og VÖRN.");
const u8 gMoveDescription_Bounce[] = _("Notandinn stekkur hátt\nog lendir á óvininum\ní næstu umferð. Getur\nlamað hann.");
const u8 gMoveDescription_MudShot[] = _("Notandinn ræðst á\nóvininn með leðju.\nÞað lækkar einnig\nHRAÐA óvinarins.");
const u8 gMoveDescription_PoisonTail[] = _("Árás sem getur eitrað\nóvininn. Gæfuhögg\neru líklegri.");
const u8 gMoveDescription_Covet[] = _("Krúttleg árás sem\nstelur einnig haldnum\nhlut óvinarins.");
const u8 gMoveDescription_VoltTackle[] = _("Rafmagnað áhlaup sem\nsærir einnig notandann\nlítillega.");
const u8 gMoveDescription_MagicalLeaf[] = _("Undarlegt lauf ræðst á\nóvininn. Ekki er hægt\nað forðast bragðið.");
const u8 gMoveDescription_WaterSport[] = _("Veikir árásarbrögð af\nELDUR-gerð meðan\nnotandinn er í\nbardaganum.");
const u8 gMoveDescription_CalmMind[] = _("Notandinn einbeitir\nhuganum og hækkar\nSÉR. ÁRÁS og\nSÉR. VÖRN sína.");
const u8 gMoveDescription_LeafBlade[] = _("Beitt laufblað sker\nóvininn. Gæfuhögg\neru líklegri.");
const u8 gMoveDescription_DragonDance[] = _("Dularfullur, kröftugur\ndans sem hækkar ÁRÁS\nog HRAÐA notandans.");
const u8 gMoveDescription_RockBlast[] = _("Notandinn kastar\ntveimur til fimm hörðum\nsteinum á óvininn.");
const u8 gMoveDescription_ShockWave[] = _("Hröð rafbylgja hittir\nóvininn. Ekki er hægt\nað forðast bragðið.");
const u8 gMoveDescription_WaterPulse[] = _("Árás með\npúlsandi vatnssprengingu.\nHún gæti líka\nruglað óvininn.");
const u8 gMoveDescription_DoomDesire[] = _("Bragðið ræðst á\nóvininn með ljósblossa\ntveimur umferðum eftir\nnotkun.");
const u8 gMoveDescription_PsychoBoost[] = _("Áköf árás sem lækkar\nSÉR. ÁRÁS notandans\nverulega.");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_DOUBLE_SLAP   - 1] = gMoveDescription_DoubleSlap,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_VICE_GRIP     - 1] = gMoveDescription_ViceGrip,
    [MOVE_GUILLOTINE    - 1] = gMoveDescription_Guillotine,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_SLAM          - 1] = gMoveDescription_Slam,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_HORN_ATTACK   - 1] = gMoveDescription_HornAttack,
    [MOVE_FURY_ATTACK   - 1] = gMoveDescription_FuryAttack,
    [MOVE_HORN_DRILL    - 1] = gMoveDescription_HornDrill,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_TWINEEDLE     - 1] = gMoveDescription_Twineedle,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_SUPERSONIC    - 1] = gMoveDescription_Supersonic,
    [MOVE_SONIC_BOOM    - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_ACID          - 1] = gMoveDescription_Acid,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_ICE_BEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_BLIZZARD      - 1] = gMoveDescription_Blizzard,
    [MOVE_PSYBEAM       - 1] = gMoveDescription_Psybeam,
    [MOVE_BUBBLE_BEAM   - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_LOW_KICK      - 1] = gMoveDescription_LowKick,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLAR_BEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_DANCE   - 1] = gMoveDescription_PetalDance,
    [MOVE_STRING_SHOT   - 1] = gMoveDescription_StringShot,
    [MOVE_DRAGON_RAGE   - 1] = gMoveDescription_DragonRage,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_THROW    - 1] = gMoveDescription_RockThrow,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_CONFUSION     - 1] = gMoveDescription_Confusion,
    [MOVE_PSYCHIC       - 1] = gMoveDescription_Psychic,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_MEDITATE      - 1] = gMoveDescription_Meditate,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_BIDE          - 1] = gMoveDescription_Bide,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_MIRROR_MOVE   - 1] = gMoveDescription_MirrorMove,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_EGG_BOMB      - 1] = gMoveDescription_EggBomb,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_SLUDGE        - 1] = gMoveDescription_Sludge,
    [MOVE_BONE_CLUB     - 1] = gMoveDescription_BoneClub,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_CLAMP         - 1] = gMoveDescription_Clamp,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_SPIKE_CANNON  - 1] = gMoveDescription_SpikeCannon,
    [MOVE_CONSTRICT     - 1] = gMoveDescription_Constrict,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_KINESIS       - 1] = gMoveDescription_Kinesis,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_GLARE         - 1] = gMoveDescription_Glare,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_POISON_GAS    - 1] = gMoveDescription_PoisonGas,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS   - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_SPORE         - 1] = gMoveDescription_Spore,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_ACID_ARMOR    - 1] = gMoveDescription_AcidArmor,
    [MOVE_CRABHAMMER    - 1] = gMoveDescription_Crabhammer,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_BONEMERANG    - 1] = gMoveDescription_Bonemerang,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_HYPER_FANG    - 1] = gMoveDescription_HyperFang,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_SUPER_FANG    - 1] = gMoveDescription_SuperFang,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_TRIPLE_KICK   - 1] = gMoveDescription_TripleKick,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_MIND_READER   - 1] = gMoveDescription_MindReader,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_POWDER_SNOW   - 1] = gMoveDescription_PowderSnow,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_FAINT_ATTACK  - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_SLUDGE_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_OCTAZOOKA     - 1] = gMoveDescription_Octazooka,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_ZAP_CANNON    - 1] = gMoveDescription_ZapCannon,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_BONE_RUSH     - 1] = gMoveDescription_BoneRush,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_CHARM         - 1] = gMoveDescription_Charm,
    [MOVE_ROLLOUT       - 1] = gMoveDescription_Rollout,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_MILK_DRINK    - 1] = gMoveDescription_MilkDrink,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_MEAN_LOOK     - 1] = gMoveDescription_MeanLook,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_RETURN        - 1] = gMoveDescription_Return,
    [MOVE_PRESENT       - 1] = gMoveDescription_Present,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_MEGAHORN      - 1] = gMoveDescription_Megahorn,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_SWEET_SCENT   - 1] = gMoveDescription_SweetScent,
    [MOVE_IRON_TAIL     - 1] = gMoveDescription_IronTail,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_MORNING_SUN   - 1] = gMoveDescription_MorningSun,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_MOONLIGHT     - 1] = gMoveDescription_Moonlight,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_TWISTER       - 1] = gMoveDescription_Twister,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_FUTURE_SIGHT  - 1] = gMoveDescription_FutureSight,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_BEAT_UP       - 1] = gMoveDescription_BeatUp,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_UPROAR        - 1] = gMoveDescription_Uproar,
    [MOVE_STOCKPILE     - 1] = gMoveDescription_Stockpile,
    [MOVE_SPIT_UP       - 1] = gMoveDescription_SpitUp,
    [MOVE_SWALLOW       - 1] = gMoveDescription_Swallow,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_FLATTER       - 1] = gMoveDescription_Flatter,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_FOLLOW_ME     - 1] = gMoveDescription_FollowMe,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_ROLE_PLAY     - 1] = gMoveDescription_RolePlay,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_GRUDGE        - 1] = gMoveDescription_Grudge,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_DIVE          - 1] = gMoveDescription_Dive,
    [MOVE_ARM_THRUST    - 1] = gMoveDescription_ArmThrust,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_TAIL_GLOW     - 1] = gMoveDescription_TailGlow,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_MUD_SPORT     - 1] = gMoveDescription_MudSport,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_POISON_FANG   - 1] = gMoveDescription_PoisonFang,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_BLAST_BURN    - 1] = gMoveDescription_BlastBurn,
    [MOVE_HYDRO_CANNON  - 1] = gMoveDescription_HydroCannon,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_CUTTER    - 1] = gMoveDescription_AirCutter,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_ODOR_SLEUTH   - 1] = gMoveDescription_OdorSleuth,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_METAL_SOUND   - 1] = gMoveDescription_MetalSound,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_COSMIC_POWER  - 1] = gMoveDescription_CosmicPower,
    [MOVE_WATER_SPOUT   - 1] = gMoveDescription_WaterSpout,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_SKY_UPPERCUT  - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_SHEER_COLD    - 1] = gMoveDescription_SheerCold,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_AERIAL_ACE    - 1] = gMoveDescription_AerialAce,
    [MOVE_ICICLE_SPEAR  - 1] = gMoveDescription_IcicleSpear,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_DRAGON_CLAW   - 1] = gMoveDescription_DragonClaw,
    [MOVE_FRENZY_PLANT  - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_TAIL   - 1] = gMoveDescription_PoisonTail,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_WATER_SPORT   - 1] = gMoveDescription_WaterSport,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_DRAGON_DANCE  - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_DOOM_DESIRE   - 1] = gMoveDescription_DoomDesire,
    [MOVE_PSYCHO_BOOST  - 1] = gMoveDescription_PsychoBoost,
};
