CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "Halló! Velkomin í\n"
    .string "CELADON-STÓRVERSLUN.\p"
    .string "Taflan til hægri sýnir skipulag\n"
    .string "verslunarinnar.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "1F: ÞJÓNUSTUBORÐ\p"
    .string "2F: ÞJÁLFARAMARKAÐUR\p"
    .string "3F: TÖLVULEIKJABÚÐ\p"
    .string "4F: GJAFIR FRÁ VITRINGUM\p"
    .string "5F: LYFJABÚÐ\p"
    .string "ÞAKSVÆÐI: SJÁLFSALAR$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "1F: ÞJÓNUSTUBORÐ$"

