@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords::
    .string "とびらを あけるには パスワードが 2つ いるようだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded::
    .string "{PLAYER} sló inn lykilorð.\p"
    .string "'BLEIKHYRNA þarf staur.'\p"
    .string "… … … … … …\p"
    .string "Annað lykilorð þarf til að opna\n"
    .string "dyrnar…$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened::
    .string "{PLAYER} sló inn tvö lykilorð.\p"
    .string "'BLEIKHYRNA þarf staur.' 'Já, nei,\n"
    .string "SÆLEGG.'\p"
    .string "… … … … … …\p"
    .string "Dyrnar að VÖRUHÚSINU opnuðust!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen::
    .string "Hurð VÖRUHÚSSINS er nú þegar opinn.$"

FiveIsland_Meadow_Text_Rocket1Intro::
    .string "Þetta svæði er stranglega bannað!\n"
    .string "Út, út!$"

FiveIsland_Meadow_Text_Rocket1Defeat::
    .string "Er þetta í alvöru?$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
    .string "Þú átt ekkert erindi hingað! Farðu\n"
    .string "heim!$"

FiveIsland_Meadow_Text_Rocket2Intro::
    .string "Það er ekkert hérna fyrir utan\n"
    .string "VÖRUHÚSIÐ okkar.\p"
    .string "Svo hvað kemur þér hingað?$"

FiveIsland_Meadow_Text_Rocket2Defeat::
    .string "Það átti ekki að gerast…$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
    .string "Viltu vita hvað er inni í þessu\n"
    .string "VÖRUHÚSI?\p"
    .string "Það er betra að þú vitir það ekki.\n"
    .string "Fyrir þinn eigin hag, meina ég.$"

FiveIsland_Meadow_Text_Rocket3Intro::
    .string "Þú værir að eyða tíma jafnvel þó þú\n"
    .string "myndir komast framhjá mér.$"

FiveIsland_Meadow_Text_Rocket3Defeat::
    .string "Ó, það gerir mig brjálaðan!$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
    .string "Þú munt hvort sem er ekki komast inn\n"
    .string "án lykilorðanna.$"

