CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "Handtekin vasaskrímsli eru skráð með\n"
    .string "auðkennisnúmeri (ID No.) og\p"
    .string "upprunalegum þjálfara (OT).\p"
    .string "OT stendur fyrir 'Original ÞJÁLFARI'\n"
    .string "- þjálfarinn sem fangaði það fyrst.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "Allt í lagi!\p"
    .string "Félagi minn ætlar að láta mig fá\n"
    .string "KENGÚRILL í skiptum fyrir REIMNI!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "Komdu, REIMNIR!\p"
    .string "Ég elska REIMNA! Ég safna þeim!\p"
    .string "Huh?\p"
    .string "REIMNIR breyttist í allt annað\n"
    .string "vasaskrímsli á meðan á skiptunum\p"
    .string "stóð!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "Þú getur þekkt vasaskrímsli sem þú\n"
    .string "færð í skiptum á auðkennisnúmerum\p"
    .string "þeirra.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "Þetta er Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "RPG-leikur! Það er enginn tími fyrir\n"
    .string "það!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "Íþróttaleikur! Pabbi kann að meta\n"
    .string "hann!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "Þrautaleikur! Hann virðist\n"
    .string "ávanabindandi!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "Bardagaleikur! Hann virðist erfiður!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "3F: TÖLVULEIKJABÚÐ$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "Rauður og Grænn! Bæði eru\n"
    .string "vasaskrímsli!$"

Text_CounterTeach::
    .string "Ó, hæ! Ég kláraði loksins leikinn um\n"
    .string "vasaskrímsli.\p"
    .string "Ertu ekki búinn enn? Hvernig væri að\n"
    .string "ég kenndi þér gott bragð?\p"
    .string "Bragðið sem ég hef í huga er\n"
    .string "GAGNÁTAK.\p"
    .string "Ekki afgreiðsluborðið sem ég halla\n"
    .string "mér á, athugaðu það!$"

Text_CounterDeclined::
    .string "Hefurðu ekki áhuga? Komdu aftur ef\n"
    .string "þú skiptir um skoðun.$"

Text_CounterWhichMon::
    .string "Hvaða vasaskrímsli ætti ég að kenna\n"
    .string "GAGNÁTAK?$"

Text_CounterTaught::
    .string "Ertu að nota GAGNÁTAK-bragðið sem ég\n"
    .string "kenndi vasaskrímslinu þínu?$"
