Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "Hæ! Manstu eftir mér? Ég er einn af\n"
    .string "AÐSTOÐARMÖNNUM Prófessor EIK.\p"
    .string "Ef VasaDEX-ið þitt er með full gögn\n"
    .string "um {STR_VAR_1} tegundir á ég að gefa\p"
    .string "þér verðlaun.\p"
    .string "Prófessor EIK fól mér {STR_VAR_2}\n"
    .string "handa þér.\p"
    .string "Svo, {PLAYER}, leyfðu mér að spyrja.\p"
    .string "Hefurðu safnað gögnum um að minnsta\n"
    .string "kosti {STR_VAR_1} gerðir\p"
    .string "vasaskrímsla?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "Frábært! Þú hefur náð eða átt\n"
    .string "{STR_VAR_3} gerðir vasaskrímsla!\p"
    .string "Til hamingju! Gjörðu svo vel!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER} fékk {STR_VAR_2} frá\n"
    .string "AÐSTOÐARMANNINUM.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "Það eru hlutir á jörðinni sem gætu\n"
    .string "verið faldir.\p"
    .string "Notaðu HLUTALEITARA til að finna\n"
    .string "falda hluti nálægt þér.\p"
    .string "Tækið er dálítið takmarkað. Það\n"
    .string "getur ekki staðsett hlutina\p"
    .string "nákvæmlega.\p"
    .string "Það sýnir bara í hvaða átt hluturinn\n"
    .string "er.\p"
    .string "Notaðu það til að ná áttum, leitaðu\n"
    .string "svo sjálfur á grunsamlega svæðinu.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Sjáum hvað sjónaukinn sýnir...\p"
    .string "Stórt vasaskrímsli sefur á vegi!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "Sjáum hvað sjónaukinn sýnir...\p"
    .string "Hvílíkt stórkostlegt útsýni!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "Sjáum hvað sjónaukinn sýnir...\p"
    .string "Til að komast til LAVENDER BORGAR\n"
    .string "frá CERULEAN BORG...\p"
    .string "STEINA GÖNG virðast vera góð leið.$"
