PewterCity_House1_Text_Nidoran::
    .string "NÁLDUR♂: Voffvoff!$"

PewterCity_House1_Text_NidoranSit::
    .string "NÁLDUR, sestu!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Vasaskrímslið okkar er\n"
    .string "utanaðkomandi, svo það er\p"
    .string "dutlungafullt og erfitt í meðförum.\p"
    .string "Utanaðkomandi vasaskrímsli er eitt\n"
    .string "sem þú færð í skiptum.\p"
    .string "Það vex hratt, en gæti hunsað\n"
    .string "óreyndan ÞJÁLFARA í bardaga.\p"
    .string "Ef við bara ættum einhver MERKI...$"

