Route13_Text_SebastianIntro::
    .string "Fugla-Vasaskrímslin mín vilja\n"
    .string "berjast við þig!$"

Route13_Text_SebastianDefeat::
    .string "Tapaði DÚFUTETUR og DÚFINN\n"
    .string "samsetningin mín?$"

Route13_Text_SebastianPostBattle::
    .string "My Vasaskrímsli look happy even\n"
    .string "though they lost.$"

Route13_Text_SusieIntro::
    .string "Mér er sagt að ég sé góð fyrir barn.$"

Route13_Text_SusieDefeat::
    .string "Ó! Ég tapaði!$"

Route13_Text_SusiePostBattle::
    .string "Ég vil verða góður ÞJÁLFARI. Ég mun\n"
    .string "æfa stíft, bíddu bara.$"

Route13_Text_ValerieIntro::
    .string "Vá! BADGES þínir eru of flottir!$"

Route13_Text_ValerieDefeat::
    .string "Ekki nóg!$"

Route13_Text_ValeriePostBattle::
    .string "Þú fékkst þessa BADGES frá SALUR\n"
    .string "LEIÐTOGAR. Ég veit það!$"

Route13_Text_GwenIntro::
    .string "Krúttlegu Vasaskrímslin mín óska\n"
    .string "eftir að kynnast þér.$"

Route13_Text_GwenDefeat::
    .string "Vel gert! Þú vannst algjörlega!$"

Route13_Text_GwenPostBattle::
    .string "Maður þarf að láta Vasaskrímsli\n"
    .string "berjast til að herða þau.$"

Route13_Text_AlmaIntro::
    .string "Ég fann CARBOS í helli einu sinni á\n"
    .string "meðan ég var að hellaskoða.$"

Route13_Text_AlmaDefeat::
    .string "Ó, of slæmt! Ég klúðraði bara!$"

Route13_Text_AlmaPostBattle::
    .string "CARBOS hækkaði HRAÐA\n"
    .string "Vasaskrímslisins míns.$"

Route13_Text_PerryIntro::
    .string "Ég ætla ekki að tapa. Ekki þegar\n"
    .string "vindurinn blæs í mína átt!$"

Route13_Text_PerryDefeat::
    .string "Vindurinn snerist!$"

Route13_Text_PerryPostBattle::
    .string "Ég er búinn. Ég held að ég FLJÚGI\n"
    .string "heim.$"

Route13_Text_LolaIntro::
    .string "Jú, ég skal leika við þig, krútt.$"

Route13_Text_LolaDefeat::
    .string "Ó! Þú litla skrímsli!$"

Route13_Text_LolaPostBattle::
    .string "Ég velti fyrir mér hvort karlkyns\n"
    .string "eða kvenkyns Vasaskrímsli séu\p"
    .string "sterkari.$"

Route13_Text_SheilaIntro::
    .string "Viltu berjast með nokkrum\n"
    .string "Vasaskrímslum við mig?$"

Route13_Text_SheilaDefeat::
    .string "Er þetta búið nú þegar?$"

Route13_Text_SheilaPostBattle::
    .string "Ég veit reyndar ekkert um\n"
    .string "Vasaskrímsli.\p"
    .string "Þau sem ég nota… Ég valdi þau bara\n"
    .string "útlitsins vegna!$"

Route13_Text_JaredIntro::
    .string "Hvað ertu að horfa á?$"

Route13_Text_JaredDefeat::
    .string "Djöfull! Gírarnir slitnuðu!$"

Route13_Text_JaredPostBattle::
    .string "Hafðu þig á brott!$"

Route13_Text_RobertIntro::
    .string "Ég vel alltaf fugla-Vasaskrímsli. Ég\n"
    .string "hef helgað mig þeim.$"

Route13_Text_RobertDefeat::
    .string "Enginn kraftur eftir!$"

Route13_Text_RobertPostBattle::
    .string "Ég vildi að ég gæti flogið eins og\n"
    .string "DÚFUTETUR og DÚFINN…$"

Route13_Text_LookToLeftOfThatPost::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Sjáðu, sjáðu! Horfðu til vinstri við\n"
    .string "þennan staur!$"

Route13_Text_SelectToSwitchItems::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "Notaðu SELECT til að skipta um hluti\n"
    .string "í HLUTA-glugganum.$"

Route13_Text_RouteSign::
    .string "LEIÐ 13 Norður til SILENCE BRIDGE$"
