VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .string "Jafnvel á sama stigi geta\n"
    .string "vasaskrímsli haft mjög ólík gildi og\p"
    .string "hæfileika.\p"
    .string "Vasaskrímsli alið upp af ÞJÁLFARA er\n"
    .string "sterkara en villt vasaskrímsli.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .string "Vasaskrímslið mitt var eitrað! Það\n"
    .string "rotaðist á meðan við gengum!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .string "Það er satt að vasaskrímsli á hærra\n"
    .string "stigi verður öflugra...\p"
    .string "En öll vasaskrímsli hafa veika\n"
    .string "punkta gagnvart ákveðnum gerðum.\p"
    .string "Því virðist ekkert vasaskrímsli vera\n"
    .string "algilt sterkt.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .string "Löngunin til að berjast aftur við\n"
    .string "einhvern sem þú hefur áður mætt...\p"
    .string "Hefurðu nokkurn tíma fundið hana? Ég\n"
    .string "er viss um það.\p"
    .string "Mig langaði líka að berjast við\n"
    .string "ákveðið fólk aftur og aftur.\p"
    .string "Þess vegna hef ég verið að gefa\n"
    .string "þetta frá mér. Vinsamlegast, taktu\p"
    .string "einn!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .string "Notaðu þetta tæki og þú finnur\n"
    .string "ÞJÁLFARA sem vilja endurbardaga.\p"
    .string "Þú þarft samt að hlaða rafhlöðuna\n"
    .string "til að nota það.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .string "Hvernig notarðu VS LEITARA? Það er\n"
    .string "ekkert mál.\p"
    .string "Notaðu hann svona bíp-bíp-bíp, og\n"
    .string "ÞJÁLFARAR í kringum þig taka eftir.\p"
    .string "Ef einhver ÞJÁLFARI vill\n"
    .string "endurbardaga lætur hann þig vita\p"
    .string "strax.\p"
    .string "Hladdu rafhlöðuna og notaðu hann á\n"
    .string "vegi.$"
