ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Þessir VASA BOLTAR á mittinu þínu!\n"
    .string "Þú átt Vasaskrímsli, er það ekki?\p"
    .string "Það er frábært að þú getur borið og\n"
    .string "notað Vasaskrímsli hvenær sem er,\p"
    .string "hvar sem er.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Þessi Vasaskrímslasalur er alltaf\n"
    .string "lokaður.\p"
    .string "Ég velti fyrir mér hver LEIÐTOGINN\n"
    .string "er.$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "LEIÐTOGI VIRIDIAN SALARINS er kominn\n"
    .string "aftur!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "Viltu vita um tvær tegundir\n"
    .string "maðka-Vasaskrímsla?$"

ViridianCity_Text_OhOkayThen::
    .string "Ó, allt í lagi þá!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "LIRFINGUR hefur ekkert eitur, en\n"
    .string "NÁLGUR hefur það.\p"
    .string "Passaðu að Vasaskrímslið þitt verði\n"
    .string "ekki stungið af EITURSTUNGU NÁLGURS.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Æ, afi! Ekki vera svona leiðinlegur!\p"
    .string "Fyrirgefðu. Hann hefur ekki fengið\n"
    .string "kaffið sitt enn.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "Ég fer stundum að versla í PEWTER\n"
    .string "BORG.\p"
    .string "Þá þarf ég að fara krókóttu leiðina\n"
    .string "um VIRIDIAN FOREST.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "Ég banna þér algjörlega að fara hér\n"
    .string "í gegn!\p"
    .string "Þetta er einkalóð!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Jæja, nú hef ég fengið kaffið mitt,\n"
    .string "og það kemur mér í gang!\p"
    .string "Hm? Hvað er þessi rauði kassi sem þú\n"
    .string "ert með?\p"
    .string "Ah, þú ert að vinna í VasaDEX.\p"
    .string "Leyfðu mér þá að gefa þér ráð.\p"
    .string "Alltaf þegar þú fangar Vasaskrímsli\n"
    .string "uppfærist VasaDEX sjálfkrafa.\p"
    .string "Veistu ekki hvernig á að fanga\n"
    .string "Vasaskrímsli?\p"
    .string "Ég skal sýna þér það.$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "Svona! Þetta var nú fræðandi,\n"
    .string "var það ekki?\p"
    .string "Og hér, taktu þetta líka.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "Ef það er eitthvað sem þú skilur\n"
    .string "ekki, horfðu á þetta.\p"
    .string "Það mun kenna þér grunnatriðin um að\n"
    .string "vera Vasaskrímsli ÞJÁLFARI.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Jæja, nú hef ég fengið kaffið mitt,\n"
    .string "og það kemur mér í gang!\p"
    .string "En ég gerði það of sterkt. Ég fékk\n"
    .string "hausverk…\p"
    .string "Annars, ertu að fylla VasaDEX?\p"
    .string "Byrjaðu á að veikja Vasaskrímslið\n"
    .string "áður en þú reynir að fanga það.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Jæja, nú hef ég fengið kaffið mitt,\n"
    .string "og það kemur mér í gang!\p"
    .string "En ég gerði það of sterkt. Ég fékk\n"
    .string "hausverk…\p"
    .string "Annars, hjálpar gamla kennslu-\n"
    .string "sjónvarpið\n"
    .string "mitt þér?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha! Það er barnabarnið mitt í\n"
    .string "þættinum!\p"
    .string "Þar sem hann kennir þetta, lærirðu\n"
    .string "örugglega eitthvað.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… Þú ert svo upptekin/n að þú\n"
    .string "hefur ekki einu sinni tíma fyrir\p"
    .string "kennslusjónvarp…\p"
    .string "Tími er peningar, og hvorugu ætti að\n"
    .string "sóa…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN BORG Hin eilífgræna paradís$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "ÞJÁLFARI RÁÐ\p"
    .string "Fangaðu Vasaskrímsli og stækkaðu\n"
    .string "safnið þitt.\p"
    .string "Því fleiri sem þú átt, því\n"
    .string "auðveldara er að berjast.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "ÞJÁLFARI RÁÐ\p"
    .string "Bardagahreyfingar Vasaskrímsla eru\n"
    .string "takmarkaðar af ORKUPUNKTUM, PP.\p"
    .string "Til að fylla á PP skaltu hvíla\n"
    .string "þreytt Vasaskrímsli í\p"
    .string "Vasaskrímslasetri.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN BORG Vasaskrímslasalur$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN SALUR's hurðir eru læstar…$"
