@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach::
    .string "Tilbúinn? Boing!\p"
    .string "Við erum í BODY SLAM keppni til að\n"
    .string "sjá hver gefst fyrst upp.\p"
    .string "Ef þú tækir þátt yrðirðu samt\n"
    .string "kraminn eins og pöddur…\p"
    .string "Hvernig væri að ég kenndi einu\n"
    .string "Vasaskrímslinu þínu BODY SLAM í\p"
    .string "staðinn?$"

Text_BodySlamDeclined::
    .string "Komdu aftur! Boing!$"

Text_BodySlamWhichMon::
    .string "Hvaða Vasaskrímsli vill læra BODY\n"
    .string "SLAM?$"

Text_BodySlamTaught::
    .string "Boing!$"

FourIsland_House1_Text_FatMan::
    .string "それ ぼよーん！ おまえ おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "Sjaldgæf ÍS-gerð Vasaskrímsla býr í\n"
    .string "hellinum.\p"
    .string "Við fáum marga gesti sem vonast til\n"
    .string "að sjá það Vasaskrímsli.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "Ha? Vasaskrímsla EGG? …Ég hef\nekki\n"
    .string "hugmynd.\n\n…Ó, bíddu. Fólkið á\p"
    .string "DAGHEIMILINU\ní bænum var að segja\n"
    .string "eitthvað.\n\nÞau sögðust hafa fundið\p"
    .string "EGG áður\ná lóðinni sinni.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .string "Hvað er þetta?\p"
    .string "Nýja Vasaskrímsla-BLAÐIÐ hefur ekki\n"
    .string "komið til þessarar eyju?$"

