CeruleanCity_House4_Text_NothingEntertaining::
    .string "Andvarp... Of mikill tími, of lítið\n"
    .string "að gera...\p"
    .string "Gerist ekkert skemmtilegt einhvers\n"
    .string "staðar?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
    .string "Ah! Ný frétt!\p"
    .string "Hmm...\p"
    .string "Ég skil! Þetta var býsna fróðlegt!\p"
    .string "Ég hrósa þér fyrir að hafa áhuga á\n"
    .string "fréttum á svona ungum aldri.\p"
    .string "Sem þökk fyrir að deila fréttunum\n"
    .string "með mér vil ég að þú fáir þetta.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
    .string "Ó, ó! Þ-þessi frétt!\p"
    .string "Hmm...\p"
    .string "Magnað! Hvílík ótrúleg frétt!\p"
    .string "Ég hef ekki séð svona magnaða frétt\n"
    .string "í langan tíma!\p"
    .string "Takk fyrir að deila þessari frábæru\n"
    .string "frétt. Fáðu slatta af BERJUM!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
    .string "Það er synd að deila ekki þessari\n"
    .string "frétt með fleira fólki...\p"
    .string "Ég vildi að ég gæti sagt\n"
    .string "einhverjum... Látið aðra vita af\p"
    .string "fréttunum...$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
    .string "Ah, hefurðu dreift fréttunum fyrir\n"
    .string "mig?\p"
    .string "Góðar fréttir verða verðmætar þegar\n"
    .string "alls konar fólk deilir þeim.\p"
    .string "Sem þökk fyrir að dreifa fréttunum\n"
    .string "skaltu taka þetta!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
    .string "Hefurðu dreift fréttunum enn meira?\n"
    .string "Stórkostlegt!\p"
    .string "Þessi frétt hlýtur að vera ánægð með\n"
    .string "að ganga svona á milli.\p"
    .string "Já, svo sannarlega!\p"
    .string "Líttu á þetta sem þakklætisvott frá\n"
    .string "mér og fréttinni.\p"
    .string "Ég gef þér fleiri BER en venjulega.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
    .string "Ég nýt mín vel með alls konar\n"
    .string "fréttum.\p"
    .string "Já, ég er sáttur! Mér mun ekki\n"
    .string "leiðast um stund.$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
    .string "Hm? BERJAPOKINN þinn er fullur.\n"
    .string "Gjöfin mín bíður þá áfram.$"

