VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Hæ! Áttu {STR_VAR_1}?\p"
	.string "Viltu skipta því fyrir minn\n"
	.string "{STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "Það er leitt.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "...Þetta er ekki {STR_VAR_1}.\p"
	.string "Ef þú færð einn, vinsamlegast skiptu\n"
	.string "honum við mig!$"

VermilionCity_House2_Text_ThankYou::
	.string "Takk fyrir!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "Hvernig hefur gamli {STR_VAR_2} minn\n"
	.string "það?\p"
	.string "{STR_VAR_1} minn hefur það frábært!$"
