CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "Ég fékk KÍGILDIÐ mitt í CINNABAR.\p"
    .string "Það er venjulega gæft, en andar frá\n"
    .string "sér eitri þegar það reiðist.$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "Heheh! Þessi SALUR er frábær! Hann\n"
    .string "er fullur af konum!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "CELADON leggur metnað í að halda\n"
    .string "borginni fallegri.\p"
    .string "Þess vegna spillir nýi SPILASALURINN\n"
    .string "fyrir ímynd borgarinnar.$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Urr… Ég klúðraði öllu í\n"
    .string "spilakössunum!\p"
    .string "Ég vissi að ég hefði átt að skipta\n"
    .string "PENINGUNUM mínum út fyrir vinninga!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "Þetta er trausti vinur minn,\n"
    .string "SPÍRALOFSI.\p"
    .string "Hann þróaðist úr HRINGEKLI þegar ég\n"
    .string "notaði VATNSSTEIN.$"

CeladonCity_Text_Poliwrath::
    .string "SPÍRALOFSI: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "Hvað ertu að glápa á? Farðu í burtu,\n"
    .string "annars slæ ég þig.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "Haltu þig frá ROCKET-GENGINU!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "X HITTNI eykur nákvæmni bragða.\p"
    .string "DIRE HIT hækkar líkurnar á rothöggi.\p"
    .string "Kauptu hlutina þína í\n"
    .string "CELADON-STÓRVERSLUN!$"

CeladonCity_Text_CitySign::
    .string "CELADON BORG Borg regnbogadrauma$"

CeladonCity_Text_GymSign::
    .string "CELADON BORGAR VASASKRÍMSLA-SALUR\p"
    .string "SALSTJÓRI: ERIKA Prinsessan sem\n"
    .string "elskar náttúruna!$"

CeladonCity_Text_MansionSign::
    .string "CELADON STÓRHÝSI$"

CeladonCity_Text_DeptStoreSign::
    .string "Finndu það sem þig vantar í CELADON\n"
    .string "VÖRUHÚSINU!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "ÞJÁLFARA RÁÐ\p"
    .string "GUARD SPEC. verndar vasaskrímsli\n"
    .string "gegn brögðum sem lækka stöður í\p"
    .string "bardaga.\p"
    .string "Kauptu hlutina þína í\n"
    .string "CELADON-STÓRVERSLUN!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "PENINGUM skipt fyrir vinninga!\n"
    .string "VINNINGASKIPTI$"

CeladonCity_Text_GameCornerSign::
    .string "ROCKET-SPILASALUR Leikvöllur\n"
    .string "fullorðna fólksins!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Aaaagh, ás… Ég brenndi á mér\n"
    .string "tunguna!\p"
    .string "Þessi indæla gamla kona í STÓRHÝSINU\n"
    .string "gaf mér TE.\p"
    .string "En það var sjóðandi heitt! Verð að\n"
    .string "kæla það til að drekka það.$"

Text_SoftboiledTeach::
    .string "Hæ þarna!\p"
    .string "Ég hef séð þig á ferli en aldrei\n"
    .string "fengið tækifæri til að spjalla.\p"
    .string "Það hlýtur að vera heppnin sem\n"
    .string "loksins leiddi okkur saman.\p"
    .string "Ég vil fagna því með því að kenna\n"
    .string "þér bragðið MJÚKSOÐIÐ.$"

Text_SoftboiledDeclined::
    .string "Ég mun alltaf fylgjast með þér.\p"
    .string "Ég vona að við getum spjallað aftur.$"

Text_SoftboiledWhichMon::
    .string "Jæja, hvaða vasaskrímsli á að fá\n"
    .string "tækifæri til að læra MJÚKSOÐIÐ?$"

Text_SoftboiledTaught::
    .string "Ég óska þér alls hins besta!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Ó, hvað á ég að gera...\p"
    .string "Einhver stal SILPH SCOPE okkar.\p"
    .string "Þjófurinn hljóp þessa leið, ég er\n"
    .string "viss um það.\p"
    .string "En ég missti sjónar á honum! Hvert\n"
    .string "fór hann?$"
