ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hæ! Komstu frá PALLET BÆ?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "Þú þekkir Prófessor EIK, ekki satt?\p"
    .string "Pöntunin hans kom. Gætirðu farið með\n"
    .string "hana til hans?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} fékk PAKKA EIKS frá\n"
    .string "afgreiðslumanninum.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Allt í lagi, takk! Skilaðu líka\n"
    .string "kveðju til Prófessor EIK frá mér.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "Þessi búð selur vel af MÓTEITRUM,\n"
    .string "hef ég heyrt.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "Ég þarf að kaupa nokkur SEYÐI.\p"
    .string "Maður veit aldrei hvenær\n"
    .string "Vasaskrímslin þurfa skjóta\p"
    .string "lækningu.$"
