VermilionCity_Gym_Text_LtSurgeIntro::
    .string "Hey, krakki! Hvað heldurðu að þú\n"
    .string "sért að gera hér?\p"
    .string "Þú lifir ekki lengi í bardaga! Ekki\n"
    .string "með þennan vesæla kraft!\p"
    .string "Ég segi þér, krakki, rafmagns-\n"
    .string "vasaskrímsli björguðu mér í\p"
    .string "stríðinu!\p"
    .string "Þau lömuðu óvini mína með raflosti!\p"
    .string "Ég geri það sama við\n"
    .string "þig!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "Smá ráð, krakki!\p"
    .string "Rafmagn er sannarlega öflugt!\p"
    .string "En það gagnast ekkert gegn\n"
    .string "JARÐAR-gerðar vasaskrímslum!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "ÞRUMUMERKIÐ hækkar HRAÐA hjá\n"
    .string "vasaskrímslunum þínum!\p"
    .string "Það leyfir vasaskrímslunum þínum\n"
    .string "líka að nota FLY eldingarhratt\p"
    .string "hvenær sem er, krakki!\p"
    .string "Þú ert sérstakur, krakki! Taktu\n"
    .string "þetta!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} fékk TM34 frá LT. SURGE.$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "TM34 inniheldur ÁFALLABYLGJU!\p"
    .string "Kenndu hana rafmagns-vasaskrímsli!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Yo, krakki, gerðu pláss í TÖSKUNNI!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Nú er ég lostinn!\p"
    .string "Þú ert alvöru efni, krakki!\p"
    .string "Jæja þá, taktu ÞRUMUMERKIÐ!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "Þegar ég var í hernum var LT. SURGE\n"
    .string "strangur yfirforingi minn.\p"
    .string "Hann var harður húsbóndi.$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Hættu! Þú ert mjög góður!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "Það er ekki auðvelt að opna þessa\n"
    .string "hurð.\p"
    .string "LT. SURGE var alltaf frægur fyrir\n"
    .string "varkára eðlið sitt í hernum.$"

VermilionCity_Gym_Text_BailyIntro::
    .string "Ég er léttavigtarmaður, en ég er\n"
    .string "góður með rafmagn!\p"
    .string "Þess vegna gekk ég í þennan SAL.$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Steiktur!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Allt í lagi, ég segi frá!\p"
    .string "LT. SURGE sagðist hafa falið\n"
    .string "dyrarofa inni í einhverju.$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "Þetta er enginn staður fyrir krakka!\n"
    .string "Ekki einu sinni ef þú ert góður!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Vá! Þú kom mér á óvart!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "LT. SURGE setti gildrurnar í SALNUM\n"
    .string "upp sjálfur.\p"
    .string "Hann setti tvöfalda lása alls\n"
    .string "staðar. Ég skal gefa þér\p"
    .string "vísbendingu.\p"
    .string "Þegar þú opnar fyrsta lásinn er\n"
    .string "annar lásinn rétt hjá honum.$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "Yo! Verðandi meistari!\p"
    .string "LT. SURGE hefur gælunafn.\p"
    .string "Fólk kallar hann Eldingamanninn frá\n"
    .string "Ameríku!\p"
    .string "Hann er sérfræðingur í rafmagns-\n"
    .string "vasaskrímslum.\p"
    .string "FLUG/VATNS-gerðar vasaskrímsli\n"
    .string "standa illa gegn RAFMAGNS gerðinni.\p"
    .string "Varastu lömun líka.\p"
    .string "LT. SURGE er mjög varkár.\p"
    .string "Hann hefur læst sig inni, svo það\n"
    .string "verður ekki auðvelt að komast til\p"
    .string "hans.$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "Úff! Þessi bardagi var rafmagnaður!$"

VermilionCity_Gym_Text_GymStatue::
    .string "VERMILION VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: LT. SURGE\p"
    .string "SIGURÞJÁLFARAR: {RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "VERMILION VASASKRÍMSLA-SALUR\n"
    .string "SALSTJÓRI: LT. SURGE\p"
    .string "SIGURÞJÁLFARAR: {RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "Nei! Hér er bara rusl.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Hey! Það er rofi undir ruslinu!\n"
    .string "Kveiktu á honum!\p"
    .string "Fyrsti raflásinn opnaðist!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！ おっと！ ゴミばこの そこに また スイッチが あった！\n"
    .string "おして みよう！ ‥ ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "Annar raflásinn opnaðist! Vélknúna\n"
    .string "hurðin opnaðist!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Neibb! Hér er bara rusl.\p"
    .string "Hey! Raflásarnir endurstilltust!$"
