FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "Velkomin í SAFARI SVÆÐIÐ!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "Fyrir aðeins ¥500 geturðu spilað\n"
    .string "SAFARI LEIKINN.\p"
    .string "Þú getur reikað um víðáttumikið\n"
    .string "safaríið og veitt það sem þú vilt.\p"
    .string "Viltu spila?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "Það kostar ¥500, takk!\p"
    .string "Hér notum við aðeins sérstaka VASA\n"
    .string "BOLTA.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "{PLAYER} fékk 30 SAFARI BOLTA frá\n"
    .string "starfsmanninum.$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "Við munum kalla á þig í kallkerfinu\n"
    .string "þegar þú klárast tíma eða SAFARI\p"
    .string "BOLTA.\p"
    .string "Jæja, ég óska þér alls hins besta!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "Allt í lagi. Komdu aftur!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "Úps! Ekki nóg af peningum!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "Ætlarðu að yfirgefa SAFARI SVÆÐIÐ\n"
    .string "snemma?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "Skilaðu öllum SAFARI BOLTUM sem þú\n"
    .string "átt eftir.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "Gangi þér vel!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "Fangaðirðu nóg? Komdu aftur!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "Hæ! Er þetta í fyrsta skipti sem þú\n"
    .string "ert hér í SAFARI SVÆÐINU?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "Í SAFARI SVÆÐINU eru í raun fjögur\n"
    .string "svæði.\p"
    .string "Á hverju svæði eru mismunandi\n"
    .string "Vasaskrímsli, jafnvel sjaldgæf.\p"
    .string "Notaðu SAFARI BOLTANA sem þú færð\n"
    .string "til að fanga þau.\p"
    .string "Þú getur líka kastað BEITU eða\n"
    .string "STEINUM auk SAFARI BOLTANNA.\p"
    .string "Ef þú kastar BEITU verða\n"
    .string "Vasaskrímslin ólíklegri til að\p"
    .string "flýja, en erfiðari að fanga.\p"
    .string "Ef þú kastar STEINUM verða\n"
    .string "Vasaskrímslin líklegri til að flýja,\p"
    .string "en auðveldari að fanga.\p"
    .string "Þegar tíminn eða SAFARI BOLTARNIR\n"
    .string "klárast er leiknum lokið hjá þér!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "Fyrirgefðu, þú ert fastagestur hér!$"

