SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .string "Ha? Þú…$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .string "Ertu kannski… … …\p"
    .string "Þú ert það! Þú ert {PLAYER}!\p"
    .string "Við vorum einmitt að tala um þig!\p"
    .string "Við vorum að tala um að ótrúlega\n"
    .string "góður ÞJÁLFARI hefði birst.\p"
    .string "Og sú manneskja ert þú! Þú ert svo\n"
    .string "flott/ur!\p"
    .string "Þannig að við ákváðum að verða\n"
    .string "AÐDÁENDAKLÚBBURINN þinn!\p"
    .string "Við vonum öll að þú haldir áfram að\n"
    .string "berjast og sýnir okkur hvað þú ert\p"
    .string "flott/ur.\p"
    .string "Þannig verða kannski fleiri að\n"
    .string "aðdáendum eins og ég.$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .string "Ég mun alltaf hvetja þig!\p"
    .string "Áfram, {PLAYER}, áfram!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .string "Ég mun alltaf trúa á þig, {PLAYER}.\p"
    .string "Vinsamlegast sýndu öðrum hvernig þú\n"
    .string "ert þegar þú berst af alvöru.$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .string "Fyrirgefðu. Ég var aðdáandi þinn\n"
    .string "áður.\p"
    .string "En núna virðist þú hafa misst\n"
    .string "drifkraftinn sem þú hafðir áður.\p"
    .string "Undanfarið held ég að {STR_VAR_1}\n"
    .string "hafi verið miklu svalari.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .string "Ó! {PLAYER}!\p"
    .string "Allir hafa verið svo spenntir yfir\n"
    .string "þér undanfarið.\p"
    .string "Ég skil af hverju. Ég veit að þú ert\n"
    .string "sterkur.\p"
    .string "En, veistu hvað?\p"
    .string "Þegar ég varð aðdáandi {STR_VAR_1}s,\n"
    .string "get ég ekki bara hætt að vera\p"
    .string "aðdáandi.$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .string "Mér finnst ÞJÁLFARAR svo flottir\n"
    .string "þegar þeir berjast.\p"
    .string "Finnst þér það ekki líka?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .string "Ó! Þetta er {PLAYER}! Of flott!\p"
    .string "Ó! Ó, já!\p"
    .string "Geturðu áritað eitthvað? Hvað með\n"
    .string "stuttbuxurnar mínar?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .string "Sama hversu heitt hefur verið…\p"
    .string "Og sama hversu kalt það verður…\p"
    .string "Ég hef alltaf trúað á stuttbuxur og\n"
    .string "gengið í þeim!\p"
    .string "Ég treysti á að þú haldir áfram að\n"
    .string "vinna!\p"
    .string "Ég trúi á þig jafnmikið og ég trúi á\n"
    .string "stuttbuxur!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .string "BROCK er hetjan mín! Hann er maður\n"
    .string "meðal manna!\p"
    .string "Heheh, ég fékk mömmu til að gera\n"
    .string "eitthvað fyrir mig.\p"
    .string "Ég fékk hana til að sauma 'BROCK' á\n"
    .string "stuttbuxurnar mínar!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .string "… …\p"
    .string "… … Ég er aðdáandi BROCKS!\p"
    .string "Jafnvel þótt ég væri eini aðdáandi\n"
    .string "hans, sver ég það við steinhardan\p"
    .string "vilja minn og stuttbuxurnar mínar!\p"
    .string "Ég verð aðdáandi hans allt til enda!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .string "BROCK er síðasta orðið um svalleika,\n"
    .string "punktur og basta!\p"
    .string "Nú er þar strákur sem ég vil vera\n"
    .string "eins og!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .string "{PLAYER}, ég hef notið þess að horfa\n"
    .string "á þig berjast.\p"
    .string "Það vekur upp ljúfar minningar um\n"
    .string "mína eigin löngu týndu æsku.\p"
    .string "Megi þér halda áfram að ganga vel.\n"
    .string "Þú átt aðdáanda í mér!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .string "Ég hef ferðast vítt og breitt um\n"
    .string "löndin.\p"
    .string "En aldrei hef ég séð ÞJÁLFARA með\n"
    .string "þína reisn.\p"
    .string "Treystu á hæfileika þína og haltu\n"
    .string "áfram að berjast!\p"
    .string "Lofaðu mér því, unga átrúnaðargoðið\n"
    .string "mitt!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .string "Hmm… Og þú ert?\p"
    .string "Varstu að vonast til að skrá þig í\n"
    .string "AÐDÁENDAKLÚBBINN okkar?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .string "Ah, svo þú ert hinn margumtalaði\n"
    .string "{PLAYER}.\p"
    .string "Þú berð vissulega með þér svip\n"
    .string "sigurvegara.\p"
    .string "En til að ég viðurkenni þig sem\n"
    .string "sanna Vasaskrímsla-stjörnu…\p"
    .string "… …\p"
    .string "Þú átt enn nokkuð í land!$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .string "Við sem erum hér saman komin erum\n"
    .string "aðdáendur Vasaskrímslaþjálfara.\p"
    .string "Hvernig þeir líta út í bardaga… Þeir\n"
    .string "eru ímynd svalleikans.\p"
    .string "Kannski verður talað um þig hér líka\n"
    .string "ef þú heldur áfram að vinna.$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .string "Þetta er {PLAYER}! Þetta er\n"
    .string "{PLAYER}!\p"
    .string "Ég vil verða eins og {PLAYER} einn\n"
    .string "daginn!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .string "Allir hættu að vera aðdáendur\n"
    .string "{PLAYER}…\p"
    .string "En það þýðir að ég get haft {PLAYER}\n"
    .string "alveg fyrir mig!\p"
    .string "Jibbí! Áfram! Minn eini og sanni\n"
    .string "{PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .string "Veistu hvað? Ég vil vera eins og\n"
    .string "SABRINA!\p"
    .string "Ég vil vera skyggn stelpa alveg eins\n"
    .string "og hún!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .string "Jafnvel þó ég sé sú eina, mun ég\n"
    .string "ekki hætta að vera aðdáandi SABRINA.\p"
    .string "Draumur minn er að vera eins og\n"
    .string "SABRINA, sæt en flott.\p"
    .string "Ég vil vera sálfræðistúlka alveg\n"
    .string "eins og hún!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .string "Ætli ég geti orðið svalur ÞJÁLFARI\n"
    .string "einn daginn?$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .string "Ó maður, ó maður! Svalt! Of svalt!\p"
    .string "…Ha? Nei, ekki þú.\p"
    .string "Bara hvernig þú berst. Það er svalt.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .string "Yo, {PLAYER}!\p"
    .string "Það lítur út fyrir að ég sé eini\n"
    .string "aðdáandinn þinn sem eftir er.\p"
    .string "En veistu, mér finnst gott að vera\n"
    .string "eini aðdáandinn… Það er minna\p"
    .string "stress.\p"
    .string "Haltu áfram og láttu vaða!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .string "{STR_VAR_1} er svalur, ha? Ég elska\n"
    .string "hvernig hann talar.\p"
    .string "Ég myndi virkilega njóta þess að fá\n"
    .string "tækifæri til að hitta hann í eigin\p"
    .string "persónu einu sinni.$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .string "Ha, trúirðu því? Allir urðu\n"
    .string "aðdáendur þínir.\p"
    .string "Svo eftir allt sem við höfum gengið\n"
    .string "í gegnum, er ég eini {STR_VAR_1}\p"
    .string "aðdáandinn?\p"
    .string "Eh, að vera eini {STR_VAR_1}\n"
    .string "aðdáandinn er minn stíll, hvort eð\p"
    .string "er.$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .string "Ó, minn góður! Ert þetta virkilega\n"
    .string "þú, {PLAYER}?\p"
    .string "Ég verð að segja þér, ég dýrka\n"
    .string "hvernig þú berst.\p"
    .string "Ég vona að þú haldir áfram. Ég verð\n"
    .string "aðdáandi númer eitt!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .string "Ó, minn kæri! Er þetta ekki\n"
    .string "{PLAYER}!\p"
    .string "Það eru svo mikil vonbrigði… Ég\n"
    .string "áttaði mig á því að ég er aðdáandi\p"
    .string "númer eitt og sá eini!\p"
    .string "Jæja, við því er ekkert að gera!\n"
    .string "Leyfðu mér að hvetja þig að minnsta\p"
    .string "kosti!\p"
    .string "Húrra, húrra, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .string "Undanfarið hefur {STR_VAR_1} verið á\n"
    .string "eldi.\p"
    .string "Hvernig hann berst… Það er\n"
    .string "nákvæmlega það sem mér líkar!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .string "Ó, halló! Ef þetta er ekki {PLAYER}!\p"
    .string "Undanfarið tala allir bara um þig.\p"
    .string "Mér líður einmana því ég vil frekar\n"
    .string "{STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .string "Magnað! {PLAYER}, þú ert virkilega\n"
    .string "mögnuð/magnaður!\p"
    .string "Í stað þess að horfa bara á ætti ég\n"
    .string "kannski líka að verða ÞJÁLFARI.$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .string "Ég er eini aðdáandinn þinn… Andvarp…\n"
    .string "Þetta er einmanalegt…\p"
    .string "Geturðu ekki reynt aðeins meira og\n"
    .string "fengið hina til að taka eftir þér?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .string "Meistari {STR_VAR_1} er svo\n"
    .string "virðulegur… Hann er alveg mín týpa.\p"
    .string "Af hverju sjá hinir ekki reisnina\n"
    .string "sem streymir af honum?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .string "Ég trúi á Meistara {STR_VAR_1} af\n"
    .string "öllu mínu hjarta.\p"
    .string "Jafnvel þótt ég sé eini sem trúir á\n"
    .string "hann.\p"
    .string "Mér mun aldrei líða einmana, þó.\p"
    .string "Ekki ef ég held áfram að hugsa um\n"
    .string "Meistara {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .string "Hiyah!\p"
    .string "Bardagastíll þinn er mjög fræðandi.\p"
    .string "Ég vona að þú haldir áfram að vinna\n"
    .string "að árangri, hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .string "Í stað þess að horfa bara á aðra\n"
    .string "berjast skaltu berjast sjálf/ur!\p"
    .string "…MEISTARINN minn í DÓJÓINU skammaði\n"
    .string "mig svona…\p"
    .string "En ég læt það ekki stoppa mig frá\n"
    .string "því að vera aðdáandi þinn!\p"
    .string "Ég get ekki hætt að vera aðdáandi\n"
    .string "þinn!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .string "Híja! Það er aðeins einn ÞJÁLFARI\n"
    .string "sem hefur virðingu mína.\p"
    .string "Og það er enginn annar en MEISTARI\n"
    .string "minn í BARDAGADÓJÓINU.\p"
    .string "Þú ættir að verða aðdáandi MEISTARA\n"
    .string "míns eins og ég! Híja!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .string "Hiyah! Ég virði MEISTARA minn í\n"
    .string "BARDAGADÓJÓINU.\p"
    .string "Ég verð aldrei aðdáandi neins annars\n"
    .string "en MEISTARA míns!\p"
    .string "Ég laumast meira að segja út úr\n"
    .string "DÓJÓINU til að segja frá snilld hans.\p"
    .string "Hiyah!$"
