Route8_Text_AidanIntro::
    .string "Þú virðist góð/ur í Vasaskrímslum,\n"
    .string "en hvernig gengur þér í efnafræði?$"

Route8_Text_AidanDefeat::
    .string "Ó! Bráðnun!$"

Route8_Text_AidanPostBattle::
    .string "Ég er betri í skóla en þessu!$"

Route8_Text_StanIntro::
    .string "Allt í lagi! Spilum leik!$"

Route8_Text_StanDefeat::
    .string "Helvítis! Kom upp stutt!$"

Route8_Text_StanPostBattle::
    .string "Hlutirnir gengu ekki í dag.$"

Route8_Text_GlennIntro::
    .string "Þú ættir að vera upplýstur. Þú þarft\n"
    .string "stefnu til að vinna í þessu!$"

Route8_Text_GlennDefeat::
    .string "Það er ekki rökrétt!$"

Route8_Text_GlennPostBattle::
    .string "Byrja á DRULLUPOLL… og… og svo…$"

Route8_Text_PaigeIntro::
    .string "Mér líkar við NIDORAN, svo ég safna\n"
    .string "þeim!$"

Route8_Text_PaigeDefeat::
    .string "Af hverju? Af hverju??$"

Route8_Text_PaigePostBattle::
    .string "Þegar Vasaskrímsli vaxa úr grasi\n"
    .string "verða þau ljót! Þau ættu ekki að þróast.$"

Route8_Text_LeslieIntro::
    .string "Skólinn er skemmtilegur, en\n"
    .string "Vasaskrímsli líka.$"

Route8_Text_LeslieDefeat::
    .string "Þú gerðir mér ljóst að ég ætti að\n"
    .string "halda mig við skólann.$"

Route8_Text_LesliePostBattle::
    .string "Ég ætlaði að fá mér ferskt loft til\n"
    .string "tilbreytingar, en…\p"
    .string "Við erum föst hér vegna hliðanna við\n"
    .string "SAFFRON.$"

Route8_Text_AndreaIntro::
    .string "MJÁGJARN er svo sætur, mjá, mjá,\n"
    .string "mjá!$"

Route8_Text_AndreaDefeat::
    .string "Mjááá!$"

Route8_Text_AndreaPostBattle::
    .string "Mér finnst DÚFUTETUR og ROTTÓTTUR\n"
    .string "líka sæt!$"

Route8_Text_MeganIntro::
    .string "Við hljótum að líta kjánalega út\n"
    .string "standandi svona hér.$"

Route8_Text_MeganDefeat::
    .string "Sjáðu hvað þú gerðir við fátæku,\n"
    .string "sætu Vasaskrímslin mín!$"

Route8_Text_MeganPostBattle::
    .string "Hliðvörður SAFFRON leyfir okkur ekki\n"
    .string "að komast í gegn.\p"
    .string "Ég veit að hann er að sinna starfi\n"
    .string "sínu, en ég held að hann sé vondur.$"

Route8_Text_RichIntro::
    .string "Ég er ráfandi, spilandi gaur!$"

Route8_Text_RichDefeat::
    .string "Missti af stóra tækifærinu!$"

Route8_Text_RichPostBattle::
    .string "Leikir og Vasaskrímsli eru eins og\n"
    .string "hnetur! Ég get bara ekki hætt!$"

Route8_Text_JuliaIntro::
    .string "Hvaða Vasaskrímsli er sætt,\n"
    .string "kringlótt og loðið?$"

Route8_Text_JuliaDefeat::
    .string "Stop!\p"
    .string "Ekki vera svona vond/ur við\n"
    .string "BLEIKÁLFUR minn!$"

Route8_Text_JuliaPostBattle::
    .string "Ég las að BLEIKÁLFUR þróist þegar\n"
    .string "hann verður fyrir áhrifum\p"
    .string "TUNLSTEINS.\p"
    .string "Ég las það í Vasaskrímsla-BLAÐI.\n"
    .string "Ætli það sé satt?$"

Route8_Text_UndergroundPathSign::
    .string "JARÐGÖNG CELADON BORG - LAVENDER BÆR$"

Route8_Text_EliIntro::
    .string "ELI: Tvíburakraftur er frábær.\n"
    .string "Vissirðu það?$"

Route8_Text_EliDefeat::
    .string "ELI: En… Við notuðum tvíburakraftinn\n"
    .string "okkar…$"

Route8_Text_EliPostBattle::
    .string "ELI: Ég fangaði Vasaskrímslin mín\n"
    .string "með ANNE!$"

Route8_Text_EliNotEnoughMons::
    .string "ELI: Við getum ekki barist ef þú ert\n"
    .string "ekki með tvö Vasaskrímsli.$"

Route8_Text_AnneIntro::
    .string "ANNE: Við munum sjokkera þig með\n"
    .string "tvíburar krafti okkar!$"

Route8_Text_AnneDefeat::
    .string "ANNE: Tvíburakraftur okkar…$"

Route8_Text_AnnePostBattle::
    .string "ANNE: Ég er að ala upp Vasaskrímsli\n"
    .string "með ELI.$"

Route8_Text_AnneNotEnoughMons::
    .string "ANNE: Hæ, hæ! Berjumst! En komdu með\n"
    .string "tvö Vasaskrímsli.$"

Route8_Text_RicardoIntro::
    .string "Hjólið mitt er að stríða mér, maður.$"

Route8_Text_RicardoDefeat::
    .string "Æ, maður. Ég er ekki hrifinn af\n"
    .string "þessu.$"

Route8_Text_RicardoPostBattle::
    .string "Ég fékk gras fast í svasas mínum,\n"
    .string "maður.$"

Route8_Text_JarenIntro::
    .string "Ryðjið brautina, eða ég keyri yfir\n"
    .string "ykkur!$"

Route8_Text_JarenDefeat::
    .string "Ertu í alvöru, krakki?$"

Route8_Text_JarenPostBattle::
    .string "Ekki halda að þú sért eitthvað\n"
    .string "sérstakur bara vegna þessa.$"
