FiveIsland_LostCave_Room10_Text_SelphyIntro::
    .string "H-hvað ætlarðu að gera við mig?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
    .string "Ó… Ég var hrædd um að þú ætlaðir mér\n"
    .string "illt.$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
    .string "Ég er svo ánægð að þú komst hingað.\p"
    .string "Ég varð frekar leið á að ganga, og\n"
    .string "ég er orðin þreytt.\p"
    .string "Má ég biðja þig um að fara með mig\n"
    .string "heim héðan?$"

