CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "Ég er að kaupa gjöf handa kærustunni\n"
    .string "minni.\p"
    .string "Ég held að VASa DÚKKA verði fyrir\n"
    .string "valinu. Hún er vinsæl núna.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "Ég heyrði gagnlegt leyndarmál.\p"
    .string "Ef villt vasaskrímsli birtist\n"
    .string "geturðu dreift athygli þess með\p"
    .string "VASa DÚKKU.\p"
    .string "Þú getur flúið á meðan villta\n"
    .string "vasaskrímslið er annars hugar.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Tjáðu þig með gjöfum! 4F: GJAFIR FRÁ\n"
    .string "VITRINGUM\p"
    .string "Sértilboð fyrir þróun!\n"
    .string "ÞRÓUNARSTEINAR á útsölu núna!$"
