ViridianCity_House_Text_NicknamingIsFun::
    .string "Það er gaman að finna gælunöfn, en\n"
    .string "það er ekki svo auðvelt.\p"
    .string "Snjöll nöfn eru góð, en einföld nöfn\n"
    .string "er auðveldara að muna.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "My daddy loves Vasaskrímsli, too.$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tví-tví!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPJÓTRUNGU Name: SPEARY$"

