SilphCo_3F_Text_WhatAmIToDo::
    .string "Ég vinn hjá SILPH CO. Hvað á ég að\n"
    .string "gera?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}! Þú og Vasaskrímslin þín\n"
    .string "björguðuð okkur!$"

SilphCo_3F_Text_GruntIntro::
    .string "Hættu að angra okkur, krakki!$"

SilphCo_3F_Text_GruntDefeat::
    .string "Ég gefst upp!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "Vísbending? Þú getur opnað dyr með\n"
    .string "KORTALYKLI!$"

SilphCo_3F_Text_JoseIntro::
    .string "Ég styð ROCKET-GENGIÐ meira en ég\n"
    .string "styð SILPH CO.!$"

SilphCo_3F_Text_JoseDefeat::
    .string "Þú náðir mér svo sannarlega!$"

SilphCo_3F_Text_JosePostBattle::
    .string "Humph…\p"
    .string "ROCKET-GENGIÐ sagði að ef ég hjálpaði\n"
    .string "þeim myndu þeir leyfa mér að rannsaka\p"
    .string "Vasaskrímsli.$"

SilphCo_3F_Text_FloorSign::
    .string "SILPH CO. HÖFUÐSKRIFSTOFA 3H$"
