PalletTown_Text_OakDontGoOut::
    .string "EIK: Hæ! Bíddu! Ekki fara út!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "EIK: Það er hættulegt! VASaSKRÍMSLI\n"
    .string "búa í háu grasi!\p"
    .string "Þú þarft þitt eigið VASaSKRÍMSLI til\n"
    .string "að vernda þig.\p"
    .string "Ég veit! Komdu með mér!$"

PalletTown_Text_RaisingMonsToo::
    .string "Ég er líka að hækka VASaSKRÍMSLI.\p"
    .string "Þegar þeir verða sterkir geta þeir\n"
    .string "verndað mig.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Tæknin er ótrúleg!\p"
    .string "Þú getur nú geymt og afturkallað\n"
    .string "hluti og VASaSKRÍMSLI sem gögn í\p"
    .string "gegnum Tölvu.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "VASaSKRÍMSLARANNSÓKNARSTOFA EIK$"

PalletTown_Text_PlayersHouse::
    .string "Hús {PLAYER}$"

PalletTown_Text_RivalsHouse::
    .string "Hús {RIVAL}$"

PalletTown_Text_TownSign::
    .string "PALLET BÆR Ný ferð bíður þín!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "EIK: Ah, {PLAYER}! Þú ert kominn\n"
    .string "aftur, er það?\p"
    .string "Hversu mikið hefur þú fyllt í\n"
    .string "VasaDEX þinn?\p"
    .string "Má ég sjá það?\p"
    .string "Við skulum sjá…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "Þú hefur náð {STR_VAR_2}…\p"
    .string "Hm, það lítur út fyrir að þú sért að\n"
    .string "leggja á þig heiðarlega tilraun.\p"
    .string "Þegar þér tekst að fylla það meira,\n"
    .string "komdu og sýndu mér, vinsamlegast.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "Þú hefur lent í… {STR_VAR_2}!? Nú,\n"
    .string "þetta er áhrifamikið!\p"
    .string "Það er eitthvað sem ég vildi spyrja\n"
    .string "þig, {PLAYER}.\p"
    .string "Komdu. Fylgdu mér.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "EIK: Ah, {PLAYER}! Þú virðist njóta\n"
    .string "þess að ferðast.\p"
    .string "Með því að þekkja þig, {PLAYER}, get\n"
    .string "ég auðveldlega ímyndað mér að þú\p"
    .string "farir út á enn framandi slóðir.\p"
    .string "Gott hjá þér, gott hjá þér. Hohoho.$"

