ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "LOSTELLE: Snökt… Snökt… Ó! Hjálp,\n"
    .string "gerðu það!\p"
    .string "Ógnvekjandi Vasaskrímsli birtist\n"
    .string "þarna rétt áðan.\p"
    .string "Það hélt áfram að hræða. Það hræddi\n"
    .string "LOSTELLE.\p"
    .string "Ég er of hrædd til að hreyfa mig! En\n"
    .string "mig langar heim…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "Ó! Þetta kemur aftur! Nei! Farðu!\n"
    .string "Þetta hræðir mig!\p"
    .string "Vááááááá! Ég vil pabba minn!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "Ó! Þetta var svo hræðilegt! Takk\n"
    .string "fyrir!\p"
    .string "LOSTELLE kom til að tína BER.\p"
    .string "Þú getur fengið þetta!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "Hvað heitirðu?\p"
    .string "LOSTELLE er hrædd, svo get ég farið\n"
    .string "með þér heim til pabba míns?\p"
    .string "Allt í lagi! Förum heim!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "BERJAPOKINN þinn er fullur. Þú vilt\n"
    .string "þetta þá líklega ekki.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Velkomin/n í BERJA SKÓG\p"
    .string "Vertu vingjarnleg/ur og deildu\n"
    .string "BERJUM með öðrum og Vasaskrímslum.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Varastu villt Vasaskrímsli sem elska\n"
    .string "BER!$"
