CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .string "Vasaskrímsli? Nei, þetta er hótel\n"
    .string "fyrir fólk.\p"
    .string "Því miður er allt uppbókað.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "Ég er í fríi með bróður mínum og\n"
    .string "kærastanum.\p"
    .string "CELADON er svo falleg borg!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "Af hverju? Af hverju tók hún bróður\n"
    .string "sinn með?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "Jibbí! Ég er í fríi!\p"
    .string "Systir mín tók mig með! Geggjað!$"

