FourIsland_Text_IslandSign::
    .string "FOUR EYJA Hlýja, bláa rekeyjan$"

FourIsland_Text_LoreleiHasReturned::
    .string "LORELEI er komin aftur.\p"
    .string "Fannst henni borgarlífið of\n"
    .string "streituvaldandi, skyldi ég?$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "LORELEI er farin aftur.\p"
    .string "LAGARGANDAN sem hún á held ég að sé\n"
    .string "sú sem hún hitti sem barn.\p"
    .string "Ég held að hún hafi fangað hana í\n"
    .string "ICEFALL CAVE.\p"
    .string "Kannski hefur það Vasaskrímsli verið\n"
    .string "með henni síðan.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "{RIVAL}: Hey! {PLAYER}!\p"
    .string "Hvað ertu að gera hér á SEVII\n"
    .string "ISLANDS?\p"
    .string "Þú ættir að hætta að herma eftir\n"
    .string "mér, veistu?\p"
    .string "Allavega, ég er þegar kominn með\n"
    .string "Vasaskrímsla EGG, svo ég er búinn\p"
    .string "með þessa eyju.\p"
    .string "Heh, ég veðja að þú veist ekki einu\n"
    .string "sinni hvað EGG er.\p"
    .string "Jæja, ég þarf að rúlla! Sjáumst!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .string "Ó, þú fannst mig! Vinsamlegast ekki\n"
    .string "segja LORELEI.\p"
    .string "Vissirðu að LORELEI á fullt, fullt\n"
    .string "af bangsum?\p"
    .string "Í hvert skipti sem hún kemur aftur\n"
    .string "til FOUR EYJU stækkar safnið hennar!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "Úff, kalt!\p"
    .string "Ég bjó til ískrap úr ís sem ég\n"
    .string "rakaði inni í ICEFALL CAVE.\p"
    .string "Það er kalt og bragðgott!$"

FourIsland_Text_LoreleisHouse::
    .string "HÚS LORELEI$"

